### ISSUE TITLE
Installation runs in a loop on the original SSD

### ISSUE THREAD

**Issue by nephthys** [daliansky/XiaoMi-Pro-Hackintosh#118]
Hi,

I can't finish installing OS X on the Mi Notebook Pro i7, either on High Sierra (10.13.6) or Mojave (10.14.2)...

I used the last release of this repository (EFI v1.2.8) and some earlier versions, but the installation is stuck at 60% and restarts after a few minutes to have chosen the installation disc.

Last time, I managed to restart on the second screen (with the Apple logo and "18 minutes remaining") but after a few minutes, the computer restarts again and it turns in a loop...

I'm trying to install OS X on the SSD included with the computer (MZVLB256HAHQ-00000) and I read that there are some problems with this SSD (PM981?) ? How did you do it because it's the original disk? I don't have a second SSD right now to try if it would work better.

Thanks for your help.

**Comment by stevezhengshiqi** [comment]
Currently there’re no way to install macOS in PM981. Older models (which produced before May, 2018 ) have a supported PM961. You have to insert another supported SSD to install mac.

**Comment by stevezhengshiqi** [comment]
By the way, it's a duplicate issue of https://github.com/daliansky/XiaoMi-Pro/issues/82.

**Comment by nephthys** [comment]
@stevezhengshiqi : thanks for the information and sorry for the duplicate...

I removed the SSD from my computer and put it in the Mi Notebook Pro: the installation of High Sierra finally works (with EFI v1.2.8). My SSD is a Samsung 970 Evo 1 TB.

But if I install Mojave (10.14.2) with EFI v1.2.8 or with the latest version of the repository (by clicking on zip archive), the system installs itself but restarts once more during the installation. And after installation, the system restarts again and there is an error. I don't have this problem with High Sierra (10.13.6), it could be due to what?

Thanks in advance.

**Comment by nephthys** [comment]
In fact, it does the same thing on High Sierra (10.13.6): a few minutes have arrived on the desktop, the system crashes and restarts (sometimes with an error instead of the Apple logo)... 

I'm using EFI v1.2.8. I haven't yet had the time to apply HIDPI / Color Profile as the problem arises... How to fix this? Thanks again.

**Comment by MAX-POLKOVNIK** [comment]
@stevezhengshiqi I think you need update readme to indicate that on new versions of laptop macOS can't be installed without changing SSD. Just move SSD block to top of file :)

**Comment by stevezhengshiqi** [comment]
@MAX-POLKOVNIK I think I have written in README `Recent model uses PM981 SSD instead of PM961. This EFI doesn't fully support PM981, and PM981 users can replace their SSDs or visit How to fix PM981 in 10.3.3.`.

**Comment by Menchen** [comment]
I think we need add '(after May 2018)' after 'recent model' to avoid confusion.. maybe in bold.

**Comment by stevezhengshiqi** [comment]
@MAX-POLKOVNIK I am not quite sure the date `May 2018` is exactly when Xiaomi change their SSD. I just highlight the text to alert people.

**Comment by nephthys** [comment]
Good idea for updating the README, it's clearer now :) Thanks @stevezhengshiqi and @MAX-POLKOVNIK 

In any case, I finally installed Mojave with the latest version of this repository. But sometimes I have kernel panic, like when I install the software to manage the WiFi with a USB dongle, where when I do a speed test on the original SSD... Is it possible to record the errors generated following kernel panic?

Thanks anyway for your work, it's nice to use OS X on this laptop ;-)

**Comment by FallenChromium** [comment]
@nephthys there's Activity Console app in macOS which is a log app, inside here you can find .panic files and if tracelog is useful enough - determine what happened. (If you're looking for something related to SSD, if AppleNVME crashed - it's 100% the case)

**Comment by nephthys** [comment]
@FallenChromium Thank you for the precision, I will look at it carefully ;-)

An off-topic question: is there a simple way to completely turn off bluetooth? I don't use it at all on OS X, and it must consume battery for nothing.

About the life of the battery, it's not very high... Maximum 5 hours. It's a lot less than on Windows 10. It's normal or not?

**Comment by Menchen** [comment]
@nephthys read readme about Bluetooth,  and 5h is normal, windows have better pm I think?

**Comment by nephthys** [comment]
Hi,

I haven't yet tested the latest version (v1.2.9) but I have this error sometimes (the rest works pretty well): "_Your computer has detected a potential problem_".

It generates an archive "eficheck.dump" or I can send the report to Apple (not a good idea).

There is no way to disable eficheck cleanly?

Thanks.

**Comment by Menchen** [comment]
After a quick search I found this, so try to install it?(personally I just ignore that. )https://www.tonymacx86.com/threads/your-computer-has-detected-a-potential-problem.234287/
