### ISSUE TITLE
Smbios 8,1 (macbook air late 2018).

### ISSUE THREAD

**Issue by Mateo1234454545** [daliansky/XiaoMi-Pro-Hackintosh#147]
For anyone interested , I'm now using smbios 8,1 and it seems that fits well. So far no problem at all and the benefit is that cpu idles at 1ghz , without cpufriend.

If you want to try it yourself you have to be on Mojave or if you prefer High Sierra you have to add -no_compat_check at clover boot arguments.

Please comment your results.

**Comment by qeeqez** [comment]
What about battery life?

**Comment by stevezhengshiqi** [comment]
Just a remind: Because USBPorts is specific to the SMBIOS model, people need to edit info.plist if model is changed.

**Comment by Mateo1234454545** [comment]
> What about battery life?

Same as with 15,2. Haven't seen any changes so far.


> Just a remind: Because USBPorts is specific to the SMBIOS model, people need to edit info.plist if model is changed.

You are right. But I'm using ssdt for usb.

**Comment by stevezhengshiqi** [comment]
New recommended model is MBP15,4 see https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/245 by @Mateo1234454545 

https://github.com/daliansky/XiaoMi-Pro-Hackintosh/tree/master/one-key-cpufriend has also added MBP15,4 for better power management.
