### ISSUE TITLE
Hard Drive too small

### ISSUE THREAD

**Issue by Vichearith** [daliansky/XiaoMi-Pro-Hackintosh#151]
Hello ! 
I try to install MacOS Mojave on a Xiaomi Pro with an 256Go SSD 760p Series SSDPEKKW256G8XT
After the first restart, I've got a message that the Hard Drive is too small. Doesn't somebody know the origin of this problem ?

**Comment by FallenChromium** [comment]
Was there Windows installation before? If it was not fully formatted there's a chance that EFI partition is too small (should be more than 200MB). By the way, I had Acer Swift 3 with Intel 600p and it caused bullshit situation in OS so it was force-restarting and freezing, I don't know about 760p, but just FYI.

**Comment by Vichearith** [comment]
Could it be due to _Clover Boot Loader_ parameters ?

**Comment by Menchen** [comment]
There shuold be no issue with this repo EFI, so most likely is about your ssd,  as Intel one is known to have poor support with hackintosh..

**Comment by Menchen** [comment]
> I was thinking about the parameters to choose here
> ![image](https://user-images.githubusercontent.com/15385222/52279690-78ae6000-295a-11e9-92d5-2c28d384e9f3.png)

Have you tried to just copy Efi from this repo?  also in which port is your ssd at? and I think sata support is included in this repo

**Comment by Vichearith** [comment]
![1549723056481292696047899365730](https://user-images.githubusercontent.com/15385222/52522054-a9570800-2c80-11e9-83c4-7e8712fde42e.jpg)
That what happen if i only copy the folder EFI and dont use clover

**Comment by Vichearith** [comment]
This is the other message issue 
![15497278498864866133267918208881](https://user-images.githubusercontent.com/15385222/52522924-ce04ad00-2c8b-11e9-804e-ba256a43e23a.jpg)
