### ISSUE TITLE
iMessage not working with nullethernet and new serial

### ISSUE THREAD

**Issue by artemis77799** [daliansky/XiaoMi-Pro-Hackintosh#152]
![schermata 2019-02-08 alle 18 30 27](https://user-images.githubusercontent.com/46961774/52494979-b0720d80-2bcf-11e9-9b15-4a34f4203d39.png)
![schermata 2019-02-08 alle 18 31 36](https://user-images.githubusercontent.com/46961774/52495091-fe871100-2bcf-11e9-8000-a7ba0c447154.png)

I have a fake ethernet and followed lots of tutorials on how to set my serial Number to get iMessage to work but it still doesn't work (ethernet appears as en0 and wifi dongle as en1)

**Comment by Menchen** [comment]
I'm sure that we have  nulletherner kext in this repo so you don't have to touch it... have you checked your serial number at apple ?,also I'm pretty sure that SmUUID empty is wrong.. and trust need be checked And maybe try to delete some iCloud cache..(see at tonymacosx iCloud guide ).

**Comment by artemis77799** [comment]
> I'm sure that we have nulletherner kext in this repo so you don't have to touch it... have you checked your serial number at apple ?,also I'm pretty sure that SmUUID empty is wrong.. and trust need be checked And maybe try to delete some iCloud cache..(see at tonymacosx iCloud guide ).

I did everything you said and still does not work, my serial appears as not valid at apple but i Think that's ok, people online say that non valid serials work fine and won't mess with people using real macs

**Comment by Menchen** [comment]
After using the serial it became "valid" at apple.... also check at other site before using it to check format. And if you did all thing it shuold be working.

**Comment by artemis77799** [comment]
> After using the serial it became "valid" at apple.... also check at other site before using it to check format. And if you have make sure that all thing is done correctly, it shuold be working.

![schermata 2019-02-08 alle 19 35 57](https://user-images.githubusercontent.com/46961774/52498324-c9cb8780-2bd8-11e9-880e-2705a0b9852b.png)
serial checked, still not working

**Comment by artemis77799** [comment]
![schermata 2019-02-08 alle 19 38 00](https://user-images.githubusercontent.com/46961774/52498426-0f885000-2bd9-11e9-880a-36ba28689eab.png)
 maybe that's because ethernet doesn't have an ip?

**Comment by stevezhengshiqi** [comment]
Duplicate issue, this one is pretty the same as https://github.com/daliansky/XiaoMi-Pro/issues/152.

The ethernet in the picture is a fake one, so it won't have IP address.

Please read instruction in https://www.tonymacx86.com/threads/how-to-fix-imessage.110471/. Detailed instructions and informative replies are also there.

**Comment by artemis77799** [comment]
> Duplicate issue, this one is pretty the same as #152.
> 
> The ethernet in the picture is a fake one, so it won't have IP address.
> 
> Please read instruction in https://www.tonymacx86.com/threads/how-to-fix-imessage.110471/. Detailed instructions and informative replies are also there.

![schermata 2019-02-08 alle 19 54 36](https://user-images.githubusercontent.com/46961774/52499315-6e4ec900-2bdb-11e9-9908-a00ff112b818.png)
now it has ip, still not working

**Comment by Menchen** [comment]
Read Link above... may need remove mac from your iCloud....

**Comment by stevezhengshiqi** [comment]
As I said, please read https://www.tonymacx86.com/threads/how-to-fix-imessage.110471/ carefully and safe time from trying something else. As you can see in the last line, the MAC address of ethernet is 11:22:33:44:55:66, which means that the ethernet is a fake one and no use to give it ip.
