### ISSUE TITLE
Where do you get the BIOS?

### ISSUE THREAD

**Issue by johnnync13** [daliansky/XiaoMi-Pro-Hackintosh#162]
I’m looking for the XMAKB3M0P130D bios version. The XMAKB3M0P120C  bios, I found on bbs.xiaomi forum chinese. I have mi Air 2018

**Comment by vimcaw** [comment]
I found this: 
https://en.miui.com/thread-2561359-9-1.html#post_34122183
![image](https://user-images.githubusercontent.com/21964227/53800727-5408d080-3f78-11e9-9adc-eb47fe7a3d17.png)

**Comment by johnnync13** [comment]
but this not official .exe @vimcaw

**Comment by Raphencoder** [comment]
Hi @johnnync13, I used this website to flash mu bios, I think this is the official ones
[Techtabs](https://techtablets.com/xiaomi-mi-notebook-pro/downloads/)

**Comment by johnnync13** [comment]
here is all bios Xiaomi laptops https://drive.google.com/drive/folders/1RIqdN3C9UDBN0KPwazyaerW1bEApivqN

**Comment by webcaptcha** [comment]
@johnnynunez Hi is it a way to flash from Linux? All BIOS here has .exe extension
