### ISSUE TITLE
使用帧缓存和 0xE2 修复的批处理后变砖了....

### ISSUE THREAD

**Issue by datougansini** [daliansky/XiaoMi-Pro-Hackintosh#166]
Xiaomi PRO GTX 使用后BIOS变砖头了....求大佬们告知如何救机!!!!!

**Comment by Menchen** [comment]
有保修的话去维修点让官方修，自己有能力的话去找备份然后拆机 spi 刷。

**Comment by stevezhengshiqi** [comment]
仓库里的脚本只适用于MX150版。如果没有备份BIOS的话可能需要去售后维修了。README有注明只限于0603和0906 BIOS。

**Comment by bliekp** [comment]
Can we please use English? Then the rest of the globe can learn from you guys too! :)
