### ISSUE TITLE
Using virtual machine to upload the onboard Internal Bluetooth firmware

### ISSUE THREAD

**Issue by wisper-shadow** [daliansky/XiaoMi-Pro-Hackintosh#168]
@daliansky following the [instruction](https://osxlatitude.com/forums/topic/10127-updated-nov-2017-fix-btfirmwareuploader-in-macos-high-sierra/) mentioned in the [Work Around with Bluetooth](https://github.com/daliansky/XiaoMi-Pro/wiki/Work-Around-with-Bluetooth), I successfully power up the Internal Bluetooth. 
![system info](https://user-images.githubusercontent.com/29170455/54830523-9c9fe800-4cf3-11e9-8055-b2cfbe67802b.png)
![Airdrop](https://user-images.githubusercontent.com/29170455/54830584-bb05e380-4cf3-11e9-96b7-e6f0be65620c.png)
And I finished the airdrop test.
However, I find that when i using my iPhone, i cannot trigger the Handoff function. I hope you can help me with this. 
Also, i consider that you can make a instruction of powering the Internal Bluetooth in the ReadMe.

**Comment by Menchen** [comment]
Well first of all, steve is maintaining this repo now, and what wifi card are you using? and how is your iCloud account setup( correct working smbios)?

**Comment by wisper-shadow** [comment]
> Well first of all, steve is maintaining this repo now, and what wifi card are you using? and how is your iCloud account setup( correct working smbios)?
This step is to power up the internal Intel Bluetooth. Also, my iCloud account functions normally.

**Comment by Menchen** [comment]
Which wifi card are you using?( external usb dongle or m2 card. )

**Comment by wisper-shadow** [comment]
> Which wifi card are you using?( external usb dongle or m2 card. )

我是说按照蓝牙解决方案里的第三种通过虚拟机上传固件来驱动板载的英特尔蓝牙。

**Comment by stevezhengshiqi** [comment]
接力必须要m2内置网卡+任意蓝牙

**Comment by wisper-shadow** [comment]
@stevezhengshiqi 我也使用的淘宝BCM94360CS2转接m.2网卡，但是我没有用博通蓝牙，用的是板载的英特尔蓝牙，这是我的wifi信息，设置里也出现了handoff的选项，但是我在使用iPhone的时候不弹出dock栏图标。
![Wi-Fi](https://user-images.githubusercontent.com/29170455/54861125-1caf6780-4d5f-11e9-9558-37d5db9e7be5.png)

**Comment by stevezhengshiqi** [comment]
尝试重新登录Mac和iPhone的iCloud账户

**Comment by wisper-shadow** [comment]
@stevezhengshiqi 仍然无法启用handoff。我会焊完蓝牙飞线再测试。
