### ISSUE TITLE
Need help on keyboard shortcut F6, F7, and F11

### ISSUE THREAD

**Issue by stevezhengshiqi** [daliansky/XiaoMi-Pro-Hackintosh#181]
Hi, I started to work on the hotkeys very early actually, about a year ago, and I didn't get much progress on it. I decided to share my results and hope smart guys could bring new ideas.

### Already worked:

Natively, we have working hotkeys on F1(Mute), F2(Volume Down), F3(Volume Up), F8(Switch Apps), F9(Disable Trackpad), and F10(Keyboard Light Off). And a year ago, I followed [[Guide] Patching DSDT/SSDT for LAPTOP backlight control](https://www.tonymacx86.com/threads/guide-patching-dsdt-ssdt-for-laptop-backlight-control.152659/) and successfully mapped `Brightness Down` and `Brightness Up` to F4 and F5, see the code in [SSDT-LGPA.dsl](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/ACPI/SSDT-LGPA.dsl#L123).

### Problems we need to solve are:
  - Pressing F6 key triggers Print Screen window, and we hope F6 key triggers Video Mirror function.
  - Nothing happens when press F7, which supposed to trigger Screenshot function. However, by using [ApplePS2SmartTouchPad](https://osxlatitude.com/forums/topic/1948-elan-focaltech-and-synaptics-smart-touchpad-driver-mac-os-x/), the screenshot function works well, so studying the driver code may help.
  - Nothing happens when press F11, which supposed to trigger Print Screen window.

### What I have done

It seems like the function keys are handled in ACPI by GPE method. I used [ACPIDebug](https://github.com/RehabMan/OS-X-ACPI-Debug) and patched my DSDT. I did find corresponding DSDT lines for F3, F4 and F6, but there's no return for F7 and F11. I will share my patched DSDT below. 

I also debug all the PS2 codes for each key by using [ioio](https://github.com/RehabMan/OS-X-ioio), and I will attach a picture below.

The final is coming so I won't spend more time on this. Hope someone could work on this and bring us prefect function keys!

### Resources:
  - [Remapping keyboard with VoodooPS2](https://www.tonymacx86.com/threads/remapping-keyboard-with-voodoops2.207586/)
  - [[Guide] Patching DSDT/SSDT for LAPTOP backlight control](https://www.tonymacx86.com/threads/guide-patching-dsdt-ssdt-for-laptop-backlight-control.152659/)
  - [How to Use Custom Keyboard Mapping](https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/wiki/How-to-Use-Custom-Keyboard-Mapping)
  - [ApplePS2ToADBMap.h](https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/blob/master/VoodooPS2Keyboard/ApplePS2ToADBMap.h)
  - [Rehabman/HP-Envy-DSDT-Patch/SSDT-Q13.dsl](https://github.com/RehabMan/HP-Envy-DSDT-Patch/blob/fb21808b96f453a02bdbe0fc0c908bada34å08878/SSDT-Q13.dsl)

[Patched DSDT.dsl.zip](https://github.com/daliansky/XiaoMi-Pro/files/3130766/Patched.DSDT.dsl.zip)
[ApplePS2SmartTouchPad.kext.zip](https://github.com/daliansky/XiaoMi-Pro/files/3130847/ApplePS2SmartTouchPad.kext.zip)
![Keyboard](https://user-images.githubusercontent.com/36894554/56957947-60c23300-6b7b-11e9-9b00-12845b2235ae.jpg)

**Comment by influenist** [comment]
Hey Steve,

I have the same issue with 12.5. Cant figure how to remap these using ACPI. Would love to provide some input on this matter once I find time.

**Comment by stevezhengshiqi** [comment]
#### Update:
I found out that Case 10 in SSDT-LGPA is for the Screenshot key. Since Apple does not support screenshot PS2 code, and the screenshot hotkey is the combination of Command + Shift + 3, I decide to map all these three keys to the screenshot key.

- First, I assign the PS2 code of `shift` key to a DEADKEY `e025` and assign the PS2 code of `3` key to a DEADKEY `e026`. This step is done in SSDT-PS2K.
- Second, in SSDT-LGPA, I add a few Notify statements to let OS call the combination of `Win`, `Shift` and `3` key. According to https://www.tonymacx86.com/threads/remapping-keyboard-with-voodoops2.207586/post-1373254,

> 0x02xx: extended PS2 codes (e0)... make/break separate

so we can make sure all the three keys are pressed down at the same time by the following code:
```
Notify (PS2K, 0x025B) // Press Down Win
Notify (PS2K, 0x0225) // Press Down e025
Notify (PS2K, 0x0226) // Press Down e026
Notify (PS2K, 0x02A6) // Press Up e026
Notify (PS2K, 0x02A5) // Press Up e025
Notify (PS2K, 0x02DB) // Press Up Win
```

Therefore, we got the screenshot key work.

**Comment by stevezhengshiqi** [comment]
This issue is mostly solved in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/commit/49427e3108a20cff1c146de49a87d47cb5c8daf2 with 0A07 BIOS firmware. But older firmware still needs discovery. I won’t dig deeper anymore and anyone who is interested can take a look.

**Comment by stevezhengshiqi** [comment]
For details on how I implement screenshot and other function keys, here's the instruction I wrote: https://www.insanelymac.com/forum/topic/344327-guide-map-screenshotmission-controlother-function-keys-to-keyboard-hotkeys-without-syspref/
