### ISSUE TITLE
OpenCore Bootloader

### ISSUE THREAD

**Issue by Mateo1234454545** [daliansky/XiaoMi-Pro-Hackintosh#184]
Would be great if you found time to make efi using the new opencore bootloader.

**Comment by stevezhengshiqi** [comment]
Hi, I am in a school final actually, and I hope someone else could make an oc for us.
OC Configuration Instruction is in https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf for anyone who is intertested.

**Comment by stevezhengshiqi** [comment]
Great News! I succeeded in booting with OpenCore, will submit my branch later.

**Comment by johnnync13** [comment]
What it this for our laptops?

**Comment by jackreeves** [comment]
Opencore is a newer replacement for clover. Have a read of interested...seems like it could be good. Will test once Steve commits.

**Comment by johnnync13** [comment]
I would like to do for Mi Air and others. I will read more about this

**Comment by jackreeves** [comment]
What are your initial thoughts @stevezhengshiqi ? Improvement in performance / behavior expected with opencore? Ready for help testing? Happy to help on my i7/16gb.

**Comment by stevezhengshiqi** [comment]
@jackreeves To be honest, currently, I can't tell advantages of using OpenCore than Clover. For example, the unfriendly GUI, no common ACPI fixes in Clover(e.g. FixRTC), fewer instructions...

The things I notice that OpenCore does better: it has more customizations for patching ACPI. In Clover, we only have `Find`, `Replace`, `TgtBridge`(buggy), and in OpenCore, there are `Mask`, `OemTableId`... which supports advanced patching.

I once read a post which says that OpenCore supports SHA-256 hashing by running `create_vault.sh` to avoid unintended modifications. If you sign `OpenCore.efi` and `BOOTx64.efi` with appropriate key, it even support `SecureBoot` in BIOS.

However, I have great confidence for [Acidanthera](https://github.com/acidanthera). They have taken over the most hackintosh kernel extensions projects, and I believe in the future, they can make their OpenCore boot loader work with their kexts in a perfect way.

**Comment by Mateo1234454545** [comment]
I agree.
As untill now there is no diffirence in perfomance,stability etc.
But you never know in the future.

**Comment by onemanosx** [comment]
> Great News! I succeeded in booting with OpenCore, will submit my branch later.

How did you do renames with TgtBridge for Opencore?

**Comment by stevezhengshiqi** [comment]
@onemanosx Sorry for delay. I didn’t see this post til today. Actually, I force myself to not use TgtBridge in Clover because it’s so buggy. All OEM SSDT will be accidentally influenced by TgrBridge in Clover.

I add more strings in Find for more specific patch.

**Comment by onemanosx** [comment]
![64506363_1240934369390492_5907089266327945216_n](https://user-images.githubusercontent.com/37058929/60030314-56349d80-96d5-11e9-9222-b1ce328a01be.jpg)

This is how I recently figured out. Where "Count" is the number of times patch is to be executed and "Skip" is the patch location in ACPI scope
But its painstaking process. Would love to know how you did yours. Mind to share?
