### ISSUE TITLE
OpenCore and I2C KP

### ISSUE THREAD

**Issue by webfalter** [daliansky/XiaoMi-Pro-Hackintosh#192]
I have a KernelPanic when I shut down or restart with I2C Kext. However, this only occurs in conjunction with OpenCore.

**Comment by stevezhengshiqi** [comment]
It is a known issue in VoodooI2C’s repository: https://github.com/alexandred/VoodooI2C/issues/187

**Comment by gshenlgli** [comment]
抱歉，不会




| |
高胜利
|
|
邮箱：gshengli@126.com
|
On 06/12/2019 02:26, MengChen. Huang wrote:

Can someone confirm VoodooI2C is working with OpenCore under Catalina?

**Comment by stevezhengshiqi** [comment]
Fixed. Try to use the VoodooI2C and VoodooI2CHID in this repository. Tested in 10.14 in OpenCore.

**Comment by johnnync13** [comment]
My trackpad not works on Open Core. I use voodooi2csynaptics and the GenI2C repository patches for my DSDT. https://github.com/johnnync13/EFI-Xiaomi-Notebook-air-12-5

**Comment by stevezhengshiqi** [comment]
@johnnync13 First, need to make sure your trackpad is working in Clover.

Then, be careful to the loading sequence of VoodooI2C plugins. VoodooGPIO and VoodooService first, then VoodooI2C. You can take the OC config in this repository as a reference.

**Comment by johnnync13** [comment]
Yeah I know but I need some more patches

**Comment by johnnync13** [comment]
Gpio mode, TPD0 and USTP

**Comment by stevezhengshiqi** [comment]
Just do the same patch as in Clover.

**Comment by johnnync13** [comment]
Yeah I have the same patches. Gpio and vodooi2c too because I can see on ioreg but TPD0 not appear. Do you know how Can I fix OSI?

**Comment by stevezhengshiqi** [comment]
@johnnync13 It seems that you didn’t add your SSDT-XOSI path in your config

**Comment by johnnync13** [comment]
@stevezhengshiqi now my trackpad works!
