### ISSUE TITLE
Apple Music not downloading song on my disk

### ISSUE THREAD

**Issue by Recreabox** [daliansky/XiaoMi-Pro-Hackintosh#193]
All is great on my Xiaomi Mi Pro i7 1 TB Nvme but i can't download tack on Apple Music.
It automatically fail to download...

**Comment by ftapps** [comment]
I think Apple Music uses your computer MAC address to identify your computer. The MAC address in the EFI folder is set to 11:22:33:44:55:66. Try changing it to a random value and restart your computer. You can change it by editing the file SSDT-RMNE.aml (EFI/CLOVER/ACPI/patched) using the app MaciASL.

**Comment by Violettx** [comment]
Hi guys I've tried this way to change my MAC address for accessing Apple Music library and it worked pretty good. Just use a random MAC address and that will be fine. I think this issue could be closed.

**Comment by Recreabox** [comment]
Hello ! Sorry for the late answer...

I tried to update SSDT-RMNE.aml and change my MAC address to a new one with MaciASL app but when i try to save the changes i have lot of errors.

There is a way to just change the MAC address without having errors ?

**Comment by stevezhengshiqi** [comment]
@Recreabox Run `bash -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/master/install.sh)"` and type 11.
