### ISSUE TITLE
macOS Catalina?

### ISSUE THREAD

**Issue by GummybearCanada** [daliansky/XiaoMi-Pro-Hackintosh#200]
Does macOS Catalina (beta) work on the Xiaomi Mi Notebook Pro?

**Comment by stevezhengshiqi** [comment]
Great question. It’s near bed time in my time zone. I may get sleep during updating, so welcome other people to test.

**Comment by stevezhengshiqi** [comment]
Success
![Screen Shot 2019-06-04 at 4 50 33 AM](https://user-images.githubusercontent.com/36894554/58833877-9e3b4400-8684-11e9-8bb6-6b94201bf27a.png)
So far what's working:
- Audio
- Keyboard
- USB

**Comment by bliekp** [comment]
Very nice! Was it a seamless install? Just use the installer and "go"?

**Comment by stevezhengshiqi** [comment]
It needs a few modifications:
- Add boot argument: `-lilubetaall`
- Inject ig-platform-id:0x12345678
- Add kerneltopatch, according to https://www.insanelymac.com/forum/topic/339035-pre-release-macos-catalina/:
```
find
00 85 C0 0F 84 87 00 00 00 49
replace
00 85 C0 90 90 90 90 90 90 49
```

BTW, the graphic card and trackpad are not working as we expected, so I don't recommend to update at this time.

**Comment by stevezhengshiqi** [comment]
For solving graphics 7mb,
- try to build latest WhateverGreen with latest Lilu

I didn’t have laptops these days, so I can’t test more.

**Comment by johnnync13** [comment]
With lastest kext works fine with 1536mb...

**Comment by johnnync13** [comment]
@stevezhengshiqi accept my pull request, please!

**Comment by GummybearCanada** [comment]
![C95719AF-2E6B-4DC2-9B39-DA7F5365E0CA](https://user-images.githubusercontent.com/48004998/58933874-a653bc00-8736-11e9-914c-cb48e2688f0d.jpeg)
It is stuck on "estimating time remaining" for a few hours.
What might be the problem? Is there a log file I can provide you?

**Comment by johnnync13** [comment]
@GummybearCanada try https://github.com/johnnync13/XiaoMi-Pro/releases/tag/v1.3.4

**Comment by GummybearCanada** [comment]
![6362E16B-7461-401E-A74A-5D0C6963D2C2](https://user-images.githubusercontent.com/48004998/59010870-cd76c000-8800-11e9-9a3b-41c823f3f267.jpeg)
You are a genius! It works perfectly after I used your EFI folder, including graphics and trackpad.

**Comment by GummybearCanada** [comment]
Unfortunately my USB Wifi doesn't work anymore. I have ASUS AC53 Nano, which is RTL8812BU chipset. I installed the driver for macOS from official ASUS website like I did for previous versions, but after restart nothing happened.

**Comment by rewhex** [comment]
@GummybearCanada Hello, I have 2 questions about installing, can I just run "install macOS Catalina.app" from apps directory, and also, can I edit my EFI folder before installation?

**Comment by johnnync13** [comment]
@rewhex you should put this efi before. It is compatibility with 10..14.x too

**Comment by GummybearCanada** [comment]
Found a USB Wifi Driver for Catalina https://github.com/chris1111/Wireless-USB-Adapter-Clover
The driver on ASUS website is annoyingly still from 2017.

> @GummybearCanada Hello, I have 2 questions about installing, can I just run "install macOS Catalina.app" from apps directory, and also, can I edit my EFI folder before installation?

I created a bootable USB and did a clean install. I don't have enough technical knowledge to say whether running the installer from the apps directory would work or not, but my guess is that it should work...
In both cases, you should use the EFI folder from johnnync13 before starting the install.

**Comment by GummybearCanada** [comment]
Anyone able to get sidecar working?

**Comment by LisztFU** [comment]
今天的10.15beta3更新时最后20%会直接关机。重复无解。

**Comment by stevezhengshiqi** [comment]
@LisztFU 我这里无问题，beta3。
<img width="583" alt="Screen Shot 2019-07-02 at 11 27 14 PM" src="https://user-images.githubusercontent.com/36894554/60561492-b359d000-9d21-11e9-8105-32e1b7251f0a.png">
