### ISSUE TITLE
problem with config plist

### ISSUE THREAD

**Issue by artemis77799** [daliansky/XiaoMi-Pro-Hackintosh#209]
Hi, I updated my efi folder and noticed an audio problem as described here #207, I was able to isolate the source of the problem and it turned out it was in the config.plist, so I decided to change it with my old config.plist, now audio has no problem at all but brightness keys no longer work, with the new config.plist audio has problems but brightness keys actually work. I don't understand the problem, hope someone can help me.
I'm uploading the two config.plist as txt files

-old config.plist (working audio, not working brightness)
[config.txt](https://github.com/daliansky/XiaoMi-Pro/files/3268507/config.txt)

-new config.plist (buggy audio, working brightness)
[config.txt](https://github.com/daliansky/XiaoMi-Pro/files/3268508/config.txt)

**Comment by Menchen** [comment]
Try adding `<key>SetIntelBacklight</key>
		<true/>
		<key>SetIntelMaxBacklight</key>
		<true/>` search in new config for location..

It would be better if you can diff the config and test what's is causing the problem...

**Comment by stevezhengshiqi** [comment]
@artemis77799 Also, try to use PlistEditor o TextEditor to modify config.plist, and never use Clover Configurator. It is not recommended by Rehabman and Clover dev team.

**Comment by artemis77799** [comment]
> @artemis77799 Also, try to use PlistEditor or TextEditor to modify config.plist, and never use Clover Configurator. It is not recommended by Rehabman and Clover dev team.
> 
> Since both of the configs you sent are corrupted, you need a new one from latest release

with the config.plist in the new release I have that audio problem

**Comment by stevezhengshiqi** [comment]
Your new config.plist is not the origin one in release pack.

**Comment by artemis77799** [comment]
> Your new config.plist is not the origin one in release pack if you compare. Agree that you can generate a diff file to find difference.

correct, I tried now with the original config.plist in the latest release and I still have the problem, here's the diff between the old working plist (brightnes not working) and the one in the latest release 
[diff.txt](https://github.com/daliansky/XiaoMi-Pro/files/3268584/diff.txt)
