### ISSUE TITLE
在10.14.5上无法使用触摸板双击来移动窗口

### ISSUE THREAD

**Issue by justforlxz** [daliansky/XiaoMi-Pro-Hackintosh#212]
还遇到一个问题，手指在触摸板左下角按下，此时光标就无法移动了，但是如果向里面稍微移动一点点，就可以用另一根手指进行光标的移动。机器是19款的mx250pro。

谢谢。

**Comment by stevezhengshiqi** [comment]
触控板问题请反馈给触控板驱动作者https://github.com/alexandred/VoodooI2C，也可以在触控板讨论区https://gitter.im/alexandred/VoodooI2C和大佬讨论
