### ISSUE TITLE
Installation of a wifi card on the second m2 slot

### ISSUE THREAD

**Issue by Lillabius1314** [daliansky/XiaoMi-Pro-Hackintosh#213]
Hi, I purchased a compatible wificard to put in my second m2 slot, do I need to install some kexts or change something in the EFI folder before the installation of the card or it will be detected by default? Thanks for your time

**Comment by Menchen** [comment]
It depends whether your card need extra driver or not..

**Comment by Lillabius1314** [comment]
> It depends whether your card need extra driver or not..

I have a BCM943602CS, I'm asking if I need additional kexts because I red it in the end of this guide but since I use a different card I don't know if this is the case or not 
[Xiaomi.Mi.Notebook.Pro.BROADCOM.WiFi.Installation.Guide.v0.3.pdf](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/3311076/Xiaomi.Mi.Notebook.Pro.BROADCOM.WiFi.Installation.Guide.v0.3.pdf)

**Comment by Menchen** [comment]
Apple brand wifi card dont need driver..

**Comment by ltfysl** [comment]
did you manage to get the BCM943602CS working ?
Do you need a adapter or does it fit in the second m2 slot ?

**Comment by stevezhengshiqi** [comment]
No need extra kexts if it's an Apple card. https://github.com/acidanthera/AirportBrcmFixup is needed if you have any problem.
