### ISSUE TITLE
Will this bluetooth card will be fine ?

### ISSUE THREAD

**Issue by P0SlX** [daliansky/XiaoMi-Pro-Hackintosh#219]
Hi I would like to know, as I don't have access to Taobao, if this bluetooth card adapter will be fine and will works just as the Taobao's one:
https://www.aliexpress.com/item/32949190082.html?spm=a2g0o.cart.0.0.7b843c00ZsSMYJ

Thanks !

**Comment by influenist** [comment]
Hi, should work indeed, yet please note that you need to solden the usb lanes to make BT work.
