### ISSUE TITLE
长时间睡眠会重启

### ISSUE THREAD

**Issue by Likenttt** [daliansky/XiaoMi-Pro-Hackintosh#222]
Anonymous UUID:       8451CD59-99BB-AF4C-7596-76B0513E20B8

Fri Jul 19 14:08:49 2019

*** Panic Report ***
panic(cpu 3 caller 0xffffff800f1c9973): "A kext releasing a(n) IOBluetoothHostControllerUSBTransport has corrupted the registry."@/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-4903.261.4/libkern/c++/OSObject.cpp:215
Backtrace (CPU 3), Frame : Return Address
0xffffff81feb63c00 : 0xffffff800ebaea2d 
0xffffff81feb63c50 : 0xffffff800ece9e95 
0xffffff81feb63c90 : 0xffffff800ecdb70a 
0xffffff81feb63d00 : 0xffffff800eb5bb40 
0xffffff81feb63d20 : 0xffffff800ebae447 
0xffffff81feb63e40 : 0xffffff800ebae293 
0xffffff81feb63eb0 : 0xffffff800f1c9973 
0xffffff81feb63ed0 : 0xffffff800f23c5e7 
0xffffff81feb63ef0 : 0xffffff800f239268 
0xffffff81feb63f30 : 0xffffff800f256362 
0xffffff81feb63f70 : 0xffffff800f2558bc 
0xffffff81feb63fa0 : 0xffffff800eb5b0ce 

BSD process name corresponding to current thread: kernel_task
Boot args: darkwake=0 dart=0 gfxrst=1 

Mac OS version:
18F132

Kernel version:
Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
Kernel UUID: 7C8BB636-E593-3CE4-8528-9BD24A688851
Kernel slide:     0x000000000e800000
Kernel text base: 0xffffff800ea00000
__HIB  text base: 0xffffff800e900000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)

System uptime in nanoseconds: 9885887363492
last loaded kext at 7586931756185: com.apple.driver.AppleXsanScheme	3 (addr 0xffffff7f92b59000, size 32768)
last unloaded kext at 7664358895900: com.apple.driver.AppleXsanScheme	3 (addr 0xffffff7f92b59000, size 32768)
loaded kexts:
org.virtualbox.kext.VBoxNetAdp	6.0.8
org.virtualbox.kext.VBoxNetFlt	6.0.8
org.virtualbox.kext.VBoxUSB	6.0.8
org.virtualbox.kext.VBoxDrv	6.0.8
com.realtek.driver.RtWlanU	1830.20.b31
as.acidanthera.voodoo.driver.PS2Keyboard	2.0.2
org.rehabman.driver.NullEthernet	1.0.6
com.alexandred.VoodooI2CHID	1
com.alexandred.VoodooI2C	2.2
org.coolstar.VoodooGPIO	1.1
as.acidanthera.voodoo.driver.PS2Controller	2.0.2
as.vit9696.SMCProcessor	1.0.6
as.lvs1974.HibernationFixup	1.2.6
as.vit9696.AppleALC	1.3.9
org.tw.CodecCommander	2.7.1
as.vit9696.WhateverGreen	1.3.1
com.rehabman.driver.USBInjectAll	0.7.1
ru.usrsse2.SMCBatteryManager	1
as.vit9696.VirtualSMC	1.0.6
as.vit9696.Lilu	1.3.7
com.alexandred.VoodooI2CServices	1
com.apple.filesystems.smbfs	3.3.2
com.apple.driver.AudioAUUC	1.70
com.apple.fileutil	20.036.15
com.apple.filesystems.autofs	3.0
com.apple.driver.AGPM	110.25.10
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AppleUpstreamUserClient	3.6.5
com.apple.driver.AppleMCCSControl	1.5.9
com.apple.driver.AppleHDA	282.54
com.apple.private.KextAudit	1.0
com.apple.driver.AppleGraphicsDevicePolicy	3.40.16
com.apple.driver.AppleIntelPCHPMC	2.0.1
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleIntelKBLGraphics	12.0.9
com.apple.AGDCPluginDisplayMetrics	3.40.16
com.apple.driver.eficheck	1
com.apple.driver.AppleHV	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	6.0.12f1
com.apple.driver.pmtelemetry	1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleSMCLMU	212
com.apple.driver.AppleIntelKBLGraphicsFramebuffer	12.0.9
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleTopCaseHIDEventDriver	138.3
com.apple.driver.AppleVirtIO	2.1.3
com.apple.filesystems.hfs.kext	407.200.4
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleSystemPolicy	1.0
com.apple.filesystems.apfs	945.260.7
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleBacklight	170.12.11
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	201
com.apple.security.TMSafetyNet	8
com.apple.iokit.IOUSBUserClient	900.4.2
com.apple.kext.triggers	1.0
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.driver.DspFuncLib	282.54
com.apple.kext.OSvKernDSPLib	528
com.apple.driver.AppleGraphicsControl	3.40.16
com.apple.driver.AppleHDAController	282.54
com.apple.iokit.IOHDAFamily	282.54
com.apple.iokit.IOBluetoothHostControllerUSBTransport	6.0.12f1
com.apple.iokit.IOBluetoothHostControllerTransport	6.0.12f1
com.apple.iokit.IOAVBFamily	740.1
com.apple.plugin.IOgPTPPlugin	740.2
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.iokit.IOSkywalkFamily	1
com.apple.driver.AppleSSE	1.0
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.iokit.IOAcceleratorFamily2	404.9
com.apple.iokit.IOSurface	255.5.4
com.apple.AppleGPUWrangler	3.40.16
com.apple.AppleGraphicsDeviceControl	3.40.16
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleHSBluetoothDriver	138.3
com.apple.driver.IOBluetoothHIDDriver	6.0.12f1
com.apple.iokit.IOBluetoothFamily	6.0.12f1
com.apple.driver.AppleActuatorDriver	2450.1
com.apple.driver.AppleMultitouchDriver	2450.1
com.apple.driver.AppleInputDeviceSupport	2440.2
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.iokit.IOSerialFamily	11
com.apple.filesystems.hfs.encodings.kext	1
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	530.51
com.apple.iokit.IOGraphicsFamily	530.66
com.apple.security.quarantine	3
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.driver.DiskImages	493.0.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	456.260.3
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	145.200.2
com.apple.iokit.IOSCSIBlockCommandsDevice	408.250.3
com.apple.iokit.IOSCSIArchitectureModelFamily	408.250.3
com.apple.iokit.IOStorageFamily	2.1
com.apple.kext.CoreTrust	1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOReportFamily	47
com.apple.iokit.IOTimeSyncFamily	740.2
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0

EOF
Model: MacBookPro14,1, BootROM 196.0.0.0.0, 4 processors, Intel Core i7, 1.99 GHz, 16 GB, SMC 2.43f6
Graphics: Intel UHD Graphics 620, Intel UHD Graphics 620, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 8 GB, DDR4, 2400 MHz, Samsung, -
Memory Module: BANK 1/DIMM0, 8 GB, DDR4, 2400 MHz, Samsung, -
Bluetooth: Version 6.0.12f1, 3 services, 19 devices, 1 incoming serial ports
Network Service: 802.11ac NIC, Ethernet, en2
PCI Card: Intel UHD Graphics 620, VGA-Compatible Controller, Internal
PCI Card: Intel Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th Gen Core Processor Gaussian Mixture Model, System Peripheral, Internal
PCI Card: Intel Sunrise Point-LP USB 3.0 xHCI Controller, USB eXtensible Host Controller, Internal
PCI Card: Intel Sunrise Point-LP Serial IO I2C Controller #0, Signal Processing Controller, Internal
PCI Card: Intel Sunrise Point-LP Serial IO I2C Controller #1, Signal Processing Controller, Internal
PCI Card: Intel Sunrise Point-LP CSME HECI #1, Communication Controller, Internal
PCI Card: Intel Sunrise Point-LP PMC, Memory Controller, Internal
PCI Card: Intel Sunrise Point-LP HD Audio, Audio Device, Internal
PCI Card: Intel Sunrise Point-LP SMBus, System Management Bus, Internal
PCI Card: Intel Sunrise Point-LP PCI Express Root Port #5, NVM Express Controller, Internal
PCI Card: Intel Sunrise Point-LP PCI Express Root Port #9, NVM Express Controller, Internal
PCI Card: Intel Wireless 8265, Other Network Controller, Internal
USB Device: USB 3.0 Bus
USB Device: MI Mouse A1w
USB Device: XiaoMi USB 2.0 Webcam
USB Device: Bluetooth HCI
USB Device: 802.11ac NIC
Thunderbolt Bus:

**Comment by stevezhengshiqi** [comment]
根据日志可以看出是蓝牙导致的。

请根据[插入一个USB蓝牙](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/蓝牙解决方案#插入一个usb蓝牙)章节来屏蔽内置蓝牙。

**Comment by Likenttt** [comment]
关闭内置蓝牙是否可行呢

**Comment by stevezhengshiqi** [comment]
内置intel蓝牙无法通过按钮关闭，只能按照教程替换ssdt来屏蔽。
