### ISSUE TITLE
How Can I disable internal bluetooth?

### ISSUE THREAD

**Issue by DarkMac90** [daliansky/XiaoMi-Pro-Hackintosh#227]
I have daliansky EFI folder.

**Comment by stevezhengshiqi** [comment]
@DarkMac90 Hi, please read https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/Work-Around-with-Bluetooth#insert-a-usb-bluetooth

and you can also run the following command in terminal and choose 2
```bash
bash -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/master/install.sh)"
```

**Comment by stevezhengshiqi** [comment]
Same issue as https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/24
