### ISSUE TITLE
耳机无声，必须热重启，就是在Win下有声音重启后进入mac就有声音了

### ISSUE THREAD

**Issue by lifeng5478** [daliansky/XiaoMi-Pro-Hackintosh#232]
耳机无声，必须热重启，就是在Win下有声音重启后进入mac就有声音了

**Comment by stevezhengshiqi** [comment]
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/ALCPlugFix/README_CN.md

**Comment by lifeng5478** [comment]
这个方法进去以后只要插拔两三次耳机就又没有声音了。。。。。

**Comment by Menchen** [comment]
@lifeng5478 你说的是那个方法？

**Comment by lifeng5478** [comment]
> @lifeng5478 你说的是那个方法？

https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/ALCPlugFix/README_CN.md

**Comment by lifeng5478** [comment]
@Menchen https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/ALCPlugFix/README_CN.md
我用这个指令打开了耳机，但是插拔两次之后耳机又失效了，必须要重启才可以解决。重启之后要是插拔两次依旧会失效。

**Comment by Menchen** [comment]
直接在终端里面运行 ’ALCPlugFix’ 然后插拔耳机有输出吗？

**Comment by lifeng5478** [comment]
@Menchen 直接运行是没有声音的，必须要重启才可以。重启之后第一次插拔耳机没有问题，但是2，3次以后就没有声音了。

**Comment by Menchen** [comment]
直接运行后插拔耳机有输出吗？

**Comment by lifeng5478** [comment]
没有。就在给你回复之前，我刚刚测试过。

**Comment by Menchen** [comment]
上传整个运行的输出看看。

**Comment by lifeng5478** [comment]
` ____    _                   _____   _         
|  _ \  | |  _   _    __ _  |  ___| (_) __  __ 
| |_) | | | | | | |  / _` | | |_    | | \ \/ / 
|  __/  | | | |_| | | (_| | |  _|   | |  >  <  
|_|     |_|  \__,_|  \__, | |_|     |_| /_/\_\ 
                      |___/                    
支持小米笔记本电脑Pro(ALC298, 节点99)
===============================================
(1) 开启 ALCPlugFix
(2) 关闭 ALCPlugFix
(3) 退出
你想选择哪个选项? (1/2/3):1

正在下载声卡修复文件...
下载完成

正在卸载...
卸载完成

正在拷贝声卡修复文件...
拷贝完成

正在修复权限...
修复完成

正在加载进程...
/Library/LaunchDaemons/good.win.ALCPlugFix.plist: service already loaded
加载完成

正在清理...
清理完成

棒！安装ALCPlugFix守护进程完成！

请按任何键返回主菜单...
`

**Comment by Menchen** [comment]
是 直接运行 ALCPlugFix， 直接在终端里面输入。不是安装的那个脚本

**Comment by lifeng5478** [comment]
哦，可以了，谢谢~`2019-08-06 18:25:57.025 ALCPlugFix[8724:56084] Current Directory /Users/lifeng
2019-08-06 18:25:57.026 ALCPlugFix[8724:56084] Headphones daemon running!
2019-08-06 18:25:57.043 ALCPlugFix[8724:56084] Correctly added Audio Listener!
2019-08-06 18:25:57.043 ALCPlugFix[8724:56084] Fixing...
2019-08-06 18:25:57.053 ALCPlugFix[8724:56084] Performing periodical work
2019-08-06 18:26:14.083 ALCPlugFix[8724:56421] Audio device changed!
2019-08-06 18:26:14.083 ALCPlugFix[8724:56421] Fixing...
2019-08-06 18:26:14.938 ALCPlugFix[8724:56421] Audio device changed!
2019-08-06 18:26:14.938 ALCPlugFix[8724:56421] Fixing...

`
是不是每次开机插拔的时候都得输一下这个命令行？

**Comment by lifeng5478** [comment]
把这个command关了以后，插拔又没有声音了。是每次插耳机就得运行一下吗？

**Comment by Menchen** [comment]
添加

````
<key>StandardErrorPath</key>
<string>/tmp/alcp.log</string>
<key>StandardOutPath</key>
<string>/tmp/alcp.log</string>
```

在
```
<key>WorkingDirectory</key>
<string>/usr/local/bin/</string>
```
下面

文件在 /Library/LaunchDaemons/good.win.ALCPlugFix.plist

然后重启，把`/tmp/alcp.log` 发上来

**Comment by lifeng5478** [comment]
OK，你稍等，刚刚有事了！感谢~

**Comment by lifeng5478** [comment]
Last login: Tue Aug  6 18:54:47 on console
(base) lifengdeMacBook-Pro:~ lifeng$ cat /tmp/alcp.log 
2019-08-06 18:54:36.434 ALCPlugFix[54:708] Found had-verb in work dir
2019-08-06 18:54:36.435 ALCPlugFix[54:708] Headphones daemon running!
2019-08-06 18:54:36.484 ALCPlugFix[54:708] Correctly added Audio Listener!
2019-08-06 18:54:36.484 ALCPlugFix[54:708] Fixing...
2019-08-06 18:54:36.525 ALCPlugFix[54:708] Performing periodical work
(base) lifengdeMacBook-Pro:~ lifeng$

**Comment by Menchen** [comment]
看上去没问题。。不过能发下 md5（在 /usr/local/bin/) 和 `which ALCPlugFix` 吗？

**Comment by lifeng5478** [comment]
插拔耳机log里面没有输出的。但是如果执行ALCPugFix就有显示了。/usr/local/bin里面没有md5文件。有个ALCPlugFix

**Comment by Menchen** [comment]
等我待会能用电脑的时候看看吧。。用时间没办法。

**Comment by Menchen** [comment]
@lifeng5478 试试用 `https://github.com/Menchen/ALCPlugFix/raw/master/build/Release/ALCPlugFix` 这个版本试试.. (替换 `/usr/local/bin` 里面的), 然后重启 插拔耳机, 然后发log上来.

**Comment by yipingw** [comment]
我的小米笔记本pro，i5 8G 256G版本，设置layoutid 为 30 一直完美使用。

**Comment by lifeng5478** [comment]
@Menchen 我来试下

**Comment by lifeng5478** [comment]
(base) lifengdeMacBook-Pro:~ lifeng$ cat /tmp/alcp.log 
2019-08-07 09:31:34.352 ALCPlugFix[54:708] ALCPlugFix v1.3
2019-08-07 09:31:35.293 ALCPlugFix[54:708] Found had-verb in work dir
2019-08-07 09:31:35.293 ALCPlugFix[54:708] Headphones daemon running!
2019-08-07 09:31:35.307 ALCPlugFix[54:708] Correctly added Audio Listener!
2019-08-07 09:31:35.307 ALCPlugFix[54:708] Fixing...
2019-08-07 09:31:35.389 ALCPlugFix[54:708] Performing periodical work
(base) lifengdeMacBook-Pro:~ lifeng$ 

@Menchen

**Comment by lifeng5478** [comment]
@yipingw 跟这个ID有关系？在哪里设置ID我试下

**Comment by lifeng5478** [comment]
我是i7 16 256的机器

**Comment by yipingw** [comment]
> @yipingw 跟这个ID有关系？在哪里设置ID我试下

EFI文件夹里面有个config.plist文件，搜索layoutid，找到值为99的地方，修改为30.

**Comment by lifeng5478** [comment]
@yipingw  兄弟，你这招管用啊！真的好了哎❤️！谢了！
@Menchen 改ID可以解决。你看看什么原因。

**Comment by stevezhengshiqi** [comment]
又是30vs99，有的人觉得30好用，有人觉得99好用。

**Comment by lifeng5478** [comment]
@stevezhengshiqi  这个东西不是跟着机器主板识别的吗？难道内部使用的硬件还不太一样？

**Comment by lifeng5478** [comment]
无论如何！非常感谢！我会长期赞助咱们团队的！

**Comment by yipingw** [comment]
目前系统10.14.6，layoutid设置为30可用，但是据说10.15移除了layoutid = 30，建议谨慎升级。

**Comment by lifeng5478** [comment]
@yipingw 感谢告知！目前我也是10.14.6，10.15还不知道啥时候的事儿呢
