### ISSUE TITLE
Question about update

### ISSUE THREAD

**Issue by FirefighterZinnowitz** [daliansky/XiaoMi-Pro-Hackintosh#239]
I have not updated EFI for a long time.

How do I correctly update to the current version EFI 1.3.5?

Is it sufficient if I enter the following command in the terminal and dial number 1, so that everything is updated?
bash -c "$ (curl -fsSL https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/master/install.sh)"

Sorry, I'm a beginner

**Comment by Menchen** [comment]
It should be ok with just that.

**Comment by FirefighterZinnowitz** [comment]
If I go into the EFI folder on the Mac hard drive, the files are still provided with the modification date 17.02.2019.

Can I check somewhere if EFI has really been updated to 1.3.5?

**Comment by Menchen** [comment]
Download 1.3.5 in release tab and compare it. (using md5)
