### ISSUE TITLE
About SAT0 -> SATA rename

### ISSUE THREAD

**Issue by Mateo1234454545** [daliansky/XiaoMi-Pro-Hackintosh#240]
I see that you have removed SAT0 -> SATA rename.

Is this rename unuseful or it causes any problems?

I'm asking because Hackintool suggests that it should be enabled.
[Screenshot 2019-08-19 at 8.33.00 am.pdf](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/3514342/Screenshot.2019-08-19.at.8.33.00.am.pdf)

**Comment by stevezhengshiqi** [comment]
The SAT rename pairs with SSDT-SATA. If you use SATA-unsupported.kext, then you don’t need that rename and SSDT.

**Comment by Mateo1234454545** [comment]
I'm not using SATA-unsupported.kext or SSDT-SATA (in patched folder).
Do I need the rename ?

**Comment by stevezhengshiqi** [comment]
Nope. Only rename won’t make a difference.
