### ISSUE TITLE
PC randomly shutting off

### ISSUE THREAD

**Issue by artemis77799** [daliansky/XiaoMi-Pro-Hackintosh#241]
Hi, today for the first time my xiaomi mi notebook pro hackintoshed started to powering itself off randomly, I have no idea why, if i check the cause of the previous shut downs they all appear with the code "5" wich means that the pc has been turned off by the user and nothing should be wrong but this is definetly not the case, I can't troubleshoot this by myself I hope someone could help
![Schermata 2019-08-19 alle 21 13 13](https://user-images.githubusercontent.com/46961774/63292715-958efd00-c2c6-11e9-996b-05abc5e9fc07.png)

**Comment by artemis77799** [comment]
here there is a video of the problem, i noticed this only happens when the pc is running on battery and not connected to power, could a dead battery be the issue even is the laptop is only 6 months old?
https://imgur.com/a/PCtWXGj

**Comment by MarFre22** [comment]
Hi,
I have this problem too. I can solve it disconnecting tplink WiFi adapter every time I want the PC to sleep. 
I think it is a tplink driver's bug for hackintosh.

**Comment by FallenChromium** [comment]
Check out system log, maybe it has some valuable suggestions. It's kind of reminds me #218, but I'm not sure if it's SSD-related too

**Comment by artemis77799** [comment]
the battery connector was not plugged well, sorry for the useless thread lmao
