### ISSUE TITLE
麦克风输入无声

### ISSUE THREAD

**Issue by ifkid** [daliansky/XiaoMi-Pro-Hackintosh#242]
麦克风的输入电平为0，但是点击输入声音进度条时会出现电平，之后接没有了，麦克风输入不了声音，求解答

**Comment by Menchen** [comment]
是笔记本麦克风还是耳机麦克风?

**Comment by ifkid** [comment]
自带的和耳机都没有，我在clover里加了万能声卡驱动后，可以麦克风输入，但是不能自动切换耳机和外放，能不能既实现自动切换又能麦克风输入呢

**Comment by Menchen** [comment]
为什么要加入 万能声卡驱动 .... 已经有了驱动了..  试试用原本的EFI 然后 clover config 里面 layout-id 改 30 试试, 随便 看看 #232 .

**Comment by stevezhengshiqi** [comment]
兄弟走远了。。 ALCPlugFix和切换layout-id为30就可以了。万能声卡是不能碰的东西。

**Comment by ifkid** [comment]
感谢大佬，layout-id改为30就可以了
