### ISSUE TITLE
problem with triple boot. Linux not boot

### ISSUE THREAD

**Issue by mrcolix** [daliansky/XiaoMi-Pro-Hackintosh#244]
there are a problems with boot linux. 
if you use clover to boot linux it doesn't works. The MI logo remains

**Comment by Menchen** [comment]
Did you used that patch in install script? It work for linux and windows.

**Comment by stevezhengshiqi** [comment]
Agree. This issue is perhaps a duplication of https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/93 .

**Comment by mrcolix** [comment]
I solved with old AptioMemoryFix-64.efi
now it works

thanks
