### ISSUE TITLE
Unable to update to MacOs Catalina

### ISSUE THREAD

**Issue by matvada** [daliansky/XiaoMi-Pro-Hackintosh#253]
Hello, 
i'm trying to install the public beta of MacOs Catalina, i joined the Apple beta program and the system detected the update, but once downloaded, an error message appears that prevents the installation.

Is the path correct or should it be installed by downloading the dmg file by hand?

Any idea?
Thanks

**Comment by Menchen** [comment]
If you can upload the error message it would be helpful to know what's wrong.

**Comment by stevezhengshiqi** [comment]
Mark as invalid because few information is provided.

**Comment by matvada** [comment]
@stevezhengshiqi i'm sorry but i had no time to re-download 6.35 gb before now, this time it worked fine, i don't know why the first two times it showed the error.

Thanks

**Comment by stevezhengshiqi** [comment]
Don't be sorry. Gald to hear that your problem is solved.
