### ISSUE TITLE
长时间睡眠重启，点击web版本的outlook立即重启,频繁异常重启

### ISSUE THREAD

**Issue by Likenttt** [daliansky/XiaoMi-Pro-Hackintosh#257]
**Pre-requirement**
**前提条件**
- Try to rebuild the kextcache and restart whenever you encounter a problem. It always works like a charm!
- 请在遇到任何问题时，先重建缓存并重启。它通常能修复99%的问题！
- To rebuild the kextcache, run `sudo kextcache -i /` in `Terminal.app`.
- 在`终端.app`运行命令`sudo kextcache -i /`来重建缓存。

**State the model**
**阐述您的机型**
- e.g. XiaoMi-Pro MX150, XiaoMi-Pro GTX,...

XiaoMi-Pro MX250

**State the version of the EFI**
**阐述您的EFI版本**
- e.g v1.3.4, v1.3.5,...

V1.35

**Describe the bug**
**描述您遇到的问题**
- A clear and concise description of what the bug is.
- 清晰并详细地描述问题所在。

Click outlook for web，my laptop reboot at once.Yesterday I changed the settings for screen:sleep after 3h without operations.Besides,my book often reboot for long sleep.
点击网页版的outlook，立刻重启。昨天屏幕设置了三小时才睡眠，因为常常睡眠导致重启

**System log**
**系统报告**
- If a windows "Your computer was restarted because of a problem" appears, click `Report` and attach the log to help find the problem.
- 如果出现窗口"您的电脑因为出现问题而重新启动"，点击`报告`并附上错误日志来帮助定位问题。

My error log is below:
我的错误日志如下：
[2019-09-10-error.log](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/3594135/2019-09-10-error.log)

**Screenshots**
**截图**
- If applicable, add screenshots to help explain your problem.
- 如果可用，请添加截图来帮助说明您遇到的问题。

点击网页版的outlook登录按钮，立刻重启

**Attach your entire EFI folder**
**附上您的整个EFI文件夹**
- Please attach your entire EFI folder to help solve your problem.
- Erasing serial numbers in config.plist is required!
- 请附上整个EFI文件夹来方便解决问题。
- 附件里的config.plist请清除序列号！

**Attach system.log**
**附上system.log**
- If applicable, please run `log show --predicate "processID == 0" --start YYYY-MM-DD --debug` in `Terminal.app` to help locate the problem.
- 如果可用，请在`终端.app`运行命令`log show --predicate "processID == 0" --start YYYY-MM-DD --debug`来帮助定位问题。

**Comment by stevezhengshiqi** [comment]
@Likentt 请卸载问题驱动OCular.LSDEfs

**Comment by Likenttt** [comment]
> @Likenttt 请卸载问题驱动OCular.LSDEfs

感谢，已经确定，此问题与黑苹果无关，是我司安全软件的问题
