### ISSUE TITLE
Downgrade BIOS

### ISSUE THREAD

**Issue by P0SlX** [daliansky/XiaoMi-Pro-Hackintosh#260]
Hi, I want to undervolt my CPU but I realised that my BIOS version is XMAKB5R0P0A07, and it might be a newer version. So I was thinking, how can I downgrade ? If it fails, does the BIOS have a backup ? And what are the chances to successfully downgrade ?

Thanks

**Comment by stevezhengshiqi** [comment]
As far as I know, the scripts support 0A07.
