### ISSUE TITLE
各位高技能人才们。这是(Hackintosh固有缺陷吗？

### ISSUE THREAD

**Issue by jc654123** [daliansky/XiaoMi-Pro-Hackintosh#263]
1：视频有色阶
https://azeria-labs.com/memory-instructions-load-and-store-part-4/
2：比如这个的页面纯色上就会有点点
是hidpi引起的还是？

如果这样的话  装Mac系统将不再是一种好的解决方案

**Comment by jc654123** [comment]
![Jietu20190922-205703](https://user-images.githubusercontent.com/13203841/65387789-492f5500-dd7d-11e9-9978-b8ad16505442.jpg)
![Jietu20190922-210644](https://user-images.githubusercontent.com/13203841/65387790-4c2a4580-dd7d-11e9-988d-9b75b3436e5b.jpg)

**Comment by jc654123** [comment]
尤其是第二张·更过分 ，在截图时还会“优化显示”                我的苹果梦要破灭了  
                                                                                                           ------jc654123

**Comment by stevezhengshiqi** [comment]
描述问题时请保持克制，不要过分阐述个人观点。如果没有刚需，windows永远是普通群众的最好选择，因为他有更好的兼容性和更完善的技术支持。但如果有特定的开发需求和工作学习需求需要macOS，黑苹果才是他们的选择。

**Comment by jc654123** [comment]
不是hidpi引起。可能是一种老的技术显示方式。更有“质感”一点

**Comment by jc654123** [comment]
https://developer.apple.com/macos/
https://www.apple.com/cn/macos/catalina/
我为什么用的系统和官网上画的不一样呢？

**Comment by stevezhengshiqi** [comment]
@jc654123 1. 首先确保你的系统是10.15
2. 因为屏幕素质不同，米pro显示效果会和macbookpro有些许差异。
3. 请详细描述不一样的地方，方便网友诊断。

**Comment by yipingw** [comment]
感觉这种issue没什么意义吧
