### ISSUE TITLE
no internet access after upgrading to Catalina

### ISSUE THREAD

**Issue by macguru341** [daliansky/XiaoMi-Pro-Hackintosh#264]
hello
i had my Xiaomi notebook pro with mac and windows in dual boot.
last night i tried to upgrade to catalina 
the upgrade went well and i have an internet access for 5 min since than i can't connect to internet .
i copied the new EFI folder to the EFI portion but still nothing 

what can i do ?

**Comment by stevezhengshiqi** [comment]
Please provide specific information to help solve the problem.
In this case, information about your wireless card is needed.
If you are using a USB wireless armed, you can have a look at https://github.com/chris1111/Wireless-USB-Adapter

**Comment by macguru341** [comment]
Thanks - I’m now using a WiFi card , I’m Using Ethernet with a regular usb c hub

**Comment by stevezhengshiqi** [comment]
Then, it’s a known issue in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/256

**Comment by macguru341** [comment]
Thanks - going back ...
