### ISSUE TITLE
求一款支持的好用的没乱七八糟问题的免驱黑苹果网卡

### ISSUE THREAD

**Issue by zb2947244682** [daliansky/XiaoMi-Pro-Hackintosh#266]
求一款支持的好用的没乱七八糟问题的免驱黑苹果网卡！
想完美一点～～
哪位知道

**Comment by stevezhengshiqi** [comment]
个人用BCM943602CS，这类问题可在小米PRO黑苹果高级群进行讨论。

**Comment by zb2947244682** [comment]
> 个人用BCM943602CS，这类问题可在小米PRO黑苹果高级群进行讨论。

好的谢谢～怎么github怎么没通知我。。。
