### ISSUE TITLE
Readme.md中的 QQ 689011732 搜索不到，而且群都满了，进不去了。

### ISSUE THREAD

**Issue by zb2947244682** [daliansky/XiaoMi-Pro-Hackintosh#267]
Readme.md中的 QQ 689011732 搜索不到，而且群都满了，进不去了。

**Comment by stevezhengshiqi** [comment]
可以尝试发私信给管理或者加入别的小米黑苹果群。
Issue页是用来讨论和完善EFI问题的，此Issue不太适合在此仓库。

**Comment by zb2947244682** [comment]
> 可以尝试发私信给管理或者加入别的小米黑苹果群。
> Issue页是用来讨论和完善EFI问题的，此Issue不太适合在此仓库。

我是没地方发了，找不到发的地方。。。哈哈哈哈，只能发这里。
