### ISSUE TITLE
怎么解决macOS Catalina中不能使用USB WiFi 驱动

### ISSUE THREAD

**Issue by zhanghanbing1998** [daliansky/XiaoMi-Pro-Hackintosh#269]
我使用的USB wifi是COMFAST CF-WU810N，在更新了macOS Catalina后，打不开usb wifi的驱动，提示我软件需要更新

**Comment by stevezhengshiqi** [comment]
https://github.com/chris1111/Wireless-USB-Adapter

**Comment by zb2947244682** [comment]
> https://github.com/chris1111/Wireless-USB-Adapter

有些人的USB WIFI是中文的，我的是英文的，用了啥套路？

**Comment by stevezhengshiqi** [comment]
不知道，而且此issue和本仓库关系不大。类似USB网卡驱动问题可在QQ群讨论。

**Comment by zhanghanbing1998** [comment]
谢了，互撸娃大哥！
