### ISSUE TITLE
Using the advised bluetooth and wifi dongles - still no Continuity

### ISSUE THREAD

**Issue by macguru341** [daliansky/XiaoMi-Pro-Hackintosh#270]
hello
I have been using the advised bluetooth and wifi dongles and I can't use the Continuity on my iPhone and Mac.
is there something special I need to turn on on my Mac? the handoff in my iPhone is turned on

thanks

**Comment by stevezhengshiqi** [comment]
Wifi dongle can’t activate handoff or use continuity.
