### ISSUE TITLE
iPhone sync problem

### ISSUE THREAD

**Issue by artemis77799** [daliansky/XiaoMi-Pro-Hackintosh#271]
Hi, I'm actually running mojave on my xiaomi mi notebook pro and I don't want to upgrade to catalina because I red on this github that it has problems with usb c. I also have an iphone on ios 13 and I can't connect it to the "mac" because it tells me I need to update the software first, is there a way to connect the iphone anyway or the update to catalina is necessary? 
(sorry for the screenshot in italian, it basically says that I need to update mac os and not much more)
![Schermata 2019-10-02 alle 16 37 46](https://user-images.githubusercontent.com/46961774/66053849-542f7580-e533-11e9-8d2a-52db60d77b8c.png)

**Comment by Menchen** [comment]
You just need to upgrade iTunes to connect.

**Comment by stevezhengshiqi** [comment]
It seems like iTunes is deprecated to Music, Podcast and Apple TV. New Finder.app now takes control of connection with Apple products. 
I am afraid updating to Catalina is the only way currently.

**Comment by Menchen** [comment]
I mean you can just need to upgrade iTunes in Mojave... Right now I'm using that to sync IOS13

**Comment by stevezhengshiqi** [comment]
That's good. I haven't used Mojave for a long time. Love this backward support,

**Comment by stevezhengshiqi** [comment]
https://osxdaily.com/2019/11/06/fix-iphone-11-not-showing-syncing-itunes-mac/
