### ISSUE TITLE
Doesn't working wireless utility on Catalina

### ISSUE THREAD

**Issue by Detrous** [daliansky/XiaoMi-Pro-Hackintosh#274]
Error when install wireless utility: "This package is not compatible with this version of macOS."
Old setup of utility can't run because of x64 Catalina

**Don't update system to catalina if you using wireless adapter**

**Comment by vimcaw** [comment]
Try those:
https://github.com/chris1111/Wireless-USB-Adapter-Clover
https://github.com/chris1111/Wireless-USB-Adapter

**Comment by stevezhengshiqi** [comment]
Related issue:https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/269

**Comment by Detrous** [comment]
> Try those:
> https://github.com/chris1111/Wireless-USB-Adapter-Clover
> https://github.com/chris1111/Wireless-USB-Adapter

Thank you. Now my Tenda U12 work great
