### ISSUE TITLE
升级Catalina后，电源USB-C连接转换器无法同时PD充电+HDMI输出；另一个USB-C连接以太网需要插上网线后手动重新加载驱动

### ISSUE THREAD

**Issue by imjonat** [daliansky/XiaoMi-Pro-Hackintosh#275]
**Pre-requirement**
**前提条件**
已重建缓存

**State the model**
**阐述您的机型**
XiaoMi-Pro MX150 i5-8G-256G

**State the version of the EFI**
**阐述您的EFI版本**
10.8 的 master

**Describe the bug**
**描述您遇到的问题**
正常升级了10.15，usb网卡驱动失效 要了最新版本的驱动安装后正常
然而type-c转以太网有线连接失效，目前dhcp地址无法获得 mac硬件地址变成了11-22-33-44-55-66，此前的同样efi在10.14.6中一切正常

**System log**
**系统报告**
系统报告：还没有遇到panic

**Screenshots**
**截图**
- If applicable, add screenshots to help explain your problem.
- 如果可用，请添加截图来帮助说明您遇到的问题。

**Attach your entire EFI folder**
**附上您的整个EFI文件夹**
- Please attach your entire EFI folder to help solve your problem.
- Erasing serial numbers in config.plist is required!
- 请附上整个EFI文件夹来方便解决问题。
- 附件里的config.plist请清除序列号！
30Mb上传不了。。

**Attach system.log**
**附上system.log**
- If applicable, please run `log show --predicate "processID == 0" --start YYYY-MM-DD --debug` in `Terminal.app` to help locate the problem.
- 如果可用，请在`终端.app`运行命令`log show --predicate "processID == 0" --start YYYY-MM-DD --debug`来帮助定位问题。
[1009.log](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/3705525/1009.log)

以下为截图
查了各种资料 蒙了 好像没有类似情况发生
![Screen Shot 2019-10-09 at 11 40 05](https://user-images.githubusercontent.com/42567368/66450685-fac3cb00-ea8b-11e9-9255-2f8266e4219b.png)
![Screen Shot 2019-10-09 at 11 41 49](https://user-images.githubusercontent.com/42567368/66450705-0911e700-ea8c-11e9-97c4-490526c6fc6f.png)

看网卡的想法貌似是mac地址的问题

**Comment by imjonat** [comment]
自己有尝试修改手动dhcp地址 Ethernet显示为绿色 然而无法上网
自己有尝试更换网络环境，更换了三个路由器环境，问题依旧100%复现
很好奇我该如何解决这个问题，我认为这是一个挑战。。

**Comment by stevezhengshiqi** [comment]
Ethernet是仿冒的en0端口的有线网卡，是为了连接AppStore等苹果服务。根据你的情况，你的有线网卡是第二个 USB 10/...00 LAN。

有线网卡不能驱动是在测试版就存在的已知问题，见https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/256 和 https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/264

**Comment by imjonat** [comment]
okay, thanks a lot lot lot !!

**Comment by stevezhengshiqi** [comment]
你这个挺详细的，不介意的话把这个issue开着？

**Comment by imjonat** [comment]
emmm, 但好像还木有解决……大家都有同样的问题嘛。。有线网的速度很稳定性很重要。。

**Comment by imjonat** [comment]
开！作为伸手党，必须要问的详细

**Comment by imjonat** [comment]
![291570595236_ pic_hd](https://user-images.githubusercontent.com/42567368/66451703-32347680-ea90-11e9-9c55-287d13014e3a.jpg)

![image](https://user-images.githubusercontent.com/42567368/66451733-4d9f8180-ea90-11e9-82e6-6b96958210d5.png)

顺手补两张实况图

**Comment by HsOjo** [comment]
点击左上角苹果菜单-关于本机，点击系统报告-硬件-USB-网卡对应的产品id，然后寻找相应的驱动安装。

以下是我使用的网卡信息：
```text
USB 10/100/1000 LAN：

  产品ID：	0x8153
  厂商ID：	0x0bda  (Realtek Semiconductor Corp.)
  版本：	31.00
  序列号：	001000001
  速度：	最高可达5 Gb/秒
  生产企业：	Realtek
  位置ID：	0x14620000 / 7
  可用电流(mA)：	900
  所需电流(mA)：	288
  额外的操作电流(mA)：	0
```

例如此处产品ID为**8153**，且厂商为**Realtek**，即RTL8153方案的网卡，其驱动可以在官方网站中找到。（如果一致，可直接[点击此处下载](https://www.realtek.com/en/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-usb-3-0-software)）

下载并安装最新的macOS驱动即可。

如接入网线无响应，可尝试在**终端**执行以下脚本，重新加载驱动：

```bash
#!/bin/bash

# Unload
sudo kextunload /Library/Extensions/AppleRTL815XEthernet109.kext
sudo kextunload /Library/Extensions/AppleRTL815XComposite109.kext

# Load
sudo kextload /Library/Extensions/AppleRTL815XEthernet109.kext
sudo kextload /Library/Extensions/AppleRTL815XComposite109.kext
```

**Comment by imjonat** [comment]
> 点击左上角苹果菜单-关于本机，点击系统报告-硬件-USB-网卡对应的产品id，然后寻找相应的驱动安装。
> 
> 以下是我使用的网卡信息：
> 
> ```
> USB 10/100/1000 LAN：
> 
>   产品ID：	0x8153
>   厂商ID：	0x0bda  (Realtek Semiconductor Corp.)
>   版本：	31.00
>   序列号：	001000001
>   速度：	最高可达5 Gb/秒
>   生产企业：	Realtek
>   位置ID：	0x14620000 / 7
>   可用电流(mA)：	900
>   所需电流(mA)：	288
>   额外的操作电流(mA)：	0
> ```
> 
> 例如此处产品ID为**8153**，且厂商为**Realtek**，即RTL8153方案的网卡，其驱动可以在官方网站中找到。（如果一致，可直接[点击此处下载](https://www.realtek.com/en/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-usb-3-0-software)）
> 
> 下载并安装最新的macOS驱动即可。
> 
> 如接入网线无响应，可尝试在**终端**执行以下脚本，重新加载驱动：
> 
> ```shell
> sudo kextunload /Library/Extensions/AppleRTL815XEthernet109.kext
> sudo kextunload /Library/Extensions/AppleRTL815XComposite109.kext
> sudo kextload /Library/Extensions/AppleRTL815XEthernet109.kext
> sudo kextload /Library/Extensions/AppleRTL815XComposite109.kext
> ```

Wow awesome, thanks for your reply, i'm going to take a try.

**Comment by rewhex** [comment]
> 点击左上角苹果菜单-关于本机，点击系统报告-硬件-USB-网卡对应的产品id，然后寻找相应的驱动安装。
> 
> 以下是我使用的网卡信息：
> 
> ```
> USB 10/100/1000 LAN：
> 
>   产品ID：	0x8153
>   厂商ID：	0x0bda  (Realtek Semiconductor Corp.)
>   版本：	31.00
>   序列号：	001000001
>   速度：	最高可达5 Gb/秒
>   生产企业：	Realtek
>   位置ID：	0x14620000 / 7
>   可用电流(mA)：	900
>   所需电流(mA)：	288
>   额外的操作电流(mA)：	0
> ```
> 
> 例如此处产品ID为**8153**，且厂商为**Realtek**，即RTL8153方案的网卡，其驱动可以在官方网站中找到。（如果一致，可直接[点击此处下载](https://www.realtek.com/en/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-usb-3-0-software)）
> 
> 下载并安装最新的macOS驱动即可。
> 
> 如接入网线无响应，可尝试在**终端**执行以下脚本，重新加载驱动：
> 
> ```shell
> sudo kextunload /Library/Extensions/AppleRTL815XEthernet109.kext
> sudo kextunload /Library/Extensions/AppleRTL815XComposite109.kext
> sudo kextload /Library/Extensions/AppleRTL815XEthernet109.kext
> sudo kextload /Library/Extensions/AppleRTL815XComposite109.kext
> ```

I've installed same driver, and everything seems ok until restart, script helped but I need to run this script after every login, what should I do to fix this?

**Comment by HsOjo** [comment]
> > 点击左上角苹果菜单-关于本机，点击系统报告-硬件-USB-网卡对应的产品id，然后寻找相应的驱动安装。
> > 以下是我使用的网卡信息：
> > ```
> > USB 10/100/1000 LAN：
> > 
> >   产品ID：	0x8153
> >   厂商ID：	0x0bda  (Realtek Semiconductor Corp.)
> >   版本：	31.00
> >   序列号：	001000001
> >   速度：	最高可达5 Gb/秒
> >   生产企业：	Realtek
> >   位置ID：	0x14620000 / 7
> >   可用电流(mA)：	900
> >   所需电流(mA)：	288
> >   额外的操作电流(mA)：	0
> > ```
> > 
> > 
> > 例如此处产品ID为**8153**，且厂商为**Realtek**，即RTL8153方案的网卡，其驱动可以在官方网站中找到。（如果一致，可直接[点击此处下载](https://www.realtek.com/en/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-usb-3-0-software)）
> > 下载并安装最新的macOS驱动即可。
> > 如接入网线无响应，可尝试在**终端**执行以下脚本，重新加载驱动：
> > ```shell
> > sudo kextunload /Library/Extensions/AppleRTL815XEthernet109.kext
> > sudo kextunload /Library/Extensions/AppleRTL815XComposite109.kext
> > sudo kextload /Library/Extensions/AppleRTL815XEthernet109.kext
> > sudo kextload /Library/Extensions/AppleRTL815XComposite109.kext
> > ```
> 
> I've installed same driver, and everything seems ok until restart, script helped but I need to run this script after every login, what should I do to fix this?

You can use the "Automator.app" to build a quick fix program.

* First, new an application.

* Second, From the left panel to search "applescript", double click to add it, and copy/paste code below these:

```applescript
on run {input, parameters}
	
	do shell script "kextunload /Library/Extensions/AppleRTL815XEthernet109.kext;
	kextunload /Library/Extensions/AppleRTL815XComposite109.kext;
	kextload /Library/Extensions/AppleRTL815XEthernet109.kext;
	kextload /Library/Extensions/AppleRTL815XComposite109.kext" with administrator privileges
	
	return input
end run
```

* Finally, save this program on an usually directory.

Now, If you unplug/plug your ethernet adaptor, you just need to run this app to fix this problem.

PS: Use "Spotlight" to run this app is so quickly.

> My English is not good, If you understood just OK.

**Comment by rewhex** [comment]
> > > 点击左上角苹果菜单-关于本机，点击系统报告-硬件-USB-网卡对应的产品id，然后寻找相应的驱动安装。
> > > 以下是我使用的网卡信息：
> > > ```
> > > USB 10/100/1000 LAN：
> > > 
> > >   产品ID：	0x8153
> > >   厂商ID：	0x0bda  (Realtek Semiconductor Corp.)
> > >   版本：	31.00
> > >   序列号：	001000001
> > >   速度：	最高可达5 Gb/秒
> > >   生产企业：	Realtek
> > >   位置ID：	0x14620000 / 7
> > >   可用电流(mA)：	900
> > >   所需电流(mA)：	288
> > >   额外的操作电流(mA)：	0
> > > ```
> > > 
> > > 
> > > 例如此处产品ID为**8153**，且厂商为**Realtek**，即RTL8153方案的网卡，其驱动可以在官方网站中找到。（如果一致，可直接[点击此处下载](https://www.realtek.com/en/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-usb-3-0-software)）
> > > 下载并安装最新的macOS驱动即可。
> > > 如接入网线无响应，可尝试在**终端**执行以下脚本，重新加载驱动：
> > > ```shell
> > > sudo kextunload /Library/Extensions/AppleRTL815XEthernet109.kext
> > > sudo kextunload /Library/Extensions/AppleRTL815XComposite109.kext
> > > sudo kextload /Library/Extensions/AppleRTL815XEthernet109.kext
> > > sudo kextload /Library/Extensions/AppleRTL815XComposite109.kext
> > > ```
> > 
> > 
> > I've installed same driver, and everything seems ok until restart, script helped but I need to run this script after every login, what should I do to fix this?
> 
> **I think this problem need offical driver update to fix it.**
> 
> But, You can use the "Automator.app" to build a quick fix program.
> 
> * First, new an application.
> * Second, From the left panel to search "applescript", double click to add it, and copy/paste code below these:
> 
> ```applescript
> on run {input, parameters}
> 	
> 	do shell script "kextunload /Library/Extensions/AppleRTL815XEthernet109.kext;
> 	kextunload /Library/Extensions/AppleRTL815XComposite109.kext;
> 	kextload /Library/Extensions/AppleRTL815XEthernet109.kext;
> 	kextload /Library/Extensions/AppleRTL815XComposite109.kext" with administrator privileges
> 	
> 	return input
> end run
> ```
> 
> * Finally, save this program on an usually directory.
> 
> Now, If you unplug/plug your ethernet adaptor, you just need to run this app to fix this problem.
> 
> PS: Use "Spotlight" to run this app is so quickly.
> 
> > My English is not good, If you understood just OK.

Thanks, helped me.

**Comment by imjonat** [comment]
有点尴尬的是，打驱动之前，USB下没显示网卡信息。所以干脆打了楼上上上上上的驱动，然后it works
紧接着遇到了楼上上上的问题，写了个脚本加到开机自启或者loginhook都没辙，放弃
![Screen Shot 2019-10-12 at 10 40 42](https://user-images.githubusercontent.com/42567368/66693588-2093de80-ecdd-11e9-8bfa-087504b2d3fc.png)
`sudo defaults write com.apple.loginwindow LoginHook /Users/jonat/Downloads/LoginHook/enableUsbNetwork.sh`
果然如我所料。。要sudo 不输密码肯定卡在后台然并卵
于是delete之，当然在delete之前可以先看下，把delete改成read即可
`sudo defaults delete com.apple.loginwindow LoginHook`

####最后发现了一个有意思的现象，开机前插着USB以太网转换器，开机后就不需要执行脚本了，我在想……是不是可以从这里入手

**Comment by Menchen** [comment]
LaunchDaemon 和系统级的 LaunchAgents 默认就是root。所以不用sudo

**Comment by HsOjo** [comment]
> * 有点尴尬的是，打驱动之前，USB下没显示网卡信息。所以干脆打了楼上上上上上的驱动，然后it works
> * 紧接着遇到了楼上上上的问题，写了个脚本加到开机自启或者loginhook
>   ![Screen Shot 2019-10-12 at 10 40 42](https://user-images.githubusercontent.com/42567368/66693588-2093de80-ecdd-11e9-8bfa-087504b2d3fc.png)
>   `sudo defaults write com.apple.loginwindow LoginHook  /Users/jonat/Downloads/LoginHook/enableUsbNetwork.sh`
> * 果然如我所料。。要sudo 不输密码肯定卡在后台，因此然并卵
>   于是delete之，当然在delete之前可以先看下，把delete改成read即可
>   `sudo defaults delete com.apple.loginwindow LoginHook`
> 
> #### 最后发现了一个有意思的现象，开机前插着USB以太网转换器，开机后就不需要执行脚本了，我在想……是不是可以从这里入手

参考以下代码：

```bash
pwd='password'
echo $pwd|sudo -S kextunload /Library/Extensions/AppleRTL815XEthernet109.kext
echo $pwd|sudo -S kextunload /Library/Extensions/AppleRTL815XComposite109.kext
echo $pwd|sudo -S kextload /Library/Extensions/AppleRTL815XEthernet109.kext
echo $pwd|sudo -S kextload /Library/Extensions/AppleRTL815XComposite109.kext
```

将**password**替换成你的密码即可。

**Comment by imjonat** [comment]
> > * 有点尴尬的是，打驱动之前，USB下没显示网卡信息。所以干脆打了楼上上上上上的驱动，然后it works
> > * 紧接着遇到了楼上上上的问题，写了个脚本加到开机自启或者loginhook
> >   ![Screen Shot 2019-10-12 at 10 40 42](https://user-images.githubusercontent.com/42567368/66693588-2093de80-ecdd-11e9-8bfa-087504b2d3fc.png)
> >   `sudo defaults write com.apple.loginwindow LoginHook  /Users/jonat/Downloads/LoginHook/enableUsbNetwork.sh`
> > * 果然如我所料。。要sudo 不输密码肯定卡在后台，因此然并卵
> >   于是delete之，当然在delete之前可以先看下，把delete改成read即可
> >   `sudo defaults delete com.apple.loginwindow LoginHook`
> > 
> > #### 最后发现了一个有意思的现象，开机前插着USB以太网转换器，开机后就不需要执行脚本了，我在想……是不是可以从这里入手
> 
> 参考以下代码：
> 
> ```shell
> pwd='password'
> echo $pwd|sudo -S kextunload /Library/Extensions/AppleRTL815XEthernet109.kext
> echo $pwd|sudo -S kextunload /Library/Extensions/AppleRTL815XComposite109.kext
> echo $pwd|sudo -S kextload /Library/Extensions/AppleRTL815XEthernet109.kext
> echo $pwd|sudo -S kextload /Library/Extensions/AppleRTL815XComposite109.kext
> ```
> 
> 将**password**替换成你的密码即可。

wow, shell 非常妙，运行直接跳过了密码

不管是loginhook还是设置中user登录我都试过了加入该脚本
发现开机后脚本跑了，然而插上网线没用。好尴尬 估计是登录后脚本执行太早了

**Comment by imjonat** [comment]
![Screen Shot 2019-10-13 at 15 29 57](https://user-images.githubusercontent.com/42567368/66712371-6c728080-edce-11e9-9f1f-97f71e635cf4.png)
### 再更一波 外接显示器的时候 PD供电一分钟左右会停止供电 10.14下是ok的……唔 我要回退版本了

**Comment by joaomiranda00** [comment]
With MacOs Catalina 10.15.1 ethernet is already working.

**Comment by p0we7** [comment]
我用的是淘宝上面宣称免驱的 AX88179 的有线网卡。
昨天从 10.14 通过 U 盘抹掉系统盘安装了 10.15.5，然后进入系统后有线网卡是正常的。
但是10.15.5系统下 HDMI 不能正常输出所以又重装到 10.15.4， 之后发现有线网卡和 HDMI 都不行，过了一晚上重启后 HDMI 又正常了。
接着今天再次降到10.14.6， HDMI 在安装系统的时候就能正常输出，有线网卡依然不行。
在 `系统报告 -> USB`里面能看到 AX88179 , 但是在网络设置里面没有看到对应的网卡。

请教一下应该怎么处理？ 重建缓存是不是用命令 `sudo kextcache -i` 
看到 @joaomiranda00  说已经能工作，我应该提供什么信息去判断问题？
