### ISSUE TITLE
Catalina系统，插入HDMI后，电脑黑屏无法恢复，外置显示器也无画面

### ISSUE THREAD

**Issue by zb2947244682** [daliansky/XiaoMi-Pro-Hackintosh#278]
Catalina系统，插入HDMI后，电脑黑屏无法恢复，外置显示器也无画面

**Comment by stevezhengshiqi** [comment]
@zb2947244682 看[常见问题解答](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/常见问题解答),

> 一个解决方案是合盖约五秒后再开盖。

**Comment by zb2947244682** [comment]
> @zb2947244682 看[常见问题解答](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94),
> 
> > 一个解决方案是合盖约五秒后再开盖。

蛮叫有空试试看。。。
