### ISSUE TITLE
开机爆音问题

### ISSUE THREAD

**Issue by Violettx** [daliansky/XiaoMi-Pro-Hackintosh#279]
每次黑苹果开机的时候，如果耳机处于插入状态就会爆音一秒左右，网上搜索有人说是因为Gain增益加载的时候很高导致的，不知道这个参数在哪里修改？似乎应该修改VoodooHDA.kext里的plist文件，不过我没找到这个kext啊。
我的设备是GTX版，这个问题在10.14和10.15都有出现。

**Comment by Menchen** [comment]
自从 AppleALC 出现后 VoodooHDA 几乎没人用了。。。 爆音问题应该是因为切换到耳机的时候给 AMP通电的时候的噪音。 你可以试试关闭 ALCPlugFix 在/Library/LaunchDaemons/good....... 里面然后手动运行 https://askubuntu.com/questions/138266/distorted-and-choppy-audio
里面的hda-verb 

hda-verb  0x20 SET_COEF_INDEX 0x67
hda-verb  0x20 SET_PROC_COEF 0x3000

然后在手动运行alcplugfix 在终端里面看看有没有爆音，上面的hda-verb 是给ALc295的而我们的是Alc298.所以如果真要解决的话要手动提取 codec然然后看 那个是正确的node。
