### ISSUE TITLE
It takes much longer time to boot and shutdown after updating to Catalina

### ISSUE THREAD

**Issue by vimcaw** [daliansky/XiaoMi-Pro-Hackintosh#281]
**State the model**
**阐述您的机型**
- Xiaomi Air 2018

**State the version of the EFI**
**阐述您的EFI版本**
- v1.3.5

**Describe the bug**
**描述您遇到的问题**
- It takes a very long time (About a few minutes) to boot and shutdown on Catalina.

**Attach system.log**
**附上system.log**
- Pivotal parts of boot log:
```log
apfs_keybag_init:1583: failed to initialize volume keybag, err = 2
apfs_keybag_init:1583: failed to initialize volume keybag, err = 2
apfs_keybag_init:1583: failed to initialize volume keybag, err = 2
AGDCC: Unauthorized client 'PerfPowerService' (IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/IGPU@2/AppleIntelFramebufferController/IntelFBClientControl)
IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0
AppleLMUController::smcReadKey Error: received error 0x84 when reading key 'MSLD'
```

**Comment by stevezhengshiqi** [comment]
@vimcaw Hi, firstly, it's a XiaoMi-Pro repository so there're would be several compatibility issues on XiaoMi Air. 

A common difference between XiaoMi Pro and XiaoMi Air is the EC device in DSDT. XiaoMi Air has to rename its EC0 device or disable it and fake a new one, like [SSDT-EC sample](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/SSDT-EC.dsl.)

Another difference is LGPA method, which controls the brightness key. It's recommended to find EFI specifically for XiaoMi Air.

**Comment by vimcaw** [comment]
@stevezhengshiqi Thank you very much for the detailed answer! It will teach me a lot of things.
