### ISSUE TITLE
更新EFI出错

### ISSUE THREAD

**Issue by aaaisan** [daliansky/XiaoMi-Pro-Hackintosh#282]
更新到10.15之后，使用`bash -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/master/install_cn.sh)"`更新EFI时出错
提示：苹果原生驱动被修改, 请确保S/L/E和L/E目录里的驱动未被修改!

**Comment by stevezhengshiqi** [comment]
@aaaisan 你好，终端运行命令`sudo kextcache -i /`来检查哪些驱动被修改。

**Comment by aaaisan** [comment]
执行`sudo kextcache -i /`后的输出信息：
Kext with invalid signature (-67050) allowed: <OSKext 0x7f94374a6620 [0x7fff9447cb00]> { URL = "file:///Library/Apple/System/Library/Extensions/AppleUSBEthernetHost.kext/", ID = "com.apple.macos.driver.AppleUSBEthernetHost" }

**Comment by stevezhengshiqi** [comment]
嗯，最好找到原版驱动来替换被修改的驱动，然后重建缓存重启。

**Comment by aaaisan** [comment]
请问原版驱动要去哪里找？……

**Comment by stevezhengshiqi** [comment]
可以拷贝别人的电脑的，或者提取镜像里的。

**Comment by aaaisan** [comment]
镜像中只有一个`AppleUSBEthernet.kext`文件，而没有`AppleUSBEthernetHost.kext`

**Comment by aaaisan** [comment]
不好意思，找到了……

**Comment by aaaisan** [comment]
用提取出的`AppleUSBEthernetHost.kext`替换后，还是出现同样的错误提示……

**Comment by stevezhengshiqi** [comment]
那就手动更新efi吧。BOOT CLOVER文件夹删除再复制新的。

**Comment by stevezhengshiqi** [comment]
此问题是脚本的驱动检查机制，非bug。需用户手动解决驱动问题或手动更新EFI。
