### ISSUE TITLE
PCI device all be "0x" on 10.15/OC ? ? ?

### ISSUE THREAD

**Issue by HsOjo** [daliansky/XiaoMi-Pro-Hackintosh#283]
**Pre-requirement**
**前提条件**
- Try to rebuild the kextcache and restart whenever you encounter a problem. It always works like a charm!
- 请在遇到任何问题时，先重建缓存并重启。它通常能修复99%的问题！
- To rebuild the kextcache, run `sudo kextcache -i /` in `Terminal.app`.
- 在`终端.app`运行命令`sudo kextcache -i /`来重建缓存。

OMG, I tried it, but can't fix this problem.

When I replace EFI to Clover, this problem fixed.

**State the model**
**阐述您的机型**
- e.g. XiaoMi-Pro MX150, XiaoMi-Pro GTX,...

XiaoMi-Pro GTX

**State the version of the EFI**
**阐述您的EFI版本**
- e.g v1.3.4, v1.3.5,...

v1.3.5/OC

**Describe the bug**
**描述您遇到的问题**
- A clear and concise description of what the bug is.
- 清晰并详细地描述问题所在。

1. I discovered My MiPro sound device is not available.
2. I check the sound device list, It's empty.
3. I check hardware list, when I view the PCI device list, All devices be "0x".

**System log**
**系统报告**
- If a windows "Your computer was restarted because of a problem" appears, click `Report` and attach the log to help find the problem.
- 如果出现窗口"您的电脑因为出现问题而重新启动"，点击`报告`并附上错误日志来帮助定位问题。

It Haven't "restarted" problem.

**Screenshots**
**截图**
- If applicable, add screenshots to help explain your problem.
- 如果可用，请添加截图来帮助说明您遇到的问题。

![image](https://user-images.githubusercontent.com/28259134/66711926-8eb4d000-edc7-11e9-83a7-8d9b04f8bfcd.png)

**Attach your entire EFI folder**
**附上您的整个EFI文件夹**
- Please attach your entire EFI folder to help solve your problem.
- Erasing serial numbers in config.plist is required!
- 请附上整个EFI文件夹来方便解决问题。
- 附件里的config.plist请清除序列号！

[EFI](https://mega.nz/#!2KIjmYjL!PF99GUYyWBYdERT3eNuNEqgQndXkf31c3EwRM9cVH5Q)

**Attach system.log**
**附上system.log**
- If applicable, please run `log show --predicate "processID == 0" --start YYYY-MM-DD --debug` in `Terminal.app` to help locate the problem.
- 如果可用，请在`终端.app`运行命令`log show --predicate "processID == 0" --start YYYY-MM-DD --debug`来帮助定位问题。

I don't know when is this problem start. So export three days log.

[Log](https://mega.nz/#!yHQDmQZZ!quzy8CceFRoEcyUXruzQzFOG6cnu8iJ7Qj9x5k0sjpg)

**Comment by stevezhengshiqi** [comment]
@HsOjo Hi, always remember to download the EFI folder from [release page](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/releases).

Never directly download or clone from the repository master branch. The master branch is mainly the source code.

**Comment by HsOjo** [comment]
> @HsOjo Hi, always remember to download the EFI folder from [release page](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/releases).
> 
> Never directly download or clone from the repository master branch for daily use. The master branch is mainly the source code for development.

I never use master branch, just use v1.3.5 OpenCore release version.

I just modify serial number and enable USBBT by "OpenCore Configurator", And add kext for "EFICheckDisabler".

I don't know why the sound device isn't working.

:) Thanks your reply this.

**Comment by stevezhengshiqi** [comment]
@HsOjo Then please remember to delete BOOT and OC folder and then copy these two folders from the release. Never replace them. Your ACPI folder is messy and include many useless dsl files which are not included in the release pack.

**Comment by HsOjo** [comment]
@stevezhengshiqi Now,I replaced "BOOT and OC" from the release version now, just modify my serial number. But this problem still exists. :(

**Comment by stevezhengshiqi** [comment]
@HsOjo Submit your new EFI folder and let’s have a look.

**Comment by stevezhengshiqi** [comment]
@HsOjo Oh, I think I find the problem. In your `config.plist`:
```
<key>DeviceProperties</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x14,0x0)</key>
			<dict>
				<key>AAPL,slot-name</key>
				<data>
				</data>
				<key>model</key>
				<data>
				</data>
				<key>name</key>
				<data>
				</data>
			</dict>
```
the data values are lost. Make sure your are using an proper plist editor to edit your plist. No `OC Configurator` and be run `diff -u <plist1> <plist2> to check the difference.

**Comment by HsOjo** [comment]
@stevezhengshiqi Oh, thanks! This problem has been solved. :)
