### ISSUE TITLE
小米pro开启了HiDPI后字体有点发虚

### ISSUE THREAD

**Issue by jim4ever** [daliansky/XiaoMi-Pro-Hackintosh#285]
小米pro开启了HiDPI后字体有点发虚，字体的边缘比较模糊，使用脚本开启后还需要做别的处理么？

**Comment by Menchen** [comment]
去设置-显示里面改分辨率，正确的是1400左右

**Comment by stevezhengshiqi** [comment]
@jim4ever 开启次像素抗锯齿。

**Comment by jim4ever** [comment]
@stevezhengshiqi  多谢，回头试下看。

**Comment by stevezhengshiqi** [comment]
已在https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/one-key-hidpi/README_CN.md 添加说明。
(如果你在小米Pro黑苹果QQ群里，输入`hidpi`，群里的机器人也会给出答复，很多问题QQ群机器人都囊括了，多注意哦)
