### ISSUE TITLE
Catalina USB Wifi driver worked!!

### ISSUE THREAD

**Issue by suenhj** [daliansky/XiaoMi-Pro-Hackintosh#286]
most USB Wifi drivers which worked on Catalina included here :
https://github.com/chris1111/Wireless-USB-Adapter-Clover

**Comment by stevezhengshiqi** [comment]
Yes. Related issues: https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/274 and https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/269
