### ISSUE TITLE
Want to make a dual boot on single 1TB SSD Drive - Need recommendation  

### ISSUE THREAD

**Issue by macguru341** [daliansky/XiaoMi-Pro-Hackintosh#287]
Hello
I've ordered [this](https://item.taobao.com/item.htm?id=532197802538&ft=t&toSite=main) wifi and bluetooth card to upgrade my Xiaomi notebook pro.
So now I need to upgrade my SSD to a bigger one so I will be able to make a dual boot for windows 10 and Mac osx.
first I would like to know if this machine can take 1TB SSD Drive?
second it will be great if someone can recommend me about some amazon drive in reasonable price. 
I found [this](https://www.amazon.com/Crucial-1TB-NAND-NVMe-PCIe/dp/B07J2Q4SWZ/ref=sr_1_1?keywords=Crucial+P1+CT1000P1SSD8+1TB+SSD+PCIe+NVMe+M.2+2280&qid=1571642239&s=pc&sr=1-1) one from Crucial that got great reviews 

thanks

**Comment by P0SlX** [comment]
Hi !
So I got a Corsair MP510 960Go and it works like a charm !
![Screenshot 2019-11-16 at 16 00 44](https://user-images.githubusercontent.com/25037788/68995100-45eeac00-088a-11ea-8e0c-ded3c0421723.png)
So yeah I think this PC can handle a 1Tb SSD
