### ISSUE TITLE
使用的最新版EFI，每次合盖之后都会重启？

### ISSUE THREAD

**Issue by skyRuo** [daliansky/XiaoMi-Pro-Hackintosh#289]
错误日志：
panic(cpu 0 caller 0xffffff800ce290b7): "AppleUSBHostLegacyClient::setPowerState(0xffffff8036b5ed20 : 0xffffff7f8d5261da, 2 -> 1) timed out after 10341 ms"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.11.26/iokit/Kernel/IOServicePM.cpp:5302
Backtrace (CPU 0), Frame : Return Address
0xffffff81217dbb40 : 0xffffff800c73f98b 
0xffffff81217dbb90 : 0xffffff800c876c15 
0xffffff81217dbbd0 : 0xffffff800c86861e 
0xffffff81217dbc20 : 0xffffff800c6e6a40 
0xffffff81217dbc40 : 0xffffff800c73f077 
0xffffff81217dbd40 : 0xffffff800c73f45b 
0xffffff81217dbd90 : 0xffffff800ced2d89 
0xffffff81217dbe00 : 0xffffff800ce290b7 
0xffffff81217dbe50 : 0xffffff800ce28c79 
0xffffff81217dbe60 : 0xffffff800ce4002e 
0xffffff81217dbea0 : 0xffffff800ce27a28 
0xffffff81217dbec0 : 0xffffff800c7811d5 
0xffffff81217dbf40 : 0xffffff800c780d01 
0xffffff81217dbfa0 : 0xffffff800c6e613e 

BSD process name corresponding to current thread: kernel_task
Boot args: darkwake=0 dart=0 gfxrst=1 

Mac OS version:
19A602

Kernel version:
Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64
Kernel UUID: 70EDD61F-86EE-3E1B-873F-98D909B78160
Kernel slide:     0x000000000c400000
Kernel text base: 0xffffff800c600000
__HIB  text base: 0xffffff800c500000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 34744844421529
last loaded kext at 252677808240: @filesystems.msdosfs	1.10 (addr 0xffffff7f8ebb4000, size 69632)
loaded kexts:
org.virtualbox.kext.VBoxNetAdp	5.2.14
org.virtualbox.kext.VBoxNetFlt	5.2.14
org.virtualbox.kext.VBoxUSB	5.2.14
org.virtualbox.kext.VBoxDrv	5.2.14
com.netease.nemu.kext.NemuDrv	15.2.97
com.realtek.driver.RtWlanU	1830.32.b7
as.acidanthera.voodoo.driver.PS2Keyboard	2.0.2
as.acidanthera.voodoo.driver.PS2!C	2.0.2
org.rehabman.driver.NullEthernet	1.0.6
com.alexandred.VoodooI2CHID	1
com.alexandred.VoodooI2C	2.2
org.coolstar.VoodooGPIO	1.1
as.vit9696.SMCProcessor	1.0.6
as.lvs1974.HibernationFixup	1.2.6
as.vit9696.!AALC	1.3.9
org.tw.CodecCommander	2.7.1
as.vit9696.WhateverGreen	1.3.1
com.rehabman.driver.USBInjectAll	0.7.1
org.vanilla.driver.CPUFriend	1.1.5
ru.usrsse2.SMCBatteryManager	1
as.vit9696.VirtualSMC	1.0.6
as.vit9696.Lilu	1.3.7
com.alexandred.VoodooI2CServices	1
@filesystems.msdosfs	1.10
@filesystems.smbfs	3.4
>AudioAUUC	1.70
@fileutil	20.036.15
@filesystems.autofs	3.0
@filesystems.ntfs	3.14.3
>AGPM	111.1.18
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
>!AHDAHardwareConfigDriver	283.14
>!AUpstreamUserClient	3.6.8
>!AMCCSControl	1.12
>!AHDA	283.14
>!AGraphicsDevicePolicy	4.1.46
@AGDCPluginDisplayMetrics	4.1.46
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.0f8
>pmtelemetry	1
@Dont_Steal_Mac_OS_X	7.0.0
>!A!IKBLGraphics	14.0.0
>ACPI_SMC_PlatformPlugin	1.0.0
>!AFIVRDriver	4.1.0
>eficheck	1
>!A!IPCHPMC	2.0.1
>!ASMCLMU	212
>!AGFXHDA	100.1.421
>!A!IKBLGraphicsFramebuffer	14.0.0
>!A!ISlowAdaptiveClocking	4.0.0
@private.KextAudit	1.0
>!ATopCaseHIDEventDriver	153
>!AFileSystemDriver	3.0.1
>!AVirtIO	1.0
@filesystems.hfs.kext	522.0.9
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@filesystems.apfs	1412.11.7
>!ASmartBatteryManager	161.0.0
>!ARTC	2.0
>!AACPIButtons	6.1
>!ABacklight	170.18
>!ASMBIOS	2.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	302
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
|IOUSBUserClient	900.4.2
@kext.triggers	1.0
>!ASMBus!C	1.0.18d1
>DspFuncLib	283.14
@kext.OSvKernDSPLib	529
>!AGraphicsControl	4.1.46
|IOAVB!F	800.17
>!ASSE	1.0
>!AHDA!C	283.14
|IOHDA!F	283.14
>IOPlatformPluginLegacy	1.0.0
>X86PlatformPlugin	1.0.0
>!ASMBusPCI	1.0.14d1
>IOPlatformPlugin!F	6.0.0d8
|IO!BHost!CUSBTransport	7.0.0f8
|IO!BHost!CTransport	7.0.0f8
|IOAccelerator!F2	438.1.23
@!AGPUWrangler	4.1.46
@!AGraphicsDeviceControl	4.1.46
|IOSlowAdaptiveClocking!F	1.0.0
@plugin.IOgPTPPlugin	800.14
|IOEthernetAVB!C	1.1.0
|IOSkywalk!F	1
>!AHS!BDriver	153
>IO!BHIDDriver	7.0.0f8
|IO!B!F	7.0.0f8
|IO!BPacketLogger	7.0.0f8
>!AActuatorDriver	3400.35
>!AMultitouchDriver	3400.35
>!AInputDeviceSupport	3400.27
>usb.IOUSBHostHIDDevice	1.2
>usb.!UHub	1.2
>!UAudio	320.47
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
|IOSerial!F	11
|IOSurface	269.6
@filesystems.hfs.encodings.kext	1
>!AXsanScheme	3
|IONVMe!F	2.1.0
>!A!ILpssGspi	3.0.60
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOHID!F	2.0.0
>!ABacklightExpert	1.1.0
|IONDRVSupport	558.3
|IOGraphics!F	558.3
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|IOAudio!F	300.2
@vecLib.kext	1.2.0
|IOSMBus!F	1.1
>DiskImages	493.0.0
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AKeyStore	2
>!UTDM	489.11.2
|IOSCSIBlockCommandsDevice	422.0.2
>!ACredentialManager	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOUSBMass!SDriver	157.11.2
|IOSCSIArchitectureModel!F	422.0.2
|IO!S!F	2.1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
|CoreAnalytics!F	1
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|IOTimeSync!F	800.14
|IONetworking!F	3.4
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1

**Comment by stevezhengshiqi** [comment]
USB问题导致。可尝试卸载VirtualBox和网卡驱动再进行测试。

**Comment by zb2947244682** [comment]
> USB问题导致。可尝试卸载VirtualBox和网卡驱动再进行测试。不兼容的网卡驱动/虚拟机驱动会导致这个问题。

这都能看得懂，哪一行写的。

**Comment by stevezhengshiqi** [comment]
`AppleUSBHostLegacyClient::setPowerState` 代表唤醒后USB切换电源状态时出错。

根据你的`loaded kexts`，可发现`org.virtualbox.kext.VBoxUSB` 和 `com.realtek.driver.RtWlanU`这两个和USB唤醒相关的第三方驱动。不兼容的第三方驱动导致的USB睡眠问题很常见。

**Comment by skyRuo** [comment]
我更新到10.15.1好像就没这个问题了。不会 重启了
