### ISSUE TITLE
[Help Wanted] "recovery server could not be contacted"

### ISSUE THREAD

**Issue by rajibxo** [daliansky/XiaoMi-Pro-Hackintosh#292]
hi, i am trying to install mac os high sierra on my mi notebook pro (mx150) i5-8250U model. I have installed 2nd 128 lenovo M.2 ssd for mac os. I followed tonymacx86 guide and using daliansky's EFI folder and made my bootable usb as disk maker x. after booting up to installing high siera, i get an pop up saying -"recovery server could not be contacted." and dosent install. Here the things I have tried-
1. I heard its a date problem so i tried to change my date using terminal from utilities
2. I have tried using other versions of disk makers including unibeast
3. I couldn't connect to the internet that moment to solve the issue
4. I tried USB LAN adapters
5. I have tried mac os highsiera 10.13.6 and also 10.14.1 Mojave, both with same problem
6. I have not found any such solution to my problem yet, i have been stuck for few weeks now
Anyone can suggest me what is the problem and how can i solve it....it would be really helpfull.

**Comment by stevezhengshiqi** [comment]
I recommend to post the installation question on hackintosh forums such as https://www.insanelymac.com/forum/ or https://www.tonymacx86.com/forums/mojave-laptop-support.196/ to get more professional help. This repository is mainly for after-installation issues.

**Comment by rajibxo** [comment]
oh, ok sorry, will do, thanks

**Comment by stevezhengshiqi** [comment]
You can leave it open to let more people to see if they have the same issue^^

**Comment by rajibxo** [comment]
I solved it, silly problems. since I have no experience in this, I can't explain the reasons and
 it may not work for all...
1. The problem was, when click install macOS Mojave, it says the image is damaged. I looked online for solutions, which is to remove the install.info file in the bootable usb.
2. Then it works but clicking continue to install shows the error as recovery server could not be contacted, and I tried all the solutions to fix it but didn't work.
3. The trick is not to delete the install.info file in the bootable usb.
4. Then go to terminal and change the date way back even the date is correct, I changed my date
to November 2015. command is- date mmddhhmmyy. then you can start to install.
5. Next issue I faced is at the end of installation process it says couldn't install because failed to update firmware. it fixed by going to BIOS setting and change the boot order to your usb drive as first.
6. Another issue I faced is after first step of installation, it shows an error of " installation resources couldn't be found", there is a lot of complicated solutions out there what works for me is I converted my installation drive to APFS format, in halfway of installation. also its because its an M.2 ssd, after that installation went smoothly.

**Comment by Zurana132** [comment]
Hi Rajibxo, did you find a solution? I have the same problem, After all this, I shut down my laptop and now I can not even see my HD in the selection for any utility changes to be done. Any advise/guidance would be appreciated!

**Comment by rajibxo** [comment]
@Zurana132 maybe you can start from fresh...the problem is really silly...can you tell me which step are you stuck on? sorry for late reply, I don't usually came here....

**Comment by Zurana132** [comment]
Hello thank you. It is resolved now. Cheers

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
