### ISSUE TITLE
NVME PM981 Really works in Mojave?

### ISSUE THREAD

**Issue by andreszerocross** [daliansky/XiaoMi-Pro-Hackintosh#293]
Hi, Are you using PM981 Samsung for macOS Boot?? Is it working? can you share IOREG Output?

**Comment by stevezhengshiqi** [comment]
Nope. PM981 works with numerous problems in macOS. https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/FAQ has clearly demonstrates that PM981 is not working good on hackintosh.
