### ISSUE TITLE
windows启用hyper-v后，用clover或者opencore引导蓝屏

### ISSUE THREAD

**Issue by yhl452493373** [daliansky/XiaoMi-Pro-Hackintosh#295]
win10，1909，20H1都试过了，一旦启用了Hyper-V，用opencore或者clover引导windows都会蓝屏，报SYSTEM_THREAD_EXVEPTION_NOT_HANDLED。采用安全模式，取消Hyper-V功能就正常了。两外直接用windows引导启动而不经过clover或者opencore，是完全可以进系统的

**Comment by stevezhengshiqi** [comment]
@yhl452493373 你好，这是一个已知问题，请注意阅读https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/README_CN.md

> 同时确保 沙盒(Sandbox) 功能关闭。

这里指的就是Hyper-v。

**Comment by stevezhengshiqi** [comment]
已修正README，我之前错把沙盒当成Hyper-V了。
