### ISSUE TITLE
修复后触控板依旧失灵问题

### ISSUE THREAD

**Issue by blacke20** [daliansky/XiaoMi-Pro-Hackintosh#296]
小米笔记本pro 13.3 四核增强版，i5-8250U
系统版本10.14.6
安装使用的EFI版本，最新的V1.3.5

安装完第一次进系统就不能用，找不到触摸板，终端清理缓存也没用，f9按了也没用，请问是不是没救了

希望大佬有空就帮一下，谢谢了~

**Comment by stevezhengshiqi** [comment]
你好 你的机子不是小米笔记本Pro。小米笔记本Pro没有13.3寸版本。其他机型的触控板需要修改GPIO Pin来驱动VoodooI2C，可参考教程http://www.penghubingzhou.cn/2019/01/06/VoodooI2C%20DSDT%20Edit/

**Comment by blacke20** [comment]
你好，那我下载正确的efi替换了就会好了吧，不用重新安装啊吧，麻烦了


| |
岳博闻
|
|
邮箱：bowenbest@163.com
|

签名由 网易邮箱大师 定制

在2019年11月11日 23:13，Steve Zheng 写道：

你好 你的机子不是小米笔记本Pro。小米笔记本Pro没有13.3寸版本。其他机型的触控板需要修改GPIO Pin来驱动VoodooI2C，可参考教程http://www.penghubingzhou.cn/2019/01/06/VoodooI2C%20DSDT%20Edit/

**Comment by stevezhengshiqi** [comment]
确保EFI正确，符合你的符合你的机型。跟系统无关，重装不能解决问题。

**Comment by blacke20** [comment]
好的，谢谢你




| |
岳博闻
|
|
邮箱：bowenbest@163.com
|

签名由 网易邮箱大师 定制

在2019年11月12日 00:00，Steve Zheng 写道：

确保EFI正确，符合你的符合你的机型。跟系统无关，重装不能解决问题。
