### ISSUE TITLE
关于QQ群满员而无法加入的问题

### ISSUE THREAD

**Issue by lh404** [daliansky/XiaoMi-Pro-Hackintosh#297]
希望大佬能够在某些时候清理一下交流群中不活跃的人员，有机会让后来者进入；
或者重要资源在这里能够找到，比如内置网卡相关教程；
感谢！

**Comment by stevezhengshiqi** [comment]
@lh404 嗯我联系一下管理员去清理不活跃成员。
内置网卡牵涉到商业利益问题，我不是很想把本仓库变得商业化，所以没怎么放网卡型号的推荐。我个人推荐是BCM943602CS，装网卡无需太多教程，免驱网卡即插即用，可能天线需要操心一下。

**Comment by lh404** [comment]
@stevezhengshiqi 明白，多谢大佬！

**Comment by 634236704** [comment]
> @lh404嗯我联系一下管理员去清理不活跃成员。我最近都会很忙，无暇顾及QQ群的情况。
> 内置网卡牵涉到商业利益问题，我不是很想把本仓库变得商业化，所以不会放网卡型号的推荐到README里。我个人推荐是BCM943602CS，装网卡无需太多教程，免驱网卡即插即用，可能天线需要操心一下。

老哥QQ群人满满人了，能把不活跃的人员，踢出来让出几个位置吗，弱弱的问句进群的qq验证问题答案不是blog.daliansky.net吗？请问下大佬答案是什么

**Comment by stevezhengshiqi** [comment]
@634236704 联系其他群管理，我不怎么上QQ
