### ISSUE TITLE
小米笔记本Pro 15增强版（i7-10510u）从clover引导后黑屏

### ISSUE THREAD

**Issue by zr1530052796** [daliansky/XiaoMi-Pro-Hackintosh#300]
**小米笔记本Pro 15增强版**（i7-10510u，MX250，英特尔660p 1T SSD）

EFI版本：v1.3.5

1. 可以正常进入Clover，但选择从Mac进入即**黑屏**（等待一小时也没有反应），无论是在安装前还是安装后替换EFI均如此。Option里加 `-v` 也不管用，仍然黑屏。
2. 从该Clover进入Win10，声音设备会丢失，右下角声音图标是红叉叉。直接启动Win10，或用小兵部落阁的 `10.14` 、 `10.15` 等镜像的EFI，对于Win10的声音都是正常的。

**Comment by Menchen** [comment]
10代u目前是不支持的。黑屏估计是因为 mx250，还有不推荐用clover加载其他系统。。

**Comment by stevezhengshiqi** [comment]
注意看主页，此仓库仅支持2017和2018款
