### ISSUE TITLE
外接HDMI显示器的时候黑屏过会就关机了

### ISSUE THREAD

**Issue by skyRuo** [daliansky/XiaoMi-Pro-Hackintosh#301]
具体的信息
panic(cpu 2 caller 0xffffff7f844ecad5): userspace watchdog timeout: no successful checkins from com.apple.WindowServer in 140 seconds
service: com.apple.logd, total successful checkins since load (6170 seconds ago): 618, last successful checkin: 0 seconds ago
service: com.apple.WindowServer, total successful checkins since load (6170 seconds ago): 604, last successful checkin: 140 seconds ago

Backtrace (CPU 2), Frame : Return Address
0xffffff913bb6b820 : 0xffffff8003939a3b 
0xffffff913bb6b870 : 0xffffff8003a70fe5 
0xffffff913bb6b8b0 : 0xffffff8003a62a5e 
0xffffff913bb6b900 : 0xffffff80038e0a40 
0xffffff913bb6b920 : 0xffffff8003939127 
0xffffff913bb6ba20 : 0xffffff800393950b 
0xffffff913bb6ba70 : 0xffffff80040d1875 
0xffffff913bb6bae0 : 0xffffff7f844ecad5 
0xffffff913bb6baf0 : 0xffffff7f844ec7e6 
0xffffff913bb6bb10 : 0xffffff80040663fb 
0xffffff913bb6bb60 : 0xffffff800406f393 
0xffffff913bb6bca0 : 0xffffff8003a20b92 
0xffffff913bb6bdb0 : 0xffffff800393f8b8 
0xffffff913bb6be10 : 0xffffff8003916545 
0xffffff913bb6be70 : 0xffffff800392cff5 
0xffffff913bb6bf00 : 0xffffff8003a49085 
0xffffff913bb6bfa0 : 0xffffff80038e1226 
      Kernel Extensions in backtrace:
         com.apple.driver.watchdog(1.0)[AA44EEB8-57FA-3CAC-9105-C7AB21900B9A]@0xffffff7f844eb000->0xffffff7f844f3fff

BSD process name corresponding to current thread: watchdogd
Boot args: darkwake=0 dart=0 gfxrst=1 

Mac OS version:
19B88

Kernel version:
Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64
Kernel UUID: 7503CD47-851F-321E-8747-50DB4299165F
Kernel slide:     0x0000000003600000
Kernel text base: 0xffffff8003800000
__HIB  text base: 0xffffff8003700000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 6193308647236
last loaded kext at 258893528580: @filesystems.msdosfs	1.10 (addr 0xffffff7f875e8000, size 69632)
last unloaded kext at 6120457165734: org.vanilla.driver.CPUFriend	1.1.5 (addr 0xffffff7f85eb2000, size 20480)
loaded kexts:
com.netease.nemu.kext.NemuDrv	15.2.97
com.realtek.driver.RtWlanU	1830.32.b7
as.acidanthera.voodoo.driver.PS2Keyboard	2.0.2
as.acidanthera.voodoo.driver.PS2!C	2.0.2
org.rehabman.driver.NullEthernet	1.0.6
com.alexandred.VoodooI2CHID	1
com.alexandred.VoodooI2C	2.2
org.coolstar.VoodooGPIO	1.1
as.vit9696.SMCProcessor	1.0.6
as.lvs1974.HibernationFixup	1.2.6
as.vit9696.!AALC	1.3.9
org.tw.CodecCommander	2.7.1
as.vit9696.WhateverGreen	1.3.1
com.rehabman.driver.USBInjectAll	0.7.1
ru.usrsse2.SMCBatteryManager	1
as.vit9696.VirtualSMC	1.0.6
as.vit9696.Lilu	1.3.7
com.alexandred.VoodooI2CServices	1
@filesystems.smbfs	3.4
>AudioAUUC	1.70
@fileutil	20.036.15
@filesystems.autofs	3.0
@filesystems.ntfs	3.14.3
>!AGraphicsDevicePolicy	4.5.9
@AGDCPluginDisplayMetrics	4.5.9
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.1f1
>pmtelemetry	1
>AGPM	111.2.5
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
>!AHDA	283.14
>!AUpstreamUserClient	3.6.8
@Dont_Steal_Mac_OS_X	7.0.0
>!A!IKBLGraphics	14.0.2
>eficheck	1
>!A!IPCHPMC	2.0.1
>!ASMCLMU	212
>!A!IKBLGraphicsFramebuffer	14.0.2
>!A!ISlowAdaptiveClocking	4.0.0
>!AMCCSControl	1.13
>!ABacklight	180.1
@private.KextAudit	1.0
>!ATopCaseHIDEventDriver	3410.1
>!AVirtIO	1.0
@filesystems.hfs.kext	522.0.9
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@filesystems.apfs	1412.41.1
>!ASmartBatteryManager	161.0.0
>!ARTC	2.0
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
@kext.triggers	1.0
>!AGraphicsControl	4.5.9
|IOAVB!F	800.17
>!ASSE	1.0
>DspFuncLib	283.14
@kext.OSvKernDSPLib	529
>!AHDA!C	283.14
|IOHDA!F	283.14
@!AGPUWrangler	4.5.9
@!AGraphicsDeviceControl	4.5.9
|IOAccelerator!F2	438.2.7
|IOSlowAdaptiveClocking!F	1.0.0
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
>!ASMBus!C	1.0.18d1
@plugin.IOgPTPPlugin	810.1
|IOEthernetAVB!C	1.1.0
|IOSkywalk!F	1
>!ABacklightExpert	1.1.0
|IONDRVSupport	568
|IO!BHost!CUSBTransport	7.0.1f1
|IO!BHost!CTransport	7.0.1f1
>!AHS!BDriver	3410.1
>IO!BHIDDriver	7.0.1f1
|IO!B!F	7.0.1f1
|IO!BPacketLogger	7.0.1f1
>!AActuatorDriver	3410.2
>!AMultitouchDriver	3410.2
>!AInputDeviceSupport	3410.1
>usb.!UHub	1.2
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
|IOSerial!F	11
|IOSurface	269.6
@filesystems.hfs.encodings.kext	1
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
|IONVMe!F	2.1.0
>!AEFINVRAM	2.1
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFIRuntime	2.1
|IOHID!F	2.0.0
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|IOAudio!F	300.2
@vecLib.kext	1.2.0
|IOSMBus!F	1.1
|IOGraphics!F	568
>DiskImages	493.0.0
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AKeyStore	2
>!UTDM	489.41.1
|IOSCSIBlockCommandsDevice	422.0.2
>!ACredentialManager	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOTimeSync!F	810.1
|IONetworking!F	3.4
|IOUSBMass!SDriver	157.40.7
|IOSCSIArchitectureModel!F	422.0.2
|IO!S!F	2.1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
|CoreAnalytics!F	1
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.Libm	1
@kec.corecrypto	1.0

**Comment by stevezhengshiqi** [comment]
@skyRuo CPUFriend版本过老，删除CPUFriend.kext再重新测试。

**Comment by skyRuo** [comment]
删除后需要重新安装吗？

**Comment by stevezhengshiqi** [comment]
@skyRuo 安装啥？

**Comment by skyRuo** [comment]
就是我用的是最新的EFI,删除了删除CPUFriend.kext需要下载一个放进去吗？

**Comment by stevezhengshiqi** [comment]
@skyRuo 最新efi没有CPUFriend，替换efi的时候要删除BOOT和CLOER文件夹再复制新的进去，不能直接覆盖。

**Comment by skyRuo** [comment]
好的，谢谢
