### ISSUE TITLE
[ ERROR ]:Native apple kexts have been modified, please keep S/L/E and L/E untouched!

### ISSUE THREAD

**Issue by recre4te** [daliansky/XiaoMi-Pro-Hackintosh#302]
[ ERROR ]:Native apple kexts have been modified, please keep S/L/E and L/E untouched! how it fix?

**Comment by stevezhengshiqi** [comment]
@recre4te Open `Terminal.app` and run `sudo kextcache -i /`, then check the output.

**Comment by Detrous** [comment]
> @recre4te Open `Terminal.app` and run `sudo kextcache -i /`, then check the output.

IOKitWaitQuiet() timed out.
KernelCache ID: A020C06D4449BEC97FCEBCA21FC1E98C
Kext with invalid signature (-67050) allowed: <OSKext 0x7fef60da66f0 [0x7fff92ac0090]> { URL = "file:///Library/Apple/System/Library/Extensions/AppleUSBEthernetHost.kext/", ID = "com.apple.macos.driver.AppleUSBEthernetHost" }
