### ISSUE TITLE
大佬麻烦看看这个问题，睡眠的时候自动关机

### ISSUE THREAD

**Issue by itruo** [daliansky/XiaoMi-Pro-Hackintosh#303]
Sleep Wake failure in EFI

Failure code:: 0xffffffff 0x0000001f

Please IGNORE the below stackshot

================================================================
Date/Time:        2019-11-24 20:06:00 +0800
OS Version:       ??? ??? (Build ???)
Architecture:     x86_64
Report Version:   29

Data Source:      Stackshots
Shared Cache:     0xca9000 5ECA35C8-BFD4-3D7B-99AF-745814EA21BB

Event:            Sleep Wake Failure
Duration:         0.00s
Steps:            1

Boot args:        darkwake=0 dart=0 gfxrst=1 

Time Awake Since Boot: 16s

Process:          swd [280]
Architecture:     x86_64
Footprint:        440 KB
Start time:       2019-11-24 20:06:00 +0800
End time:         2019-11-24 20:06:00 +0800
Num samples:      1 (1)

  Thread 0x6c6    1 sample (1)    priority 4 (base 4)
  <thread QoS background (requested background), thread darwinbg, process darwinbg, IO tier 2>
  1  start + 1 (libdyld.dylib + 70373) [0x7fff63c9d2e5] 1
    1  ??? [0x10e961454] 1
      1  ??? [0x10e9611dd] 1
        1  __stack_snapshot_with_config + 10 (libsystem_kernel.dylib + 135938) [0x7fff63e06302] 1
         *1  ??? [0xffffff80002e1206] 1
           *1  ??? [0xffffff800099a1aa] 1
             *1  ??? [0xffffff80008b3211] 1
               *1  ??? [0xffffff8000304387] (running) 1

  Binary Images:
        0x7fff63c8c000 -     0x7fff63cc1fff  libdyld.dylib (733.6)              <2FA4B359-624B-337C-9207-CDCF841C2E52>  /usr/lib/system/libdyld.dylib
        0x7fff63de5000 -     0x7fff63e11fff  libsystem_kernel.dylib (6153.41.3) <18918E9C-45BC-3D5A-A6B6-3DBC60EEE2E1>  /usr/lib/system/libsystem_kernel.dylib
Model: MacBookPro14,1, BootROM 196.0.0.0.0, 4 processors, Quad-Core Intel Core i5, 1.80 GHz, 8 GB, SMC 2.43f6
Graphics: Intel UHD Graphics 620, Intel UHD Graphics 620, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR4, 2400 MHz, Samsung, -
Memory Module: BANK 1/DIMM0, 4 GB, DDR4, 2400 MHz, Samsung, -
Bluetooth: Version 7.0.1f1, 3 services, 20 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
PCI Card: Intel UHD Graphics 620, sppci_vgacontroller, Internal
PCI Card: Intel Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th Gen Core Processor Gaussian Mixture Model, System Peripheral, Internal
PCI Card: Intel Sunrise Point-LP USB 3.0 xHCI Controller, sppci_usbxhci, Internal
PCI Card: Intel Sunrise Point-LP Serial IO I2C Controller #0, Signal Processing Controller, Internal
PCI Card: Intel Sunrise Point-LP Serial IO I2C Controller #1, Signal Processing Controller, Internal
PCI Card: Intel Sunrise Point-LP CSME HECI #1, Communication Controller, Internal
PCI Card: Intel Sunrise Point-LP HD Audio, sppci_audiodevice, Internal
PCI Card: Intel Sunrise Point-LP PMC, Memory Controller, Internal
PCI Card: Intel Sunrise Point-LP SMBus, sppci_systemmanagementbus, Internal
PCI Card: Intel Sunrise Point-LP PCI Express Root Port #5, sppci_nvme, Internal
PCI Card: Intel Sunrise Point-LP PCI Express Root Port #9, sppci_nvme, Internal
PCI Card: Intel Wireless 8265, sppci_othernetwork, Internal
USB Device: USB 3.0 Bus
USB Device: XiaoMi USB 2.0 Webcam
USB Device: Bluetooth HCI
Thunderbolt Bus:

**Comment by zb2947244682** [comment]
你下载一个叫做nosleep的软件，装上，用不休眠。就不会重启了。

**Comment by HKMV** [comment]
我也有这个问题

**Comment by stevezhengshiqi** [comment]
Transfer to the issue with more detail:  https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/414

**Comment by HKMV** [comment]
> Transfer to the issue with more detail: #414

Thanks, I went back to try it at night.
