### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by Chazy12** [daliansky/XiaoMi-Pro-Hackintosh#305]
hi all.
i have the 10.14.3 installed and i would like to know how to update to the latest 10.15.
thanks again for your hard work!

**Comment by paajake** [comment]
Just use the Mac System updater to update, and update the EFI afterwards using the bash command in the README

**Comment by Chazy12** [comment]
> Just use the Mac System updater to update, and update the EFI afterwards using the bash command in the README

i have to update the BOOT and EFI before the update or after?

**Comment by paajake** [comment]
After

**Comment by Chazy12** [comment]
> After

couse, after installing the update, system reboots..

**Comment by paajake** [comment]
On reboot, boot into the "update installation" till it completes, then on final boot when you see your desktop, you update, which is very simple using the bash command.

**Comment by Chazy12** [comment]
> On reboot, boot into the "update installation" till it completes, then on final boot when you see your desktop, you update, which is very simple using the bash command.

perfect. thank you so much!
so, i just need the bash command to update the EFI or i have to uncompress BOOT and EFI too?!

**Comment by Chazy12** [comment]
sorry for all this questions, but the system works and i don't want to ail something while updating

**Comment by Menchen** [comment]
Generally there’s no issue to just update, but updating EFI before an update is a good idea.

If you need a stable system then don’t update or update as few as possible. There’s always a change that update _can and will_ break something. 

So if you can’t or don’t have time to fix to risk your system my advice is to not update (though MacOS make a backups before update so you can rollbacks)

**Comment by Chazy12** [comment]
the bash command says: could not resolve host: raw.githubusercontent.com..

**Comment by Menchen** [comment]
Check your internet.

**Comment by Chazy12** [comment]
> Check your internet.

so, i did the update. but now my text are too small. the resolution is 1920x1080, but seems so small :(

**Comment by Chazy12** [comment]
i would love to have larger text without lowering the resolution

**Comment by paajake** [comment]
Use the HiDPI fix, it also can be accessed using the bash update

**Comment by Chazy12** [comment]
> Use the HiDPI fix, it also can be accessed using the bash update

perfect! thank you so much! really! i used the 1680x945 and seems perfect!
a great news is that, with the update, the integrated bluetooth works without a dongle :)
now i just have to figure how to let airplay work to extend the desktop to an ipad..

**Comment by paajake** [comment]
I believe the recommended resolution is 1424x802, but if you're ok with your results, that's good.
For internal Bluetooth use, checkout #262 

And please close this issue :)
