### ISSUE TITLE
从mac app store下载欧路词典提示损坏，请删除从mac app store重新下载

### ISSUE THREAD

**Issue by zwyyy456** [daliansky/XiaoMi-Pro-Hackintosh#306]
不论是下载欧路词典的普通版还是增强版都是同样的问题，但是下载其他的app 没有问题，可以正常打开，在别人的黑苹果上登录该帐号下载下来也能正常打开

**Comment by vimcaw** [comment]
我也遇到过，不过是别的 EFI 别的 App，而且不止一个

**Comment by vimcaw** [comment]
我发现我这里付费（包括订阅）的 App 才会，免费的不会，而且有个软件之前不行的，后面又可以了，很怪异，有时候也会弹出说这是在另一台电脑上购买的，需要输入 AppleId 密码，输入完后等半天说已损坏请重新从 AppStore 下载，猜测跟苹果的电脑验证有关，但是我序列号和 smUUID 什么的没变过，也许苹果识别出我这个序列号无效就不让用。

**Comment by stevezhengshiqi** [comment]
不属于EFI问题，自行查阅资料。
