### ISSUE TITLE
Windows driver for WiFi after installing new card

### ISSUE THREAD

**Issue by macguru341** [daliansky/XiaoMi-Pro-Hackintosh#309]
Hello
I’ve installed the new WiFi card With native card in my laptop and now I’ve lost the WiFi connectivity in windows and I see in my device manger that I have a new network controller without a driver , where can I get this driver ?

**Comment by P0SlX** [comment]
What's your WiFi card's model ?

**Comment by macguru341** [comment]
Yes , it’s important 
Here is a photo shot from my Mac 

![image](https://user-images.githubusercontent.com/22807164/70331823-f710b280-1848-11ea-882e-733216828efa.jpg)

**Comment by stevezhengshiqi** [comment]
@macguru341 Please get a more specific model from the shop where you buy this card.

**Comment by macguru341** [comment]
> @macguru341 Please get a more specific model from the shop where you buy this card.

Thanks but I can’t read Chinese, maybe you can help ?

**Comment by stevezhengshiqi** [comment]
@macguru341 Please send the link, it can be BCM943602CS or any other model starts with BCM943.

**Comment by stevezhengshiqi** [comment]
According to 0x14E4, 0x133 in the picture, it probably is a BCM943602CS.
Please read https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/132 for windows driver.

**Comment by macguru341** [comment]
Thanks - here is the link

**Comment by stevezhengshiqi** [comment]
@macguru341 The link is not helpful, but you can try the driver in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/132

**Comment by stevezhengshiqi** [comment]
Duplicate issue, closed.
