### ISSUE TITLE
Updates on internal wifi

### ISSUE THREAD

**Issue by nedpals** [daliansky/XiaoMi-Pro-Hackintosh#31]
Hi, I just happened to seen a comment in a previous issue about the internal wifi patch updates in this model. Is there any new news about it? thanks in advance

**Comment by stevezhengshiqi** [comment]
Currently there's no available kexts for internal wifi. You can wait for the Intel wifi process: https://www.tonymacx86.com/threads/intel-wifi-driver-effort.186344/ , or you can add a support wifi  adapter at M.2 key.

**Comment by Parmarti** [comment]
Any suggestions on a M.2 wifi and bluetooth adaptor that works?

**Comment by Neolo** [comment]
> Bluetooth needs soldering on WLAN-LTE pin4&5.
What is it?? How?

**Comment by stevezhengshiqi** [comment]
@Neolo D+ solder in pin4 and D- solder in pin5. You can look
![40855807-3e925da6-6608-11e8-92a7-1a1f6cebc856](https://user-images.githubusercontent.com/36894554/42390910-661e2e08-8102-11e8-8bcd-bfd0c4057226.jpg)
 the picture below.

**Comment by Neolo** [comment]
Thanks, but I don't get it. Where are these wires come to? To your BCM943602CS (not clear how you even fit it inside the laptop) or those wires are just an antennas for internal Bluetooth from Intel (I see internal bluetooth is working out of the box on Xiomi Air Pro, but I'm unable to scan any devices, so it makes sense to assume those wires are antennas)?

**Comment by stevezhengshiqi** [comment]
@Neolo Intel BT on Xiaomi Air/Pro don't work well. You can see more information in https://github.com/daliansky/XiaoMi-Pro/issues/24 . 

Apart from using BT dongle, I insert an native Apple wireless card(BCM943602CS) into my M.2 key. Since M.2 key don't have USB channel which BT requires, I soldered D+ and D- wires to WLAN_LTE slot. PIN 4 and 5 of WLAN_LTE slot are USB channels.

**Comment by Neolo** [comment]
I see. Where exactly did you solder the other side of wires on the card? Please upload the picture.

**Comment by stevezhengshiqi** [comment]
The other side has been attached already. Red wire is D+ and orange one is D-.
![40855793-306a02ce-6608-11e8-9f49-3511dfb4415f](https://user-images.githubusercontent.com/36894554/42398922-a6874092-8120-11e8-8d08-4833a4118917.jpg)

**Comment by Neolo** [comment]
I see it now, thank you for the information.

**Comment by Parmarti** [comment]
So what adaptor are you using?

**Comment by Neolo** [comment]
Not using anything yet, planning to solder a socket and preserve 2 drives in the system + wifi.
https://www.tonymacx86.com/threads/guide-xiaomi-mi-notebook-pro-high-sierra-10-13-4.242724/page-63#post-1773608

**Comment by Parmarti** [comment]
I'm fine with only 1ssd, of course your solution would be ideal but I'd love to see what @stevezhengshiqi is using.

**Comment by stevezhengshiqi** [comment]
@Parmarti It's a BCM943602CS wireless card. I bought from Taobao (https://item.taobao.com/item.htm?spm=a1z09.2.0.0.6d3b2e8dK7sNkk&id=532197802538&_u=22diegp9f1ed) Maybe amazon has something similar.

**Comment by Neolo** [comment]
Nice, but there is nothing like that on Amazon or Ebay, it's just like this: https://www.ebay.com/itm/BCM94360CS2-867M-Bluetooth-4-0-Card-to-NGFF-M-2-Key-A-E-Adapter-for-Hackintosh/253412604407?_trkparms=aid%3D555018%26algo%3DPL.SIM%26ao%3D2%26asc%3D44040%26meid%3D09dd945d1b6244ffa3811228844fc5ec%26pid%3D100005%26rk%3D3%26rkt%3D12%26sd%3D263437687821%26itm%3D253412604407&_trksid=p2047675.c100005.m1851

**Comment by stevezhengshiqi** [comment]
It seems good. But I am not sure whether the seller will give the wires of BT(for example the D+ and D-) since pictures on that page don't have them.

**Comment by Neolo** [comment]
@tevezhengshiqi No it's not good, loot at M.2 Key on it, it's A/E. Board has M

**Comment by stevezhengshiqi** [comment]
Yes, you are right. We need to find a M.2 Key M/B.

**Comment by Neolo** [comment]
@stevezhengshiqi Does taobao website ship to US?
Or can you track down to which pins of the card are those BT wires go, so we can just solder them directly?

I found this https://www.ebay.com/itm/Hot-sell-mSATA-Mini-PCI-E-3-0-SSD-to-NGFF-M-2-B-Key-SATA-Interface-Adapter-Card/282772258884?hash=item41d68a4044:g:eRkAAOSw3xVaH3IZ
which is M.2 B+M -> MiniPCIE.
It wont fit in 4G slot because of wide shoulders, but will fit in SSD1 slot on a right side of the laptop.

**Comment by Neolo** [comment]
Actually, is 3.10 cm (1.22") will fit is that SSD1 slot? Are you able to measure? Thank you.

**Comment by stevezhengshiqi** [comment]
@Neolo Sorry, I am in summer program now and I don't have tools. 
Taobao can't ship to US. You have to find other people to ship.

**Comment by tthrx** [comment]
Hi, guys, I have the Intel 9560NGW user manusal, which i believe has the same pinout assignment( 1216 ) as Intel 8260 in Xiaomi Pro.  Any one who want to replace the original intel Wifi module may be interest in this. 
https://pan.baidu.com/s/1pIv_xqDhI_UU6q7BReOcqA

**Comment by MrJosu** [comment]
Any advice how to launch bluetooth, i installed this thing from Taobao, wifi is fine, but bluetooth dead :(

**Comment by Neolo** [comment]
@MrJosu Been discussed multiple times. For taobao adapter the instruction is right above, you need to solder.
More complicated is in my post if used different adapter https://www.tonymacx86.com/threads/guide-xiaomi-mi-notebook-pro-high-sierra-10-13-6.242724/page-70

**Comment by MrJosu** [comment]
@Neolo i soldered :) wifi working fine, but bluetooth is same story, not working :(

**Comment by Neolo** [comment]
Swap the wires, check if usb port is mapped over ssdt

**Comment by MrJosu** [comment]
I think no issue with wires, done exactly same, and power going through. But i dont have any idea how to map usb port :)

**Comment by l-l-l-l-l-l-l-l-l** [comment]
@stevezhengshiqi I am getting really bad signal with the BCM943602CS card even when the antennas are located under my trackpad, is there anything wrong with their placements?
![img2](https://user-images.githubusercontent.com/38693485/44296366-42b7e980-a2f0-11e8-8a94-0ae9f7e34322.jpeg)
![img1](https://user-images.githubusercontent.com/38693485/44296367-42b7e980-a2f0-11e8-9dd9-d407f31ed893.jpeg)

**Comment by stevezhengshiqi** [comment]
@l-l-l-l-l-l-l-l-l It seems alright. You can try to uncheck `Awake on Wifi` in `SysPref - Energy`. By the way, I personally recommend to stick the two big antennas at the top of the trackpad, besides your small antenna, because you may find that the trackpad is little 'hard' to use.

**Comment by l-l-l-l-l-l-l-l-l** [comment]
@stevezhengshiqi Do you get reasonable speed with your setup? I am getting less than 1 Mbps of download and upload speed for 2.4Ghz and less than 10Mbps download and 5Mbps upload for 5Ghz, while I get over 20 and 100 when using dongle.

**Comment by MrJosu** [comment]
I got around 100 in same room with router, and another thing Steve, can you solder antennas to original ones? and 3rd antenna leave under touchpad

**Comment by stevezhengshiqi** [comment]
@l-l-l-l-l-l-l-l-l Yes, I get normal speed after uncheck that option. You can check your arrangement
of antennas. I personally recommend to stick them under the trackpad.

@MrJosu Some of my friends did, and they get lower delay than sticking antennas under the trackpad. I don't want to lose the origin `Intel Dual Band 8265`, so I haven't tried. Here's a sample picture.
![cs2](https://user-images.githubusercontent.com/36894554/44334426-0f1dc080-a4a4-11e8-9e89-bfac13bd4be8.jpg)

I recently have some big tests, and I am sorry for the slow reply.

**Comment by Neolo** [comment]
> You can try to uncheck Awake on Wifi in SysPref - Energy
There is no such option at all.

**Comment by FunkyDolohin** [comment]
Hi! I bought the wifi card and adapter off taobao. It seems I have received different antennas from what I see you guys have. I can't seem to get any range at all, I have to quite literally stand right next to the router for the card even to detect my wifi. Also, there is no difference in signal strength from when the antennas in the picture below are attached from when they aren't. 
![img_20181010_203122](https://user-images.githubusercontent.com/44037809/46760900-86691700-ccd3-11e8-8224-f2d257474d3b.jpg)
![img_20181010_203037](https://user-images.githubusercontent.com/44037809/46760901-86691700-ccd3-11e8-8d3f-3ab95847118b.jpg)
Can anyone tell me if those even are antennas, or just some kind of adapter? I'm very new to all this stuff. Are these usable, if so how? Or should I buy antennas similar to yours? Any help or tips would be greatly appreciated! 
Here's a picture of the internals:
![img_20181010_202945](https://user-images.githubusercontent.com/44037809/46761077-f1b2e900-ccd3-11e8-8dac-8537cd5d7252.jpg)

**Comment by kvn1351** [comment]
> Hi! I bought the wifi card and adapter off taobao. It seems I have received different antennas from what I see you guys have. I can't seem to get any range at all, I have to quite literally stand right next to the router for the card even to detect my wifi. Also, there is no difference in signal strength from when the antennas in the picture below are attached from when they aren't.
> ![img_20181010_203122](https://user-images.githubusercontent.com/44037809/46760900-86691700-ccd3-11e8-8224-f2d257474d3b.jpg)
> ![img_20181010_203037](https://user-images.githubusercontent.com/44037809/46760901-86691700-ccd3-11e8-8d3f-3ab95847118b.jpg)
> Can anyone tell me if those even are antennas, or just some kind of adapter? I'm very new to all this stuff. Are these usable, if so how? Or should I buy antennas similar to yours? Any help or tips would be greatly appreciated! @stevezhengshiqi @Neolo
> Here's a picture of the internals:
> ![img_20181010_202945](https://user-images.githubusercontent.com/44037809/46761077-f1b2e900-ccd3-11e8-8dac-8537cd5d7252.jpg)

That's not an antenna but rather a U.FL antenna connection. What the others have is a chip/pcb based antenna. You could either connect antennas to that connection or buy other chip antennas to solder on. Be careful to buy the correct antenna for the wifi frequency bands.

**Comment by FunkyDolohin** [comment]
Figured it had to be something like that, already ordered some antennas that should work. And yeah, I will definitely put some effort into cable management, once I solder the data lines and get Bluetooth up and working. Thank you so much for your response. :)

**Comment by shilch** [comment]
As detailed in #99 I'm having issues when connecting to a specific enterprise wifi access point: The complete laptop freezes after a few minutes of being connected.  
There are several instances where laptops with two wifi chips freeze, e.g. [this](https://ubuntuforums.org/showthread.php?t=2144433).  
The unsupported Intel chip is still recognised by the operating system, so I'm wondering whether there's a way to disable it in Clover?  
![Bildschirmfoto 2019-05-28 um 09 38 45](https://user-images.githubusercontent.com/11890358/58459877-b06d2d80-812c-11e9-9b1d-7a0bbca79e2d.png)

**Comment by MrJosu** [comment]
> @l-l-l-l-l-l-l-l-l Yes, I get normal speed after uncheck that option. You can check your arrangement
> of antennas. I personally recommend to stick them under the trackpad.
> 
> @MrJosu Some of my friends did, and they get lower delay than sticking antennas under the trackpad. I don't want to lose the origin `Intel Dual Band 8265`, so I haven't tried. Here's a sample picture.
> ![cs2](https://user-images.githubusercontent.com/36894554/44334426-0f1dc080-a4a4-11e8-9e89-bfac13bd4be8.jpg)
> 
> I recently have some big tests, and I am sorry for the slow reply.

I am still strugling with my wifi speeds :( Maybe you can give me link for spare antenna (i mean internal which one is in the lid) and i will try to solder existing one. (one pin which one is connecting to intel chip is broken)

**Comment by artemis77799** [comment]
do I have to change something in the efi folder after the installation of the card to get it to work?

**Comment by summershrimp** [comment]
anyone tried solider the 220nf capacitors and b-key connector for m.2 wwan pcie lanes and try directly using wlan card on wwan solt ?

**Comment by Neolo** [comment]
Tried, wwan does not get passed to the OS by bios. So I’ve ended up with ruined wwan lanes.

**Comment by summershrimp** [comment]
> Tried, wwan does not get passed to the OS by bios. So I’ve ended up with ruined wwan lanes.
> […](#)
> On May 26, 2020, at 4:01 PM, Yibai Zhang ***@***.***> wrote: ﻿ anyone tried solider the 220nf capacitors and b-key connector for m.2 wwan pcie lanes and try directly using wlan card on wwan solt ? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

What a pity, I saw the pcb have connection to PCH.  Still has some chance to modify the bios to enable it although it's difficult LOL

**Comment by stevezhengshiqi** [comment]
https://github.com/OpenIntelWireless/itlwm
