### ISSUE TITLE
系统升级到10.15后，电池状态出现小叹号，处于‘修理电池’状态，使用正常，如何是好？

### ISSUE THREAD

**Issue by nishizhen** [daliansky/XiaoMi-Pro-Hackintosh#311]

**Comment by tianh** [comment]
继续使用, 没啥, 就是 容量减少到了80% 以下

**Comment by nishizhen** [comment]
> 继续使用, 没啥, 就是 容量减少到了80% 以下

哈哈，应该不是吧，前几天，我有一次用电池，电池到60%显示，就关机了， 然后我重启，不到一分钟后又关机了。。。

**Comment by nishizhen** [comment]
当然，只出现过一次上面的情况

**Comment by tianh** [comment]
那要看你减少到了多少了，下个电池管理工具看看容量吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nishizhen <notifications@github.com&gt;
发送时间: 2020年2月10日 23:10
收件人: daliansky/XiaoMi-Pro-Hackintosh <XiaoMi-Pro-Hackintosh@noreply.github.com&gt;
抄送: tianh <981563526@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[daliansky/XiaoMi-Pro-Hackintosh] 系统升级到10.15后，电池状态出现小叹号，处于‘修理电池’状态，使用正常，如何是好？ (#311)



 
继续使用, 没啥, 就是 容量减少到了80% 以下
  
哈哈，应该不是吧，前几天，我有一次用电池，电池到60%显示，就关机了， 然后我重启，不到一分钟后又关机了。。。

**Comment by nishizhen** [comment]
可能是吧，关闭了，谢谢大家～
