### ISSUE TITLE
10.15.1睡眠唤醒重启

### ISSUE THREAD

**Issue by Jalery521** [daliansky/XiaoMi-Pro-Hackintosh#312]
XiaoMi-Pro MX150  最新EFI

睡眠唤醒重启
**System log**
**系统报告**
panic(cpu 4 caller 0xffffff80138a1c6c): Wake transition timed out after 180 seconds while calling power state change callbacks. Suspected bundle: com.apple.iokit.IOUSBHostFamily. Thread 0x4df35.
Failure code:: 0x00000004 00000027

Backtracing specified thread
Backtrace (CPU 4), Frame : Return Address
0xffffff8127ef3900 : 0xffffff801325dc88 
0xffffff812806b960 : 0xffffff801315b5b1 
0xffffff812806b9d0 : 0xffffff8013159daf 
0xffffff812806ba20 : 0xffffff801314abf3 
0xffffff812806ba60 : 0xffffff801383ecbf 
0xffffff812806baa0 : 0xffffff801383fdc3 
0xffffff812806bae0 : 0xffffff7f942cd258 
0xffffff812806bc50 : 0xffffff7f94669af4 
0xffffff812806bcc0 : 0xffffff7f9478be1a 
0xffffff812806bd10 : 0xffffff7f947940c5 
0xffffff812806bd60 : 0xffffff7f942cc053 
0xffffff812806bdc0 : 0xffffff8013841698 
0xffffff812806be20 : 0xffffff7f942cbd74 
0xffffff812806be30 : 0xffffff8013826654 
0xffffff812806bea0 : 0xffffff801382645a 
0xffffff812806bec0 : 0xffffff801317b625 
0xffffff812806bf40 : 0xffffff801317b151 
0xffffff812806bfa0 : 0xffffff80130e013e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOUSBHostFamily(1.2)[5E8D1616-2C4B-3E81-B199-59D3531E0759]@0xffffff7f942b8000->0xffffff7f943b0fff
            dependency: com.apple.driver.AppleBusPowerController(1.0)[5F8013C3-D135-3795-8C05-F5DDA387ADC4]@0xffffff7f9429e000
            dependency: com.apple.driver.usb.AppleUSBCommon(1.0)[98454AB6-B806-330F-98C6-FEA7F44D22BA]@0xffffff7f942a6000
            dependency: com.apple.driver.AppleUSBHostMergeProperties(1.2)[A7569701-C592-31CF-8740-439114078F9F]@0xffffff7f942b4000
         com.apple.driver.usb.AppleUSBXHCI(1.2)[599B22B3-975E-3473-9C75-0E850D3EDE8D]@0xffffff7f94655000->0xffffff7f946acfff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[4A40B298-87E0-373E-84A9-9A2227924F8F]@0xffffff7f9426b000
            dependency: com.apple.iokit.IOUSBHostFamily(1.2)[5E8D1616-2C4B-3E81-B199-59D3531E0759]@0xffffff7f942b8000
            dependency: com.apple.driver.usb.AppleUSBCommon(1.0)[98454AB6-B806-330F-98C6-FEA7F44D22BA]@0xffffff7f942a6000
         com.apple.driver.usb.AppleUSBXHCIPCI(1.2)[23A02E94-8F3B-30A2-9980-251B4E702CB9]@0xffffff7f94784000->0xffffff7f947b5fff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[4A40B298-87E0-373E-84A9-9A2227924F8F]@0xffffff7f9426b000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[AA7C7A4F-9F5D-3533-9E78-177C3B6A72BF]@0xffffff7f93b2f000
            dependency: com.apple.iokit.IOUSBHostFamily(1.2)[5E8D1616-2C4B-3E81-B199-59D3531E0759]@0xffffff7f942b8000
            dependency: com.apple.driver.usb.AppleUSBCommon(1.0)[98454AB6-B806-330F-98C6-FEA7F44D22BA]@0xffffff7f942a6000
            dependency: com.apple.driver.usb.AppleUSBXHCI(1.2)[599B22B3-975E-3473-9C75-0E850D3EDE8D]@0xffffff7f94655000

BSD process name corresponding to current thread: kernel_task
Boot args: darkwake=0 dart=0 gfxrst=1 

Mac OS version:
19B88

Kernel version:
Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64
Kernel UUID: 7503CD47-851F-321E-8747-50DB4299165F
Kernel slide:     0x0000000012e00000
Kernel text base: 0xffffff8013000000
__HIB  text base: 0xffffff8012f00000
System model name: MacBookPro15,4 (Mac-53FDB3D8DB8CA971)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 7392672479196
last loaded kext at 246524995911: @filesystems.msdosfs	1.10 (addr 0xffffff7f94560000, size 69632)
loaded kexts:
com.intel.kext.intelhaxm	7.5.1
com.realtek.driver.RtWlanU	1830.20.b31
as.acidanthera.voodoo.driver.PS2Keyboard	2.0.4
as.acidanthera.voodoo.driver.PS2!C	2.0.4
com.alexandred.VoodooI2CHID	1
com.alexandred.VoodooI2C	2.2
org.coolstar.VoodooGPIO	1.1
org.rehabman.driver.NullEthernet	1.0.6
as.vit9696.SMCProcessor	1.0.8
as.vit9696.!AALC	1.4.2
org.tw.CodecCommander	2.7.1
as.lvs1974.HibernationFixup	1.2.9
com.rehabman.driver.USBInjectAll	0.7.1
ru.usrsse2.SMCBatteryManager	1
as.vit9696.VirtualSMC	1.0.8
com.alexandred.VoodooI2CServices	1
as.vit9696.WhateverGreen	1.3.3
as.vit9696.Lilu	1.3.8
@filesystems.msdosfs	1.10
>AudioAUUC	1.70
@fileutil	20.036.15
@filesystems.autofs	3.0
>!APlatformEnabler	2.7.0d0
>AGPM	111.2.5
>X86PlatformShim	1.0.0
>!AHDAHardwareConfigDriver	283.14
>!AUpstreamUserClient	3.6.8
>!AHDA	283.14
>!AGraphicsDevicePolicy	4.5.9
@AGDCPluginDisplayMetrics	4.5.9
>!AHV	1
|IOUserEthernet	1.0.1
>!A!IKBLGraphics	14.0.2
|IO!BSerialManager	7.0.1f1
>!A!IPCHPMC	2.0.1
>pmtelemetry	1
@Dont_Steal_Mac_OS_X	7.0.0
>ACPI_SMC_PlatformPlugin	1.0.0
>!A!IKBLGraphicsFramebuffer	14.0.2
>!ASMCLMU	212
>!A!ISlowAdaptiveClocking	4.0.0
>!AGFXHDA	100.1.422
>!AFIVRDriver	4.1.0
>AGDCBacklightControl	4.5.9
>!ABacklight	180.1
>!AMCCSControl	1.13
@private.KextAudit	1.0
>!ATopCaseHIDEventDriver	3410.1
>!AFileSystemDriver	3.0.1
>!AVirtIO	1.0
@filesystems.hfs.kext	522.0.9
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@filesystems.apfs	1412.41.1
>!ASmartBatteryManager	161.0.0
>!ARTC	2.0
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
@kext.triggers	1.0
>DspFuncLib	283.14
@kext.OSvKernDSPLib	529
>!AGraphicsControl	4.5.9
|IOAVB!F	800.17
>!ASSE	1.0
>!ASMBusPCI	1.0.14d1
>!AHDA!C	283.14
|IOHDA!F	283.14
>IOPlatformPluginLegacy	1.0.0
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
|IOAccelerator!F2	438.2.7
@!AGPUWrangler	4.5.9
|IOSlowAdaptiveClocking!F	1.0.0
@!AGraphicsDeviceControl	4.5.9
>!ABacklightExpert	1.1.0
|IONDRVSupport	568
>!ASMBus!C	1.0.18d1
@plugin.IOgPTPPlugin	810.1
|IOEthernetAVB!C	1.1.0
|IOSkywalk!F	1
>!AActuatorDriver	3410.2
>!AHS!BDriver	3410.1
>IO!BHIDDriver	7.0.1f1
|IO!B!F	7.0.1f1
|IO!BPacketLogger	7.0.1f1
>!AMultitouchDriver	3410.2
>!AInputDeviceSupport	3410.1
>!UAudio	320.49
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
|IOSerial!F	11
|IOSurface	269.6
@filesystems.hfs.encodings.kext	1
>!AXsanScheme	3
|IONVMe!F	2.1.0
>!A!ILpssI2C	3.0.60
>!A!ILpssGspi	3.0.60
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOGraphics!F	568
|IOHID!F	2.0.0
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|IOAudio!F	300.2
@vecLib.kext	1.2.0
|IOSMBus!F	1.1
>DiskImages	493.0.0
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AKeyStore	2
>!UTDM	489.41.1
|IOSCSIBlockCommandsDevice	422.0.2
>!ACredentialManager	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOUSBMass!SDriver	157.40.7
|IOSCSIArchitectureModel!F	422.0.2
|IO!S!F	2.1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
|CoreAnalytics!F	1
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|IOTimeSync!F	810.1
|IONetworking!F	3.4
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1

**Comment by stevezhengshiqi** [comment]
@Jalery521 先自行通过卸载网卡驱动/拔掉网卡/拔掉U盘等方式来尝试解决。USB网卡驱动往往是导致睡眠问题的原因。

**Comment by Jalery521** [comment]
> @Jalery521 先自行通过卸载网卡驱动/拔掉网卡/拔掉U盘等方式来尝试解决。USB网卡驱动往往是导致睡眠问题的原因。

谢谢,我更新Wireless Network 到v11试下
