### ISSUE TITLE
How does SSDT-TPD0 and OC ACPI Patch work together?

### ISSUE THREAD

**Issue by FallenChromium** [daliansky/XiaoMi-Pro-Hackintosh#314]
Hello! This is not really an issue but rather a question. Everything works like a charm on my Mi Notebook Pro, so charmy that it looks like a black magic 😂
I want to switch my other laptop, Acer Swift 3, to OpenCore, but without XOSI the trackpad simply doesn't work. I tried to understand how @stevezhengshiqi rewrote TPD0 here and got the idea how SSDT replace works and why it is like this, but I can't inject mine. The problem is that decoding replace values to ASCII doesn't give me TPD0._INI or _CRS, it gives me something unreasonable. How do I get the values for patching TPL1._INI to XINI, for example? Also I've seen full device rewrite in Dell XPS 9550/9560 repositories without patching, I don't really get how this inject works either. Please enlighten me👀

**Comment by stevezhengshiqi** [comment]
- First, you need to download iasl from https://bitbucket.org/RehabMan/acpica/downloads/ or somewhere else. 
- Then in the terminal window, run `iasl -l <yourDSL.dsl>`, and you will get an `lst` log.
- You can find the corresponding hex value of _INI or whatever. Be careful that your piece of hex value may appear several times. In this case, you need to enlarge your piece of hex value to make sure it's unique.

**Comment by FallenChromium** [comment]
Okay, I see. I got away from this with full device definition replacement, but it's always good to know how things work. Thanks! :)
