### ISSUE TITLE
10.15系统拷贝大量文件导致系统重启

### ISSUE THREAD

**Issue by linkerGitHub** [daliansky/XiaoMi-Pro-Hackintosh#315]
**State the model**
**阐述您的机型**
XiaoMi-Pro GTX,...

**State the version of the EFI**
**阐述您的EFI版本**
v1.3.5,...

**Describe the bug**
**描述您遇到的问题**
我的mac系统是装在新加的固态中的，当我从小米自带的硬盘中拷贝一个有 **37435**个项目，约**202MB**的文件夹至mac的固态中时，系统崩溃重启。

**System log**
**系统报告**
anic(cpu 0 caller 0xffffff7f9a81c4a7): nvme: "Fatal error occurred. CSTS=0x1 US[1]=0x0 US[0]=0x1b VID=0x144d DID=0xa808
. FW Revision=EXD7101Q\n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-470.40.4/IONVMeController.cpp:5258
Backtrace (CPU 0), Frame : Return Address
0xffffff812cc0b9e0 : 0xffffff8018b3bb1b 
0xffffff812cc0ba30 : 0xffffff8018c733e5 
0xffffff812cc0ba70 : 0xffffff8018c64e5e 
0xffffff812cc0bac0 : 0xffffff8018ae2a40 
0xffffff812cc0bae0 : 0xffffff8018b3b207 
0xffffff812cc0bbe0 : 0xffffff8018b3b5eb 
0xffffff812cc0bc30 : 0xffffff80192d24f9 
0xffffff812cc0bca0 : 0xffffff7f9a81c4a7 
0xffffff812cc0bcc0 : 0xffffff7f9a80747a 
0xffffff812cc0be20 : 0xffffff8019245a89 
0xffffff812cc0be90 : 0xffffff80192459a9 
0xffffff812cc0bec0 : 0xffffff8018b7d765 
0xffffff812cc0bf40 : 0xffffff8018b7d291 
0xffffff812cc0bfa0 : 0xffffff8018ae213e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[0DDEF73A-BDF3-316B-820B-9479CAF678F4]@0xffffff7f9a7f9000->0xffffff7f9a83bfff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[2FAEE793-59BC-3ADF-A5E2-3BC8760AFE0B]@0xffffff7f99584000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[1286D5E5-A6A1-3C44-A244-04C068903DB2]@0xffffff7f996f7000
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[07910380-1296-307C-A25B-FDB9D2DEBDDE]@0xffffff7f998e9000
            dependency: com.apple.iokit.IOStorageFamily(2.1)[D6C7A1D3-1E90-37A3-9D36-F6793A476858]@0xffffff7f99465000
            dependency: com.apple.iokit.IOReportFamily(47)[E3C37E96-3AFA-301F-B89C-719FB3D4DA53]@0xffffff7f99627000

BSD process name corresponding to current thread: kernel_task
Boot args: darkwake=0 dart=0 gfxrst=1 

Mac OS version:
19C57

Kernel version:
Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64
Kernel UUID: C3E7E405-C692-356B-88D3-C30041FD1E72
Kernel slide:     0x0000000018800000
Kernel text base: 0xffffff8018a00000
__HIB  text base: 0xffffff8018900000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 198613377981
last loaded kext at 10434862470: >AudioAUUC	1.70 (addr 0xffffff7f9c2d6000, size 28672)
loaded kexts:
com.intel.driver.EnergyDriver	3.6.1
com.realtek.driver.RtWlanU	1830.32.b13
as.acidanthera.voodoo.driver.PS2Keyboard	2.0.2
as.acidanthera.voodoo.driver.PS2!C	2.0.2
com.alexandred.VoodooI2CHID	1
com.alexandred.VoodooI2C	2.2
org.coolstar.VoodooGPIO	1.1
org.rehabman.driver.NullEthernet	1.0.6
as.vit9696.SMCProcessor	1.0.6
as.vit9696.!AALC	1.3.9
org.tw.CodecCommander	2.7.1
as.lvs1974.HibernationFixup	1.2.6
com.rehabman.driver.USBInjectAll	0.7.1
ru.usrsse2.SMCBatteryManager	1
as.vit9696.VirtualSMC	1.0.6
com.alexandred.VoodooI2CServices	1
as.vit9696.WhateverGreen	1.3.1
as.vit9696.Lilu	1.3.7
>AudioAUUC	1.70
@fileutil	20.036.15
>!AGraphicsDevicePolicy	4.5.21
@AGDCPluginDisplayMetrics	4.5.21
@filesystems.autofs	3.0
@filesystems.ntfs	3.14.3
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.2f4
>pmtelemetry	1
>!AHDAHardwareConfigDriver	283.15
>AGPM	111.4.1
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
@Dont_Steal_Mac_OS_X	7.0.0
>!AHDA	283.15
>!AUpstreamUserClient	3.6.8
>ACPI_SMC_PlatformPlugin	1.0.0
>!A!IKBLGraphics	14.0.3
>AGDCBacklightControl	4.5.21
>eficheck	1
>!A!IPCHPMC	2.0.1
>!ASMCLMU	212
>!AGFXHDA	100.1.422
>!A!IKBLGraphicsFramebuffer	14.0.3
>!A!ISlowAdaptiveClocking	4.0.0
>!AFIVRDriver	4.1.0
>!AMCCSControl	1.13
@private.KextAudit	1.0
>!ABacklight	180.1
>!ATopCaseHIDEventDriver	3420.1
>!AFileSystemDriver	3.0.1
>!AVirtIO	1.0
@filesystems.hfs.kext	522.0.9
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@filesystems.apfs	1412.61.1
>!AAHCIPort	341.0.2
>!ASmartBatteryManager	161.0.0
>!ARTC	2.0
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
>!AGraphicsControl	4.5.21
@kext.triggers	1.0
|IOAVB!F	800.17
>!ASSE	1.0
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
@!AGPUWrangler	4.5.21
>IOPlatformPluginLegacy	1.0.0
>!AHDA!C	283.15
|IOHDA!F	283.15
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
>!ASMBusPCI	1.0.14d1
@!AGraphicsDeviceControl	4.5.21
|IOAccelerator!F2	438.2.8
|IOSlowAdaptiveClocking!F	1.0.0
>!ASMBus!C	1.0.18d1
@plugin.IOgPTPPlugin	800.14
|IOEthernetAVB!C	1.1.0
|IOSkywalk!F	1
>!ABacklightExpert	1.1.0
|IONDRVSupport	569.3
>usb.IOUSBHostHIDDevice	1.2
>!AHS!BDriver	3420.1
>IO!BHIDDriver	7.0.2f4
|IO!B!F	7.0.2f4
|IO!BPacketLogger	7.0.2f4
>!AActuatorDriver	3420.2
>!AMultitouchDriver	3420.2
>!AInputDeviceSupport	3420.4
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>usb.!UHub	1.2
|IOSerial!F	11
|IOSurface	269.6
@filesystems.hfs.encodings.kext	1
>!AXsanScheme	3
|IOAHCIBlock!S	316.40.3
|IOAHCI!F	290.0.1
|IONVMe!F	2.1.0
>!A!ILpssGspi	3.0.60
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOHID!F	2.0.0
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|IOAudio!F	300.2
@vecLib.kext	1.2.0
|IOSMBus!F	1.1
|IOGraphics!F	569.3
>DiskImages	493.0.0
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AKeyStore	2
>!UTDM	489.60.3
|IOSCSIBlockCommandsDevice	422.0.2
>!ACredentialManager	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOTimeSync!F	800.14
|IONetworking!F	3.4
|IOUSBMass!SDriver	157.40.7
|IOSCSIArchitectureModel!F	422.0.2
|IO!S!F	2.1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
|CoreAnalytics!F	1
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.Libm	1
@kec.corecrypto	1.0

**Attach your entire EFI folder**
**附上您的整个EFI文件夹**
efi没有做任何更改，只是装了一个Wireless-USB-Adapter-Clover，并按其要求将inject一项改为了yes

非常感谢你的工作。

**Comment by linkerGitHub** [comment]
附：拷贝并不是立刻发生重启，而是在拷贝进行一段时间后重启。

**Comment by stevezhengshiqi** [comment]
@linkerGitHub 请检查硬盘型号，如果是PM981，则拷贝大文件崩溃是正常情况。

**Comment by linkerGitHub** [comment]
确认小米自带的固态是三星PM981，此issue关闭，感谢解答。
