### ISSUE TITLE
Disable MX150

### ISSUE THREAD

**Issue by gplast** [daliansky/XiaoMi-Pro-Hackintosh#316]
Hello again and thank you again for all this great effort and support.

I commented on a previous thread (https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/224#issuecomment-559897974) about that but it seems that it got lost. :)

[Original Message]
So i also noticed that the power consumption on Mac OS is not as good as on Linux (with disabled MX150) and on Windows. I have all three operating systems install on my Notebook Pro and i like to monitor the temperature all the time on all operating systems. What i noticed is that on Windows and on Linux (with Intel only enable) the CPU was getting 36-38C on idle. The strange thing is that on Mac OS the temp was 42-44C on idle, which was the same temp that i get on Linux when i have the MX150 enable.

I also noticed that using the Intel Power Gadget on Windows the PKG power was able to drop bellow 1 (0.90W) compared with the Mac OS where the lower power is around 2.80W. I don't know a lot on how to patch and all these stuff that you guys know but i've been a hackintosh user for the last 7 years and i at least i'm able to test stuff, break them and fix them again :p

So moving back to the power consumption, a couple of months ago, there was a version where the temp was good and i was able to get 4-5 hours on my device. From some point this was gone, and now i'm getting maybe 3-3,5 hours with a kind of hot laptop. So my first question is if the MX150 GPU is actually disable? Because it seems that is not.

As i was digging around to see whether there is a way to test if the GPU is off, i found this repository: https://github.com/SiddheshNan/Acer-A515-51G-Hackintosh. I noticed two file (attached) in ACPI/patched that are used to disable DGPU. I tried a lot of configuration but it seems that by copying this two files into our ACPI/patched folder the temp drops on 39C on idle and the power in the PKG is now around 2W. This is great but does that make any sense? I also have Battery Monitor for my battery and i notice that before copying the files the lowest power usage value was 12 Watts, while after copying the files i was able to get 9Watts.

I would really appreciate it if someone can test it or let me know if this is actually correct. I will test it for a couple of days of course to see also if the laptop last longer with the battery.
[Original Message]

After testing for a few days along with the WIFI SSDT to disable it seems that we can gain 1.5 - 2 hours battery life. @stevezhengshiqi i'll really appreciate it if you can test it and confirm whether or not this patch is working.

Sorry for the long message and thank you again.

[SSDT-Disable_DGPU.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/3970401/SSDT-Disable_DGPU.zip)

**Comment by stevezhengshiqi** [comment]
@gplast Thank you for testing. However, I don’t have XiaoMiPro to conduct any test. Until release v1.3.3, we use SSDT to disable discrete graphic card.
Because WhateverGreen has property disable-external-egpu which does the same thing as SSDT-Disable_DGPU, and it’s a “cleaner” way to disable DGPU, the SSDT way may not be considered anymore.

**Comment by Menchen** [comment]
@stevezhengshiqi I can confirm that by using this ssdt I got better battery life and thermals. So something must be wrong with whatevergreen.
