### ISSUE TITLE
Caps lock按键无法熄灭

### ISSUE THREAD

**Issue by Jalery521** [daliansky/XiaoMi-Pro-Hackintosh#317]
你好，我的电脑机型是XiaoMi-Pro MX150
EFI版本：v1.3.5
问题描述： 我无法关闭Caps lock大小写切换按键的指示灯，重建缓存无效，已取消勾选`使用大些锁定键切换ABC输入模式`

**Comment by Jalery521** [comment]
在别的issue中找到解决办法了，抱歉

**Comment by Jalery521** [comment]
你好，我多次重启后发现有大约一般的几率进入系统后点击开启大些后之后点击仍常亮

**Comment by Menchen** [comment]
我的cap灯好像也有问题...但是我是亮不了.

**Comment by Jalery521** [comment]
我放在了优酷上 https://v.youku.com/v_show/id_XNDQ3ODIxNjc2OA==.html?spm=a2h3j.8428770.3416059.1

**Comment by RXDA** [comment]
长按就关了

**Comment by Jalery521** [comment]
> 长按就关了

试了，不行，你是长按多少秒

**Comment by RXDA** [comment]
> > 长按就关了
> 
> 试了，不行，你是长按多少秒

你就长按短按来回按，短按完稍微等一下，多试几次就关了

**Comment by webfalter** [comment]
https://github.com/acidanthera/VoodooPS2/commit/a9cee60d35d388ff444ff27d5e29330601e7f877

**Comment by AI-Python-QI** [comment]
对于这个问题我很有发言权，因为我解决了 哈哈， 解决的方法：  把禁用的系统自带的拼音输入法再次添加上就好了，如果本来就有系统输入法，那就删了再添加一遍哈，我的电脑是xiaomi Pro GTX 版本亲测可行
