### ISSUE TITLE
Black screen when booting high sierra installer.

### ISSUE THREAD

**Issue by leo02yt** [daliansky/XiaoMi-Pro-Hackintosh#318]
Model XiaoMi-Pro GTX, i7 16gb ram

EFI Version: v1.3.5

tried to boot high sierra installer from usb, only got a black screen with a white underscore on the top left corner.

**Comment by stevezhengshiqi** [comment]
Hi, this repository is mainly for post-installation issues. You can visit detailed installation instructions on [tonymacx86](https://www.tonymacx86.com/forums/high-sierra-laptop-support.192/).
