### ISSUE TITLE
「Ethernet is not working in macOS 10.15」转接头形式的网卡是不是也不行？还是仅只板载WIFI?

### ISSUE THREAD

**Issue by daigong** [daliansky/XiaoMi-Pro-Hackintosh#319]
大佬打扰了，之前一直使用Mojave，现在想升级到Catalina，看到说明中提到的 「Ethernet is not working in macOS 10.15」是指板载wifi，还是只任何形式的转接头也不好用？

使用 Mojave时使用：https://item.jd.com/12882281248.html 绿联，一切正常，在 10.15 下是不是就不好用了？

多谢，待大佬确认

**Comment by stevezhengshiqi** [comment]
请看中文版README https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/README_CN.md Ethernet指的是有线网卡，10.15可能有问题，详情见https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/275
