### ISSUE TITLE
请问米本Pro 2019款 i7+MX250可以用这个EFI吗？

### ISSUE THREAD

**Issue by kqkdChen** [daliansky/XiaoMi-Pro-Hackintosh#322]
请问米本Pro 2019款 i7+MX250可以用这个EFI吗？
或者说有没有针对2019的EFI？感激不尽

**Comment by stevezhengshiqi** [comment]
仔细对照[电脑配置](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/README_CN.md#电脑配置)，此仓库仅支持2017和2018款的。
