### ISSUE TITLE
全屏看视频时闪屏

### ISSUE THREAD

**Issue by Exildoutsider** [daliansky/XiaoMi-Pro-Hackintosh#324]
- 机型：米本Pro MX150高配版
- 系统：10.15.2
- EFI ：最新未作修改
- 问题：全屏看视频时闪屏，十几到几十秒一次，复现频率极高。
> 我一般在B站看视频，其他视频网站没有测试过。闪屏问题一直有，

**Comment by chaohui78120** [comment]
只有全屏都是视频的时候才会出现此问题，全屏时有弹幕飘过，或者全屏时一直保持底部进度栏浮现等有其他元素和视频同时出现就不会发生闪屏的现象。
同求解答

**Comment by FantDing** [comment]
I have the same problem

**Comment by yipingw** [comment]
google chrome 确实有此问题, 其他浏览器:safari, firefox均正常.

**Comment by 27392** [comment]
关闭chrome中的硬件加速模式即可解决

**Comment by yipingw** [comment]
最新的chrome版本似乎解决了该问题, 我当前使用的是80.0的版本.

**Comment by FantDing** [comment]
> 关闭chrome中的硬件加速模式即可解决

谢谢，关闭问题解决了

**Comment by Exildoutsider** [comment]
解决办法：换用safari或关闭Chrome的硬件加速功能

**Comment by ju0594** [comment]
> 只有全屏都是视频的时候才会出现此问题，全屏时有弹幕飘过，或者全屏时一直保持底部进度栏浮现等有其他元素和视频同时出现就不会发生闪屏的现象。
> 同求解答
是的，我也发现了，我发现了一个[添加进度条](https://greasyfork.org/zh-CN/scripts/394512-youtube-progressbar-preserver)的油猴脚本，可以解决YouTube的问题，依照这个原理，写一个油猴脚本，在检测到全屏的时候悬浮显示一张1*1像素的透明图片，也许也可以防止花屏？

虽然关闭硬件加速可以解决，但是耗电呀！也不知道白果有没有这个问题...
