### ISSUE TITLE
关于默认super和alt按键映射的疑问

### ISSUE THREAD

**Issue by justforlxz** [daliansky/XiaoMi-Pro-Hackintosh#327]
默认情况下super被映射为command，而alt被映射为option，这和实际上苹果的按键是相反的。我想知道是否特殊处理过？

谢谢！

**Comment by justforlxz** [comment]
目前根据我用synergy软件得出的情况，按alt也是触发的option  :sob:

**Comment by jackreeves** [comment]
Can fix using native MacOS options. Just goto Settings > Keyboard

![image](https://user-images.githubusercontent.com/9420407/72051877-56d50000-32c4-11ea-9aa8-e459f27061d4.png)

And use these settings...

![image](https://user-images.githubusercontent.com/9420407/72051894-5ccae100-32c4-11ea-8acc-3cc3ba57d3ea.png)

**Comment by justforlxz** [comment]
> Can fix using native MacOS options. Just goto Settings > Keyboard
> 
> ![image](https://user-images.githubusercontent.com/9420407/72051877-56d50000-32c4-11ea-9aa8-e459f27061d4.png)
> 
> And use these settings...
> 
> ![image](https://user-images.githubusercontent.com/9420407/72051894-5ccae100-32c4-11ea-8acc-3cc3ba57d3ea.png)

Thank you, I know that it can be modified through settings. Why the system does not have the same key position as mac, what I want to know is this.
