### ISSUE TITLE
Finished Soldering BT and WIFI (photos inside) and some question 

### ISSUE THREAD

**Issue by macguru341** [daliansky/XiaoMi-Pro-Hackintosh#328]
So I’ve decided to take my Xioami to some expert to make the soldering and also use that chance to solder the WiFi because I had some issues connecting the new WiFi card cables to the WiFi connections On the MB.

![B8A3B1CC-3AD9-43DB-9CDC-CC55BA35FB2E](https://user-images.githubusercontent.com/22807164/73478289-7f6d8880-439e-11ea-85a5-262553844c25.jpeg)
![96AC1569-1336-44DD-A11A-48D82E74D778](https://user-images.githubusercontent.com/22807164/73478290-7f6d8880-439e-11ea-956f-9c9df9ff4fb4.jpeg)

Just to know , can I update to Mac OS X 10.15 through the settings in the regular way? And what will not work anymore? Only the Ethernet?
Thanks

**Comment by stevezhengshiqi** [comment]
Yes.
