### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by spita90** [daliansky/XiaoMi-Pro-Hackintosh#329]
Hi!
I wonder if the new Bluetooth compatibility could be the reason for you to publish a new release.
Thank you

**Comment by stevezhengshiqi** [comment]
I will receive my laptop in a week, and sorry for the delay. My old XiaoMi laptop was broken long time ago due to a short circuit on the mainboard.

**Comment by Menchen** [comment]
@stevezhengshiqi , That's great news! By the way, was the damage caused by hardware mods or just bad bad quality control from Xiaomi?

**Comment by stevezhengshiqi** [comment]
@Menchen I think it’s my issue. I put some liquid metal on the CPU, and it flows to the mainboard, resulting a short circuit ><. I used thermal paste around the CPU to stop liquid metal from flowing elsewhere, but it seems not work.

**Comment by j8m1e** [comment]
any updates?
