### ISSUE TITLE
Windows not running smoothly after MacOS Install

### ISSUE THREAD

**Issue by clmsftsw** [daliansky/XiaoMi-Pro-Hackintosh#334]
Somebody else has the problem that Windows is not running good after the Hackintosh install? It really seems as it lacks performance all of a sudden. Even opening the Explorer or the Settings is really slow. Furthermore the slider to change performance mode or battery save mode is missing.

Is there a way to fix these issues? Maybe an reinstall of Windows would help? I would prefer if not to though...

Thank you in advance!

**Comment by Drun555** [comment]
It's theoretically can happen if you installed macos and windows on same disk - maybe there's not enough space on windows partition, and SSD is gone wild. It's the only situation I could imagine when hackintosh can be the reason.

**Comment by clmsftsw** [comment]
Actually both OS are on different SSDs. I will reinstall Windows clean and look if this will help.

**Comment by zb2947244682** [comment]
I do not  meet with this issue

**Comment by charlesld** [comment]
Same hits.   
when staring win10 , it's really slow  .    
And I use 2 ssds, win10 on the main slot , mac on the second slot.    

![image](https://user-images.githubusercontent.com/23304239/79304363-c1c94f00-7f23-11ea-9f6b-dc45e30b117c.png)
