### ISSUE TITLE
双系统小米pro更新失败

### ISSUE THREAD

**Issue by zeusro** [daliansky/XiaoMi-Pro-Hackintosh#336]
**State the model**
**阐述您的机型**
-  XiaoMi-Pro GTX,...

**State the version of the EFI**
**阐述您的EFI版本**
- XiaoMi NoteBook Pro EFI v1.3.5

**Describe the bug**
**描述您遇到的问题**
- 使用脚本在线EFI，之后点击 macOS Catalina 10.15.3(19D76) Installer for Clover 5103 and WEPE.dmg （黑果小兵的最新镜像），4分钟后重启，选择 install ，之后会卡住或者直接黑屏，无法继续更新下去。当前mac系统版本：10.14.2

**Comment by stevezhengshiqi** [comment]
@zeusro 你好，黑屏五分钟之后有尝试过强制重启吗，README里有写。

**Comment by zeusro** [comment]
> @zeusro 你好，黑屏五分钟之后有尝试过强制重启吗，README里有写。

感谢你的回复，我直接更新EFI,然后 app store 升级系统就好了。

蓝牙都可以用了，非常感谢你们的劳作。

Thank you for your work

**Comment by zeusro** [comment]
目前用的是 XiaoMi NoteBook Pro EFI v1.3.5

系统升级到 10.15.3

**Comment by fang0814** [comment]
我的没法正常更新到10.15.4 重启进入install data 后卡在白色苹果logo界面 没有进度条 一直卡了好几个小时没变化

**Comment by fang0814** [comment]
好像是这个的原因https://www.reddit.com/r/hackintosh/comments/fo9bfv/macos_10154_update/

**Comment by stevezhengshiqi** [comment]
@fang0814 正确更新efi v1.3.7就可以升级

**Comment by fang0814** [comment]
> @fang0814 正确更新efi v1.3.7就可以升级。先删除BOOT 和 CLOVER文件夹，然后把release包里的相应文件夹放进去。不用任何多余操作，大家都升级成功了。

谢谢🙏您 我更换EFI后也成功了！！！感谢这个社区项目
