### ISSUE TITLE
[ ERROR ]: 未检测到CLOVER文件夹

### ISSUE THREAD

**Issue by binbinyounimen** [daliansky/XiaoMi-Pro-Hackintosh#337]
### 你好。先谢谢作者的辛苦。在按照你的步骤进行『更新EFI』的时候，出现了错误
**[ ERROR ]: 未检测到CLOVER文件夹**
`
您的主板型号是 TM1701
=====================================================================
(1) 更新EFI
(2) 更改蓝牙模式 (仅支持最新release)
(3) 通用声卡修复 (credits Menchen)
(4) 添加色彩文件
(5) 更新变频管理
(6) 更改TDP和CPU电压 (credits Pasi-Studio)
(7) 开启HiDPI
(8) 设置帧缓存为64mb (4K 屏幕) 和 解锁0xE2寄存器 (credit Menchen)
(9) 修复Windows启动 (仅支持最新release)
(10) 修复Apple服务
(11) 反馈问题
(12) 退出
您想选择哪个选项? (1/2/3/4/5/6/7/8/9/10/11/12)
:1

正在重建缓存...
[ OK ]重建完成

----------------------------------------------------------------------------------
|* 正在下载EFI, 源于 https://github.com/daliansky/XiaoMi-Pro-Hackintosh/releases *|
----------------------------------------------------------------------------------
######################################################################################################################################################### 100.0%######################################################################################################################################################### 100.0%
[ OK ]下载完成

正在挂载EFI分区...
Password:
[ ERROR ]: 未检测到CLOVER文件夹

正在取消挂载EFI分区...
[ OK ]取消挂载成功

请按任何键返回主菜单...`

### 我确定我删除了Windows下面的EFI，保证了只存在一个EFI目录，请问该错误如何解决？
` bin@MacbookPro  ~   sudo diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *256.1 GB   disk0
   1:       Microsoft Basic Data                         314.6 MB   disk0s1
   2:       Microsoft Basic Data                         255.7 GB   disk0s2

/dev/disk1 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.1 GB   disk1
   1:                        EFI EFI                     209.7 MB   disk1s1
   2:                 Apple_APFS Container disk2         499.9 GB   disk1s2

/dev/disk2 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +499.9 GB   disk2
                                 Physical Store disk1s2
   1:                APFS Volume Mac_lu - 数据           37.6 GB    disk2s1
   2:                APFS Volume Preboot                 82.5 MB    disk2s2
   3:                APFS Volume Recovery                526.6 MB   disk2s3
   4:                APFS Volume VM                      1.1 GB     disk2s4
   5:                APFS Volume Mac_lu                  11.0 GB    disk2s5`

**Comment by stevezhengshiqi** [comment]
这个更新脚本只支持一个EFI分区，你的disk0s1和disk1s1可能都是EFI分区。两个EFI分区的情况下需要手动更新EFI。
