### ISSUE TITLE
Wi-Fi adapter stopped working after update 10.14 -> 10.15

### ISSUE THREAD

**Issue by LoonyMan** [daliansky/XiaoMi-Pro-Hackintosh#339]
Hello everyone, I have an ASUS USB-N13 WiFi adapter based on the rtl8192cu chipset. Before the update at 10.15, everything worked as it should, but after the update the program from the official Asus website stopped working. I found a driver on GitHub (link) that was supposed to help me, since my chipset and WiFi adapter are on the list of supported ones. But after installation, my WiFi adapter does not find any networks. [https://github.com/chris1111/Wireless-USB-Adapter-Clover](url)
I use hackintosh on the Xiaomi Mi Notebook Pro 15 ".
From here i use clover and kexts [https://github.com/daliansky/XiaoMi-Pro-Hackintosh](url)
![18881121](https://user-images.githubusercontent.com/55630467/74934963-65045900-53f8-11ea-842c-3004240d672c.png)  
//Translate: Choosing a network to connect <empty>
![18881120](https://user-images.githubusercontent.com/55630467/74934964-659cef80-53f8-11ea-9780-279309f6637c.png) 
I use Xiaomi Mi Notebook Pro 15" i5 8250U + 8gb, EFI v1.3.5. In the config.plist file, only injectKexts = Yes was fixed. 
[kexts.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4230804/kexts.zip)

**Comment by fredtanz** [comment]
Try to move `RtWlanU1827.kext` and `RtWlanU.kext` from `/Volumes/EFI/CLOVER/kexts/Other/` to `<your esp partition>/EFI/CLOVER/kexts/Other/`, run `sudo kextcache -i /` then reboot.

**Comment by LoonyMan** [comment]
OMG, You are the best! I booted from USB and did not know that in eps partiton I needed to install kexts. I move RtWlanU1827.kext and RtWlanU.kext to /Volumes/CLOVER/EFI/CLOVER/kexts/Other. After that, wifi adapter still didn't work. I reinstalled the driver and wifi works even better than 10.14. Thx for the help!
P.S. 
Sorry for my English :)
