### ISSUE TITLE
Bootloop after catalina public beta update

### ISSUE THREAD

**Issue by arandax** [daliansky/XiaoMi-Pro-Hackintosh#341]
Hi all,
I already updated to other catalina public beta update but today after some reboot during the update process, hackintosh can't boot anymore and the "your computer has restarted..." screen appear. Tried reboot again but I face into this bootloop.
Any suggestions how to fix without reinstall everything again?

**Comment by Menchen** [comment]
See #340

**Comment by arandax** [comment]
thank you and sorry for the duplicate issue!
