### ISSUE TITLE
最近总是重启

### ISSUE THREAD

**Issue by zeusro** [daliansky/XiaoMi-Pro-Hackintosh#342]
**State the model**
**阐述您的机型**
- XiaoMi-Pro GTX 1050
- MAC10.15.3

**State the version of the EFI**
**阐述您的EFI版本**
- XiaoMi NoteBook Pro EFI v1.3.5

**Describe the bug**
**描述您遇到的问题**
- A clear and concise description of what the bug is.
- 频繁无规律重启

**System log**
**系统报告**
- If a windows "Your computer was restarted because of a problem" appears, click `Report` and attach the log to help find the problem.
- 如果出现窗口"您的电脑因为出现问题而重新启动"，点击`报告`并附上错误日志来帮助定位问题。

**Screenshots**
**截图**
- If applicable, add screenshots to help explain your problem.
- 如果可用，请添加截图来帮助说明您遇到的问题。

**Attach your entire EFI folder**
**附上您的整个EFI文件夹**
- Please attach your entire EFI folder to help solve your problem.
- Erasing serial numbers in config.plist is required!
- 请附上整个EFI文件夹来方便解决问题。
- 附件里的config.plist请清除序列号！

**Attach system.log**
**附上system.log**
- If applicable, please run `log show --predicate "processID == 0" --start YYYY-MM-DD --debug` in `Terminal.app` to help locate the problem.

```
2020-03-01 19:17:40.282176+0800 0x3ec      Fault       0x0                  0      0    kernel: (IOAcceleratorFamily2) virtual IOReturn IOAccelLegacySurface::set_id_mode(uint32_t, uint32_t): Surface mode contains bad bits
2020-03-01 19:17:40.282298+0800 0x3ec      Fault       0x0                  0      0    kernel: (IOAcceleratorFamily2) virtual IOReturn IOAccelLegacySurface::set_id_mode(uint32_t, uint32_t): Surface mode contains bad bits
2020-03-01 19:17:40.282400+0800 0x3ec      Fault       0x0                  0      0    kernel: (IOAcceleratorFamily2) virtual IOReturn IOAccelLegacySurface::set_id_mode(uint32_t, uint32_t): Surface mode contains bad bits
2020-03-01 19:17:40.282454+0800 0x3ec      Fault       0x0                  0      0    kernel: (IOAcceleratorFamily2) virtual IOReturn IOAccelLegacySurface::set_id_mode(uint32_t, uint32_t): Surface mode contains bad bits
```

**Comment by zeusro** [comment]
panic(cpu 0 caller 0xffffff7f8b1b94a7): nvme: "Fatal error occurred. CSTS=0x1 US[1]=0x0 US[0]=0x36 VID=0x144d DID=0xa808
. FW Revision=EXD7201Q\n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-470.80.1/IONVMeController.cpp:5258
Backtrace (CPU 0), Frame : Return Address
0xffffff92224b39e0 : 0xffffff800893bb2b 
0xffffff92224b3a30 : 0xffffff8008a734d5 
0xffffff92224b3a70 : 0xffffff8008a64f4e 
0xffffff92224b3ac0 : 0xffffff80088e2a40 
0xffffff92224b3ae0 : 0xffffff800893b217 
0xffffff92224b3be0 : 0xffffff800893b5fb 
0xffffff92224b3c30 : 0xffffff80090d2aa9 
0xffffff92224b3ca0 : 0xffffff7f8b1b94a7 
0xffffff92224b3cc0 : 0xffffff7f8b1a447a 
0xffffff92224b3e20 : 0xffffff8009045e59 
0xffffff92224b3e90 : 0xffffff8009045d79 
0xffffff92224b3ec0 : 0xffffff800897d7e5 
0xffffff92224b3f40 : 0xffffff800897d311 
0xffffff92224b3fa0 : 0xffffff80088e213e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[6BD739D2-AAF2-36CA-AB08-1B84F0E860C2]@0xffffff7f8b196000->0xffffff7f8b1d8fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[A243D030-19AC-30AA-AC70-6C786DF9E6CE]@0xffffff7f8942a000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[ADD485B5-3EF8-37C4-B3C5-F86326E497A4]@0xffffff7f892da000
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[D1753114-1FE3-3849-A7FA-452EDAB62495]@0xffffff7f8a325000
            dependency: com.apple.iokit.IOStorageFamily(2.1)[76CF8513-C8B7-3A6F-9717-6D3F65B298BB]@0xffffff7f8926a000
            dependency: com.apple.iokit.IOReportFamily(47)[988360A2-2E10-3014-A119-BE81BC045A10]@0xffffff7f894dd000

BSD process name corresponding to current thread: kernel_task
Boot args: darkwake=0 dart=0 gfxrst=1 

Mac OS version:
19D76

Kernel version:
Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
Kernel UUID: A8DDE75C-CD97-3C37-B35D-1070CC50D2CE
Kernel slide:     0x0000000008600000
Kernel text base: 0xffffff8008800000
__HIB  text base: 0xffffff8008700000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 236427740237
last loaded kext at 178920857033: >usb.IOUSBHostHIDDevice	1.2 (addr 0xffffff7f8d560000, size 45056)
last unloaded kext at 137315020539: >!A!ILpssGspi	3.0.60 (addr 0xffffff7f898fa000, size 45056)
loaded kexts:
com.realtek.driver.RtWlanU	1830.32.b13
com.zxystd.!I!BFirmware	1.0.2
as.acidanthera.voodoo.driver.PS2Keyboard	2.0.2
as.acidanthera.voodoo.driver.PS2!C	2.0.2
com.alexandred.VoodooI2CHID	1
com.alexandred.VoodooI2C	2.2
org.coolstar.VoodooGPIO	1.1
org.rehabman.driver.NullEthernet	1.0.6
as.vit9696.SMCProcessor	1.0.6
org.tw.CodecCommander	2.7.1
as.vit9696.!AALC	1.3.9
com.rehabman.driver.USBInjectAll	0.7.1
ru.usrsse2.SMCBatteryManager	1
as.vit9696.VirtualSMC	1.0.6
com.alexandred.VoodooI2CServices	1
as.vit9696.WhateverGreen	1.3.1
as.lvs1974.HibernationFixup	1.2.6
as.vit9696.Lilu	1.3.7
>AudioAUUC	1.70
@fileutil	20.036.15
@filesystems.autofs	3.0
@filesystems.ntfs	3.14.3
>AGPM	111.4.2
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
>!AUpstreamUserClient	3.6.8
>!AMCCSControl	1.13
>!AHDA	283.15
>!AGraphicsDevicePolicy	4.7.2
@AGDCPluginDisplayMetrics	4.7.2
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.3f5
>pmtelemetry	1
>!AHV	1
@Dont_Steal_Mac_OS_X	7.0.0
>!A!IKBLGraphics	14.0.4
>!A!ISlowAdaptiveClocking	4.0.0
>!A!IPCHPMC	2.0.1
>!A!IKBLGraphicsFramebuffer	14.0.4
>!ASMCLMU	212
>eficheck	1
>usb.!UHostBillboardDevice	1.0
@private.KextAudit	1.0
>usb.realtek8153patcher	5.0.0
>!ATopCaseHIDEventDriver	3430.1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
>!AVirtIO	1.0
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@filesystems.hfs.kext	522.0.9
@filesystems.apfs	1412.81.1
>!ASmartBatteryManager	161.0.0
>!ARTC	2.0
>!AACPIButtons	6.1
>!ABacklight	180.1
>!ASMBIOS	2.1
>!AAPIC	1.7
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	303
$!AImage4	1
|EndpointSecurity	1
>usb.IOUSBHostHIDDevice	1.2
>usb.cdc.acm	5.0.0
>usb.serial	6.0.0
>usb.cdc.ecm	5.0.0
>!UAudio	320.49
@kext.triggers	1.0
>!ASMBus!C	1.0.18d1
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
>!AGraphicsControl	4.7.2
|IOAVB!F	800.17
>!ASSE	1.0
@!AGPUWrangler	4.7.2
|IOSlowAdaptiveClocking!F	1.0.0
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
@!AGraphicsDeviceControl	4.7.2
|IOAccelerator!F2	438.3.1
@plugin.IOgPTPPlugin	810.1
|IOEthernetAVB!C	1.1.0
>!AHDA!C	283.15
|IOHDA!F	283.15
|IOSkywalk!F	1
>!AActuatorDriver	3430.1
>!AHS!BDriver	3430.1
>IO!BHIDDriver	7.0.3f5
>!AMultitouchDriver	3430.1
>!AInputDeviceSupport	3430.1
|Broadcom!BHost!CUSBTransport	7.0.3f5
|IO!BHost!CUSBTransport	7.0.3f5
|IO!BHost!CTransport	7.0.3f5
|IO!B!F	7.0.3f5
|IO!BPacketLogger	7.0.3f5
>usb.!UHub	1.2
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
|IOSerial!F	11
@filesystems.hfs.encodings.kext	1
|IOSurface	269.6
|IONVMe!F	2.1.0
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOHID!F	2.0.0
>!ABacklightExpert	1.1.0
|IONDRVSupport	569.4
|IOGraphics!F	569.4
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|IOAudio!F	300.2
@vecLib.kext	1.2.0
|IOSMBus!F	1.1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AKeyStore	2
>!UTDM	489.80.2
|IOSCSIBlockCommandsDevice	422.0.2
|IOUSBMass!SDriver	157.40.7
|IOSCSIArchitectureModel!F	422.0.2
>DiskImages	493.0.0
|IO!S!F	2.1
|CoreAnalytics!F	1
|IOTimeSync!F	810.1
|IONetworking!F	3.4
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.Libm	1
@kec.corecrypto	1.0

**Comment by zeusro** [comment]
我来试试  https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/238
提到的脚本
```
windows=$(diskutil list |grep 'Microsoft Reserved')
re="(disk[0-9]+).*"
if [[ $windows =~ $re ]]; then obj=${BASH_REMATCH[1]}; fi
diskutil unmountDisk $obj
```

**Comment by stevezhengshiqi** [comment]
你好，这个问题和https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/338 类似。可以尝试NvmeFix。

**Comment by HKMV** [comment]
我的耳机也连上了,但是耳机的声音很大,都调到2%了感觉还是有点大;还有一个问题是耳机的音频输入好像不起作用接受不到声音.
![image](https://user-images.githubusercontent.com/26456469/75685516-a4bf2080-5cd5-11ea-8ec3-1b54c9ada21c.png)
