### ISSUE TITLE
Geekbench difference Windows vs MacOS

### ISSUE THREAD

**Issue by p33k** [daliansky/XiaoMi-Pro-Hackintosh#343]
With Geekbench 5 I get this results:
Xiaomi Mi Notebook Pro I7 8550u

Windows 10 Pro: **Single Core: 1080 Multi Core: 3733**
MacOS Catalina 10.15.3: **Single Core: 913 Multi Core: 2921**

How can this be optimized?
Strangely with my other hackintoshs, especially desktop I get better scores under MacOS than Windows.

In my case battery life doesn't matter because it's always running on power socket.

**Comment by stevezhengshiqi** [comment]
@p33k Hi, detailed discussions about performance are in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/53 and https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/174

You can always use the script mentioned in the README and choose option 5 to adjust the performance level.

The command to run the script:
``bash -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/master/install.sh)"``

If you are using MX150 version, you can use option 6 to have more modifications on TDP or voltage.

**Comment by p33k** [comment]
I have the MX250 version.
When I try option 6 the problem is I can't download the unlocker:
https://file.pasi.cat/powercpu/BIOS_unlock.zip

**Comment by stevezhengshiqi** [comment]
Option 6 can only be used by MX150. You can try 5.
