### ISSUE TITLE
Catalina 10.15.3 can not boot - [IGPU] Hash data from ME never returned

### ISSUE THREAD

**Issue by MarFre22** [daliansky/XiaoMi-Pro-Hackintosh#345]
Hi,
First of all, 
thank you everyone who contribute for this project.

After a long waiting to recovery data from a dead SSD (which has the MacOS Mojave 10.14.4 (I think...)) - https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/265

With a successful recovery, before I update to Carolina 10.15.3, I updated all apps and, also, the EFI partition with the most recent EFI folder (with the script in the Readmed page). I made the update from the app store (10.14.4 to 10.15.3). After the update it can not boot because it gives an error (in the video) - "[IGPU] Hash data from ME never returned, status=1, doing retry" resulting in "In Memory Panic Stackshot Succeeded".

In chronological order:
-What I tried and did not work:
a) with a SSD enclosure, change EFI to EFI 1.3.5 (deleted Apple folder and EFI Folder in EFI partition, and replace with EFI 1.3.5).

b) Inject EFI Strings (Clover), update EFI to the newest with the script. 

c) Try the solution at the Issues (Catalina 10.15.4 beta does not boot) - https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/340.
Also tried -disablegfxfirmware, but it disable the iGPU Intel, so it is not a solution in this case.

d) With Inject EFI Strigs with the update made, I made a Time Machine Backup. 
Reinstalled MacOS 10.15.3 (with a bootable USB with 1.3.5 EFI) and restore the full backup, it did not work.

What I tried and temporary worked:
e) Deleted MacOS partitions and installed 10.15.3 (with a bootable USB with 1.3.5 EFI) and restored the Time Machine backup without computer settings and network option (at restore). It could boot, but after replace Apple folder and EFI folder at EFI partition with EFI 1.3.5, it can not boot...

I can't find any related issue with this version (10.15.3) in Mi Notebook Pro Hackintosh. Also I'm a little desperate because after all tries I can not solve this problem.
I'm little newbie in this area and with all experience in this community we can solve this.

Video about the boot error: https://1drv.ms/u/s!Ah3hWN7tnl3aqknogy9LlSp_MVEV?e=txzv1G

Thank you very much for the attention!

**Comment by Menchen** [comment]
Try the latest EFI directly from repo, (delete OC folder)

**Comment by MarFre22** [comment]
@Menchen 
I did what you said, and updated whatever green from here https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/340
It doesn't boot and when I try to inject EFI strings it stuck in booting (1hour) with this "log":
https://photos.app.goo.gl/sakaae9fEPP4mmaS8

**Comment by MarFre22** [comment]
@Menchen 
The WD (dead disk) was cloned entirely to Evo. The Evo is a new disk. Also I can remove the MacOs partition and install MacOS, which I have made and it worked. But I need to restore the time machine backup.

**Comment by MarFre22** [comment]
It's very strange....
I deleted all partitions in 970 Evo. Installed 10.15.3 with a bootable Usb (with most recent EFI downloaded from repo with whatever green 1.3.7). Restored from time machine at the setup. It boots directly. But when I copy and paste BOOT and CLOVER (from bootable USB) it never boots even with Inject EFI Strings.

Is it something related with SIP from Catalina?

**Comment by Menchen** [comment]
You should be able to boot from the EFI file directly from the repo, SIP from Catalina has nothing to do with it as by default is most Hackintosh is disabled.

**Comment by MarFre22** [comment]
Booting with Inject EFI Strings give this:
![](https://i.imgur.com/vsxbPox.jpg)

**Comment by MarFre22** [comment]
@Menchen 
So it can be something related with time machine backup, it's breaking something...

**Comment by Menchen** [comment]
@MarFre22 maybe the backup is corrupted, I would recommend you to do a fresh install...

Can you try to delete InterBluetoothFirmware kext?

**Comment by MarFre22** [comment]
@Menchen 
Also can I delete  IntelBluetoothInjector.kext?

**Comment by Menchen** [comment]
Yes

**Comment by MarFre22** [comment]
@Menchen 
Unfortunately... it can not boot (also with Inject EFI Strings). 
So I have a corrupt Backup....
Thank you very much for the help!

**Comment by MarFre22** [comment]
Well, I decided to install everything again. And yes, the backup was indeed corrupted because it took a short time to do (strange..).
Once again, thank you very much for helping!
