### ISSUE TITLE
Archer T2U Nano and Google Wifi

### ISSUE THREAD

**Issue by ZambraDesigner** [daliansky/XiaoMi-Pro-Hackintosh#347]
hello to all guys, as usb wifi I use Archer T2U Nano and it never gave me problems.
But now that I need to connect to a network managed by Google Wifi my connection is really slow.
The connection should be 700MB but travel at 8-12MB.

I currently have MacOS 10.14.6 on Mi Notebook Pro updated to the latest EFI available here

https://www.tp-link.com/us/home-networking/usb-adapter/archer-t2u-nano/

**Comment by rajibxo** [comment]
Comfast USB wifi works better too, CF-811AC, AC standard 5 Ghz. maybe limit by the USB connection, its dirt cheap too, 5-8 bucks in china....

**Comment by MarFre22** [comment]
I made a summary post that includes this issue. https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/375
