### ISSUE TITLE
Webcam not working catalina 10.15.3

### ISSUE THREAD

**Issue by leo02yt** [daliansky/XiaoMi-Pro-Hackintosh#348]
hi!

i have a mi notebook pro GTX on which i have installed Catalina and windows.
i noticed, when i needed it, that my webcam is not working, is there anyone willing to help me with his or that knows a workaround?

thanks in advance

**Comment by stevezhengshiqi** [comment]
Hi, please try `sudo kextcache -i /` in `Terminal.app` and restart the device whenever meet this problem.

**Comment by leo02yt** [comment]
Thanks, this solved the problem!
