### ISSUE TITLE
小米笔记本pro增强版 十代i7 10510u能用这个EFI吗

### ISSUE THREAD

**Issue by Genmer** [daliansky/XiaoMi-Pro-Hackintosh#350]
小米笔记本pro增强版 十代i7 10510u能用这个EFI吗，显卡是mx250

**Comment by HKMV** [comment]
应该是可以的你买得最新的啊，我的也是pro只不过是去年五月份买的，那时候还不是10代，显卡是一样的，你这个固态1T很奈斯，我的使用是没问题。具体还要你自己测试。

**Comment by stevezhengshiqi** [comment]
不太可以。显卡id，声卡节点，SMBIOS机型都不太一样。

**Comment by lj3lj3** [comment]
> 不太可以。显卡id，声卡节点，SMBIOS机型都不太一样。热补丁也需要重新定制。

你好，可以在仓库上单独切个增强版的分支来么？毕竟机器相近性很高，放在一个仓库上也方便大家找到。

**Comment by stevezhengshiqi** [comment]
@lj3lj3 目前没有成熟的EFI呀。。

**Comment by lj3lj3** [comment]
@stevezhengshiqi  pcbeta上的这个其实功能基本可以使用了 只有声卡目前无法驱动 请看[http://bbs.pcbeta.com/viewthread-1840423-1-1.html](http://bbs.pcbeta.com/viewthread-1840423-1-1.html)

**Comment by Genmer** [comment]
谢谢老哥，我之前花了100找人弄了，也是声卡外放不行

**Comment by stevezhengshiqi** [comment]
@lj3lj3 让那个作者自己新开一个仓库吧。我和那个链接里的EFI没任何关系，应该要放入原始作者的仓库。
