### ISSUE TITLE
OpenCore v 1.3.6 - Cannot wake from sleep and kernel panics

### ISSUE THREAD

**Issue by kugn** [daliansky/XiaoMi-Pro-Hackintosh#352]
**State the model**
**阐述您的机型**
XiaoMi-Pro MX150

**State the version of the EFI**
**阐述您的EFI版本**
v1.3.6 OpenCore

**Describe the bug**
**描述您遇到的问题**

When it becomes idle and seems to enter into sleep mode, the fan starts whirring and it cannot wake. Pressing the power button immediately shuts down the computer. 

**System log**
**系统报告**
- If a windows "Your computer was restarted because of a problem" appears, click `Report` and attach the log to help find the problem.
- 如果出现窗口"您的电脑因为出现问题而重新启动"，点击`报告`并附上错误日志来帮助定位问题。

panic(cpu 0 caller 0xffffff8002aa2d1c): Sleep transition timed out after 180 seconds while calling power state change callbacks. Suspected bundle: com.apple.iokit.IOUSBHostFamily. Thread 0x55c4.
Failure code:: 0x00000004 00000014

Backtracing specified thread
Backtrace (CPU 0), Frame : Return Address
0xffffff81229eb900 : 0xffffff8002460178 
0xffffff812422bc40 : 0xffffff800235d771 
0xffffff812422bcb0 : 0xffffff800235bf6f 
0xffffff812422bd00 : 0xffffff800245d2b9 
0xffffff812422bd40 : 0xffffff800245cbdb 
0xffffff812422bd70 : 0xffffff8002a3f578 
0xffffff812422bda0 : 0xffffff8002a42489 
0xffffff812422be00 : 0xffffff8002a2794b 
0xffffff812422bea0 : 0xffffff8002a27344 
0xffffff812422bec0 : 0xffffff800237d7e5 
0xffffff812422bf40 : 0xffffff800237d311 
0xffffff812422bfa0 : 0xffffff80022e213e 

BSD process name corresponding to current thread: kernel_task
Boot args: darkwake=0 gfxrst=1

Mac OS version:
19D76

Kernel version:
Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
Kernel UUID: A8DDE75C-CD97-3C37-B35D-1070CC50D2CE
Kernel slide:     0x0000000002000000
Kernel text base: 0xffffff8002200000
__HIB  text base: 0xffffff8002100000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 1551668467683

**Comment by stevezhengshiqi** [comment]
Hi, could you try to disable Intel Bluetooth kexts. A lot of sleep issues are caused by these kexts. Find the following code:
```
<dict>
	<key>BundlePath</key>
	<string>IntelBluetoothFirmware.kext</string>
	<key>Comment</key>
	<string>Bluetooth</string>
	<key>Enabled</key>
	<true/>
	<key>ExecutablePath</key>
	<string>Contents/MacOS/IntelBluetoothFirmware</string>
	<key>MaxKernel</key>
	<string></string>
	<key>MinKernel</key>
	<string></string>
	<key>PlistPath</key>
	<string>Contents/Info.plist</string>
</dict>
<dict>
	<key>BundlePath</key>
	<string>IntelBluetoothInjector.kext</string>
	<key>Comment</key>
	<string>Bluetooth</string>
	<key>Enabled</key>
	<true/>
	<key>ExecutablePath</key>
	<string></string>
	<key>MaxKernel</key>
	<string></string>
	<key>MinKernel</key>
	<string></string>
	<key>PlistPath</key>
	<string>Contents/Info.plist</string>
</dict>
```
Change to:
```
<dict>
	<key>BundlePath</key>
	<string>IntelBluetoothFirmware.kext</string>
	<key>Comment</key>
	<string>Bluetooth</string>
	<key>Enabled</key>
	<false/>
	<key>ExecutablePath</key>
	<string>Contents/MacOS/IntelBluetoothFirmware</string>
	<key>MaxKernel</key>
	<string></string>
	<key>MinKernel</key>
	<string></string>
	<key>PlistPath</key>
	<string>Contents/Info.plist</string>
</dict>
<dict>
	<key>BundlePath</key>
	<string>IntelBluetoothInjector.kext</string>
	<key>Comment</key>
	<string>Bluetooth</string>
	<key>Enabled</key>
	<false/>
	<key>ExecutablePath</key>
	<string></string>
	<key>MaxKernel</key>
	<string></string>
	<key>MinKernel</key>
	<string></string>
	<key>PlistPath</key>
	<string>Contents/Info.plist</string>
</dict>
```

**Comment by kugn** [comment]
Thank you so much Steve, I will try it. Not sure whether it's related, but sometimes when it does wake up from sleep, bluetooth doesn't seem to be working. 

That said, I was wondering though whether it was an OpenCore issue, as bluetooth seemed to be working fine, and there were no similar kernel panics, when I was using your Clover (also v 1.3.6)?

**Comment by stevezhengshiqi** [comment]
@kugn Because OpenCore and Clover use different kext injection methods, I am not really sure whether the IntelBluetooth causes your issue or not. By the way, it's a USB problem. USB Wifi driver or any other USB driver may cause this issue. It's hard to find the real cause.

**Comment by matvada** [comment]
@stevezhengshiqi a friend of mine have the same problem but with Clover, same error

panic(cpu 0 caller 0xffffff800b0a2d1c): Sleep transition timed out after 180 seconds while calling power state change callbacks. Suspected bundle: com.apple.iokit.IOUSBHostFamily. Thread 0x93f8.
Failure code:: 0x00000004 00000014

Backtracing specified thread
Backtrace (CPU 0), Frame : Return Address
0xffffff81fbc6b900 : 0xffffff800aa60178 
0xffffff92142dbc40 : 0xffffff800a95d771 
0xffffff92142dbcb0 : 0xffffff800a95bf6f 
0xffffff92142dbd00 : 0xffffff800aa5d2b9 
0xffffff92142dbd40 : 0xffffff800aa5cbdb 
0xffffff92142dbd70 : 0xffffff800b03f578 
0xffffff92142dbda0 : 0xffffff800b042489 
0xffffff92142dbe00 : 0xffffff800b02794b 
0xffffff92142dbea0 : 0xffffff800b027344 
0xffffff92142dbec0 : 0xffffff800a97d7e5 
0xffffff92142dbf40 : 0xffffff800a97d311 
0xffffff92142dbfa0 : 0xffffff800a8e213e 

BSD process name corresponding to current thread: kernel_task
Boot args: darkwake=0 dart=0 gfxrst=1 

Mac OS version:
19D76

Kernel version:
Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
Kernel UUID: A8DDE75C-CD97-3C37-B35D-1070CC50D2CE
Kernel slide:     0x000000000a600000
Kernel text base: 0xffffff800a800000
__HIB  text base: 0xffffff800a700000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 5253340214691
last loaded kext at 352876519070: >usb.IOUSBHostHIDDevice	1.2 (addr 0xffffff7f8f5db000, size 45056)
last unloaded kext at 191489128179: >!A!ILpssGspi	3.0.60 (addr 0xffffff7f8d817000, size 45056)
loaded kexts:

How can he fix the error? Same way as OC? 
Thanks

**Comment by stevezhengshiqi** [comment]
Yes, remove the two Intel Bluetooth kexts and use SSDT-USB-BT to block the native bluetooth is recommended to solve this problem.

**Comment by matvada** [comment]
@stevezhengshiqi 
Thank you very much.
Related question: 
In this way can continue to use the native bluetooth? Or should he use the bluetooth dongle?

**Comment by stevezhengshiqi** [comment]
The Intel Bluetooth kexts are not stable enough currently. And yeah, if you want better bluetooth experience, you need to buy dongle or a Broadcom wireless card.

**Comment by Menchen** [comment]
@matvada You can try `sudo pmset -a hibernatemode 0` and add `setpowerstate_panic=0` boot argument.

I had the same issue for a while and that fixed for me.(I'm using OC thought).

**Comment by matvada** [comment]
@stevezhengshiqi and @Menchen thank you very much, he'll give it a try
Is strange that i have no issues with the same configuration and the Intel Bluetooth kexts.
Thanks!

**Comment by kugn** [comment]
I'm happy to report that with the latest v1.1.1 bluetooth kexts  https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases I no longer suffer from the issues
