### ISSUE TITLE
Brightness low (pro enhanced)

### ISSUE THREAD

**Issue by Trilis29** [daliansky/XiaoMi-Pro-Hackintosh#353]
Hello,

Using Mi notebook pro enhanced
Catalina
1.3.6 release

When laptop is loading brightness is full, when it is loaded to macos, brightness goes to lowest setting and is not possible to change the brightness value. What is causing the problem and where should I look?

**Comment by stevezhengshiqi** [comment]
Hi, if your model is 10 generation CPU, it’s not recommended to use this EFI. BTW, if you are using 10 generation CPU, you could try https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/hotpatch/SSDT-PNLFCFL.dsl for brightness instead of SSDT-PNLF in this repository.

**Comment by Trilis29** [comment]
perfect, working :) Thanks a a lot.

**Comment by dawidmalina** [comment]
@Trilis29 can you share your config as I have the same issue.

**Comment by Trilis29** [comment]
https://we.tl/t-KM8q3iy55Z

This is my efi. Config need to be cleaned. All working except audio. If you have working audio share with me 🔉👂😂

**Comment by dawidmalina** [comment]
Thanks for sharing this. Btw how did you build your config?

@stevezhengshiqi do you think will such config https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/config_UHD630.plist would be a good starting point?

Intel i7-10510u use UHD graphics: https://ark.intel.com/content/www/us/en/ark/products/196449/intel-core-i7-10510u-processor-8m-cache-up-to-4-90-ghz.html#tab-blade-1-0-4

**Comment by Trilis29** [comment]
just try it and you will see if it is working :)
