### ISSUE TITLE
EFI v1.3.7 Supplemental Update

### ISSUE THREAD

**Issue by stevezhengshiqi** [daliansky/XiaoMi-Pro-Hackintosh#354]
As we all know, the Hackintosh world changes really fast. In this issue, I will post some enhanced kexts that can bring better experience or help explore new features. Remember, the kexts posted here may not stable enough for daily use and that's why I don't pack them into v1.3.7 release directly.

## [VoodooI2C](https://github.com/alexandred/VoodooI2C) (Trackpad)
- We have a major update as described in this pull request https://github.com/alexandred/VoodooI2C/pull/254; the update reduces stuck and improves 3-Finger & 4-Finger Touch experience.

[VoodooI2C Mar 17th.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4344588/VoodooI2C.Mar.17th.zip) (10.15 Only!)
[VoodooI2C April 6th.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4439983/VoodooI2C.April.6th.zip)

## [itlwm](https://github.com/zxystd/itlwm) (Intel Wifi)
- There's some big progress on Intel Wifi kexts. However, the kext in the current stage only supports no password wifi, and the wifi name should be `Redmi` (Only 2.4G also). People have to wait for a certain time to let the system find the signal, and please restart if it does not work.
- Since itlwm doesn't use Apple 80211, the network will display as `Ethernet` in the SysPref - Network panel.
- This Intel Wifi kext is different from the one in http://bbs.pcbeta.com/viewthread-1838489-1-1.html. The later one is not an open-source project so I don't like it. However, the later one may have more function than itlwm, such as support WPA/WPA2.

- <b>Delete `SSDT-DRP08` first if you have this file in `/EFI/CLOVER/ACPI/patched/`</b>
- To use the following kexts, first download, and run `sudo chmod -R 755 <your kext location>` and `sudo chown -R root:wheel <your kext location>`. Then, run `sudo kextutil <your kext location>`. <b>These kexts are not for daily use, so don't put them in `S/L/E`, `L/E`, or bootloaders.</b>

[itlwm Mar 17th.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4344695/itlwm.Mar.17th.zip)
[itlwm Mar 17th update 1.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4344904/itlwm.Mar.17th.update.1.zip)

**Comment by yunsanghyeok** [comment]
Thank you for your kindness

**Comment by jackreeves** [comment]
thanks again for the amazing work steve. any chance of a compile for mojave? i had more complications with catalina and no real bonus so downgraded. however if i could vote one feature that makes me consider selling my xiaomi and buying a mac it would be the trackpad drag and drop performance. its never been great. would love to test this out!

**Comment by Menchen** [comment]
@jackreeves 
I'm pretty sure that VoodooI2C works in Mojave....  You should only install `VoodooI2CHID.kext` and `VoodooI2C.kext`

[VoodooI2C.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4354792/VoodooI2C.zip)

**Comment by Zeco-H** [comment]
Ac9560 work?

**Comment by dawidmalina** [comment]
@stevezhengshiqi as trackpad changes were moved into VoodooInput would you be so kind and provide us VoodooInput.kext built from master brunch?

**Comment by Mateo1234454545** [comment]
> [VoodooI2C Mar 17th.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4344588/VoodooI2C.Mar.17th.zip) (10.15 Only!)

Is it possible to compile latest commits?
Thanks in advance.

**Comment by yunsanghyeok** [comment]
@stevezhengshiqi 

> @jackreeves
> I'm pretty sure that VoodooI2C works in Mojave... You should only install `VoodooI2CHID.kext` and `VoodooI2C.kext`, also remember to disable Force click in touchpad settings.
> 
> [VoodooI2C.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4354792/VoodooI2C.zip)
> 
> Also, I think this patch removed all weir bugs, and feel like a real magic trackpad, the only thing I miss is the size of the trackpad(Apple still have the biggest trackpad).

I put this zip file in my kext folder.
after then , i can't boot my laptop.
It show just apple logo and loading bar.

**Comment by jackreeves** [comment]
Booted for me but trackpad wouldn't work so rolled back. Didn't have time
to look in more detail

**Comment by stevezhengshiqi** [comment]
@yunsanghyeok The kexts I provided are for 10.15 only as I write in the bracket.

**Comment by stevezhengshiqi** [comment]
Personally I don't have spare time to compile that latest commit. BTW, I believe the official release will be out soon.

**Comment by yunsanghyeok** [comment]
> @yunsanghyeok The kexts I provided are for 10.15 only as I wrote in the bracket.

sorry i wrong wrote tag. i mean menchen's file doesn't work.

@Menchen

**Comment by yunsanghyeok** [comment]
> @jackreeves
> I'm pretty sure that VoodooI2C works in Mojave... You should only install `VoodooI2CHID.kext` and `VoodooI2C.kext`, also remember to disable Force click in touchpad settings.
> 
> [VoodooI2C.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4354792/VoodooI2C.zip)
> 
> Also, I think this patch removed all weir bugs, and feel like a real magic trackpad, the only thing I miss is the size of the trackpad(Apple still have the biggest trackpad).

sir , How to install this patch?
I just copy these files to kext folder, but trackpad doesn't work.

**Comment by stevezhengshiqi** [comment]
Uploaded new VoodooI2C pack, should support 10.14.
