### ISSUE TITLE
Low Maximum Brightness (v1.3.6) (MX150)

### ISSUE THREAD

**Issue by adeniji57** [daliansky/XiaoMi-Pro-Hackintosh#355]
**阐述您的机型**
- XiaoMi-Pro MX150

**State the version of the EFI**
**阐述您的EFI版本**
- v1.3.6

**Describe the bug**
**描述您遇到的问题**
- The maximum brightness is a lot lower after switching to v1.3.6

**Comment by stevezhengshiqi** [comment]
In my device, I see no difference in backlight control between v1.3.5 and v1.3.6.

`SSDT-PNLF` mainly controls the max backlight. There're few changes on that file in v1.3.6 - only replace the _STA variable with an _STA method.
I suggest you could re-download the v1.3.6 release and update it in your EFI partition. Remember backup and delete `BOOT` and `CLOVER` folders before copying.

Also, numeric backlight-level can be found in `backlight-level` of nvram. Run `nvram -xp` to show nvram in XML format. It may help debug this issue.
