### ISSUE TITLE
Notebook ENHANCED sound issues ALC256

### ISSUE THREAD

**Issue by Trilis29** [daliansky/XiaoMi-Pro-Hackintosh#356]
Mi Notebook Pro Enhanced

has ALC256 codec, tried all the layouts, seems only sound working through headphones. 
Tried VoodooHDA and etc. Nothing worked, maybe anyone could suggest where to start looking?

**Comment by stevezhengshiqi** [comment]
@Trilis29 Hi, I can help with this probably. In the Clover boot page, press F8, and send me everything in /EFI/CLOVER/misc.

**Comment by Trilis29** [comment]
strange but pressing F8 results nothing /misc folder is empty.

**Comment by stevezhengshiqi** [comment]
Then try Fn+F8. Codec dump information is needed to make the audio work.

**Comment by stevezhengshiqi** [comment]
Close this issue since it’s not a 2017/2018 Xiaomi-Pro model.

**Comment by Trilis29** [comment]
[misc.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4364117/misc.zip)
attaching files

**Comment by dawidmalina** [comment]
@stevezhengshiqi can you take a look on the provided misc files? I also have same issue and it would be super if you could help us.

**Comment by dawidmalina** [comment]
This is the output of the /proc/asound/card0 - maybe it would be helpful.
[codec_0.txt](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4494889/codec_0.txt)
[codec_2.txt](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4494890/codec_2.txt)
