### ISSUE TITLE
AirDrop

### ISSUE THREAD

**Issue by Giannidmg** [daliansky/XiaoMi-Pro-Hackintosh#358]
Is there any way to use airdrop on mi notebook pro (mx150)?

**Comment by Menchen** [comment]
By buying a compatible WiFi card.

**Comment by Giannidmg** [comment]
with usb ethernet or usb doungle?

**Comment by Menchen** [comment]
Neither of both, you need an internal WiFi card, connected by M.2

**Comment by stevezhengshiqi** [comment]
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/FAQ#wi-fi has covered this issue.

**Comment by Neolo** [comment]
So what's up with AriDrop on Monterey with intel drivers? I can open airdrop and I see devices in it, but clicking on any to send simply does nothing, button turns in "Done" and that's it.

**Comment by stevezhengshiqi** [comment]
@Neolo See Intel Wifi driver https://github.com/OpenIntelWireless/itlwm/issues/292 for the current process. It takes time and won't be supported in a short period.

**Comment by Neolo** [comment]
> @Neolo See Intel Wifi driver [OpenIntelWireless/itlwm#292](https://github.com/OpenIntelWireless/itlwm/issues/292) for the current process. It takes time and won't be supported in a short period.

Interesting, then why I he exactly the same issue on my desktop hackintosh with Big Sur, with Fenvi Wifi card, where I also see an iphone in receivers list and clicking on it does nothing?
