### ISSUE TITLE
关于苹果服务的疑问和建议

### ISSUE THREAD

**Issue by Exildoutsider** [daliansky/XiaoMi-Pro-Hackintosh#359]
每次更新EFI，部分苹果服务（如Apple Music）就会出现部分不可用的问题
![截屏2020-03-25 下午6 33 35](https://user-images.githubusercontent.com/33362058/77528221-87423880-6ec8-11ea-8d1c-ea99aa422af1.png)
虽然可以通过EFI更新脚本中的“修复苹果服务”来修复，但是每次更新都要搞，且占用Music的五台电脑配额，还要手动取消之前授权很麻烦，请问有没有什么办法来留住更新前的设备信息呢？

**Comment by Menchen** [comment]
https://www.tonymacx86.com/threads/an-idiots-guide-to-imessage.196827/

有点老了但是应该可以用

**Comment by stevezhengshiqi** [comment]
使用脚本来更新efi也可以保留序列号等信息。

**Comment by Exildoutsider** [comment]
请问如何操作？





------------------ 原始邮件 ------------------
发件人: Steve Zheng <notifications@github.com&gt;
发送时间: 2020年3月25日 19:08
收件人: daliansky/XiaoMi-Pro-Hackintosh <XiaoMi-Pro-Hackintosh@noreply.github.com&gt;
抄送: Exildoutsider <792881306@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[daliansky/XiaoMi-Pro-Hackintosh] 关于苹果服务的疑问和建议 (#359)






使用脚本来更新efi也可以保留序列号等信息。

**Comment by stevezhengshiqi** [comment]
运行EFI更新脚本然后选1。。

**Comment by Exildoutsider** [comment]
那这就应该是一个问题了...更新以后出现图里的Apple music问题，需要重新修复服务解决。







------------------ 原始邮件 ------------------
发件人: Steve Zheng <notifications@github.com&gt;
发送时间: 2020年3月25日 19:15
收件人: daliansky/XiaoMi-Pro-Hackintosh <XiaoMi-Pro-Hackintosh@noreply.github.com&gt;
抄送: Exildoutsider <792881306@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[daliansky/XiaoMi-Pro-Hackintosh] 关于苹果服务的疑问和建议 (#359)






运行EFI更新脚本然后选1。。

**Comment by Menchen** [comment]
@Exildoutsider 你要先把生成的序列号写到 clover 的 config 里面,然后下次更新才会保存..... 默认 Clover 自动生成的 序列号 有可能因为更新或系统硬件更改或 NVRAM清空改变...
你可以记一下你现在的序列号然后看看下次更新会不会改变.

**Comment by Exildoutsider** [comment]
感谢，二位辛苦了





------------------ 原始邮件 ------------------
发件人: MengChen. Huang <notifications@github.com&gt;
发送时间: 2020年3月25日 19:19
收件人: daliansky/XiaoMi-Pro-Hackintosh <XiaoMi-Pro-Hackintosh@noreply.github.com&gt;
抄送: Exildoutsider <792881306@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[daliansky/XiaoMi-Pro-Hackintosh] 关于苹果服务的疑问和建议 (#359)





 
@Exildoutsider 你要先把生成的序列号写到 clover 的 config 里面,然后下次更新才会保存..... 默认 Clover 自动生成的 序列号 有可能因为更新或系统硬件更改或 NVRAM清空改变...
 你可以记一下你现在的序列号然后看看下次更新会不会改变.

**Comment by Yojune** [comment]
> 每次更新EFI，部分苹果服务（如Apple Music）就会出现部分不可用的问题 ![截屏2020-03-25 下午6 33 35](https://user-images.githubusercontent.com/33362058/77528221-87423880-6ec8-11ea-8d1c-ea99aa422af1.png) 虽然可以通过EFI更新脚本中的“修复苹果服务”来修复，但是每次更新都要搞，且占用Music的五台电脑配额，还要手动取消之前授权很麻烦，请问有没有什么办法来留住更新前的设备信息呢？

用更新脚本来修复具体怎么操作呢
