### ISSUE TITLE
USB C Hub Problem

### ISSUE THREAD

**Issue by Giannidmg** [daliansky/XiaoMi-Pro-Hackintosh#360]
I have problems with USB C Hubs, when I connect the adapter with a hard disk and the external monitor (without battery charger) it works without problems, once inserted the battery charger ilpc switches from the charging state to the non-charging state with an interval by 3 seconds, in addition the video and the hard disk turn off and on again.

Mi notebook pro mx150
Efi: 1.3.7
Bios: XMAKB5R0P0A07
Hub USB C: VAVA

**Comment by cavazzatommaso** [comment]
Those the mi notebook pro mx150 support pd 100w charger?

**Comment by Giannidmg** [comment]
that I know the charge of my notebook is 65W and I use the original battery charger with original cable, but it doesn't work.
Does anyone know how to help me?

**Comment by Menchen** [comment]
Does it work in Windows?

**Comment by Giannidmg** [comment]
Same problem there too

**Comment by Menchen** [comment]
Then it’s bios problem, I believe you need to roll back to 403(let me check really quick)

**Comment by Giannidmg** [comment]
ok i try to go back and text thanks

**Comment by Menchen** [comment]
Remember to backup first

**Comment by Giannidmg** [comment]
ok perfect going back to the BIOS version 502 everything works
