### ISSUE TITLE
Kexts problem?

### ISSUE THREAD

**Issue by Mateo1234454545** [daliansky/XiaoMi-Pro-Hackintosh#362]
Kexts like VoodooPS2Controller.kext and VoodooI2C.kext don't have /contents folder.

**Comment by stevezhengshiqi** [comment]
@Mateo1234454545 I am working on creating a makefile like https://github.com/williambj1/Hackintosh-Asus-ROG-Laptop-Coffee-Lake/blob/master/Makefile.sh to download all the kexts. Uploading kexts to github seems useless to me and also causes the repository extremely big.

**Comment by Mateo1234454545** [comment]
About the commit   Update `VoodooI2C` v , support trackpad in Recovery mode, and no need to rebuild kextcache after system update"

How is this done ? It is just the latest kext release?

**Comment by stevezhengshiqi** [comment]
It is done by the commit https://github.com/alexandred/VoodooI2CHID/commit/8b7bb7a98b714b7074148e78f657eb625751f821. You can compile the latest release. VoodooInput + VoodooI2C + VoodooI2CHID are changing dramatically these days, we can wait until the latest release.

**Comment by Mateo1234454545** [comment]
Have you compiled latest commits?
 Is it possible to upload? I tried myself but something went wrong, my trackpad disappeared.

**Comment by stevezhengshiqi** [comment]
I don't have my Hackintosh device on hand. Just compile one and you can take a try.
[VoodooI2C Mar 27.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4394815/VoodooI2C.Mar.27.zip)
