### ISSUE TITLE
HDMI problem

### ISSUE THREAD

**Issue by rewhex** [daliansky/XiaoMi-Pro-Hackintosh#364]
Hello, every time when lid is open I need to reconnect my HDMI cable for monitor to work, how to fix this?
I'm using 1.3.7 (macOS 10.15.4) on are MX150 version, it was working perfectly before with 1.3.5 (macOS 10.15.3).

**Comment by stevezhengshiqi** [comment]
It’s a known issue on macOS10.15.4. Related issues are https://github.com/acidanthera/bugtracker/issues/783 and https://github.com/acidanthera/bugtracker/issues/787. You can follow the first link or wait for the next official release of WhateverGreen.
