### ISSUE TITLE
一个不需要重命名的触摸板SSDT

### ISSUE THREAD

**Issue by okexi** [daliansky/XiaoMi-Pro-Hackintosh#365]
根据
> [http://bbs.pcbeta.com/viewthread-1839143-1-1.html](http://bbs.pcbeta.com/viewthread-1839143-1-1.html)（47楼是我的回复）

我重构了一个SSDT-TPD0.aml，不需要在config里重命名，直接加载就能正常使用触摸板，目前在我的小米Pro上正常工作，触摸板名称为ETD2303，oc0.5.6, macos 15.4。分享出来，希望能有用处，简化config。
[SSDT-TPD0.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4401601/SSDT-TPD0.zip)

**Comment by johnnync13** [comment]
I'm trying to do this on Xiaomi mi air. The trackpad load good, but log tell me that bus is not correct, and I put the bus like the tutorial
[SSDT-TPD0.dsl.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4462438/SSDT-TPD0.dsl.zip)

**Comment by stevezhengshiqi** [comment]
@johnnync13 Please submit the log. VoodooI2C will use default bus config if there's no FMCN or SSCN. No need to insert these values if your DSDT don't have them.

**Comment by johnnync13** [comment]
How can I extract the log?

**Comment by stevezhengshiqi** [comment]
`log show --last boot | grep "VoodooI2C"` > VoodooI2Clog.txt
Not sure whether it works, I prefer using https://github.com/syscl/maclog

**Comment by stevezhengshiqi** [comment]
@johnnync13 Your DSDT is needed for further diagnosis.

**Comment by johnnync13** [comment]
@stevezhengshiqi al files in zip. Thanks so much!
[Air.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4464485/Air.zip)

**Comment by stevezhengshiqi** [comment]
@johnnync13 Your log is OK, the prompt `(VoodooI2C) VoodooI2CControllerDriver::pci8086,9d60 Warning: Error getting bus config, using defaults where necessary` can be ignored. VoodooI2C will automatically inject the correct bus config.

BTW, I have the same error as you after adding `force-online` property
```
 (AppleIntelKBLGraphicsFramebuffer) <AppleIntelKBLGraphicsFramebuffer`IntelFBClientControl::doAttribute(unsigned int, unsigned long*, unsigned long, unsigned long*, unsigned long*, IOExternalMethodArguments*)> [IGFB][ERROR  ] [AGDC] Failed with status -536870212 for stream access aux
```

I reported my doubt on https://github.com/acidanthera/WhateverGreen/commit/8169a6ac99993f268d524dd2e7243054c283a2a7#commitcomment-38309594 but I don't get response. If you have any clue please tell me.

**Comment by johnnync13** [comment]
with the default bus it doesn't work either :(

**Comment by stevezhengshiqi** [comment]
@johnnync13 If the trackpad doesn't work, why you say 

> The trackpad load good

Need your patched SSDT with working trackpad. I have no idea which is your Trackpad device. I see you use I2C1 in your SSDT, but your TPD0 device is under I2C0.

**Comment by johnnync13** [comment]
the trackpad already works for me.  I have changed the External statements.
Thank you a lot

**Comment by stevezhengshiqi** [comment]
Then no need to worry about FMCN or SSCN.
