### ISSUE TITLE
File SSDT-PS2K.aml was not deleted after renaming

### ISSUE THREAD

**Issue by dawidmalina** [daliansky/XiaoMi-Pro-Hackintosh#366]
**Describe the bug**

According commit: https://github.com/daliansky/XiaoMi-Pro-Hackintosh/commit/920070269d514fc2a0f02ce1e3707650ae9e232f file `SSDT-PS2K.aml` was renamed to `SSDT-LGPA.aml` but original file still exist. Was it done in purpose as on the release both files are present?

**Comment by stevezhengshiqi** [comment]
The SSDT-PS2K added in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/commit/bcd8e16f54714f4fd1b32da1ea4d5e7e552bdf23 is different from SSDT-LGPA. You can see the function of each hotpatch in dsl file. SSDT-PS2K is for "Customize VoodooPS2Keyboard.kext" and SSDT-LGPA is for brightness key.
