### ISSUE TITLE
internet connection is required to install catalina

### ISSUE THREAD

**Issue by superhero75** [daliansky/XiaoMi-Pro-Hackintosh#368]
in the initial recovery console, without access to internet (wifi isnt working), catalina cant be installed. Is there any way to install from a local copy of catalina?

**Comment by Cr0wTom** [comment]
You probably did not create the disk with the proper Install image from the Mac app store. Do not use 3rd party scripts and tools to create the install media. just do it the proper way with a Mac and it will work. :)

**Comment by superhero75** [comment]
Since I didn't have access to Mac, I used my USB dongle with ethernet port to link up with my wifi router to access internet for the installation.
