### ISSUE TITLE
May I use your scripts to Xiaomi Mi Air repository?

### ISSUE THREAD

**Issue by johnnync13** [daliansky/XiaoMi-Pro-Hackintosh#369]
I can see that Mi Air and the Pro have the same bios. And with OpenCore method I can't disable MSR but with your scripts, I can do it. 
<img width="975" alt="Screenshot 2020-04-03 at 16 27 37" src="https://user-images.githubusercontent.com/22727137/78373400-da07a880-75ca-11ea-9f9d-18a808c1acef.png">

**Comment by stevezhengshiqi** [comment]
The scripts are made by @cybsuai , glad to hear that the scripts also work for Air
