### ISSUE TITLE
Inaccurate Battery Percentage Indication

### ISSUE THREAD

**Issue by steermomo** [daliansky/XiaoMi-Pro-Hackintosh#370]
**State the model**
**阐述您的机型**
XiaoMi-Pro GTX

**State the version of the EFI**
**阐述您的EFI版本**
v1.3.7

**Describe the bug**
**描述您遇到的问题**
- A clear and concise description of what the bug is.
- 清晰并详细地描述问题所在。

电池状态不准确，刚拔掉电源，电池指示百分比迅速下降，最后百分之1的电量却能持续使用半个多小时，如下图示。

**Screenshots**
**截图**
<img width="339" alt="battery1" src="https://user-images.githubusercontent.com/10905619/78375688-bf9bf200-75ff-11ea-9ef0-a391b33a297a.png">

**Comment by stevezhengshiqi** [comment]
此EFI只能保证电量百分比能正常驱动显示，并不能改善电量百分比驱动的具体实现算法。

电量百分比驱动为：[SMCBatteryManager](https://github.com/acidanthera/VirtualSMC/tree/785594f2fcd60ad68479b5e0fc8fa35d09df1e45/Sensors/SMCBatteryManager) 你可以在 https://github.com/acidanthera/bugtracker/issues 上提出意见和错误信息。

本EFI只是单纯地使用优秀开发者们设计出来的kext，并没有改善这些驱动的能力。请联系驱动作者如果你需要更多信息。

**Comment by steermomo** [comment]
多谢，我再去上游看一下
