### ISSUE TITLE
About HiDPI in 1440x810 resolution

### ISSUE THREAD

**Issue by buliaoyin** [daliansky/XiaoMi-Pro-Hackintosh#371]
After add

```
<key>framebuffer-flags</key>
<data>CwsgAA==</data>
```

in config.plist, it's able to sleep with HiDPI resolution 1440x810, but the text shown in screen is not smooth than without this flag.

Is there another framebuffer-flags value could not only support sleep with 1440x810 but also smooth text?

**Comment by stevezhengshiqi** [comment]
I believe framebuffer-flags is only for overall display configuration. Font smoothing can be handled through command defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO

**Comment by boo50** [comment]
I've tried highDPI script and set the "larger text" option (Looks like 1680x944) and fonts are diffuse.
With original 1920x1080 looks perfect, but system fonts are really small
![Screenshot 2020-05-08 at 14 30 17](https://user-images.githubusercontent.com/30969035/81383508-59dce180-913a-11ea-957c-060e35963b31.png)

**Comment by stevezhengshiqi** [comment]
@boo50 Please read README.md, on Catalina, we can only enable HiDPI resolution that less than 1600x900.

**Comment by stevezhengshiqi** [comment]
Close as it can’t be solved.
