### ISSUE TITLE
GUIDE installing MacOS Catalina

### ISSUE THREAD

**Issue by Parzivall-02** [daliansky/XiaoMi-Pro-Hackintosh#372]
Hey, I made a guide about how to install the new version of macOS Catalina in my YouTube Channel, I leave you a link in case you want to see it: https://bit.ly/2yrsU70
I also made a post If you want to read it: https://bit.ly/2Rfyr7e
English version: https://bit.ly/34biTqw

**Comment by zb2947244682** [comment]
Oh,a handsome guy~~

**Comment by zb2947244682** [comment]
Maybe you could add some English subtitles by yourself or the others who are willing to help you～～

**Comment by Parzivall-02** [comment]
I just post in English

**Comment by stevezhengshiqi** [comment]
Thank you for your efforts! Could you provide the origin youtube link? I was jumped into site123.com when I click the English version one.

**Comment by Parzivall-02** [comment]
I just changed it, that I had put it wrong.

**Comment by zb2947244682** [comment]
> Thank you for your efforts! Could you provide the origin youtube link? I was jumped into site123.com when I click the English version one.

here you are:https://www.youtube.com/watch?v=rfG4sGwhE2g&feature=emb_logo
Correctly?
