### ISSUE TITLE
after update 10.15.4, iMessage and FaceTime not working

### ISSUE THREAD

**Issue by yunsanghyeok** [daliansky/XiaoMi-Pro-Hackintosh#373]
**State the model**
 XiaoMi-Pro MX150.

**State the version of the EFI**
v1.3.7

**Describe the bug**

I used iMessage and FaceTime well.
but after updated OS from 10.15.2 to 10.15.4, I can't use iMessage and FaceTime

**Attach your entire EFI folder**
 
my efi folder is same with v1.3.7 refi

I don't know about the hackintoshi.... I can just copy the file.
please tell how to rollback my iMessage

**Comment by stevezhengshiqi** [comment]
https://www.tonymacx86.com/threads/how-to-fix-imessage.110471/

**Comment by yunsanghyeok** [comment]
> https://www.tonymacx86.com/threads/how-to-fix-imessage.110471/

Thank you! 
How to get serial number?? Ex)Serial number, board serial number, MLB(??,what is this?), UUID.

**Comment by yunsanghyeok** [comment]
I solved problem! Thank you!

https://www.tonymacx86.com/threads/an-idiots-guide-to-imessage.196827/

I followed this protocol. I hope this help someone.

**Comment by AtharvShinde** [comment]
@yunsanghyeok unable to set Ethernet en0 help please
