### ISSUE TITLE
Data Bandwidth Problems

### ISSUE THREAD

**Issue by MarFre22** [daliansky/XiaoMi-Pro-Hackintosh#375]
Hi, 

First, thank you everybody who helps this project.

As it is said in the title, I and indirectly other people (in this project) detected some problems related with data Bandwidth when using Catalina (10.15.3 and 10.15.4) with all supported EFI releases (including 1.3.7). The following problems appear at Sleep and Wake cycles
I will create topics for easy reading.

1---- Internal Memory Copy and Paste (SSD)
After a few of these cycles, the internal SSD (where is the MacOS installed, I have been using a 970 Evo consumer version) has a terrible "daily use" performance.
Before sleep, it has 2200/2300 MB/s Write Speed. After wake has 1610 MB/s. Although this does not look horrible, when I copy and paste a folder with 2,50GB it gives me 12min (normally after reboot it gives me 1min or less).

2---- External Memory Copy and Paste (2xUSB A)
Just like the previous point, it happens with USB A ports (I only tested these). With a 5GB file it gives me 15/17 min to a USB 3.0 external HDD and 3.0 flash drive (normally it is 1/1,5min).

3---- 1xUSB A with wifi thumb drive
I use wifi thumb drive (TP-Link T2U Nano), after some restarts and sleep and wake cycles, I always have problems with it, because it comes to a point that the Chriss1111 driver does not recognize my T2U after the boot.
Partial solving: Restart without T2U connected, and connect it at Clover's boot selection. But it will become worse, and this "fix" will not work anymore.
When I test T2U nano in other USB A port they simply and literary turn off (it is very common one of them turn off). In order to turn on the USB A port reboot is required.

4---- 2xUSB A (wifi thumb drive, mouse thumb drive) + HDMI + headphone jack
This combo with sleep and wake cycle is lethal! 
After the first boot I can have 50 mbps Down and 60mbps Up (on Windows is normally 89 mbps Down and 82mbps Up), when I connect HDMI I always have 20mbps Down and 25 mbps Up. 
After a long sleep and wake, the problem starts. The speeds I said (20mbps and 25mbps) are some times unstable (usually having one internet bandwidth brake at online schooling per day- without restart). And it can give me 7mbps down and up speeds!
Also, after long sleep and wake cycle, when I disconnect something from the USB A port closest to the hdmi port, the connected HDMI Screen blinks one time.
After many restarts, it comes to a point that it's impossible to have more than 7mbps speeds, also, when restarting, it takes a long time to turn off.

The unique temporary solution I founded was rebuild kext cache (sudo kextcache -i /). But, with HDMI connected, I always get 20mbps down and 25mbps up speeds on Wi-Fi thumb drive.

It's boring problem for a daily use.

Sorry for my bad English, and thank you very much for the help.

My setup:
Mi Notebook Pro i5-8250U 8GB RAM (0906 BIOS), 2x SSD (the original one, with windows, and 970 Evo), EFI release v1.3.7 + ALCPlugFix + one-key-cpufriend + Apple serial number script, TP-Link T2U Nano with Chriss1111 Driver v14, MacOS 10.15.4 installed in 970 Evo.
SIP and Gatekeeper turned off.

Some photos:
![imagem](https://user-images.githubusercontent.com/51057236/78986699-c5c03000-7b23-11ea-8732-b7e1de47f402.png)
![imagem](https://user-images.githubusercontent.com/51057236/78986738-e2f4fe80-7b23-11ea-9349-06851caaecd4.png)
![imagem](https://user-images.githubusercontent.com/51057236/78986774-fd2edc80-7b23-11ea-8d82-fffaea14a9d0.png)
![imagem](https://user-images.githubusercontent.com/51057236/78986843-218ab900-7b24-11ea-9d11-40940bd3fb7d.png)

--Edit - 1:
As I said, when the USB A ports turn off and cannot recognize anything, it occurs when I disconnect the wifi thumb drive and it remains connect (like a shadow). If I connect the wifi drive again and the mouse thumb drive, none of them will work:
![Captura de ecrã 2020-04-10, às 18 57 37](https://user-images.githubusercontent.com/51057236/79017600-a946e680-7b69-11ea-993a-8f2fa59cd19a.png)
After, when I try to rebuild the kext cache:
![Captura de ecrã 2020-04-10, às 19 23 05](https://user-images.githubusercontent.com/51057236/79017683-d6939480-7b69-11ea-989f-3448ad663d42.png)
I think it seems to be bug related with IOKitWaitQuiet(), right?

--Edit - 2:
Consistent solution (apparently):
After some tests, I can get decent speeds (more than 20mbps down / up) with a few tricks - Delete IntelBluetooth kexts from EFI (I don't know if it's really necessary), turn on with connected HDMI and connected USB Wifi, after log in, connect headphones on the 2.5 mm jack port.

**Comment by MarFre22** [comment]
After updating to EFI v1.3.8, the internet speeds are much worse with HDMI connected.
Using Chriss1111's driver V14 it's and v1.3.8 it's impossible to have decent speeds:
a) only with T2U Nano (USB A port closest to HDMI port)- 52.06mbps Down and 48.99mbps Up.
b) HDMI + T2U Nano (USB A port closest to HDMI port) - 4.53mbps Down 6.57mbps Up.
c) HDMI + T2U Nano (other USB A port) - 6.25mbps Down and 10.16mbps Up.

![imagem](https://user-images.githubusercontent.com/51057236/79014976-ddb7a400-7b63-11ea-836a-f2fe3cecc886.png)

**Comment by jackreeves** [comment]
i also use t2u nano and have noticed some quirks appearing with it. Didnt trouble shoot as its now my daily driver and were still acceptable but noticed that speed appears slower with other devices connected now and signal seems to slow down with hdmi. Infact it stops when i put a usb 3 card reader in adjacent usb port - but wasnt sure if that was interference. Resorted to using my hub on th usb 3 to resolve.

**Comment by MarFre22** [comment]
> i also use t2u nano and have noticed some quirks appearing with it. Didnt trouble shoot as its now my daily driver and were still acceptable but noticed that speed appears slower with other devices connected now and signal seems to slow down with hdmi. Infact it stops when i put a usb 3 card reader in adjacent usb port - but wasnt sure if that was interference. Resorted to using my hub on th usb 3 to resolve.

I can confirm, apparently, after some sleep and wake cicles, when we plug anything to transfer data (card reader dongle or a HDD enclosure) the t2u nano stops working (doesn't connect to any network). Immediately after I disconnected the HDD enclosure it connects to the same network it was on.

So it's important to see if it's something related with Mi Pro EFI (USB mapping for example) or Chris1111's driver which, unfortunately, is closed source.

**Comment by johnnync13** [comment]
Try to remove Bluetooth kexts and do the proofs

**Comment by MarFre22** [comment]
> Try to remove Bluetooth kexts and do the proofs
> To use sudo kextcache -I /, first disable gatekeeper

I forgot to say that I have SIP (obviously) and gatekeeper disable.
Removing Bluetooth kexts and rebuild kextcache had no effect. It remains as a Russian roulette (same poor speeds, same difficulties in trying to get decent speeds...), unfortunately.

Some proofs:
![Captura de ecrã 2020-04-20, às 10 16 52](https://user-images.githubusercontent.com/51057236/79970328-ac57a600-848a-11ea-81db-1efe2061ebe2.png)
![Captura de ecrã 2020-04-20, às 10 18 15](https://user-images.githubusercontent.com/51057236/79970338-af529680-848a-11ea-85b7-6d082e5b6863.png)
![Captura de ecrã 2020-04-20, às 10 17 49](https://user-images.githubusercontent.com/51057236/79970341-b083c380-848a-11ea-9d36-7b66722263f0.png)

**Comment by MarFre22** [comment]
@johnnync13 
Apparently, without Bluetooth kexts I found a consistent solution (I think), but shadow connected devices continue to appear:

After some tests, I can get decent speeds (more than 20mbps down / up) with a few tricks - Delete IntelBluetooth kexts from EFI (I don't know if it's really necessary), turn on with connected HDMI and connected USB Wifi, after log in, connect headphones on the 2.5 mm jack port.

**Comment by MarFre22** [comment]
After some tests:
-> With EFI 1.3.8 and with my monitor connected through HDMI to VGA Adapter (that monitor isn't support by MacOS, it's a bit old - I forgot to said that before):
I have all the problems mentioned on the initial post.

-> EFI 1.3.8 and my current monitor (MacOS compatible monitor AOC I2490PXQU/BT):
I have all mentioned problems but I have good speeds thorough T2U nano (like around 80/90 mbps up/down, which are low speeds compared to Windows)

-> EFI 1.3.9 and AOC I2490PXQU/BT monitor:
Same situation as above.
So, I detect that after some long sleep and cycles,  when I plug in an USB 3.0 HDD the Wi-Fi USB "dies" (immediately when I disconnect the HDD, the Wi-Fi USB "reborns")

**Comment by stevezhengshiqi** [comment]
@MarFre22 What about using [USBWakeFixup](https://github.com/osy86/USBWakeFixup)? It may help improve USB behavior after sleep.
- First, download [USBWakeFixup.kext](https://github.com/osy86/USBWakeFixup/releases) and add it to `/EFI/CLOVER/kexts/Other`
- Second, compile [SSDT-USBW.dsl](https://github.com/osy86/USBWakeFixup/blob/master/SSDT-USBW.dsl) to aml and add it to `/EFI/CLOVER/ACPI/patched`
[SSDT-USBW.aml.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4795630/SSDT-USBW.aml.zip)

**Comment by MarFre22** [comment]
@stevezhengshiqi 
Sorry for the late reply.
I tried your advice with EFI 1.4.8, but it's not working...

Some times, it's very annoying! I connect my USB Wi-Fi but it recognizes it two times and my usb port stops working in MacOS (because of two ghost usb WLAN adapter.....).

**Comment by stevezhengshiqi** [comment]
@MarFre22 Then I have no idea of your problem. It's something out of scope for this repository. BTW, you should try using native Intel Wi-Fi which is pretty stable at this stage.

**Comment by MarFre22** [comment]
@stevezhengshiqi 
I can't use Intel Wi-Fi because it isn't compatible with enterprise networks I think. I ordered the same Apple Wi-Fi/BT card as you did. Hope it works nicely :)

**Comment by stevezhengshiqi** [comment]
> @stevezhengshiqi
> I can't use Intel Wi-Fi because it isn't compatible with enterprise networks I think. I ordered the same Apple Wi-Fi/BT card as you did. Hope it works nicely :)

Actually, I remembered that AirportItlwm solved the enterprise network problem. It works for me a few weeks ago.

**Comment by MarFre22** [comment]
@stevezhengshiqi 
oh, nice! I will try it!
Thank you very much for the help 😁

**Comment by MarFre22** [comment]
@stevezhengshiqi 
Unfortunately, with the latest EFI 1.4.8, Wi-Fi isn't working for me, only Bluetooth appears.

**Comment by stevezhengshiqi** [comment]
@MarFre22 In Clover v148, Intel Wi-Fi wont work on macOS below than Big Sur because ForceKextsToLoad function in Clover r5127 is broken. You need to switch to OC or downgrade Clover r5122 or update to Big Sur to use Intel Wi-Fi.

**Comment by MarFre22** [comment]
@stevezhengshiqi 
Sorry! I forgot about it.
Thanks for the help :)

**Comment by MarFre22** [comment]
> > i also use t2u nano and have noticed some quirks appearing with it. Didnt trouble shoot as its now my daily driver and were still acceptable but noticed that speed appears slower with other devices connected now and signal seems to slow down with hdmi. Infact it stops when i put a usb 3 card reader in adjacent usb port - but wasnt sure if that was interference. Resorted to using my hub on th usb 3 to resolve.
> 
> I can confirm, apparently, after some sleep and wake cicles, when we plug anything to transfer data (card reader dongle or a HDD enclosure) the t2u nano stops working (doesn't connect to any network). Immediately after I disconnected the HDD enclosure it connects to the same network it was on.
> 
> So it's important to find out if it's something related with Mi Pro EFI (USB mapping for example) or Chris1111's driver which, unfortunately, is closed source.

This problem is solved after buying a BCM943602CS, thanks to XiaoMi-Pro-Hackintosh community for the help!

**Comment by MarFre22** [comment]
The problem ( "1---- Internal Memory Copy and Paste (SSD)" ) is solved too, I think due to the purchase of the Sabrent Rocket Q SSD (with MacOS's friendly Phison Controller, more info [here](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/462)).
