### ISSUE TITLE
毫无征兆自动重启

### ISSUE THREAD

**Issue by Duelist-Fiora** [daliansky/XiaoMi-Pro-Hackintosh#376]
**前提条件**
- 已使用`sudo kextcache -i /`重建缓存, 问题没有得到解决。

**阐述您的机型**
- XiaoMi-Pro MX150

**阐述您的EFI版本**
- v1.3.7
- 系统版本: 10.13.6

**描述您遇到的问题**
- 毫无征兆自动重启

**系统报告**
- [log.txt](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4459413/log.txt)

**截图**
- 无

**附上您的整个EFI文件夹**
- 整个EFI文件夹太大, 上传了几次都失败, 只好先上传CLOVER目录
- [CLOVER.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4459439/CLOVER.zip)

**附上system.log**
- [system_log.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4459454/system_log.zip)

**Comment by Menchen** [comment]
ssd型号是什么？

**Comment by stevezhengshiqi** [comment]
典型NVMe硬盘报错

**Comment by Duelist-Fiora** [comment]
MZVLW256HEHP, 应该是PM961?  之前安装过10.14.2, 用了1年多, 没出现这样的情况

**Comment by Duelist-Fiora** [comment]
> 典型NVMe硬盘报错

MZVLW256HEHP, 应该是PM961? 之前安装过10.14.2(EFI版本忘记了), 用了1年多, 没出现这样的情况

**Comment by Duelist-Fiora** [comment]
> ssd型号是什么？

PM961

**Comment by stevezhengshiqi** [comment]
相关问题https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/238 https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/218

**Comment by charlesld** [comment]
KINGSTON SA1000M8480G
也会经常重启

**Comment by Duelist-Fiora** [comment]
似乎我的这个问题跟睡眠有关, 这一周用完电脑直接关机, 再没有出现这样的情况
