### ISSUE TITLE
After installing BCM943602CS card and soldering- fixing windows problems

### ISSUE THREAD

**Issue by macguru341** [daliansky/XiaoMi-Pro-Hackintosh#378]
Hello
So I’ve made the step and installed an OS X supported WiFi/BT card BCM943602CS and also soldered to the board to fix all issues in Mac OS and now I have a full working macOS’s . I also have dual boot with windows and now I have problems in Windows . How do I install all the drivers for the WiFi and BT for Windows ? When I go to device manger i see a list of network adapters (do I need to disable the internet original WiFi card? Because I have WiFi issues like I can’t connect to WiFi ) also I have in other devices a Bluetooth USB Host Controller that have a driver issue .
Thanks 

![image](https://user-images.githubusercontent.com/22807164/79036929-d0d39880-7bd5-11ea-8363-40b5ffe64ada.jpg)

**Comment by stevezhengshiqi** [comment]
I have already provided the driver link in your duplicate issue https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/309, which is https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/132. Also, you can always switch to another WiFi card by clicking the WiFi button in the right bottom and change in the list.
