### ISSUE TITLE
AirPods Compatibility?

### ISSUE THREAD

**Issue by adeniji57** [daliansky/XiaoMi-Pro-Hackintosh#382]
Hi, I just wanted to ask if anyone has gotten AirPods to work with their device. And if so, how far does the compatibility go?

**Comment by Menchen** [comment]
While I don't have AirPods(too short battery autonomy for me), I have heard with Intel BT it should work, except mics, with other compatible BT, it should work flawlessly given that you got iCloud staff right.

**Comment by cha331** [comment]
It works, but occasionally loses its voice for a short time(with intel BT).
