### ISSUE TITLE
PM961 & PM981 drive on the same laptop 

### ISSUE THREAD

**Issue by bohdantverdyi** [daliansky/XiaoMi-Pro-Hackintosh#383]
Hi guys, 
i'm beginner with mac os, kext etc..  I'm sorry if question is so easy. I didn't found the same issue on github.

I have installed mac os on PM961 Drive, and PM981 as second drive for data storage.  Often i get NVMe error, and my laptop force restart after that:

> panic(cpu 0 caller 0xffffff7f9304a231): nvme: "Fatal error occurred. CSTS=0x1 US[1]=0x0 US[0]=0x9a VID=0x144d DID=0xa808
> . FW Revision=EXA7301Q\n"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-470.100.17/IONVMeController.cpp:5320
> Backtrace (CPU 0), Frame : Return Address
> 0xffffff8200fa39e0 : 0xffffff80113215cd 
> 0xffffff8200fa3a30 : 0xffffff801145a3c5 
> 0xffffff8200fa3a70 : 0xffffff801144bf7e 
> 0xffffff8200fa3ac0 : 0xffffff80112c7a40 
> 0xffffff8200fa3ae0 : 0xffffff8011320c97 
> 0xffffff8200fa3be0 : 0xffffff8011321087 
> 0xffffff8200fa3c30 : 0xffffff8011ac2c7c 
> 0xffffff8200fa3ca0 : 0xffffff7f9304a231 
> 0xffffff8200fa3cc0 : 0xffffff7f93035362 
> 0xffffff8200fa3e20 : 0xffffff8011a33949 
> 0xffffff8200fa3e90 : 0xffffff8011a33869 
> 0xffffff8200fa3ec0 : 0xffffff8011363545 
> 0xffffff8200fa3f40 : 0xffffff8011363071 
> 0xffffff8200fa3fa0 : 0xffffff80112c713e 
>       Kernel Extensions in backtrace:
>          com.apple.iokit.IONVMeFamily(2.1)[3DB9BFC6-422F-39A2-A445-AB2732CE5BFC]@0xffffff7f93027000->0xffffff7f93069fff
>             dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[5EF51D44-9FC7-357F-9FB7-3468FD748382]@0xffffff7f91d88000
>             dependency: com.apple.iokit.IOPCIFamily(2.9)[1B1F3BBB-9212-3CF9-94F8-8FEF0D3ACEC4]@0xffffff7f91f01000
>             dependency: com.apple.driver.AppleEFINVRAM(2.1)[6B3E9057-454A-3220-8AE3-424808CDA9E5]@0xffffff7f92109000
>             dependency: com.apple.iokit.IOStorageFamily(2.1)[425BC668-32EC-368C-B4EB-CF8510846BEE]@0xffffff7f91c65000
>             dependency: com.apple.iokit.IOReportFamily(47)[337B24B2-0261-3521-8D1B-23387FC1D657]@0xffffff7f91e30000
> 
> BSD process name corresponding to current thread: kernel_task
> Boot args: f9 g )f )e ,d
>  g

How to configure correctly mac os for working with PM961 & PM981 on the same laptop

**Comment by stevezhengshiqi** [comment]
Get rid of PM981 completely is always the best way for Hackintosh. Also, you can spoof `class-code` to let the system skip the PM981, or disable the PCI device that contains PM981.

**Comment by stevezhengshiqi** [comment]
Close this issue because PM981 is a known buggy disk for Hackintosh.
