### ISSUE TITLE
Bluetooth not working with devices

### ISSUE THREAD

**Issue by cavazzatommaso** [daliansky/XiaoMi-Pro-Hackintosh#384]
XiaoMi-Pro MX150

**State the version of the EFI**
v1.3.8

**Describe the bug**
On Bluetooth settings i can discover devices but when i try to connect to them they don't work

**Comment by stevezhengshiqi** [comment]
Hi, this repository uses [IntelBluetoothFirmware](https://github.com/zxystd/IntelBluetoothFirmware) as Bluetooth driver. I have little idea about how it works. Please report BT related questions to https://github.com/zxystd/IntelBluetoothFirmware/issues for professional help.
