### ISSUE TITLE
Catalina MacOS installation from SSD stuck

### ISSUE THREAD

**Issue by lchaffey** [daliansky/XiaoMi-Pro-Hackintosh#385]
Xiaomi Mi Notebook Pro (i5-8250/MX250)

EFI 1.3.8

I'm following the Catalina instructions given here in the github. Maybe I am missing something that is obvious to some but not to me -  this is my first attempt at a hackintosh. Additionally, I do have a graphics issue in the USB boot (Random letters are missing from text, and there's no text with the boot options). The background is totally black. I did not have this graphical issue when using a Mojave installer, but the same install from SSD bug. Note also I'm not dual booting, I just want this as the main OS. My SSD is a Crucial M2/Sata SSD.

Anyway, this is exactly what I have done:
1. Set the BIOS settings as required
2. Used Etcher to burn the .dmg to my USB
3. Booting the installer from USB is fine. It completes and reboots into Windows PE.
4. Running installer from SSD is the issue

So I'm running the installer from the SSD, it quickly goes about 1/8th along the loading bar, but then stops. Sometimes, it shows "Estimated time remaining 13 minutes" before the freeze, sometimes it does not. This same behaviour also happens withe Mojave image.

Thanks all.

Edit - attached image of the USB boot environment. I wonder why I'm getting this unlike in the video tutorial? 
![IMG_20200426_132905](https://user-images.githubusercontent.com/54183232/80308944-a3880c80-87c9-11ea-9399-5019f7be496c.jpg)

**Comment by stevezhengshiqi** [comment]
@lchaffey Hi, I don't think you are using the EFI release from this repository. Your screenshot shows a different theme from the theme `Xiaomi` embedded in this repository. Please first delete `BOOT` and `CLOVER` folders and then copy new ones.

**Comment by R10burning** [comment]
I have the same situation with you,   EFI 1.3.8 
but I still install success   and work well
it seems no influence  at all

**Comment by lchaffey** [comment]
> @lchaffey Hi, I don't think you are using the EFI release from this repository. Your screenshot shows a different theme from the theme `Xiaomi` embedded in this repository. Please first delete `BOOT` and `CLOVER` folders and then copy new ones.

This was the bit I didn't understand, thanks :) It did not say in the instructions (or show in the video) I had to do this to the USB first, I thought I was doing this after the install. I can upgrade the EFI without reinstalling the OS right?

Anyway I'm all good now. I will see what I can do about WiFi. I read the issues about it, hoping that could be stable soon!

**Comment by lchaffey** [comment]
By the way @stevezhengshiqi let me know if I should open another issue but while I had you - I am deeply confused about how to make changes to EFI. I have been mounting the supposed EFI partition on clover, and I can copy stuff to it, I've rebooted, rebuilt the kextache, but it's completely different to the EFI folder that's sitting on my root directory - does that mean anything? And if I try to copy stuff there, I can't because it's read only. I was trying to get all the kexts over because my battery percentage is not going down and it looked like SMCBatteryManagement was possibly the fix for it. If you could clarify this for me that'd be really helpful, I've been googling for some time without any luck.

**Comment by stevezhengshiqi** [comment]
Only the EFI folder located in the EFI partition can affect the device. Softwares like Clover Installer may backup the EFI folder to the root directory.

**Comment by lchaffey** [comment]
Ah okay, so assuming I've done that correctly and all the provided kexts
are loaded (i've put them in the EFI mount under Clover/kexts/Other,
rebuilt kextache, nothing else) my battery percentage issue is probably a
separate bug? Thanks.

**Comment by stevezhengshiqi** [comment]
Similiar issue https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/370. This repository just use kexts but not develop them. For professional support, please report to https://github.com/acidanthera/bugtracker/issues.
