### ISSUE TITLE
Boot Options

### ISSUE THREAD

**Issue by dpatrongomez** [daliansky/XiaoMi-Pro-Hackintosh#386]
Hi, thanks for your work. I have one question, how can I remove this screen to automatically boot into Catalina.
I am using opencore. Thanks.
![IMG_20200430_092112](https://user-images.githubusercontent.com/26688719/80683319-530ff800-8ac4-11ea-81a4-3cccdadc8f98.jpg)

**Comment by stevezhengshiqi** [comment]
Hi, basically there're two steps.
- In macOS, open SysPref - Startup Disk, choose Catalina.
- Open `/EFI/OC/config.plist`, turn off `ShowPicker`.
