### ISSUE TITLE
Latest EFI package restarts my laptop the whole time?

### ISSUE THREAD

**Issue by utkubky** [daliansky/XiaoMi-Pro-Hackintosh#387]
The first 2 or 3 times it reboots into clover and then it boots into macOS and then right before I log in it reboots again and this process just keeps repeating itself. What am I supposed to do now? I used this hackintosh as my daily driver and I have to work on a very important paper this week!

**Comment by MarFre22** [comment]
> The first 2 or 3 times it reboots into clover and then it boots into macOS and then right before I log in it reboots again and this process just keeps repeating itself. What am I supposed to do now? I used this hackintosh as my daily driver and I have to work on a very important paper this week!

Hi,
Unfortunately I don't know what's happening, but I think that you can downgrade your EFI version (to 1.3.8) using this:
Go to clover settings and find "Inject EFI Strings", use the script at Readme page (upgrade) (or - copy boot and clover folders of v1.3.8 and "sudo kextcache -i /").

If you'd like to use v1.3.9, you can try delete all intelbluetooth kext and "sudo kextcache -i /". In case you try it, share your result please.

**Comment by utkubky** [comment]
> > The first 2 or 3 times it reboots into clover and then it boots into macOS and then right before I log in it reboots again and this process just keeps repeating itself. What am I supposed to do now? I used this hackintosh as my daily driver and I have to work on a very important paper this week!
> 
> Hi,
> Unfortunately I don't know why it's happening, but I think that you can downgrade your EFI version (to 1.3.8) using this:
> Go to clover settings and find "Inject EFI Strings", use the script at Readme page (upgrade) (or - copy boot and clover folders of v1.3.8 and "sudo kextcache -i /").
> 
> If you'd like to use v1.3.9, you can try delete all intelbluetooth kext and "sudo kextcache -i /". In case you try it, share your result please.
> 
> Hope this can help you.

What's the "sudo kextcache -i /" for? Do I just have to type that into the terminal?

**Comment by utkubky** [comment]
> > The first 2 or 3 times it reboots into clover and then it boots into macOS and then right before I log in it reboots again and this process just keeps repeating itself. What am I supposed to do now? I used this hackintosh as my daily driver and I have to work on a very important paper this week!
> 
> Hi,
> Unfortunately I don't know why it's happening, but I think that you can downgrade your EFI version (to 1.3.8) using this:
> Go to clover settings and find "Inject EFI Strings", use the script at Readme page (upgrade) (or - copy boot and clover folders of v1.3.8 and "sudo kextcache -i /").
> 
> If you'd like to use v1.3.9, you can try delete all intelbluetooth kext and "sudo kextcache -i /". In case you try it, share your result please.
> 
> Hope this can help you.

![image](https://user-images.githubusercontent.com/64660097/80968928-16703380-8e19-11ea-9b96-e371944b835b.jpeg)

As of now I’m stuck like this.

**Comment by MarFre22** [comment]
> > > The first 2 or 3 times it reboots into clover and then it boots into macOS and then right before I log in it reboots again and this process just keeps repeating itself. What am I supposed to do now? I used this hackintosh as my daily driver and I have to work on a very important paper this week!
> > 
> > Hi,
> > Unfortunately I don't know why it's happening, but I think that you can downgrade your EFI version (to 1.3.8) using this:
> > Go to clover settings and find "Inject EFI Strings", use the script at Readme page (upgrade) (or - copy boot and clover folders of v1.3.8 and "sudo kextcache -i /").
> > 
> > If you'd like to use v1.3.9, you can try delete all intelbluetooth kext and "sudo kextcache -i /". In case you try it, share your result please.
> > 
> > Hope this can help you.
> 
> What's the "sudo kextcache -i /" for? Do I just have to type that into the terminal?

Yes. After change something in EFI you need to write it into the terminal (and wait some time). If you use the upgrade script in readme page, it isn't necessary to write this into the terminal.

The upgrade script (also to write into the terminal):
bash -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/master/install.sh)"

**Comment by MarFre22** [comment]
> > > The first 2 or 3 times it reboots into clover and then it boots into macOS and then right before I log in it reboots again and this process just keeps repeating itself. What am I supposed to do now? I used this hackintosh as my daily driver and I have to work on a very important paper this week!
> > 
> > Hi,
> > Unfortunately I don't know why it's happening, but I think that you can downgrade your EFI version (to 1.3.8) using this:
> > Go to clover settings and find "Inject EFI Strings", use the script at Readme page (upgrade) (or - copy boot and clover folders of v1.3.8 and "sudo kextcache -i /").
> > 
> > If you'd like to use v1.3.9, you can try delete all intelbluetooth kext and "sudo kextcache -i /". In case you try it, share your result please.
> > 
> > Hope this can help you.
> 
> ![image](https://user-images.githubusercontent.com/64660097/80968928-16703380-8e19-11ea-9b96-e371944b835b.jpeg)
> 
> As of now I’m stuck like this.

At that screen you need to go to the settings and browse through menus (without changing something), find "Inject EFI Strings" and activate it.

**Comment by utkubky** [comment]
> > > > The first 2 or 3 times it reboots into clover and then it boots into macOS and then right before I log in it reboots again and this process just keeps repeating itself. What am I supposed to do now? I used this hackintosh as my daily driver and I have to work on a very important paper this week!
> > > 
> > > 
> > > Hi,
> > > Unfortunately I don't know why it's happening, but I think that you can downgrade your EFI version (to 1.3.8) using this:
> > > Go to clover settings and find "Inject EFI Strings", use the script at Readme page (upgrade) (or - copy boot and clover folders of v1.3.8 and "sudo kextcache -i /").
> > > If you'd like to use v1.3.9, you can try delete all intelbluetooth kext and "sudo kextcache -i /". In case you try it, share your result please.
> > > Hope this can help you.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/64660097/80968928-16703380-8e19-11ea-9b96-e371944b835b.jpeg)
> > As of now I’m stuck like this.
> 
> First of all, at that screen you need to go to the settings and browse through menus (without changing anything), find "Inject EFI Strings" and activate it. After that, click on Apple icon.

I just quickly got into the desktop screen after booting up and turned off the wifi as quickly as possible! Now everything seems to work again! Unfortunately I have to rely on using my phone's 4G hotspot again as my main source of internet. Removing the intelbluetooth kexts and doing sudo kextcache didn't do anything, unfortunately. Am I the only one experiencing this issue? What might be causing it?

**Comment by MarFre22** [comment]
Apparently it's something related with Intel Wi-Fi in v1.3.9 release. I don't know much about it. I don't know if it's stable enough to use as release package. 
Maybe @stevezhengshiqi can help us.
For now I will keep v1.3.8 installed.
Thank you very much for sharing your results.

**Comment by stevezhengshiqi** [comment]
I don’t have much idea about this issue. Are you using a USB wireless dongle? If yes, you could try to replug your dongle to a different USB port and also reinstall the USB wireless drive.

**Comment by utkubky** [comment]
@stevezhengshiqi I don't have a USB dongle. I plug my iPhone into the laptop and use that as my external wifi. Since I turned off native wifi through system preferences, v1.3.9 is working fine now. I did notice that a random program called IORegistryExplorer popped up in my Launchpad? Is that normal?

**Comment by stevezhengshiqi** [comment]
@utkubky 

> a random program called IORegistryExplorer popped up in my Launchpad?

Not normal if you don't install it to your Application folder. You can delete it if you don't need it, it's for checking IO information.

Did you also update `config.plist`, 1.3.9 release made changes on config.

**Comment by utkubky** [comment]
> Did you also update `config.plist`, 1.3.9 release made changes on config.

How do you update a config.plist file? I'm using the one that was in the 1.3.9 folder.

Btw, off-topic, but is there any way to make iMessage and FaceTime work on this? I've tried all the guides and fixes and nothing seems to do it for me. You don't have to answer this if you don't want to haha. I'm mainly concerned with the wifi issue at the moment.

**Comment by stevezhengshiqi** [comment]
DIrectly use config in 1.3.9 folder should be good. What about change to another USB port?

The only way to enable iMessage and FaceTime is to adjust serial numbers, related issue is https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/373.

**Comment by stevezhengshiqi** [comment]
BTW, using OpenCore is more recommended if you only have macOS installed. Recent Clover updates have multiple bugs that break user experience.

**Comment by utkubky** [comment]
> Directly use config in 1.3.9 folder should be good. What about change to another USB port?

Can I put my old config.plist in my EFI folder? I wanted to use the same serial number and stuff.

**Comment by stevezhengshiqi** [comment]
You need to copy-paste serial numbers to the new config. Using the old config.plist would cause ACPI error due to changes in SSDT-USB.

**Comment by utkubky** [comment]
@stevezhengshiqi 
I’ve noticed my laptop also heats up like crazy when using 1.3.9 and that’s only when using light web browsing and MS word. I downgraded back to 1.3.8 and everything seems alright again.

**Comment by stevezhengshiqi** [comment]
@utkubky in v1.3.9, `SSDT-DRP08` was removed to unlock Intel Wi-Fi, which will cause higher power consumption.

**Comment by MarFre22** [comment]
> @utkubky in v1.3.9, `SSDT-DRP08` was removed to unlock Intel Wi-Fi, which will cause higher power consumption.

Can you release another v1.3.9's version with Intel Wi-Fi locked to avoid higher power consumption, please?

**Comment by stevezhengshiqi** [comment]
@MarFre22 You can just go to /EFI/CLOVER/ACPI/patched and delete SSDT-DRP08 by yourself.

**Comment by MarFre22** [comment]
> @MarFre22 You can just go to /EFI/CLOVER/ACPI/patched and delete SSDT-DRP08 by yourself.

In v1.3.9, SSDT-DRP08 was removed which means that Intel Wi-Fi is unlocked. So it's necessary to add, again, SSDT-DRP08, to lock Intel Wi-Fi, Am I right? Can I use SSDT-DRP08 from v1.3.8?

**Comment by stevezhengshiqi** [comment]
My mistake. If you want less power consumption and dont want use Intel Wi-Fi, you can add it back from v1.3.8. SSDT-DRP08 is not necessary, it’s only for better power control.

**Comment by CraKeyBoy** [comment]
@utkubky n v1.3.9, I have this same issue. I have put the USBInjectAll kext back to avoid this issue.  And now My laptop is everything ok. Hope to help you, thx.

**Comment by stevezhengshiqi** [comment]
@utkubky BTW, since you said

> Since I turned off native wifi through system preferences

are you using Intel wifi kexts like itlwm or AppleIntelWifi?

**Comment by stevezhengshiqi** [comment]
Closed this issue as it's Intel Wifi Kext related.
