### ISSUE TITLE
touchpad poor performance

### ISSUE THREAD

**Issue by boo50** [daliansky/XiaoMi-Pro-Hackintosh#388]
Hi everyone, want to ask about your touchpad, is it working good?
Mine is working jerky, huge difference compared to real mac and even to my other hackintosh - mi notebook air 12.5, where it works very smooth, almost like on real mac.
Have tried both OC and Clover bootloaders, it's the same.

Moved from ubuntu and there it also works good, no such issues.

**Comment by stevezhengshiqi** [comment]
To receive help, you need to mention your trackpad kext ([VoodooI2C + satellite](https://github.com/alexandred/VoodooI2C) / [VoodooPS2](https://github.com/acidanthera/VoodooPS2)) and the version you are using.

**Comment by boo50** [comment]
I'm using latest release XiaoMi_Pro-v1.3.9.zip
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/releases
And there are both of them inside 
![image](https://user-images.githubusercontent.com/30969035/81366859-dd380c00-9115-11ea-8659-a3b696c4e1ff.png)

**Comment by stevezhengshiqi** [comment]
Sorry for misread, I thought you are using Xiami Air. You can downgrade the EFI or trackpad kext if you don't like it.

**Comment by boo50** [comment]
I didn't try previous one, my first install on this notebook, but will do.
What kexts are responsible for touchpad? All Voodoo?

**Comment by stevezhengshiqi** [comment]
VoodooI2C + VoodooI2CHID, can be found on https://github.com/alexandred/VoodooI2C/releases

**Comment by boo50** [comment]
tried kext from my mi air, there are Voodool2c + Voodool2cSynaptics and they are not suited for mi pro, touch not working.
also tried latest release of voodool2c+voodool2CHID - no effect, poor as before.

Can someone with nice and smooth working touchpad on mi pro share propper kexts?

**Comment by stevezhengshiqi** [comment]
@boo50 v1.3.9 is using the latest release of VoodooI2C, you need to test the previous version to see the gesture experience. For example, [v2.2](https://github.com/alexandred/VoodooI2C/releases/tag/2.2) is a nice version you could take a try.

> Can someone with nice and smooth working touchpad on mi pro share propper kexts?

No, only VoodooI2C can drive Trackpad on XiaoMi-Pro.

**Comment by stevezhengshiqi** [comment]
@boo50 Also, please define what dose "jerky" means in your first post. If you fail to use click and drag gestures, please turn off `Force Touch` in `Syspref - Trackpad - Force Touch`.

**Comment by boo50** [comment]
jerky is mean what the cursor does not listen well to finger movements, i.e. it moved slowly and after increase in speed and jump , some space on the screen. All gestures are working.

**Comment by stevezhengshiqi** [comment]
I can't give much suggestion since the trackpad is working smoothly on my device. As I said, you could try different versions of VoodooI2C or report to https://github.com/alexandred/VoodooI2C/issues for professional help.

**Comment by boo50** [comment]
I've tried all of them, the old v2.2 and the new 2.4.2, no difference.
Change always VoodooI2C.kext and VoodooI2CHID.kext

**Comment by stevezhengshiqi** [comment]
You don't need `VoodooInput` if you are using version prior to and include 2.3. You can try more versions and better report your concerns on the [VoodooI2C issue page](https://github.com/alexandred/VoodooI2C/issues).
One thing you may need to check is that your trackpad device is on interrupt mode instead of polling mode.

**Comment by boo50** [comment]
Where to check this mode?

**Comment by stevezhengshiqi** [comment]
You really need to report to VoodooI2C issue page to seek for trackpad driver auhtor's help. Personally, I don't see major trackpad abnormalities in your video. 
I can't improve the trackpad as I am not the developer of VoodooI2C.

**Comment by stevezhengshiqi** [comment]
Closed as wont solve.
