### ISSUE TITLE
Is Speed Shift patch compatible with BIOS 906?

### ISSUE THREAD

**Issue by MarFre22** [daliansky/XiaoMi-Pro-Hackintosh#389]
Hi,

First of all, thanks to all the members who help daily in this community!

Long time ago I saw the Intel Speed Shift patch for Mi Notebook Pro and I'd to ask if this patch is compatible with BIOS 906. Also, if it makes a difference in battery life and/or in performance.

Other Xiaomi Pro's GitHub page where we can find more information about this patch: https://github.com/Cr0wTom/Mi-Notebook-Pro-Mods

Thank you very much for the attention!

**Comment by Menchen** [comment]
I think it's compatible, but make sure that you made a backup and have a way to reflash it in case that something went wrong. You would need a CH341 or any Seria to the USB device and another PC.

I don't think that Speed Shift would make a huge difference but it's nice to have, In my opinion, the ability to undervoltage are far more important that SS, because it both improve thermal and battery life(Less power, less heat generated and longer battery).

Also if your device is Gen 8 Cpu with MX150 you could downgrade to lower BIOS and EC so you can have fan patch too.

**Comment by MarFre22** [comment]
Thank you very much for the quick response!

I have 8th gen and MX150, but I prefer 906 BIOS due to keyboard backlight. 

Long time ago, I do not know what I did, but I can change voltage in XTU on Windows. So can I use voltageshift on MacOS, right?

Do you know what voltage I can put in order to have more battery life with same stock performance?

**Comment by MarFre22** [comment]
@Menchen 
I just activated Speed Shift, it's working!
When I try to check status on Pasi-Studio's "Modify TDP and CPU voltage" script, it gives me that (I unlocked Bios + Voltage and I rebooted without lock the bios):
![Captura de ecrã 2020-05-10, às 22 48 42](https://user-images.githubusercontent.com/51057236/81511384-f953cd00-9310-11ea-85f3-be98d46073df.png)
It seems the script does not download anything to /Library/Application Support/, I do not have any folder called "VoltageShift".

**Comment by Menchen** [comment]
Did you run the option one?

**Comment by MarFre22** [comment]
Yes, but somehow I tried another time and it worked. Thanks!

After saw all the options, I do not need more than 15w base. The second option or the fourth, do they have more battery consumption?

**Comment by Menchen** [comment]
Try to Under volt

**Comment by MarFre22** [comment]
Interesting, I didn't know about it. Thanks!!
I managed to undervolt using fladnaG86's script with -100 cpu, -70 gpu and -100 cache memory. Need I copy the edited VoltageShift kext (edited with voltage set.comand) to EFI, right?

Is my undervolting any better than 25w p1 and 40w p2 for more battery and a little more performance?

**Comment by MarFre22** [comment]
After some testing, with Speed Shift + undervolting I have better thermals, more performance and more battery.
Like I said, I made an automator's app in order to replace the VoltageShift kext. - 
[VoltageShift_replace_kext.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4611399/VoltageShift_replace_kext.zip)
You need to copy "voltageshift" folder and "VoltageShift-Documents_Folder.app" to Documents Folder.
Go to System Preferences -> Accounts -> Login items and add this "VoltageShift-Documents_Folder" app.
So it’s working, I hope I’ve contributed.

**Comment by Menchen** [comment]
You need to re run the patch for each wake as the effect is lost after sleep.

**Comment by MarFre22** [comment]
Sorry for close this issue. I forgot to test the sleep and wake cycle, thanks @Menchen!

To solve this you can follow my previous comment, https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/389#issuecomment-626885056, then download Power Manager app (here you have a "licensed" one - [Power Manager 548.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4619079/Power.Manager.548.zip) ). 
Import this custom Schedule File into the app - [VoltageShift schedule file for Power Manager.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4619087/VoltageShift.schedule.file.for.Power.Manager.zip) . Verify that you started the app (upper left corner).

Now I think it's working.

**Comment by Menchen** [comment]
You could just use the LaunchDaemon I edited in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/174 ... It automatically runs each 30m I think?

**Comment by MarFre22** [comment]
I tried with SleepWatcher into Homebrew but It didn't work.

**Comment by greenguyy** [comment]
> @Menchen
> I just activated Speed Shift, it's working!
> When I try to check status on Pasi-Studio's "Modify TDP and CPU voltage" script, it gives me that (I unlocked Bios + Voltage and I rebooted without lock the bios):

I have been trying to find this script to run. I have been getting restart or constant kill task when I run voltageshift. I have updated the BIOS to 603 and to 906 both with unlock voltage patches and unlocked bios. 

Could you share where you get the Pasi Studio's TFP and CPU voltage script?

**Comment by Mikes0** [comment]
Easiest way is to type the following into the terminal:

`sh -c "$(curl -fsSL https://raw.githubusercontent.com/Pasi-Studio/mpcpu/master/mpcpu.sh)"`

**Comment by MarFre22** [comment]
@greenguyy , or you can use the update script (which I used): `bash -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/master/install.sh)"`
I don't know what's the best.

**Comment by greenguyy** [comment]
@MarFre22 and @Mikes0 Both of the scripts work perfectly. i was skeptical about the first 2 tries whereby the watt remained at 15W even after I selected 20W option for PL1. After a few restarts and it just started to strap at 20W. Thanks guys!
