### ISSUE TITLE
Doesn't get passed first restart.

### ISSUE THREAD

**Issue by andresindlp** [daliansky/XiaoMi-Pro-Hackintosh#392]
### No matter what I do I can't get this thing to work.

Laptop: i7, 16GB, GTX 1050, 2018 version (TM1707)
BIOS Version: XMAKB5RRP0804
Supervisor Password is set.
Secure boot mode is disabled.
First boot device set to partition 0 of the USB.

So, this is what I've done so far:
1. Download the latest Catalina dmg: [macOS Catalina 10.15.4(19E287) Installer for Clover 5109 and WEPE Support UEFI and MBR.dmg](https://mirrors.dtops.cc/iso/MacOS/daliansky_macos/macOS%20Catalina%2010.15.4%2819E287%29%20Installer%20for%20Clover%205109%20and%20WEPE%20Support%20UEFI%20and%20MBR.dmg)
2. Flash it onto a USB using TransMac/balenaEtcher
3. Mount the EFI partition (I'm using a Windows PC)
4. Delete the BOOT and CLOVER folders inside EFI
5. Copy the latest EFI v1.9.3 files (I set the specific file for the GTX version too)
6. Boot into the installer, erase the SSD (the one that comes stock, I'm not dual booting)
7. Install macOS
8. The laptop restarts and boots into the SSD to continue the installation
9. Loads for a bit, gets stuck and the "About 13 minutes remaining..." text appears and it locks up
![About 13 minutes remaining...](https://user-images.githubusercontent.com/35582438/82107499-8b504100-9728-11ea-8988-8cfae324dfb2.jpg)
10. I leave it for 7 minutes or so
11. Laptop reboots into the SSD again and this error message appears:
![Error Message](https://user-images.githubusercontent.com/35582438/82107514-aae76980-9728-11ea-8973-547bdcbb7cbe.jpg)
12. Steps 9-11 constantly loop

I've also tried without copying the EFI files to the EFI partition and the same thing occurs.

**Comment by stevezhengshiqi** [comment]
Check SSD's model number. If it's PM981, remove it. PM981 starts with `MZLB`
