### ISSUE TITLE
IP520 Camera problem

### ISSUE THREAD

**Issue by djacicv** [daliansky/XiaoMi-Pro-Hackintosh#393]
Hello,

I installed USB Inject ALL, but didn't help.

It doesn't see it anywhere.. Any suggestion?

Thanks

**Comment by stevezhengshiqi** [comment]
@djale Hi, rebuild kextcache will help. View https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/FAQ#camera

**Comment by djale** [comment]
@stevezhengshiqi Hey, I missed that i FAQ, it works now. Thank you very much, cheers

**Comment by djacicv** [comment]
I've updated my system from 10.15.4 to 10.15.7 , the only thing that doesn't work is the camera. I've tried the old thing, to rebuild kextcache and restart but it doesn't work. Any thoughts? Thanks
