### ISSUE TITLE
Webcam not working - one solution

### ISSUE THREAD

**Issue by salesgroup** [daliansky/XiaoMi-Pro-Hackintosh#394]
Recently i had some problems with the webcam not showing in Skype and Zoom.
My solution was going to the terminal and run:
sudo killall VDCAssistant

Hope this can help someone.

**Comment by stevezhengshiqi** [comment]
People can also try 10.15.5 according to the Changelog of 15.5

> Resolves an issue where the built-in camera may not be detected when trying to use it after using a video conferencing app
