### ISSUE TITLE
Dual boot Windows 10

### ISSUE THREAD

**Issue by shilch** [daliansky/XiaoMi-Pro-Hackintosh#395]
Hi,

I'm trying to get dual boot with Windows 10 working.  
Windows 10 and macOS Mojave are both installed and working properly.  
  
My EFI partition structure is as follow:  
```
.
└── EFI
    ├── APPLE
    │   ├── EXTENSIONS
    │   └── FIRMWARE
    ├── BOOT
    │   └── BOOTX64.efi
    ├── CLOVER
    │   ├── ACPI
    │   ├── CLOVERX64.efi
    │   ├── config.plist
    │   ├── drivers
    │   ├── kexts
    │   ├── themes
    │   └── tools
    └── Microsoft
        ├── Boot
        └── Recovery
```

Now, the problem is that the BIOS will always execute the Microsoft bootmanager. That's the only entry that is shown to me in the BIOS configuration; selecting the `\EFI\BOOT\BOOTX64.efi` isn't possible at all.  
My workaround is to rename the `\EFI\Microsoft` directory to some other name and then specify the new path to Microsoft's bootmanager in the `config.plist` so Clover can find it. When the BIOS can not find Microsoft's bootmanager in the default path, it allows to boot into `\EFI\BOOT\BOOTX64.efi` (which is Clover) where one can then choose either macOS or Windows.  
This solution works fine, until Windows installs updates where apparently it accesses the EFI partition and fails to find the bootmanager in the default path.

Does somebody know of a solution to boot into Clover without the need of renaming the `Microsoft` directory?

Thanks in advance!

**Comment by stevezhengshiqi** [comment]
Hi, this repository is mainly for after-installation issues, I believe installation-related problems have already been well-explained by many hackintosh forums and guides. For the dual-boot question, I use `Bootice` to add a Clover boot entry and keep `Microsoft` directory untouched. You could view my [Installation Guide](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/Installation#step-5---adjust-boot-entry) for details.

**Comment by shilch** [comment]
Thanks, I wasn't aware of such guide. It did the job :)

**Comment by MarFre22** [comment]
@stevezhengshiqi , using your installation guide, will I have problems with MacOS EFI/entries due to an Windows update? 
I saw all people saying that it's a bit problematic to have Win and MacOS' EFI together. So I'd like to know if Bootice is the most secure method and non-problematic.

Thank you for the guide!

**Comment by stevezhengshiqi** [comment]
Windows entry will always try to prioritize itself to become the first to boot, especially after a Windows update. When this happens, you need to reset the Clover entry to the first one by using Bootice or manually set in BIOS panel. OpenCore has a `BootProtect` quirk if you want a more stable solution. I personally don't favor some solutions like renaming BOOTx64.efi to something else.
