### ISSUE TITLE
为什么我在efi/clover找不到cloverx64.efi文件

### ISSUE THREAD

**Issue by ILBF** [daliansky/XiaoMi-Pro-Hackintosh#396]

**Comment by stevezhengshiqi** [comment]
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/README_CN.md#安装

> 完整的EFI附件请访问 releases 页面。
如果是日常使用，请不要克隆或者下载master分支

**Comment by ILBF** [comment]
haha谢谢大佬，我已经搞明白了
