### ISSUE TITLE
Weird trackpad click behavior after release v1.3.8

### ISSUE THREAD

**Issue by zhudav** [daliansky/XiaoMi-Pro-Hackintosh#398]
Everything is working fine in v1.3.8 release.  After updating to v1.3.9 or v1.4.0, all the trackpad clicks in the Mac finder have become quick looks.  For example when clicking a folder, instead of selecting it, it shows me the quick look info details.  Very strange!  Any idea what changed that could cause this?

![Screen Shot 2020-06-02 at 11 37 01 PM](https://user-images.githubusercontent.com/204260/83539725-fd4ac780-a529-11ea-88b6-0295dab8d23b.png)

**Comment by kampav** [comment]
You have to disable Force Click and Heptic feedback in settings for trackpad

**Comment by stevezhengshiqi** [comment]
@zhudav https://github.com/daliansky/XiaoMi-Pro-Hackintosh#i-cant-click-to-drag-files-using-the-trackpad

**Comment by zhudav** [comment]
Ah!  Thanks for the help, all good now!  Note to self -- read FAQ more carefully for new releases.  :sheepish grin:
