### ISSUE TITLE
10.15.5 oc引导睡眠会重启

### ISSUE THREAD

**Issue by renyichan** [daliansky/XiaoMi-Pro-Hackintosh#399]
panic(cpu 0 caller 0xffffff801b29169c): Sleep transition timed out after 180 seconds while calling power state change callbacks. Suspected bundle: com.apple.iokit.IOUSBHostFamily. Thread 0xe2fb.
Failure code:: 0x00000004 00000014

Backtracing specified thread
Backtrace (CPU 0), Frame : Return Address
0xffffff812f8e3900 : 0xffffff801ac458f8 
0xffffff91557bbc40 : 0xffffff801ab413f1 
0xffffff91557bbcb0 : 0xffffff801ab3fc2f 
0xffffff91557bbd00 : 0xffffff801ac429f9 
0xffffff91557bbd40 : 0xffffff801ac4225b 
0xffffff91557bbd70 : 0xffffff801b22cb08 
0xffffff91557bbda0 : 0xffffff801b22fa19 
0xffffff91557bbe00 : 0xffffff801b214daa 
0xffffff91557bbea0 : 0xffffff801b2146d4 
0xffffff91557bbec0 : 0xffffff801ab61565 
0xffffff91557bbf40 : 0xffffff801ab61091 
0xffffff91557bbfa0 : 0xffffff801aac513e 

BSD process name corresponding to current thread: kernel_task
Boot args: darkwake=0 gfxrst=1

Mac OS version:
19F96

Kernel version:
Darwin Kernel Version 19.5.0: Thu Apr 30 18:25:59 PDT 2020; root:xnu-6153.121.1~7/RELEASE_X86_64
Kernel UUID: 7B7F06EE-1B75-345E-B898-2FD4FEC20F0D
Kernel slide:     0x000000001a800000
Kernel text base: 0xffffff801aa00000
__HIB  text base: 0xffffff801a900000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 7741712904277

**Comment by renyichan** [comment]
补充一下使用的是1.4.0版本，小米pro 2019 mx250

**Comment by stevezhengshiqi** [comment]
@renyichan 你好，Intel内置蓝牙驱动`IntelBluetoothFirmware.kext` 和 `IntelBluetoothInjector.kext`会导致睡眠问题，README和release界面都提到了。
请按照[蓝牙解决方案](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/蓝牙解决方案#插入一个usb蓝牙--禁用自带蓝牙)删除这两个驱动。

**Comment by zjkyz8** [comment]
@stevezhengshiqi 大佬，这个问题貌似修复了，https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/23

**Comment by stevezhengshiqi** [comment]
@zjkyz8 嗯 之前就注意到了，在https://github.com/daliansky/XiaoMi-Pro-Hackintosh/commit/2af5d4386286d8bc2d64cf9be05ddf02f2d99a7c#diff-6866aa936c606b14e1891776ddf7cb09 里已经删除了IntelBluetooth相关问题阐述。
