### ISSUE TITLE
USB网络共享和触控板无法使用

### ISSUE THREAD

**Issue by 1534841768** [daliansky/XiaoMi-Pro-Hackintosh#400]
XiaoMi-Pro MX110, i7 8550u
 v1.4.0

1. 我添加了HoRNDIS.kext，但是我的手机还是无法进行USB网络共享，请问怎么办?

2. 触控板无法使用，鼠标键盘正常。

**Comment by stevezhengshiqi** [comment]
@1534841768 MX110 是小米笔记本Ruby，请仔细检查机子型号。

**Comment by 1534841768** [comment]
> @1534841768 MX110 是小米笔记本Ruby，请仔细检查机子型号。

**Comment by 1534841768** [comment]
现在是触控板和无声音，大佬有什么方法解决吗，其它正常

**Comment by stevezhengshiqi** [comment]
https://github.com/XenOriginal/XiaoMi-Ruby-15.6-UMA-only
