### ISSUE TITLE
非EFI问题，想请教一下GTX版本蓝牙应该飞线到哪个位置。

### ISSUE THREAD

**Issue by linkerGitHub** [daliansky/XiaoMi-Pro-Hackintosh#401]
我买了一个苹果网卡插到ssd槽上了，wifi工作良好，蓝牙应该还需要飞两根线，但是我在网上搜素一番后没有找到在gtx版本上飞线的例子。
在此向各位请教一下GTX版本的应该飞线到哪里，谢谢。
此外，需要飞的两根线是什么功能，是为了做蓝牙供电的吗？我看有将两条线飞到指纹模块上的，如果这样做会不会对windows下使用指纹功能产生影响？

**Comment by Menchen** [comment]
飞的两根线是为了蓝牙USB数据, 如果你飞到指纹USB口的话就指纹就不能用了. GTX好像只能用指纹或者摄像头..

**Comment by linkerGitHub** [comment]
感谢回复，有空了打算试验一下分个usb hub接上行不行
