### ISSUE TITLE
WIFI无法打开

### ISSUE THREAD

**Issue by Notics-Seed** [daliansky/XiaoMi-Pro-Hackintosh#402]
昨天还好的，今天重启了一下就挂了，
![63866489168462D4ACE5DC44EDB36949](https://user-images.githubusercontent.com/52071868/83960451-988dc500-a8bb-11ea-99eb-a30daf0c4917.png)
咋整，我怀疑IO80211Family.kext出问题了，但又不知道咋修

**Comment by Notics-Seed** [comment]
macOS 10.15.5 Intel 8265AC 小米笔记本Air i7版

**Comment by stevezhengshiqi** [comment]
不属于本仓库讨论范畴。如果使用的是itlwm，请移步至https://github.com/zxystd/itlwm
