### ISSUE TITLE
SMBIOS reset after update

### ISSUE THREAD

**Issue by Cr0wTom** [daliansky/XiaoMi-Pro-Hackintosh#403]
Hello guys and thanks for the great work. Every time that I use the install.sh script to update my EFI it completely removes my SMBIOS configuration and of course as a result it destroys the iMessage functionality. I am not sure if this is a "feature" but if not I suggest to use some sed magik to add the previous SMBIOS in the new configuration. If not please mark this issue as closed :)

**Comment by stevezhengshiqi** [comment]
@Cr0wTom Hi, the install.sh script preserves DefaultVolume, Timeout, SerialNumber, BoardSerialNumber, SmUUID, ROM, MLB, and CustomUUID. The specific code are at here: https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/48097e3538732886b1bbc2e139a3207e9cb1f65b/install.sh#L157
Please recheck and make sure you don't leave blanks on the value you want to preserve.
