### ISSUE TITLE
Why can't I turn off GPU?

### ISSUE THREAD

**Issue by recre4te** [daliansky/XiaoMi-Pro-Hackintosh#404]
Under pr01 is displayed PXSX
![image](https://user-images.githubusercontent.com/29120905/84324085-b0499f80-ab80-11ea-9f69-028f871a13a2.png)

**Comment by stevezhengshiqi** [comment]
Please provide more information. What's your laptop model and which release are you using? Also need to mention the bootloader you are using. Better attach your CLOVER or OC folder for better diagnose.

**Comment by recre4te** [comment]
> Please provide more information. What's your laptop model and which release are you using? Also need to mention the bootloader you are using. Better attach your CLOVER or OC folder for better diagnose.

Xiaomi notebook pro mx150 2018, i use last beta build (clover)

**Comment by stevezhengshiqi** [comment]
@recre4te Please attach your CLOVER folder and ioreg file.

**Comment by recre4te** [comment]
> @recre4te Please attach your CLOVER folder and ioreg file.

[CLOVER.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4767493/CLOVER.zip)

**Comment by recre4te** [comment]
[MacBook Pro — Mark.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4767501/MacBook.Pro.Mark.zip)

**Comment by stevezhengshiqi** [comment]
@recre4te Seems good to me. In IOService graph, the PXSX device doesn't show under RP01.
I guess you are viewing IODeviceTree, which will show every device written in DSDT, whether disabled or not.
