### ISSUE TITLE
OpenCore vs Clover

### ISSUE THREAD

**Issue by recre4te** [daliansky/XiaoMi-Pro-Hackintosh#405]
Who uses what and what are the advantages of OpenCore and Clover?

**Comment by Menchen** [comment]
Both are pretty same for the end-user perspective, there are no advantages because if you don't know what features your missing, chances are that you don't need it.

IMO OpenCore is a bit harder to configure but much cleaner than Clover, also OpenCore is more "minimal" and "native" than Clover.

**Comment by Drun555** [comment]
I have some issues with OC version. Sound sometimes turns off, and work only when settings are opened on Microphone tab. Also sometimes trackpad just don’t work, even after kextcache - and I should reboot few times. Also trackpad don’t work in bootloader.

I mean, maybe it’s just me, but after a week of usage I turned back on Clover.
