### ISSUE TITLE
Fail to install macOS Big Sur

### ISSUE THREAD

**Issue by stevezhengshiqi** [daliansky/XiaoMi-Pro-Hackintosh#409]
On June 22, 2020, Apple announced macOS11 Big Sur first developer beta (build 20A4299v) with major changes

### Clover r5119
(Include commit https://github.com/CloverHackyColor/CloverBootloader/commit/a0948b2515f9b077085b63dc695512aa2c1c73c0)
- No macOS Installer boot entry
- Able to show Big Sur USB installer, but fail to boot
### OC v0.6.0
(up to commit https://github.com/acidanthera/OpenCorePkg/commit/5126895cf53758f85f345311b4293cff9a434b23)
- Not able to boot the macOS Installer

In the boot log, error messages are like below:

<img src="https://user-images.githubusercontent.com/36894554/85356091-1cf75f00-b4dc-11ea-8581-956070727664.jpg" width="500"/>

---
According to what ITzTravelInTime said at [insanelymac.com](https://www.insanelymac.com/forum/topic/344236-pre-release-macos-big-sur/?do=findComment&comment=2726346),

> the kernel has been changed so mutch that open core can't get the kexts to load so and so neither clover will succed at doing it, this problably demands for a major booutloader update/rework which will take at least a few days to have something working and a few weeks to be done properly

I guess we have to wait a couple of days for ACDT and Clover teams updating the bootloader to support Big Sur that includes major changes on Kernel and becomes difficult to hack.

Recommend Post: https://www.insanelymac.com/forum/topic/344236-pre-release-macos-big-sur/

**Comment by stevezhengshiqi** [comment]
Update: 
### OC
After setting `AvoidRuntimeDefrag` to false, I was able to boot into the installer language choosing page.
<img src="https://user-images.githubusercontent.com/36894554/85477277-03abec80-b588-11ea-86c4-9c1ccce405f2.JPG" width="700"/>

**Comment by adeniji57** [comment]
Someone on Reddit has just gotten theirs to work: https://www.reddit.com/r/hackintosh/comments/hf1q1r/big_sur_on_xiaomi_notebook_pro/

**Comment by corint1** [comment]
virtualsmc os fakesmc ? ... freeze in " not found smc...bla bla ...what is wrong ?

**Comment by stevezhengshiqi** [comment]
@adeniji57 Seems need a VM first. Will wait until the bootloader natively support the installation.

**Comment by stevezhengshiqi** [comment]
Success
![IMG_2798](https://user-images.githubusercontent.com/36894554/85669697-1a3c6b80-b68e-11ea-8b98-1453ff56bc1b.JPG)

**Comment by stevezhengshiqi** [comment]
Sample config:
[config.plist.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4829580/config.plist.zip)
Require the latest OC + Lilu + Lilu plugIns, can be download by running the following command:
```
git clone --depth=1 https://github.com/daliansky/XiaoMi-Pro-Hackintosh.git
cd XiaoMi-Pro-Hackintosh
./makefile.sh --PRE_RELEASE=Kext --PRE_RELEASE=OC
```

**Comment by HKMV** [comment]
Elder brother is really strong. It's worth congratulating on this Dragon Boat Festival.

**Comment by vladdenisov** [comment]
FInally, Managed to get Big Sur working on my Xiaomi mi Notebook Air 13" 2017.

Used VM to install to internal ssd, then booted it. Used latest [OC](https://github.com/williambj1/OpenCore-Factory/releases), latest kext build using makefile from this repo.

Basically, you need to modify your OC config under NVRAM sections as it did stevezhengshiqi

![Screenshot 2020-06-25 at 13 24 05](https://user-images.githubusercontent.com/18082735/85702595-3ddfd000-b6e7-11ea-8ad2-1ed7f9f059e5.png).  
Also, check `Booter->Quirks->AvoidRuntimeDefrag` to be `true`


As @stevezhengshiqi stated, everything works, except battery for me. But I also have some problems with touchpad, looks like it's always emulating force touch instead of normal click, but touchpad doesn't appear in settings.   

![Screenshot 2020-06-25 at 13 20 33](https://user-images.githubusercontent.com/18082735/85702046-b003e500-b6e6-11ea-9cbe-f698851c9e1b.png)

**Comment by stevezhengshiqi** [comment]
@vladdenisov Nice work! Don't worry too much about the trackpad. The trackpad setting would be available if the battery percentage can show correctly. You can turn off Force touch once SMCBatteryManager is updated.

**Comment by kampav** [comment]
@stevezhengshiqi - Thanks again for the great work. I am struggling to download a copy of MacOS11. Do you know how I go about downloading the copy without developer account

**Comment by stevezhengshiqi** [comment]
@kampav You can try https://betaprofiles.com

**Comment by kampav** [comment]
@stevezhengshiqi - Thanks a lot Steve but I am getting 10.16 other than 11. Any help to fix this will be much appreciated
<img width="689" alt="image" src="https://user-images.githubusercontent.com/31815827/85706654-54335f00-b6da-11ea-9567-9447ec32bb1f.png">

**Comment by stevezhengshiqi** [comment]
@kampav It's the same thing.

**Comment by bswaterb** [comment]
Hi, I try to update my system but something wrong happened. OC stuck here and after a time it show me a "BAN" icon. I can start my old version 10.15.6, but I can't start the macos installer.

![2732278dd693d3bb8b04f974a36cb3e](https://user-images.githubusercontent.com/50270641/85716290-e52c2980-b71e-11ea-9946-dc1e1e937199.jpg)

**Comment by kirainmoe** [comment]
Hello, I wonder that is the installation should be finished in a VM environment to escape loading the BootKernel kc in the second stage?

**Comment by kampav** [comment]
> @kampav It's the same thing.

Thanks Steve

**Comment by GalaxyXL** [comment]
After 12 hours and several times tried, got my Mi NoteBook Pro 2018 working on the Big Sur.

Native installation has failed lots of times. After Reviewing this topic and the feedback of @vladdenisov, install Big Sur successfully according to the vm. Using EFI generated by the makefile.sh and config.plist which @stevezhengshiqi gives. 

Different from the Mi NoteBook Air, I set the `AvoidRuntimeDefrag` false, just like Steve said before, after that, I got into the system.
![image](https://user-images.githubusercontent.com/23307387/85807819-de45ec80-b707-11ea-8fe0-6f5320f14021.png)

**Comment by kampav** [comment]
@GalaxyXL - Thank you so much for the post. I have the same model as you and really stuck with installation. Did you login to Windows then load the VM to install MacOS using USB on internal SSD? Any help will be much appreciated

**Comment by GalaxyXL** [comment]
> @GalaxyXL - Thank you so much for the post. I have the same model as you and really stuck with installation. Did you login to Windows then load the VM to install MacOS using USB on internal SSD? Any help will be much appreciated

I didn't use USB. I upgraded it in VM directly.

**Comment by kampav** [comment]
@stevezhengshiqi @GalaxyXL @vladdenisov - I have spent many hours now and no success to even boot Bigger using all the NVRAM setting in this post. Not sure how to upgrade using VM? Any help to share your EFI folders or how to upgrade using VM method will be much appreciated.

**Comment by vladdenisov** [comment]
@kampav 
My EFI and config: https://github.com/johnnync13/Xiaomi-Mi-Air/issues/161#issuecomment-650731656

I will try to write more detailed guide late (Busy now). Good luck anyway

**Comment by kampav** [comment]
Thanks a lot @vladdenisov. I will give it a go

**Comment by stevezhengshiqi** [comment]
![IMG_2818](https://user-images.githubusercontent.com/36894554/86436086-8abb3c00-bccf-11ea-94df-c052b46e343e.JPG)

Got Clover working on Big Sur. Reference: https://www.hackintosh-forum.de/forum/thread/49311-macos-11-bigsur-dev-beta-clover-patch/?postID=619527#post619527

**Comment by kampav** [comment]
@stevezhengshiqi, Hey Steve, hope u r good. Can you please share the EFI for OC used to install Big Sur. literally stuck to boot and tried various forms and your suggestion too. just want to compare what's wrong with my EFI

**Comment by stevezhengshiqi** [comment]
No need to rush installing Big Sur. The bootloader and kernel extensions are not fully prepared for it yet. We may have to wait a couple of weeks for Acidanthera to improve their projects.

**Comment by kampav** [comment]
@stevezhengshiqi Thank you Steve. will wait

**Comment by Giannidmg** [comment]
https://youtu.be/V1p_bePCyh0

the touchpad and battery also work in this video

**Comment by stevezhengshiqi** [comment]
@Giannidmg Use Rehabman's ACPIBatteryDriver will let the battery and touchpad work, but I still prefer VirtualSMC's SMCBatteryManager since it has more "native" communication with `AppleSmartBatteryManager` (such as more SMC keys are provided).

**Comment by gplast** [comment]
Hello @stevezhengshiqi,

I decided to give it a try and update my MacOS to Big Sur. I have a strange problem thought which is not related exactly with the installation. I followed your steps:

git clone --depth=1 https://github.com/daliansky/XiaoMi-Pro-Hackintosh.git
cd XiaoMi-Pro-Hackintosh
./makefile.sh --PRE_RELEASE=Kext --PRE_RELEASE=OC

And after everything is built i'm getting this error:

cp: directory XiaoMi_Pro-local/EFI/Clover/drivers/UEFI does not exist
[ ERROR ]: Failed to copy resources!

I checked in the build folder and i can see the "XiaoMi_Pro-local" folder but is empty.
I would really appreciate it if you can help me with that.

Thank you,
--George

**Comment by stevezhengshiqi** [comment]
@gplast I just redo your steps and everything works well here. Could you delete the whole XiaoMi-Pro-Hackintosh folder and try again? Since the latest commits all passed the CI check, the script should work on different devices.

**Comment by gplast** [comment]
Thank you @stevezhengshiqi for you quick reply. I believe that is something on my side but unfortunately i cannot find what is wrong. I tried clone it again and run make script on both Documents file and the ~/ directory. 

Just to double-check everything:
I opened the termina, clone the repository using: git clone --depth=1 https://github.com/daliansky/XiaoMi-Pro-Hackintosh.git

**Comment by stevezhengshiqi** [comment]
You can try to change --depth=1 to --depth=50 or add --IGNORE_ERR at the end of the command.

**Comment by gplast** [comment]
Thank you again,

--depth=50 did not work unfortunately so now i'm taking risks with the second one :p 

Its strange though. with --IGNORE_ERR flag it worked with all this error:
cp: Release/NullEthernet.kext: No such file or directory
[ ERROR ]: Failed to copy resources!

cp: Release/NullEthernet.kext: No such file or directory
[ ERROR ]: Failed to copy resources!

cp: directory XiaoMi_Pro-local/EFI/Clover/drivers/UEFI does not exist
[ ERROR ]: Failed to copy resources!

cp: directory XiaoMi_Pro-local/EFI/Clover/drivers/UEFI does not exist
[ ERROR ]: Failed to copy resources!

cp: directory XiaoMi_Pro-local/EFI/Clover/drivers/UEFI does not exist
[ ERROR ]: Failed to copy resources!

cp: directory XiaoMi_Pro-local/EFI/Clover/drivers/UEFI does not exist
[ ERROR ]: Failed to copy resources!

cp: directory XiaoMi_Pro-local/EFI/Clover/drivers/UEFI does not exist
[ ERROR ]: Failed to copy resources!

cp: directory XiaoMi_Pro-local/EFI/Clover/drivers/UEFI does not exist
[ ERROR ]: Failed to copy resources!

I will check whether i'm missing something and give i a try, thank you!

**Comment by stevezhengshiqi** [comment]
@gplast I think I know where the problem is . Your disk type may be captial sensitive and in this line https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/makefile.sh#L312 the clover should be captialized.

**Comment by gplast** [comment]
@stevezhengshiqi nice debugging :) 

Thank you, it worked perfectly. I will try updating now from 10.15.5 and let you know if it works.

**Comment by Giannidmg** [comment]
the pre-release clove compatible with big sur?

**Comment by stevezhengshiqi** [comment]
No for now. Clover still has a long way to go to support Big Sur OTA update.

**Comment by Giannidmg** [comment]
Does OC support the OTA installation? no need to install via VMware?

**Comment by stevezhengshiqi** [comment]
It supported OTA installation and no need for VMware a few days ago. But it seems like Acid team make certain changes these days, which possibly break the OTA process. Still, it's a sure thing that OC will fully support OTA update to Big Sur in the near future.

**Comment by Giannidmg** [comment]
I just tried to install bigsur after going to OC pre-release 1.4.1, starting the installer it gets stuck on the apple

**Comment by Giannidmg** [comment]
> I just tried to install bigsur after going to OC pre-release 1.4.1, starting the installer it gets stuck on the apple

![IMG_20200709_184935](https://user-images.githubusercontent.com/45434724/87067879-027bf000-c215-11ea-97db-0f913c04f9bc.jpg)

**Comment by Giannidmg** [comment]
I'm trying to update OTA through the file and the ovens commands in the previous posts, but I encounter this error
![15943141604741247929279947324615](https://user-images.githubusercontent.com/45434724/87069068-de211300-c216-11ea-8b06-f2b3213a87c7.jpg)

**Comment by Giannidmg** [comment]
> Hi, I try to update my system but something wrong happened. OC stuck here and after a time it show me a "BAN" icon. I can start my old version 10.15.6, but I can't start the macos installer.
> 
> ------2020/6/26
> Finally I finished the upgrade, I use VM to complete the installation then switch to OC to boot my new system (Actually I empited my disk and reinstalled the system) .
> I have no idea that why some people can finished it by OTA, may be it's not stable enough.
> Thanks Steve.
> ![2732278dd693d3bb8b04f974a36cb3e](https://user-images.githubusercontent.com/50270641/85716290-e52c2980-b71e-11ea-9946-dc1e1e937199.jpg)
how do you update via vm?

**Comment by kampav** [comment]
@stevezhengshiqi . Hi Steve, I finally managed to do a clean install of big sur but having trouble with the click on trackpad(everything else works). I usually resolved this by disabling the force click in trackpad. For some reason when I click on trackpad its searching for trackpad and can't recognise my laptop trackpad. Do you have any suggestions for me to try.

**Comment by kampav** [comment]
> > Hi, I try to update my system but something wrong happened. OC stuck here and after a time it show me a "BAN" icon. I can start my old version 10.15.6, but I can't start the macos installer.
> > ------2020/6/26
> > Finally I finished the upgrade, I use VM to complete the installation then switch to OC to boot my new system (Actually I empited my disk and reinstalled the system) .
> > I have no idea that why some people can finished it by OTA, may be it's not stable enough.
> > Thanks Steve.
> > ![2732278dd693d3bb8b04f974a36cb3e](https://user-images.githubusercontent.com/50270641/85716290-e52c2980-b71e-11ea-9946-dc1e1e937199.jpg)
> 
> how do you update via vm?

Try with the latest build, seems to work both for the upgrade and new install. If it doesn't work use Steve config file in this post

**Comment by stevezhengshiqi** [comment]
@kampav Use  Use [Rehabman's ACPIBatteryDriver](https://github.com/RehabMan/OS-X-ACPI-Battery-Driver) instead of SMCBatteryManager.

**Comment by Giannidmg** [comment]
perfect I used the latest OC 1.4.1 update and I updated without problems

**Comment by kampav** [comment]
> @kampav Use [Rehabman's ACPIBatteryDriver](https://github.com/RehabMan/OS-X-ACPI-Battery-Driver) instead of SMCBatteryManager.

@stevezhengshiqi - Thank you so much all good for now.
