### ISSUE TITLE
Compatibility with the MX250 version

### ISSUE THREAD

**Issue by charlesbel** [daliansky/XiaoMi-Pro-Hackintosh#410]
Hi there,
I was looking this amazing github repo, I looked the code but I see in a few files some specific things of the MX150 version like in config.plist :
```
<key>PciRoot(0x0)/Pci(0x1c,0x0)/Pci(0x0,0x0)</key>
<dict>
	<key>AAPL,slot-name</key>
	<string>Internal</string>
	<key>model</key>
	<string>NVIDIA GeForce MX150</string>
</dict>
```
Or also the "NVMEFix" kext, that is specific for the MX150 because Xiaomi fixed it since 2019.
I have the MX250 version and I am not sure of the total compatibility.
Is there someone that already tested, or someone that have informations about it ?
Sincerely

**Comment by stevezhengshiqi** [comment]
Please clarify your device: 2019 or enhanced version. Better with board id like TM1701.

2019 issues can be discussed at https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/380
Enhanced version issues can be discussed at https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/367

NVMeFix is basically for most NVMe except PM981, not only for XiaoMi-Pro. It can enable APST on SSD and let SSD has better PM during sleep.

The MX150 line you mentioned actually does nothing but for decoration. You can modify <string>NVIDIA GeForce MX150 to whatever you like.
