### ISSUE TITLE
OC - SMBIOS

### ISSUE THREAD

**Issue by p33k** [daliansky/XiaoMi-Pro-Hackintosh#412]
I used the clover efi all the time, now changed to oc for testing it out.
everything works fine, except for the smbois/serialnumbers.
with clover I could generate it with clover configurator. with opencore about mac says "OPENCORE_SN1".
everything seems to work OK but that looks a bit strange, is this a problem? how should I generate a proper number for this?

**Comment by stevezhengshiqi** [comment]
| OpenCore | Clover |
--------| ------
| MLB | Board Serial Number |
| SystemSerialNumber | SerialNumber |
| SmUUID | SmUUID |

Add `MLB`, `Board Serial Number`, `SmUUID` to config.plist - PlatformInfo - Generic.
Personally, I use `Clover Configurator` to generate these values.
