### ISSUE TITLE
NEED HELP FOR WIFI

### ISSUE THREAD

**Issue by gvbsxmoon** [daliansky/XiaoMi-Pro-Hackintosh#413]
I've been reading thread #330 about **itlwm+HeliPort** with little success.
I'm not very expert in this things, i downloaded itwlm and heliport zip, but i actually don't know what can i do to make this work. I don't even know how can i run the .kext file. 
Can someone please help me with a sort of installation guidelines? I will for sure appreciate this. Thank you all for all this work.

**Comment by stevezhengshiqi** [comment]
Put kext to /CLOVER/kexts/Other or /Oc/Kexts and restart. And then double click app.
