### ISSUE TITLE
The sound is quieter than in windows

### ISSUE THREAD

**Issue by recre4te** [daliansky/XiaoMi-Pro-Hackintosh#415]
I think the sound is quieter than in windows, is there a way to fix this?

XiaoMi NoteBook Pro EFI v1.4.0

**Comment by stevezhengshiqi** [comment]
Known issue, can install app like Boom 3D. Currently no fix in AppleALC can solve this, and also highly possible none in the future.

**Comment by stevezhengshiqi** [comment]
Same issue: https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/216
