### ISSUE TITLE
win10开启虚拟机平台或者hyper-v，用clover引导win10启动会蓝屏，直接引导win10启动才能正常启动

### ISSUE THREAD

**Issue by name-xiaotao** [daliansky/XiaoMi-Pro-Hackintosh#416]
- 机型：八代U小米笔记本Pro
- EFI： v1.4.0，v1.4.1

**双系统情况下，win10开启虚拟机平台或者hyper-v，用clover引导win10启动会蓝屏，直接引导win10启动才能正常启动，clover只能用来启动MacOS。**

**Comment by stevezhengshiqi** [comment]
已知问题，在 https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/README_CN.md#clover-我无法通过-clover-进入-windowslinux但是可以通过按-f12然后选择系统进入 里写了不能开启沙盒和 hyper-v，可尝试使用OC
