### ISSUE TITLE
关于原生uuid的注入

### ISSUE THREAD

**Issue by Seanwanq** [daliansky/XiaoMi-Pro-Hackintosh#417]
您好，我在用opencore安装黑苹果时注意到您提到可以给config.plist修改一些东西来注入硬件原生uuid。希望您能对具体的文件修改给一下指导，因为我并不是很确定要怎么填写相关信息。电脑里安装了部分收费软件，其中有部分是不能移机的，所以很希望有切实可行的方法避免软件失效。谢谢您。

**Comment by stevezhengshiqi** [comment]
1. 首先 F12 启动进win，在cmd里运行 wmic csproduct get "UUID" 并记住这个机子原本的UUID。
2. 打开 /EFI/OC/config.plist，在 PlatformInfo-Generic 新建 SystemUUID 键，键值即位第一步获得的UUID。

**Comment by Seanwanq** [comment]
所以只要不用opencore引导Windows而是用本来的windows boot manager引导就没有问题了对吗？

**Comment by Seanwanq** [comment]
> 1. 首先 F12 启动进win，在cmd里运行 wmic csproduct get "UUID" 并记住这个机子原本的UUID。
> 2. 打开 /EFI/OC/config.plist，在 PlatformInfo-Generic 新建 SystemUUID 键，键值即位第一步获得的UUID。
> 
> 一些软件验证可能不单单只凭UUID，想要保留所有激活的话建议使用Clover或者F12进win。

所以只要不用opencore引导Windows而是用本来的windows boot manager引导就没有问题了对吗？

**Comment by stevezhengshiqi** [comment]
是的

**Comment by Seanwanq** [comment]
> 是的

谢谢您。
