### ISSUE TITLE
Infinite Load while Booting

### ISSUE THREAD

**Issue by charlesbel** [daliansky/XiaoMi-Pro-Hackintosh#418]
Hi,
I created an USB bootable for MacOS Catalina using this command :
`sudo /Applications/Install\ macOS\ Catalina.app/Contents/Resources/createinstallmedia --volume /Volumes/USB --nointeraction –downloadassets`
I mounted the EFI partition with Clover Configurator, and I copied the latest release inside. I booted on it on my Xiaomi Mi Notebook Pro and the loading bar under the Apple logo was very very slow. Even if the loading bar was complete, nothing append... After more than hour I decided to shutdown it. Is there someone that can help me, why the loading bar is so long ?

**Comment by stevezhengshiqi** [comment]
This repository is only for post-installation issues. For the installation part, you can read from the links given in the README and posts like https://www.tonymacx86.com/threads/guide-booting-the-usb-installer-using-opencore.296375/ or https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/

**Comment by stevezhengshiqi** [comment]
BTW, a check for SSD model is required. No support for PM981.
