### ISSUE TITLE
Touchpad very bad palm rejection

### ISSUE THREAD

**Issue by cook1e0** [daliansky/XiaoMi-Pro-Hackintosh#420]
Since everyone else using the provided kexts should have the same problem, is there anyone that got around this? The palm rejection is horrible and the touchpad keeps getting pressed when typing on the keyboard. Are there any configurations possible to get rid of this?

**Comment by stevezhengshiqi** [comment]
This repository just uses kexts but not develop them. For trackpad issues, please report to https://github.com/VoodooI2C/VoodooI2C/issues for professional assistance.

The only configuration for palm rejection at this stage is to adjust `QuietTimeAfterTyping` in `VoodooI2CHID.kext/Contents/info.plst - VoodooI2CHIDDevice Precision Touchpad HID Event Driver`.
