### ISSUE TITLE
boot error notification

### ISSUE THREAD

**Issue by Giannidmg** [daliansky/XiaoMi-Pro-Hackintosh#423]
this message appears to me before starting OC in the boot with the MI logo

ocs: no sheme for BlacklistAppIsUpdate at 3 Index, context <Security>

**Comment by stevezhengshiqi** [comment]
@Giannidmg Please never use OpenCore Configurator to edit your config.plist.
An incompatible version of OpenCore Configurator will automatically add old items in config.plist, which creates conflicts with the latest OpenCore bootloader.

**Comment by Giannidmg** [comment]
thanks steve
