### ISSUE TITLE
HiDPI in BigSur

### ISSUE THREAD

**Issue by Giannidmg** [daliansky/XiaoMi-Pro-Hackintosh#424]
HiDPI in BigSur does not work?

**Comment by stevezhengshiqi** [comment]
`bash -c "$(curl -fsSL https://raw.githubusercontent.com/xzhih/one-key-hidpi/dev/hidpi.sh)"`

**Comment by stevezhengshiqi** [comment]
BTW, try to find solutions on your own first next time. Information about these issues are not hard to find.

**Comment by Giannidmg** [comment]
In the new BS beta 9 I get this error

`Last login: Tue Oct 20 13:19:30 on ttys000
giovanni@MBP-di-Giovanni ~ % bash -c "$(curl -fsSL https://raw.githubusercontent.com/xzhih/one-key-hidpi/master/hidpi.sh)"

Remote Mode
  _    _   _____   _____    _____    _____ 
 | |  | | |_   _| |  __ \  |  __ \  |_   _|
 | |__| |   | |   | |  | | | |__) |   | |  
 |  __  |   | |   | |  | | |  ___/    | |  
 | |  | |  _| |_  | |__| | | |       _| |_ 
 |_|  |_| |_____| |_____/  |_|      |_____|
                                           
============================================
Backing up...
Password:
mkdir: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup: Read-only file system
cp: directory /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup does not exist
mv: rename ./tmp/disable to /System/Library/Displays/Contents/Resources/Overrides/HIDPI/: No such file or directory
chmod: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/disable: No such file or directory

(1) Enable HIDPI
(2) Enable HIDPI (with EDID)
(3) Disable HIDPI

Enter your choice [1~3]: 2

-------------------------------------
|********** Display Icon ***********|
-------------------------------------

(1) iMac
(2) MacBook
(3) MacBook Pro
(4) LG Display
(5) Pro Display XDR
(6) Do not change

Enter your choice [1~6]: 6

------------------------------------------
|********** resolution config ***********|
------------------------------------------
(1) 1920x1080 Display
(2) 1920x1080 Display (use 1424x802, fix underscaled after sleep)
(3) 1920x1200 Display
(4) 2560x1440 Display
(5) 3000x2000 Display
(6) Manual input resolution

Enter your choice: ^C
giovanni@MBP-di-Giovanni ~ % bash -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/master/install.sh)"

Your mainboard is 
[ ERROR ]:Not a XiaoMi-Pro, please check your model!
This script is only for Clover user!


 __  __  _                   __  __   _          ____                 
 \ \/ / (_)   __ _    ___   |  \/  | (_)        |  _ \   _ __    ___  
  \  /  | |  / _` |  / _ \  | |\/| | | |  ____  | |_) | |  __|  / _ \ 
  /  \  | | | (_| | | (_) | | |  | | | | |____| |  __/  | |    | (_) |
 /_/\_\ |_|  \__,_|  \___/  |_|  |_| |_|        |_|     |_|     \___/ 

Your mainboard is 
=========================================================================
(1) Update EFI
(2) Build beta EFI
(3) Build and update beta EFI
(4) Change Bluetooth mode (Only support the latest release)
(5) General audio fix (credits Menchen)
(6) Add color profile
(7) Update power management
(9) Enable HiDPI
(10) Fix Windows boot (Only support the latest release)
(11) Fix Apple services
(12) Problem report
(13) Exit
Which option you want to choose? (1/2/3/4/5/6/7/8/9/10/11/12/13)
:9
Remote Mode
  _    _   _____   _____    _____    _____ 
 | |  | | |_   _| |  __ \  |  __ \  |_   _|
 | |__| |   | |   | |  | | | |__) |   | |  
 |  __  |   | |   | |  | | |  ___/    | |  
 | |  | |  _| |_  | |__| | | |       _| |_ 
 |_|  |_| |_____| |_____/  |_|      |_____|
                                           
============================================
Backing up...
mkdir: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup: Read-only file system
cp: directory /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup does not exist
mv: rename ./tmp/disable to /System/Library/Displays/Contents/Resources/Overrides/HIDPI/: No such file or directory
chmod: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/disable: No such file or directory

(1) Enable HIDPI
(2) Enable HIDPI (with EDID)
(3) Disable HIDPI

Enter your choice [1~3]: ^C
giovanni@MBP-di-Giovanni ~ % bash -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/master/install.sh)"

Password:
Your mainboard is 
[ ERROR ]:Not a XiaoMi-Pro, please check your model!
This script is only for Clover user!


 __  __  _                   __  __   _          ____                 
 \ \/ / (_)   __ _    ___   |  \/  | (_)        |  _ \   _ __    ___  
  \  /  | |  / _` |  / _ \  | |\/| | | |  ____  | |_) | |  __|  / _ \ 
  /  \  | | | (_| | | (_) | | |  | | | | |____| |  __/  | |    | (_) |
 /_/\_\ |_|  \__,_|  \___/  |_|  |_| |_|        |_|     |_|     \___/ 

Your mainboard is 
=========================================================================
(1) Update EFI
(2) Build beta EFI
(3) Build and update beta EFI
(4) Change Bluetooth mode (Only support the latest release)
(5) General audio fix (credits Menchen)
(6) Add color profile
(7) Update power management
(9) Enable HiDPI
(10) Fix Windows boot (Only support the latest release)
(11) Fix Apple services
(12) Problem report
(13) Exit
Which option you want to choose? (1/2/3/4/5/6/7/8/9/10/11/12/13)
:9
Remote Mode
  _    _   _____   _____    _____    _____ 
 | |  | | |_   _| |  __ \  |  __ \  |_   _|
 | |__| |   | |   | |  | | | |__) |   | |  
 |  __  |   | |   | |  | | |  ___/    | |  
 | |  | |  _| |_  | |__| | | |       _| |_ 
 |_|  |_| |_____| |_____/  |_|      |_____|
                                           
============================================
Backing up...
mkdir: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup: Read-only file system
cp: directory /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup does not exist
mv: rename ./tmp/disable to /System/Library/Displays/Contents/Resources/Overrides/HIDPI/: No such file or directory
chmod: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/disable: No such file or directory

(1) Enable HIDPI
(2) Enable HIDPI (with EDID)
(3) Disable HIDPI

Enter your choice [1~3]: 1

-------------------------------------
|********** Display Icon ***********|
-------------------------------------

(1) iMac
(2) MacBook
(3) MacBook Pro
(4) LG Display
(5) Pro Display XDR
(6) Do not change

Enter your choice [1~6]: 6

------------------------------------------
|********** resolution config ***********|
------------------------------------------
(1) 1920x1080 Display
(2) 1920x1080 Display (use 1424x802, fix underscaled after sleep)
(3) 1920x1200 Display
(4) 2560x1440 Display
(5) 3000x2000 Display
(6) Manual input resolution

Enter your choice: 1
cp: /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-9e5: Read-only file system
cp: ./tmp/DisplayVendorID-9e5: unable to copy extended attributes to /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-9e5: Read-only file system
cp: /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-9e5/DisplayProductID-747: No such file or directory
Enabled, please reboot.
Rebooting the logo for the first time will become huge, then it will not be.

Press any key to return to the main menu...
`

**Comment by stevezhengshiqi** [comment]
@Giannidmg Please see the comment I posted https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/424#issuecomment-658960500.

> In the new BS beta 9 I get this error

`giovanni@MBP-di-Giovanni ~ % bash -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/master/install.sh)"

Why u are using this command? I have clearly mentioned in README that install.sh is only for Clover user.
