### ISSUE TITLE
Is there a tutorial for Xiaomi pro migrating from Clover to OpenCore ？

### ISSUE THREAD

**Issue by fang0814** [daliansky/XiaoMi-Pro-Hackintosh#425]
Is there a tutorial for Xiaomi pro migrating from Clover to OpenCore ？Or should I keep waiting for Clover to update？
I really want to try the Big Sur Thanks!!!

**Comment by kampav** [comment]
@fang0814 I just replaced EFI folder from OC. make a backup of your clover EFI and replace it with OC

**Comment by msr1715** [comment]
I reinstalled MacOS Catalina and used the last release from this repository, then updated to Big Sur and enabled the intel wifi card, for now on it seems to be all working fine and without WiFi adapter using itlwm.kext, but it still needs to improve the speed (70mbps without adapter and 200mbps with adapter, that is 70% of speed lost).

**Comment by msr1715** [comment]
@stevezhengshiqi Is it recommended to update config.plist with real data like Serial Number and MLB, right?

**Comment by stevezhengshiqi** [comment]
Yes, https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/412#issuecomment-650790417

**Comment by msr1715** [comment]
Those entries are non existen on the repo 's config.plist right?
We must create them ourselves with OpenCore documentation

**Comment by stevezhengshiqi** [comment]
Yes.
