### ISSUE TITLE
Error on Clover after update MacOS 10.15.6

### ISSUE THREAD

**Issue by Alex131111** [daliansky/XiaoMi-Pro-Hackintosh#427]
Hello everyone, I encountered a problem after updating macos 10.15.6 after replacing the old EFI folder with that of the new release, I restarted and during the startup of clover to choose the operating system, this error came out. (see attached photo)
![IMG_7545](https://user-images.githubusercontent.com/59234269/87852299-038ddb00-c901-11ea-8784-5f78ea8aa91d.jpg)

I don't know how to proceed and I don't understand what I have done wrong I have always carried out this procedure for all updates.
Can I somehow save the files on mac or does it have to do a clean install again? My pc is one Xiaomi Notebook Pro i5
Thank you all in advance and I apologize for my non-perfect English.
I hope someone helps me

**Comment by stevezhengshiqi** [comment]
@Alex131111 When updating the EFI, please strictly follow the instruction given in [README](https://github.com/daliansky/XiaoMi-Pro-Hackintosh#upgrade)

> A complete replacement of BOOT and CLOVER(or OC) folders is required. Delete these two folders and copy them from the release pack.

You have this problem because you have old AptioMemoryFix.efi in the drivers/UEFI folder, which relates to an incomplete update of EFI.

**Comment by Alex131111** [comment]
Ok thanks i will not make this error again for sure, i wanted to know if there is a way to access the efi folder from windows and modify it so as to put the correct files.

**Comment by MarFre22** [comment]
@Alex131111 
When I needed to do it, I used an adapter (M.2 NVMe to USB) and a Linux Distro, it's easy. On Windows it's not to easy I think. Hopethis helps.

**Comment by Alex131111** [comment]
I just solved the problem, through aomei part assistant to give a letter to the EFI unit and then through Explorer ++ I modified the files with the correct ones
thanks to everyone anyway
