### ISSUE TITLE
EFI v1.4.1 and v1.4.2 break the Recovery mode in Big Sur

### ISSUE THREAD

**Issue by stevezhengshiqi** [daliansky/XiaoMi-Pro-Hackintosh#428]
My model is XiaoMi-Pro MX150 (TM1701).

It seems that the latest two releases can't get into the Recovery mode of Big Sur. When I am in the OC Boot Picker page and press `Space`, the recovery icon shows. However, I can't manage to enter the Recovery mode; the device turns back to the boot picker page after I choosing the Recovery icon.

I won't have my Xiao-Mi laptop for the rest of this year and hope someone could get some idea about this issue. Thx!

By the way, for people who want to turn off `authenticated-root`, you can change the value of `csr-active-config` to `0x77080000` or `0xE7030000`.

**Comment by ghondar** [comment]
I have followed your steps, but I still have the same log as the image above using -v and without using -v, I get 1% of the bar and the laptop restarts 😢 

I read that you do not have your laptop to test, btw thanks anyway for your help, I will keep trying and if I succeed I will post it
