### ISSUE TITLE
1.4.1和1.4.2版本的OC都装不上Catalina，但可以装上Mojave

### ISSUE THREAD

**Issue by hongzhizhou** [daliansky/XiaoMi-Pro-Hackintosh#430]
OC启动后进入U盘加载安装，每次苹果图标的加载进度条走到一半就会重启。但1.4.0版本的OC可以正常安装Catalina，不知道什么原因，有个现象就是似乎每次都是在加载到进度条要变成绿色的时候会重启。

**Comment by stevezhengshiqi** [comment]
安装问题请看README给的安装教程。EFI是没有问题的。检查硬盘型号并确保引导文件夹删除了旧的再复制进新的。
