### ISSUE TITLE
opening menus lenses big sur

### ISSUE THREAD

**Issue by Giannidmg** [daliansky/XiaoMi-Pro-Hackintosh#431]
menus bluetooth, battery, volume, etc. are slow to open why?

**Comment by stevezhengshiqi** [comment]
That's normal for Big Sur hackintosh devices that don't have native wireless card. You need to delete `com.apple.wifi.WiFiAgent.plist`.  To do this, you also need to disable `authenticated-root` and delete the APFS snapshot in order to modify system files.

**Comment by Giannidmg** [comment]
ok thx
