### ISSUE TITLE
Error update to big sur beta 3

### ISSUE THREAD

**Issue by ghondar** [daliansky/XiaoMi-Pro-Hackintosh#432]
I'm trying update to big sur beta 3 but I get this screen ![IMG_20200723_140541.jpg](https://user-images.githubusercontent.com/6628637/88329222-3a903200-ccef-11ea-832b-7468c9794693.jpg)

I've tried disabling itlwm and voodoo controller kexts but still staying on that screen

**Comment by stevezhengshiqi** [comment]
It's due to incompatibility of VirtualSMC on beta3. You need to add `vsmcgen=1` in `config.plist - NVRAM - Add - boot-args`section or use `FakeSMC`  to replace with `VirtualSMC`.

**Comment by ghondar** [comment]
It doesn't work, I tried setting vsmcgen=1 and also changing VirtualSMC to FakeSMC, I get this:

![IMG_20200725_005009.jpg](https://user-images.githubusercontent.com/6628637/88450119-40caff00-ce12-11ea-8bb8-8e85ed0094d0.jpg)

**Comment by stevezhengshiqi** [comment]
I recommend the adding `vsmcgen=1` boot-args method. Make sure you are using vanilla v1.4.2 EFI release with that boot-args.
- Download the EFI v1.4.2 release
- Delete OC and BOOT folder and then copy the new two folders into your EFI partition
- Open `/EFI/OC/config.plist` with `TextEditor.app`, press `Win + F` and find `boot-args`. Change the code to the following:
```
<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
<dict>
	<key>boot-args</key>
	<string>darkwake=0 gfxrst=1 vsmcgen=1</string>
```
- Save and exit. Restart the device.

**Comment by ghondar** [comment]
I have followed your steps, but I still have the same log as the image above using -v and without using -v, I get 1% of the bar and the laptop restarts 😢

I read that you do not have your laptop to test, btw thanks anyway for your help, I will keep trying and if I succeed I will post it

**Comment by stevezhengshiqi** [comment]
In the group chat, almost everyone succeeded by adding that boot-args, so I think it should be smooth to upgrade to beta 3. BTW, you can wait until VirtualSMC provide full support for beta 3.

**Comment by cook1e0** [comment]
Just adding on to this, I had the same issue as the author while upgrading from 10.15.6 to Big Sur Beta 2. Tried adding `vsmcgen=1` and replacing VirtualSMC with FakeSMC.

**Comment by stevezhengshiqi** [comment]
When updating the latest macOS beta version, it's better to use `./makefile.sh --NO_GH_API --PRE_RELEASE=Kext --PRE_RELEASE=OC` to generate EFI with latest drivers.

**Comment by stevezhengshiqi** [comment]
When updating the latest macOS beta version, it's better to use `./makefile.sh --NO_GH_API --PRE_RELEASE=Kext --PRE_RELEASE=OC` to generate EFI with latest drivers.

**Comment by cook1e0** [comment]
Decided to try updating to Big Sur again after updating my EFI to the new 1.4.3 release. Is anyone else experiencing this?

![unknown](https://user-images.githubusercontent.com/8332033/89302549-44a91d80-d66b-11ea-9ac2-36108d61d872.png)

**Comment by cook1e0** [comment]
Update regarding this issue, just updated my EFI to the 1.4.3 and upgraded to Big Sur Beta 3, went flawlessly.
