### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by UstinovB** [daliansky/XiaoMi-Pro-Hackintosh#434]
I'm trying to update from Mojave to Catalina
First updated CLOVER and EFI (v1.4.2). Then downloaded mac OS Catalina.
But after rebooting and choosing macOS Install...
I become this type of error:

[EB|#LOG:EXITBS:START] ERROR

What can I try to do? Thanks!

Model: Notebook Pro 15.6 - I7 / MX250

**Comment by stevezhengshiqi** [comment]
When updating the EFI, please make sure it's a complete update. Delete the `BOOT` and `CLOVER` folders and then copy them from the release pack, never replace them directly.

Also make sure the system kext directory is untouched. Run `sudo kextcache -i /` to check if there's any unexpected output.

**Comment by UstinovB** [comment]
Yes, completely updated.
After this command I become only KernelCache ID

**Comment by stevezhengshiqi** [comment]
Haven't met this problem before. I guess that the install image is probably corrupted. You could try to delete the Update directory and re-install the Catalina install.app.

**Comment by UstinovB** [comment]
Am I doing everything right?
I run the installer directly from the system

**Comment by stevezhengshiqi** [comment]
Looks good. Your Catalina image probably has been corrupted. You could try to delete the Update files generated, re-download the Catalina installer and re-run the installer.

**Comment by UstinovB** [comment]
Without any result, unfortunately.

**Comment by stevezhengshiqi** [comment]
The EFI has no problem. It’s related to your local machine and you have to make a clean setup(remove old update files generated by the installer, keep system files untouched, etc.) before update.

**Comment by UstinovB** [comment]
Today I created a bootable USB stick with the same EFI (1.4.2) and it started.
Will I be able to update the system like this or only "clean" installation?

**Comment by stevezhengshiqi** [comment]
In normal situations, it should work just as a real Mac updating the system.

**Comment by UstinovB** [comment]
Got it! Thanks.
