### ISSUE TITLE
Dual Boot different Ssd- reinstalled windows and lost clover boot

### ISSUE THREAD

**Issue by macguru341** [daliansky/XiaoMi-Pro-Hackintosh#436]
Hello , need help
My notebook have 2 SSD and I had dual boot with windows 10 and macOS.
I had to install windows 10 from scratch and now when I boot my notebook it automatically load into windows and there's no Clover boot.
I installed "Macdrive" to check that I didn't delete by mistake my Mac SSD and it still there.
I took my Mac USB Stick and when I boot with it I see the clover boot so I load into Mac and used terminal to update EFI and hope it will fix the problem but still I load into windows.
I went to xioami boot setup and I see there only the windows boot loader.
Please help me fix it.
Thanks

**Comment by stevezhengshiqi** [comment]
You can seek hackintosh forums for help on installation-related problems. This repository is mainly about post-installation problems.

BTW, you can use `Bootice` to add Clover boot entry as written in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/Installation#step-5---adjust-boot-entry

**Comment by kampav** [comment]
@macguru341 - choose your macOS SSD as the primary in BIOS. I had the same probelm
