### ISSUE TITLE
EFI folder size too high in beta builds

### ISSUE THREAD

**Issue by kampav** [daliansky/XiaoMi-Pro-Hackintosh#437]
Hi,
   
   Not sure I can raise this here, but when I built the beta builds using the bellow commands, I was not able to copy the EFI folder as it keeps saying less disk space in EFI partition. I tried rm -rf.* and rm -rf * but no luck. I have noticed that intelblutooth kext is in 15MB+ size compared to few KBs before. Adding Itlwm.kext will increase the space further. Does Anyone else has this issue?

./makefile.sh --PRE_RELEASE=Kext --PRE_RELEASE=OC

**Comment by stevezhengshiqi** [comment]
@kampav Make sure you are using the latest makefile. The latest makefile deletes redundant Intel Bluetooth firmwares when building `IntelBluetoothFirmware.kext`, and the `IntelBluetoothFirmware.kext` should no larger than 1mb.

Also, you could try to empty `Trash` after mounting EFI partition. When deleting files in macOS, OS will move selected files to `.Trash` folder, which still occupies the disk size.

**Comment by kampav** [comment]
@stevezhengshiqi, Thanks Steve. No luck I checked the latest Bluetooth release and even that is 15MB. Will investigate further

**Comment by stevezhengshiqi** [comment]
@kampav You should use ./makefile.sh --PRE_RELEASE=Kext  to build light weight IntelBluetoothFirmware. The official one is big because it has to support all hardware. Please double check v1.4.2 EFI release, the size of IntelBluetoothFirmware never larger than 1mb.

**Comment by stevezhengshiqi** [comment]
Reopen this issue since `IntelBluetoothFirmware` introduce [FwBinary.cpp](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/blob/master/IntelBluetoothFirmware/FwBinary.cpp), which incredibly enlarges the size of `IntelBluetoothFirmware.kext`.

**Comment by msr1715** [comment]
Have you checked if you have hidden files on EFI?
Usually there is a .Trashes folder on EFI that saves everything you erase on the EFI folder, in my case I couldn't add a Kext and it was because of .Trashes folder was 75% of the EFI size, too much.
Mount EFI, go inside EFI with Finder and press CMD+Shift+ dot (.) and check hidden files sizes.
