### ISSUE TITLE
Mi Notebook 14Horizon Edition

### ISSUE THREAD

**Issue by MrAwanishKumar** [daliansky/XiaoMi-Pro-Hackintosh#438]
Hi,
I am trying to install mac os sierra but unable to do so. Can you guide me?

https://www.mi.com/in/mi-notebook-14-horizon/

Mi Notebook 14Horizon Edition
10th Generation Intel® Core™ i7 / 10th Generation Intel® Core™ i5

NVIDIA® GeForce® MX350

8GB 2666MHz DDR4 RAM

Super Thin Bezels & Ultra Light

35.56cm(14) FHD Anti-glare Horizon Display

512GB PCI Express Gen 3 NVMe SSD / 512GB SATA 3 SSD

Windows 10 Home

Up to 10Hrs of Battery

Thanks

**Comment by LeslieYang6** [comment]
10th Generation Intel cpu needs extra  configurations.

**Comment by MrAwanishKumar** [comment]
Do you have any supporting documentation link for configuration? Please provide.

**Comment by AtharvShinde** [comment]
hi can i use this for mi notebook 14 i3 10th gen UHD 620

**Comment by stevezhengshiqi** [comment]
Off-topic as different model.
