### ISSUE TITLE
I can't update macOS11 beta3 with EFI V1.4.2

### ISSUE THREAD

**Issue by fang0814** [daliansky/XiaoMi-Pro-Hackintosh#440]
![Screen Shot 2020-07-28 at 11 13 29 AM](https://user-images.githubusercontent.com/41377023/88615122-de008e80-d0c3-11ea-92e1-fdf1ff4c420c.png)
I am using macOS beta1. thanks!!!!

**Comment by fang0814** [comment]
It gets stuck on the Apple logo interface when it is updated and restarted。

**Comment by stevezhengshiqi** [comment]
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/432
