### ISSUE TITLE
poor wifi quality after changing to Mac wifi card 

### ISSUE THREAD

**Issue by macguru341** [daliansky/XiaoMi-Pro-Hackintosh#441]
hello
I replaced the wifi/BT card in my xioami notebook pro to get full apple experience.
I did a test with my iPhone and connected both of the devices to the same network and same place  ,in both devices I have full wifi and went to Speedtest website.
in my Mac I'm getting 7 Mbps and in my iPhone I'm getting 90 Mbps.
i'v updated to the last EFI with the terminal.
![Screen Shot 2020-07-28 at 20 58 17](https://user-images.githubusercontent.com/22807164/88703695-b3d7bc80-d115-11ea-9485-c34b16f26ab8.png)
![IMG_0282](https://user-images.githubusercontent.com/22807164/88703713-bf2ae800-d115-11ea-9437-a115e9b6ade1.png)

**Comment by stevezhengshiqi** [comment]
- Try add ` brcmfx-country=#a` in `boot-args` and add [AirportBrcmFixup](https://github.com/acidanthera/AirportBrcmFixup)
- Turn off `Wake for Wi-Fi network access` in SysPref - EnergySaver - PowerAdapter
- Adjust antenna location

Not an EFI related issue, will close after a while.

**Comment by macguru341** [comment]
Thanks Steve 
Just where do I add this line? I'm confused

**Comment by stevezhengshiqi** [comment]
config-Boot-Arguments

**Comment by MarFre22** [comment]
@macguru341, out of curiosity, what wifi/bt card do you have?
