### ISSUE TITLE
洗白后的黑苹果，外接显示器无法显示，显示屏提示无信号

### ISSUE THREAD

**Issue by sky-chy** [daliansky/XiaoMi-Pro-Hackintosh#442]
我今天参考这个地址：https://forum.51nb.com/thread-1757464-1-1.html 洗白黑苹果之后，现在外接显示器提示无信号，内屏正常，目前使用的是您发布的OC 1.4.2引导

黑果已经成功洗白了，外接显示器不显示了，请问我该怎么去解决呢？

**Comment by stevezhengshiqi** [comment]
请提供详细资料来诊断，比如隐去序列号的config.plist。在填入序列号的时候请不要使用OCC，最好使用文本编辑器或者任意一款plist编辑器。如果使用了OCC，请回滚至142efi的原生config。

请详细描述问题，比如在注入三码前外接显示屏是正常工作吗？

**Comment by sky-chy** [comment]
我是用了OCC来注入三码的，再问一下，如果我用其他plist编辑器注入三码后，以后还可以用occ来打开这个config.plist文件吗？

注入三码前接外屏是可以正常显示的

下面是完整的config文件
[config.plist.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4992549/config.plist.zip)

**Comment by stevezhengshiqi** [comment]
@sky-chy 不要使用OCC修改config，因为OC的特殊性，每个编译可能都会带来新的键值，而OCC需要时间才能跟上OC开发的节奏。本仓库使用的OC会是EFI发布时的最新编译，使用不兼容的OCC修改会额外加入不必要的键值并且篡改内容。而且OC官方也不推荐使用OCC。

在你的config - PlatformInfo 里，因为OCC的修改多出了SMBIOS这个列表，请退回原始config并用plist编辑器修改。

**Comment by sky-chy** [comment]
可是注入三码不就是需要机型参数吗？这里我就有点小白了，因为我看了很多教程都说需要机型参数，难道用其他编辑器直接注入三码就OK了？

**Comment by stevezhengshiqi** [comment]
是的

**Comment by sky-chy** [comment]
第一次接触OC，请问您这边有没有OC洗白黑苹果的参考例子呢？

**Comment by stevezhengshiqi** [comment]
把三码填进Generic里就行了呀，见https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/412#issuecomment-650790417

**Comment by sky-chy** [comment]
好的，谢谢，我先试试

**Comment by sky-chy** [comment]
成功洗白了，谢谢大佬
