### ISSUE TITLE
小概率出现触摸板突然失灵,拖不动的情况,过几秒钟后自动恢复,不止我一个人遇到

### ISSUE THREAD

**Issue by anyingiit** [daliansky/XiaoMi-Pro-Hackintosh#445]
**Pre-requirement**
**前提条件**

- Try to rebuild the kextcache and restart whenever you encounter a problem. It always works like a charm!
- 请在遇到任何问题时，先重建缓存并重启。它通常能修复99%的问题！
- To rebuild the kextcache, run `sudo kextcache -i /` in `Terminal.app`.
- 在`终端.app`运行命令`sudo kextcache -i /`来重建缓存。

**State the model**
**阐述您的机型**
XiaoMi-Pro MX150 i7-8550U

**State the version of the EFI**
**阐述您的EFI版本**
当前使用为最新版:EFI v1.4.2, 但是这个问题自我2019年使用黑苹果就有,所以应该不是最新版本的bug,而是长期存在.

**Describe the bug**
**描述您遇到的问题**

- A clear and concise description of what the bug is.
- 清晰并详细地描述问题所在。

1. 在正常使用过程中,小概率出现触摸板突然失灵,拖不动的情况,过几秒钟后自动恢复,常发生于使用过一段时间后, 开机就遇到的情况也有, 概率更小.
2. 在小米笔记本pro的黑苹果群内提问此类情况, 发现也有小部分人遇到该类情况, 其笔记本为i7-8550u-mx250-15.6改4k, 故应该可以排除是特定机型问题.

**Attach your entire EFI folder**
**附上您的整个EFI文件夹**

- Please attach your entire EFI folder to help solve your problem.
- Erasing serial numbers in config.plist is required!
- 请附上整个EFI文件夹来方便解决问题。
- 附件里的config.plist请清除序列号！

**Attach system.log**
**附上system.log**

- If applicable, please run `log show --predicate "processID == 0" --last boot --debug | grep "ERR"` in `Terminal.app` to help locate the problem.
- 如果可用，请在`终端.app`运行命令`log show --predicate "processID == 0" --last boot --debug | grep "ERR"`来帮助定位问题。

**Comment by stevezhengshiqi** [comment]
@anyingiit 已在多个issue里多次说明过，此仓库只使用Kext，并没有开发驱动的能力。触控板驱动问题请反馈到VoodooI2C仓库来寻求专业解答：https://github.com/VoodooI2C/VoodooI2C

**Comment by anyingiit** [comment]
> @anyingiit 已在多个issue里多次说明过，此仓库只使用Kext，并没有开发驱动的能力。触控板驱动问题请反馈到VoodooI2C仓库来寻求专业解答：https://github.com/VoodooI2C/VoodooI2C

好的
