### ISSUE TITLE
Trying to change GPU name in "About My Mac"

### ISSUE THREAD

**Issue by adeniji57** [daliansky/XiaoMi-Pro-Hackintosh#447]
Hi, 
I recently just got an ADT-Link eGPU adapter and used It to connect my RX 580 8gb to my Hackintosh through M.2. So far, it's all working perfectly. I just had to make sure I had a monitor connected to the GPU. My main use case for it is so that I can use the GPU's display port to drive my Ultra-wide 1440p 144hz monitor and also for a bit of gaming. Here's my Geekbench: https://browser.geekbench.com/v5/compute/1303991.

My only issue right now is that, instead of showing my GPU name in the "About My Mac" section, it says "Intel Sunrise Point-LP PCI Express Root Port #9. Does anyone know any way to change the name? I know it won't affect performance at all but it'll just look nicer. I've looked online already but a lot of the guides seem outdated.

**Comment by Menchen** [comment]
It’s in clover configurations file... just search the name you want to replace.

**Comment by adeniji57** [comment]
@Menchen That did the trick. Thank You.

**Comment by MarFre22** [comment]
@adeniji57
Hi! 
I have been fascinated with a possibility to connect an eGPU to Xiaomi Pro, but, before that, an MacOS compatible wifi/bluetooth card is essential to me (hope the best for OpenIntelWireless, it's really an innovative and necessary project for the community).
After some research I found that is very difficult to connect both (at the same time to the M.2 ports) and continue to be portable (only the PC and the wireless card with an fast plug to eGPU). 

Did you make the above config or eGPU only?

I'm wondering if can exist a tiny M.2 PCIe x4 splitter to work around.
