### ISSUE TITLE
About the Opencore boot problem of windows and macOS dual system

### ISSUE THREAD

**Issue by fang0814** [daliansky/XiaoMi-Pro-Hackintosh#448]
After changing from clover to opencore, the boot file of windows is lost and cannot enter Windows. Every time efi updates only macOS files, can you share the windows guide?

**Comment by stevezhengshiqi** [comment]
Please strictly follow README when updating EFI. Only `BOOT` and `OC` folders should be replaced and `Microsoft` folder should never be touched. If you always keep your `Microsoft` folder safe, you won't have any problems booting into Windows.

**Comment by stevezhengshiqi** [comment]
Close this issue as it's an user-side problem.
