### ISSUE TITLE
opencore can't use HDMI after edit platformNVRAM

### ISSUE THREAD

**Issue by RXDA** [daliansky/XiaoMi-Pro-Hackintosh#449]
I've already clean nvram, and model is MI-Pro GTX

**Comment by RXDA** [comment]
[](url)

**Comment by RXDA** [comment]
here is my config.plist 
[config.plist.txt](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/5078469/config.plist.txt)

**Comment by stevezhengshiqi** [comment]
The choice of `SystemProductName` in your config is way too beyond your model. `MacBookPro16,4` is a CFL-HR model.

Using incompatible SMBIOS model will harm the power management and has numerous side effects.

**Comment by RXDA** [comment]
> The choice of `SystemProductName` in your config is way too beyond your model. `MacBookPro16,4` is a CFL-HR machine.
> 
> Using incompatible SMBIOS model will harm the power management and has numerous side effects.

thanks,It works after set SystemProductName to Macbook Pro 13
