### ISSUE TITLE
Slow boot and fail to mount EFI partition on Big Sur beta 6

### ISSUE THREAD

**Issue by clasters** [daliansky/XiaoMi-Pro-Hackintosh#452]
On the latest release of OpenSore, the system starts to start slowly every other time, the sound disappears and the efi partition is not mounted.

Also, I can't display the Windows bootloader at startup

Help me please)

**Comment by stevezhengshiqi** [comment]
Inadequate information is provided. Please tell your device model and macOS version. Also, run `sudo kextcache -i /` and restart are always the good start to solve problems.

In addition, please make sure to delete `BOOT` and `OC` folders and copy the new one instead of just replacing folders when you update the EFI.

**Comment by clasters** [comment]
> Inadequate information is provided. Please tell your device model and macOS version. Also, run `sudo kextcache -i /` and restart are always the good start to solve problems.
> 
> In addition, please make sure to delete `BOOT` and `OC` folders and copy the new one instead of just replacing folders when you update the EFI.

sudo kextcache -i / i did,
completely deleted the boot and the folder, copied from the release, changed took the old generics, and changed the plist for DVMT_and_0xE2_fix, everything worked on the last release.

xiaomi notebbok pro mx150

**Comment by stevezhengshiqi** [comment]
and macOS version?

**Comment by stevezhengshiqi** [comment]
BTW, did you use OpenCore Configurator to edit your config? It's not recommended as that tool needs frequent update to support the latest OpenCore

**Comment by clasters** [comment]
> а версия для macOS?

big sur last beta

**Comment by clasters** [comment]
> Кстати, вы использовали OpenCore Configurator для редактирования своей конфигурации? Не рекомендуется, поскольку этот инструмент требует частого обновления для поддержки последней версии OpenCore.

No

**Comment by stevezhengshiqi** [comment]
> > а версия для macOS?
> 
> big sur last beta

Then it's a known issue that a few of my friends also mentioned. I am not sure whether it's a configuration problem or bootloader problem. Therefore, I personally only recommend beta version up to 11.0 beta 5 (20A5354i). Hope someone who has a clue to this problem can help.

For professional help, https://github.com/acidanthera/bugtracker/issues and https://www.insanelymac.com/forum/topic/338516-opencore-discussion/ are great places.

**Comment by clasters** [comment]
Last release worked fine
XiaoMi NoteBook Pro EFI v1.4.3

**Comment by clasters** [comment]
> > > а версия для macOS?
> > 
> > 
> > big sur last beta
> 
> Then it's a known issue that a few of my friends also mentioned. I am not sure whether it's a configuration problem or bootloader problem. Therefore, I personally only recommend beta version up to 11.0 beta 5 (20A5354i). Hope someone who has a clue to this problem can help.
> 
> For professional help, https://github.com/acidanthera/bugtracker/issues and https://www.insanelymac.com/forum/topic/338516-opencore-discussion/ are great places.
Last release worked fine
XiaoMi NoteBook Pro EFI v1.4.3

**Comment by cook1e0** [comment]
Having the same issue, very long boot and shutdown times, even longer with a second monitor plugged in.

**Comment by stevezhengshiqi** [comment]
After some tests, my sound comes back after disabling `DisableLinkeditJettison`. @clasters could have a try.

I haven't met other problems yet.

**Comment by stevezhengshiqi** [comment]
I met the slow boot problem too. By using `-v`, I found out that it's a `IntelBluetoothFirmware` related problem. After disabling that kext, my boot speed resumes to normal.
