### ISSUE TITLE
Not an issue just a question

### ISSUE THREAD

**Issue by Remmed96** [daliansky/XiaoMi-Pro-Hackintosh#453]
How much is this repository and EFI compatibile with the last version of this notebook ? Will this works with it ?

**Comment by stevezhengshiqi** [comment]
As the title says, It only works with XiaoMi-Pro 2017/2018/2019 that use 8th Gen CPU. It’s a pain to use it on 2020 that has 10th Gen CPU.

**Comment by Remmed96** [comment]
Excuse me but I'm not an expert at all, thank you very much for your answer.

**Comment by stevezhengshiqi** [comment]
No worry.
