### ISSUE TITLE
Airportitlwm SecureBootModel not Disabled?

### ISSUE THREAD

**Issue by Giannidmg** [daliansky/XiaoMi-Pro-Hackintosh#456]
can I set up SecureBootModel to make Airportitlwm work?
I tried to set Default but OC does not start

**Comment by stevezhengshiqi** [comment]
As the [OpenCore Configuration](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf) mentions, you need to 

> either reinstall the operating system or copy the manifests (files with .im4m extension, like boot.efi.j137.im4m) from /usr/standalone/i386 to /Volumes/Preboot/<UUID>/System/Library/CoreServices.

**Comment by Giannidmg** [comment]
the files were already present in the folder, I don't get the error but it gets stuck on the MI logo and doesn't go on
![Schermata 2020-09-18 alle 15 43 00](https://user-images.githubusercontent.com/45434724/93604597-decbe780-f9c5-11ea-8e51-30f0c3597b62.png)

**Comment by stevezhengshiqi** [comment]
You have to use Debug version of OpenCore to see the error information. I never tried `Default` SecureBootModel so no more suggestions I can provide. BTW, if you just want to use AirportItlwm, updating to Big Sur to use KernelCollection could work without Default SecureBootModel, no guarantee.

**Comment by Giannidmg** [comment]
ok now i'm updating to big sur and i try to load Airportitlwm

**Comment by stevezhengshiqi** [comment]
Also, you can always load kexts after boot. In `Terminal.app`, run:
```sh
sudo chown -R root:wheel <kext_location>
sudo chmod -R 755 <kext_location>
sudo kextload <kext_location>
```

**Comment by Giannidmg** [comment]
In this way I read that it does not load correctly and the apple functions do not work

**Comment by stevezhengshiqi** [comment]
It works perfectly for me to load in Terminal on 10.15.6 except for Continuity features like handoff.

**Comment by Giannidmg** [comment]
Ok in bigsur works without problems

**Comment by stevezhengshiqi** [comment]
For anyone who wants to boot AirportItlwm on macOS10.15,
- Change your `SecureBootModel` to allow loading immutablekernel. If your macOS version >= macOS11 (KernelCollection), you don't need to do the following steps:
```diff
	<key>DmgLoading</key>
-	<string>Any</string>
+	<string>Signed</string>
```
```diff
	<key>SecureBootModel</key>
-	<string>Disabled</string>
+	<string>Default</string>
```

More details have been posted on https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/Drive-Native-Intel-Wireless-Card

**Comment by stevezhengshiqi** [comment]
@reyzafany Already covered that in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/Drive-Native-Intel-Wireless-Card#use-airportitlwm
