### ISSUE TITLE
Brightness keys not working

### ISSUE THREAD

**Issue by cook1e0** [daliansky/XiaoMi-Pro-Hackintosh#459]
With the current OpenCore config, the brightness keys do not work on Big Sur Beta 8. I have tried removing the DVMT_and_0xE2_fix and igfxrpsc=1, but the issue persists. Just making sure that this issue is within the config and not specific to my setup.

**Comment by stevezhengshiqi** [comment]
@cook1e0 You need to update the latest VoodooPS2Controller to support native brightness key.

**Comment by cook1e0** [comment]
I built this EFI a couple hours ago, according to Hackintool VoodooPS2Controller is on 2.1.6.

**Comment by stevezhengshiqi** [comment]
It should be 2.1.7, and the flag --PRE_RELEASE=Kext is necessary when building beta EFI.

**Comment by cook1e0** [comment]
Thank you, will try that again.

**Comment by cook1e0** [comment]
Thanks again, worked like a charm. For some reason the script stopped after downloading NullEthernet when i entered ./makefile.sh --NO_GH_API --PRE_RELEASE=KextOC.

**Comment by stevezhengshiqi** [comment]
Yeah, sometimes the makefile fails to download from bitbucket. Re-run the script can help.
