### ISSUE TITLE
Bought a 2018 model. Should i update the firmware to the latest ? + Other questions

### ISSUE THREAD

**Issue by ManuGithubSteam** [daliansky/XiaoMi-Pro-Hackintosh#460]
Hi Guys,

Great to be here.
I took the plunge and got myself a 2018 model. Now before i drive into the hackintosh buisness.

Sould i update the firmware of Bios etc to the latest standard? At the moment there is Windows on the Notebook and i could update the firmware.

Also as far as i read up. I would not need to do the acpi table stuff from openCore as this is all in the efi folder correct ?
In the EFI there are seperate folders for the Audio Fix if i would need them.

But there is also a Bluethooth and a GFX Folder.
Im not sure why there are there.
The GFX should be disabled out of the box, or do i need to ude the Stuff in the GFX folder to disable it ?

Same with BT. I tought it was not working unless unsing the vmware workaround from here. Why do i need the BT Kext stuff. Do i need to put it in the EFI folder or not ?

On the net there are a lot of clover guides but OpenCore seems to be too new and this model to old to make it into a guide.
I will write one but first i have to make it run on the machine. As far as i read, it should be quite easy as the OC is just an efi bootloader with some extra sauce. So i would just download the EFI-OC from the release page and use it as in the clover guides... Is this correct ?

Sorry for my confusion here. I'm a long time tinkerer with PC and Linux but mac Hacking is new to me...

Thanks again for the help :-)

**Comment by stevezhengshiqi** [comment]
> Sould i update the firmware of Bios etc to the latest standard? At the moment there is Windows on the Notebook and i could update the firmware.

Really up to users. Firmware versions won't affect hackintosh behavior too much.

> Also as far as i read up. I would not need to do the acpi table stuff from openCore as this is all in the efi folder correct ?
In the EFI there are seperate folders for the Audio Fix if i would need them.

No, you don't need to patch ACPI as this repository already does. The ALCPlugFix is a client that requires running in a installed macOS.

> But there is also a Bluethooth and a GFX Folder.
Im not sure why there are there.

Please read the [Work-Around-with-Bluetooth.pdf](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/Work-Around-with-Bluetooth) given in the Docs folder under the EFI pack. If you are using a GTX version, you need to follow [README_GTX.txt](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/Docs/README_GTX.txt). If not a GTX version, just ignore it.

> Same with BT. I tought it was not working unless unsing the vmware workaround from here. Why do i need the BT Kext stuff. Do i need to put it in the EFI folder or not ?

Intel BT is working as [README](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/README.md) has clearly mentions that `Intel Bluetooth may cause sleep problems and does not support some Bluetooth devices`. BT Kexts(IntelBluetoothFirmware) are required to drive native Intel BT. Please read [Work Around with Bluetooth](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/Work-Around-with-Bluetooth) for details.

> So i would just download the EFI-OC from the release page and use it as in the clover guides... Is this correct ?

Yes, there's no difference by using OC or Clover to install macOS.

**Comment by ManuGithubSteam** [comment]
Hi Steve,

Thanks for responding so quick and thanks to you and the others for the hard and great work! 

The wiki is a great resource :-) I will contribute my findings if i may.

I will update the firmware then before making any changes. Just wanted to make sure that nothing breaks when i update the fw of the  laptop.

I got that with the GTX Card now. 

But im still a bit confused with the BT kexts. You write that is now working (Thanks for that) but there is still the IntelBluetoothFirmware kexts so can i assume that the "normal" kexts drivers that make it work with minor problems are not the intel ones  who are in  the EFI folder? Just to clarify.  The workaround document sadly does not mentions this.

Also would you recommend heliport or Airport ?

I'm thinking of trying something like menchen with the vmware solution for the sdcard reader. If linux can detect the reader we could mount it and share the contents with shared folders. Do you think this would be possible or is it not possible at all  for some obscure reason ?

My last question for now is:

Add igfxrpsc=1 boot-args or rps-control property to enable RPS control patch and improves IGPU performance (macOS version ≠ 10.15.6)
Does it mean it does not work on 10.15.6 and later (because i want to install: macOS Catalina 10.15.7(19H2) Installer for Clover 5122 and WEPE) or does it mean it will just not work on 10.15.6 but on x.7. Or do i have to use 10.15.5 for it?

Thanks!

**Comment by stevezhengshiqi** [comment]
> I will update the firmware then before making any changes. Just wanted to make sure that nothing breaks when i update the fw of the laptop.
I got that with the GTX Card now.

Normally, it won't cause problems, but a backup is recommended. I only uploaded MX150 firmwares in this reposiotry, so make sure you are using the correct firmware versions for GTX(TM1707).

> But im still a bit confused with the BT kexts. You write that is now working (Thanks for that) but there is still the IntelBluetoothFirmware kexts so can i assume that the "normal" kexts drivers that make it work with minor problems are not the intel ones who are in the EFI folder? Just to clarify. The workaround document sadly does not mentions this.

The drivers make our Intel BT works with minor problems is exactly IntelBluetoothFirmware; macOS doesn't naturally upload firmware for our Intel BT. If you want better Bluetooth experience, you need to buy a USB Broadcom BT(need BrcmPatchRAM.kext in this case) or solder a Broadcom Wireless Card.

> I'm thinking of trying something like menchen with the vmware solution for the sdcard reader. If linux can detect the reader we could mount it and share the contents with shared folders. Do you think this would be possible or is it not possible at all for some obscure reason ?

I would say it's highly possible. I personally didn't verify that, but I may heard someone did it.

> Does it mean it does not work on 10.15.6 and later

You don't have to worry about that, this repositories fully supports 10.13 to 10.15.6. The bullet points listed in [Improvements](https://github.com/daliansky/XiaoMi-Pro-Hackintosh#improvements) part are for advanced usage. In this case,  it's to warn people who want to add `igfxrpsc=1` boot-args in their config.plist. The origin EFI pack doesn't have this boot-args so no need to worry about that.

**Comment by Menchen** [comment]
The sdcard workaround with vm is technically possible but not really worth due to power usage... I would keep a usb reader near me or just reboot to Linux as the only thing I would need a sdcard for is to flash firmware for my raspberry pi.....

Having a vm in background and 1 extra USB device is too much power usage for me....

Also I recommend you unlock cpu in bios if you can... it really help performance and power usage.
