### ISSUE TITLE
install.sh option 8 doesn't work

### ISSUE THREAD

**Issue by Remmed96** [daliansky/XiaoMi-Pro-Hackintosh#461]
I'm trying to change my tdp but this option doesn't work, is there another way to do it ??

**Comment by stevezhengshiqi** [comment]
You probably need to build voltageshift (https://github.com/sicreative/VoltageShift) on your own and manually set configurations like https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/180 and https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/174. I am not in charge of the tdp script in option 8 that is currently out of maintenance.

**Comment by Remmed96** [comment]
Yes I did exactly that, I just wanted to suggest to pay attention to the typed commands, it seems that in the readme of the repository there are suggestions of wrong commands, or better maybe they refer to previous versions because at least as far as I could notice they set the power and time window in a different way from what was stated.

**Comment by Remmed96** [comment]
I suggest to take note of the values before the change and to check that they are modified as desired by the script.

**Comment by stevezhengshiqi** [comment]
Agree with you. So what's your suggestion? I can add a warning when the user chooses option 8 or I just delete that option.

**Comment by Remmed96** [comment]
I set the parameters as suggested by the script for the version with gpu mx150, i.e. downvolt of gpu, cpu and cache of -90mv, short term power 25W with windows of 28 s, long term power of 44 with window 0.002 s and a refresh of the settings every 60 minutes (it can be set to a lower value to refresh more frequently but with 60 I'm pretty good at least for now), the command I used and suggest to run once built to instantiate the daemon is the following.
(Obviously these are parameters that I suggest and of which I'm not sure either, they are the ones I'm currently using, I'm not responsible for any kind of errors or problems that can be created using them).

sudo ./voltageshift buildlaunchd  -90 -90 -90 0 0 0 25 28 44 0.002 60

The command must be started in the folder where the executable voltageshift is present, mine for example is ./VoltageShift-master/build/release

**Comment by Remmed96** [comment]
These are the results achieved in this configuration with a max of 70-75° Celsius on the cpu

![Schermata 2020-10-09 alle 18 33 30](https://user-images.githubusercontent.com/44156733/95608786-f5fa7400-0a5d-11eb-87cf-b186b29deb5e.png)

**Comment by Remmed96** [comment]
> Agree with you. So what's your suggestion? I can add a warning when the user chooses option 8 or I just delete that option.
 
I would suggest to create a guide in the Advanced section ok the WiKi (I mean where there is also the "Drive Native Intel Wireless Card" guide) where you explain how to use this tool and insert a link to this guide in the "Improvements" section in the README of the repository.
In this way anyone who wants to use this tool can find the right info directly from the repository without having to waste time searching for this info in the issues.

**Comment by stevezhengshiqi** [comment]
Undervolt wiki page created by MarFre22.
