### ISSUE TITLE
BIOS update question

### ISSUE THREAD

**Issue by Remmed96** [daliansky/XiaoMi-Pro-Hackintosh#463]
Hi I would like to ask a suggestion to anyone who has done a similar operation, I have the bios to version 0603 with the mods present in the folder DVMT_and_0xE2_fix, but I would like to update the bios to version 0906 to have the keyboard backlight always active, what I have changed would cause problems during the installation of the bios ?

**Comment by Remmed96** [comment]
> Hi I would like to ask a suggestion to anyone who has done a similar operation, I have the bios to version 0603 with the mods present in the folder DVMT_and_0xE2_fix, but I would like to update the bios to version 0906 to have the keyboard backlight always active, what I have changed would cause problems during the installation of the bios ?

In addition to the above, Voltage Shift supports BIOS version 0906 ?

**Comment by stevezhengshiqi** [comment]
As long as your model is TM1701, you will be fine to update. No 100% guarantee, as any modifications to BIOS is risky.

> In addition to the above, Voltage Shift supports BIOS version 0906 ?

Yes, they do support.

**Comment by MarFre22** [comment]
> In addition to the above, Voltage Shift supports BIOS version 0906 ?

Answered [here](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/389) ;)

**Comment by Remmed96** [comment]
> As long as your model is TM1701, you will be fine to update. No 100% guarantee, as any modifications to BIOS is risky.
> 
> > In addition to the above, Voltage Shift supports BIOS version 0906 ?
> 
> Yes, they do support.

Ok thanks, i have just another question, DVMT_and_0xE2_fix supports the 0906 bios ?

**Comment by stevezhengshiqi** [comment]
Everything supports 0906.

**Comment by Remmed96** [comment]
> > In addition to the above, Voltage Shift supports BIOS version 0906 ?
> 
> Answered [here](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/389) ;)

Okok Thanks a lot.



> Everything supports 0906.

Will DVMT_and_0xE2_fix remain active even after BIOS update ? I try to explain better the question, there are some executables called speedshift_unlock and voltage_unlock, that allowed me to use voltage shift, once the BIOS is updated, will I be able to continue to use voltage shift or will I have to do all the steps listed in the guide again?

**Comment by Remmed96** [comment]
Thank you very much for answering my questions but I am really not very familiar with these things.

**Comment by stevezhengshiqi** [comment]
Any changes you did to BIOS would be wiped out when you updating the BIOS firmware.

All the scripts provided in this repository supports all the BIOS versions above and includes 0502.

**Comment by Remmed96** [comment]
> Any changes you did to BIOS would be wiped out when you updating the BIOS firmware. (Not includes settings in BIOS panel, such as security password)
> 
> All the scripts provided in this repository supports all the BIOS versions above and includes 0502. (TM1701)

Okok so in case any problem happens during the installation, can I always fix it with a new installation of the bios 0603 ? or risk of brick the notebook ?
I am really grateful for the help you are giving me.

**Comment by Menchen** [comment]
You would need to open the laptop and flash your backup to the SIP chip using something like CH340 in case something has gone very wrong...

**Comment by stevezhengshiqi** [comment]
If BIOS update fails, it's hight possible that you can't even turn the screen light on.

**Comment by Remmed96** [comment]
> You would need to open the laptop and flash your backup to the SIP chip using something like CH340 in case something has gone very wrong...

> If BIOS update fails, it's hight possible that you can't even turn the screen light on.

Do you mean that the installation fails because the pc shuts down during the installation or it may happen that the installation fails for other reasons ?

**Comment by Menchen** [comment]
If you have done something wrong like the wrong version(wrong bios) or power issue(...but it's a laptop with battery so..) there's a chance of brick..... But many people had done it without issue...

**Comment by stevezhengshiqi** [comment]
No one can guarantee 100 % safe even for the BIOS developers. Any possible reasons, such as update scripts are written badly, corrupt firmware, etc,  will cause issues.

**Comment by Remmed96** [comment]
> If you have done something wrong like the wrong version(wrong bios) or power issue(...but it's a laptop with battery so..) there's a chance of brick..... But many people had done it without issue...



> No one can guarantee 100 % safe even for the BIOS developers. Any possible reasons, such as update scripts are written badly, corrupt firmware, etc, will cause issues.

Okok will evaluate the possibility to update, thank you very much
