### ISSUE TITLE
big sur beta 11.0 睡眠唤醒后屏幕出现随机闪烁

### ISSUE THREAD

**Issue by eivx** [daliansky/XiaoMi-Pro-Hackintosh#464]
**Pre-requirement**
**前提条件**
- 睡眠唤醒后，重启后无此问题

**State the model**
**阐述您的机型**
- XiaoMi-Pro MX150

**State the version of the EFI**
**阐述您的EFI版本**
- v1.4.5

**Describe the bug**
**描述您遇到的问题**
- 出现频繁的屏幕快速闪烁，具体表现形式为快速黑屏后恢复

**System log**
**系统报告**
- 无可用系统报告

**Screenshots**
**截图**
- 无可用截图

**Attach system.log**
**附上system.log**
- 无可用错误日志

**Comment by stevezhengshiqi** [comment]
@eivx 关闭hidpi或者开不大于1424分辨率的hidpi。

开大于1424 hidpi分辨率的时候必须开64dvmt并在config里删除dvmt补丁，同时按照README修改framebuffer-flags

**Comment by eivx** [comment]
> @eivx 关闭hidpi或者开不大于1424分辨率的hidpi。
> 
> 开大于1424 hidpi分辨率的时候必须开64dvmt并在config里删除dvmt补丁，同时按照README修改framebuffer-flags

我目前进行到了README中最后一步删除 OC MSR 0xE2 补丁，但是我并没有在`/EFI/OC/config.plist`找到`<key>AppleXcpmCfgLock</key>`，是否无需进行这一步？

**Comment by stevezhengshiqi** [comment]
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/OC/config.plist#L1028

这步和hidpi无关，不做也行。

**Comment by eivx** [comment]
> https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/OC/config.plist#L1028
> 
> 这步和hidpi无关，不做也行。

是否有办法查看显存修改是否成功及生效，所有步骤完成后闪烁情况依旧存在

**Comment by eivx** [comment]
> https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/OC/config.plist#L1028
> 
> 这步和hidpi无关，不做也行。

是否有办法查看显存修改是否成功，所有步骤完成后闪烁现象依旧存在

**Comment by stevezhengshiqi** [comment]
> 同时按照README修改framebuffer-flags

确定做了这一步？
![Screen Shot 2020-10-11 at 05 10 54](https://user-images.githubusercontent.com/36894554/95674728-2c301480-0b80-11eb-9b8a-6c1cb6734828.jpg)

**Comment by eivx** [comment]
> > 同时按照README修改framebuffer-flags
> 
> 确定做了这一步？
> ![Screen Shot 2020-10-11 at 05 10 54](https://user-images.githubusercontent.com/36894554/95674728-2c301480-0b80-11eb-9b8a-6c1cb6734828.jpg)

多谢提醒，这一步不小心遗漏了，编辑后问题已解决
