### ISSUE TITLE
OC: Failed to parse configuration

### ISSUE THREAD

**Issue by cavazzatommaso** [daliansky/XiaoMi-Pro-Hackintosh#466]
**State the model**
XiaMi-Pro MX150

**State the version of the EFI**
V1.4.5

**Describe the bug**
When i try to boot the laptop before the disk picker this error appears.
I can’t edit the configuration.plist

**Comment by Remmed96** [comment]
How to do it: Connect your usb, when selecting the bootloader boot disk, select the efi folder, after should reload the disk selection page, select the one with macos and should start, after boot check your config.plist file, it may be corrupted.

**Comment by stevezhengshiqi** [comment]
Close this issue because it’s an user error.
