### ISSUE TITLE
Question: Does Magic Mouse 2 work with the bluetooth patch

### ISSUE THREAD

**Issue by ManuGithubSteam** [daliansky/XiaoMi-Pro-Hackintosh#468]
Hi

I read some conflicting reports on bluethooth:

https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/233
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/323

In the End i want to buy a magic mouse 2 because im just not the touchpad guy. But they are quite costy so i need to know if they will work.

Does anybody own one and uses it in the Pro 15.6 ?

Thanks!

**Comment by cavazzatommaso** [comment]
I'm currently using the gen 1 and is working ok. Gesture works.
Don't know exactly for gen 2

**Comment by stevezhengshiqi** [comment]
Gen 2 will also work. Apple devices work with no problems through Intel BT. BTW, the issue page is not like forum, please try not to open new issues if you just have questions.
