### ISSUE TITLE
Installation of an Apple WiFi card - changes ?

### ISSUE THREAD

**Issue by macguru341** [daliansky/XiaoMi-Pro-Hackintosh#469]
Hello
After I'm installing the compatible WiFi+BT card and set it up in clover should I do something ?as the original internal WiFi board is still installed:
1. In the Mac OS X and also in windows 10 ? ( I have dual boot machine)

**Comment by MarFre22** [comment]
Hi, you can find some info [here](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/378) ;)

**Comment by stevezhengshiqi** [comment]
You have asked these questions serveral times here, and yes, I replied you with driver links. Please read old posts carefully and try not to spam the issue page.
