### ISSUE TITLE
Clover To OpenCore - Is there a manual?

### ISSUE THREAD

**Issue by macguru341** [daliansky/XiaoMi-Pro-Hackintosh#471]
hello
I have dual boot working machine with windows 10 and Mac OS X using clover.
I would like to convert to open core and I'm a newbe and want to know is there's some step by step guide for removing clover and install open core .
I found this [guide](https://dortania.github.io/OpenCore-Install-Guide/clover-conversion/) but as I read the guide he's talking about cleaning the clover "junk" , Removing kexts from macOS , Cleaning the Clover Junk in your hardware , but there's no part where after all the cleaning how to install the open core and save my both operation system.
I would love to hear some advice.

thanks

**Comment by MarFre22** [comment]
Hi,
You can find some interesting info [here](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/425) and in the README of our community.

**Comment by macguru341** [comment]
So it just downloading the OC EFI and replace it? That's sound easy ...thanks

**Comment by MarFre22** [comment]
> So it just downloading the OC EFI and replace it? That's sound easy ...thanks 

I think you also need to clean NVRAM, you can find how to do it in [README page](https://github.com/daliansky/XiaoMi-Pro-Hackintosh).

**Comment by macguru341** [comment]
thanks , by the way I have dual boot with windows 10 - If I just remove and replace the EFI folder I will not lose the dual boot?
when I look at my current EFI folder there's : Apple folder , Boot folder, clover folder , Microsoft folder, and strange but also OC folder.
when I look at the EFI folder that I've downloaded from here for OC theres only Boot folder and OC folder.
 Also iv'e replaced my internal wifi card will it also work plug and play?

**Comment by MarFre22** [comment]
> thanks , by the way I have dual boot with windows 10 - If I just remove and replace the EFI folder I will not lose the dual boot?
> when I look at my current EFI folder there's : Apple folder , Boot folder, clover folder , Microsoft folder, and strange but also OC folder.
> when I look at the EFI folder that I've downloaded from here for OC theres only Boot folder and OC folder.
>  Also iv'e replaced my internal wifi card will it also work plug and play?

So you have dualboot in the same ssd right? If you want to use OpenCore, JUST replace the BOOT and CLOVER folderas for new BOOT and OC folders. Don't touch on Microsoft folder ever! (also make a backup). Before replace the folders, read the readme and understand what to do to clean NVRAM.

It will be plug and play if you don't have any kext related to broadcom.
