### ISSUE TITLE
i5GTX版 上bigsur  蓝牙只能用一次

### ISSUE THREAD

**Issue by JF950908** [daliansky/XiaoMi-Pro-Hackintosh#472]
装机第一次可以使用蓝牙，正常开关，后面就不能直接关闭蓝牙和不能搜索设备了。Catalina正常。

**Comment by stevezhengshiqi** [comment]
本仓库只使用Kext，不负责Kext开发，蓝牙问题请提交到https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues
