### ISSUE TITLE
Apple Broadcom Built-in Bluetooth windows 10 driver

### ISSUE THREAD

**Issue by macguru341** [daliansky/XiaoMi-Pro-Hackintosh#473]
Hello
I've dual boot with windows 10 and after installing the Broadcom driver for the WiFi (replaced the internal WiFi card to the Apple one) I have left with one driver missing - the Apple Broadcom Built-in Bluetooth.

![image](https://user-images.githubusercontent.com/22807164/96329601-458d0100-1057-11eb-8124-96075b21a3de.jpeg)

How do I fix it? I've tried to install something from google but with no success 

Thanks

**Comment by stevezhengshiqi** [comment]
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/132#issuecomment-457301893

**Comment by stevezhengshiqi** [comment]
Please please read old posts I sent you first before creating any duplicate issue.

**Comment by macguru341** [comment]
I know sorry but after installing the BT driver for windows I still have yellow triangular on the device on the device manger

**Comment by MarFre22** [comment]
> I know sorry but after installing the BT driver for windows I still have yellow triangular on the device on the device manger 

If you have the Intel card with the original antennas (and broadcom ones under the trackpad), you don't need to install broadcom drivers, because Intel ones have better support for Windows.

**Comment by stevezhengshiqi** [comment]
> I know sorry but after installing the BT driver for windows I still have yellow triangular on the device on the device manger

Install the driver, disable the device in device manager, then restart. And then, re-enable the device.

**Comment by macguru341** [comment]
Thanks 
Tried it - still the same results 
Maybe I should disable one of the BT so I will not have 2 at the same time ?

**Comment by stevezhengshiqi** [comment]
No you don’t have to do that.
