### ISSUE TITLE
Strange behaviour with AirportItlwm Beta v1.1.0 and Alpha v1.2.0

### ISSUE THREAD

**Issue by Remmed96** [daliansky/XiaoMi-Pro-Hackintosh#475]
Does anyone have a problem with AirportItlwm v1.1.0 Beta? I don't have continuity and universal clipboard working for me, while using the alpha verion everything works fine.

**Comment by stevezhengshiqi** [comment]
Please try to relogin icloud account on your iPhone. And also, we don't accept AirportItlwm bug here. Please report to https://github.com/OpenIntelWireless/itlwm/issues
