### ISSUE TITLE
XiaoMi-Pro MX150希望efi集成网卡驱动

### ISSUE THREAD

**Issue by z1un** [daliansky/XiaoMi-Pro-Hackintosh#476]
机型：XiaoMi-Pro MX150
希望可以在efi中直接集成wifi驱动，避免每次跟换efi还要比较麻烦的搞网卡驱动。

**Comment by Menchen** [comment]
不是所有人都有用intel wifi啊……

**Comment by z1un** [comment]
> 不是所有人都有用intel wifi啊……

好吧

**Comment by stevezhengshiqi** [comment]
@z1un 目前AirportItlwm仍需要使用对应macOS版本的驱动。如果一个驱动可同时支持多个macOS版本的话将会考虑整合进efi
