### ISSUE TITLE
Can't connect to my 5Ghz network 

### ISSUE THREAD

**Issue by macguru341** [daliansky/XiaoMi-Pro-Hackintosh#477]
helllo
I have the replaced the wifi card on my xioami and I have some strange problem.
like all modern routers I have 2 networks :  2.4 and 5 and my xioami on Mac don't want to connect to the 5 Ghz network only to the 2.4.
I enter the right password as it the same like the 2.4 but it's thinking and then saying connection failed and asks me to enter the password again.

I can only connect to the 2.4.

is there a way to fix it? its very strange

thanks

**Comment by stevezhengshiqi** [comment]
- Change your Wireless Router 5G channel, keep the channel below 100.
OR
- Add [AirportBrcmFixup](https://github.com/acidanthera/AirportBrcmFixup/releases) to Kext folder and add item in config, then add `brcmfx-country=#a` in `boot-args` (Theoretically work, haven't tested)

**Comment by MarFre22** [comment]
@macguru341 , out of curiosity, what is your Wi-Fi card?

**Comment by macguru341** [comment]
> @macguru341 , out of curiosity, what is your Wi-Fi card?

Here is a [link](https://h5.m.taobao.com/awp/core/detail.htm?id=532197802538&ft=t&toSite=main) to the card

**Comment by MarFre22** [comment]
> > @macguru341 , out of curiosity, what is your Wi-Fi card?
> 
> Here is a [link](https://h5.m.taobao.com/awp/core/detail.htm?id=532197802538&ft=t&toSite=main) to the card 

I thought that card was plug and play without any issues.
There is any card that doesn't need to install any kext to work without issues?

**Comment by tianh** [comment]
咦, 为啥不用中文聊天?

**Comment by tianh** [comment]
我也是这个卡, 可以连接5G 啊

**Comment by Mateo1234454545** [comment]
@macguru341 , how did you manage to change the wifi card? I thought it was soldered.

**Comment by MarFre22** [comment]
> @macguru341 , how did you manage to change the wifi card? I thought it was soldered.

@Mateo1234454545 , you can find many issues (and the wiki+FAQ) related to how to improve the Wi-Fi compatibility, for example [this issue](https://github.com/stevezhengshiqi/XiaoMi-Pro/issues/7).

**Comment by FallenChromium** [comment]
This happens because there are restrictions in different regions for the wifi channels, but, if you see your network in the list I doubt it's the channel problem, because you wouldn't see your network at all then. BCM94360CD/CS2/2CS doesn't need any kexts to work (checked myself), 94352 chipsets needs it though

**Comment by stevezhengshiqi** [comment]
Close as no response from issue creater.
