### ISSUE TITLE
error while updating from terminal

### ISSUE THREAD

**Issue by arandax** [daliansky/XiaoMi-Pro-Hackintosh#479]
Hi,
I run the command sh -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/master/makefile.sh)" and I get the error:

XiaoMi-Pro-Hackintosh-master/ALCPlugFix/ALCPlugFix/alc_fix: No such file or directory

macOS 11.0.1 on mi notebook pro
Any ideas?

**Comment by stevezhengshiqi** [comment]
@arandax Thank you for point out the problem. It's because ALCPlugFix is a git submodule and only supported by a full git repository. I recommend to git clone this repository, cd, and then run ./makefile.sh.

**Comment by arandax** [comment]
that's how I did the work around.
thank you for your effort!
