### ISSUE TITLE
Blocked start

### ISSUE THREAD

**Issue by VitorSaling** [daliansky/XiaoMi-Pro-Hackintosh#480]
When starting the hackintosh, it loads but after the lock screen appears.

imagen -  https://ibb.co/CKKXJHW

**Comment by stevezhengshiqi** [comment]
@VitorSaling Too little information is provided. Please mention your model, EFI version, post-install or pre-install. Also check your disk model, PM981 is not supported.

**Comment by stevezhengshiqi** [comment]
Close as no reposnse and insufficient information.
