### ISSUE TITLE
DVMT_set.cmd sets DVMT to 128mb?

### ISSUE THREAD

**Issue by larryare** [daliansky/XiaoMi-Pro-Hackintosh#481]
Inside this [patchscript_dvmt.ps1](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/b1763bc9d1337f8c85624098db297d6dc12ffa6e/BIOS/DVMT_and_0xE2_fix/bin/patchscript_dvmt.ps1) script, there are these lines:
```powershell
#$bytes[$offset] = 0x30 # 0mb
#$bytes[$offset] = 0x31 # 32mb
#$bytes[$offset] = 0x32 # 64mb
$bytes[$offset] = 0x33 # 96mb (???)
```
And the line uncommented says that it sets DVMT to 92mb, though improvement section states that it need to be set to 64mb, although the guide doesn't specify editing this script.

I also took a screenshot from Windows (eww !) and it says that DVMT is 128mb also.

![image](https://user-images.githubusercontent.com/47447699/98042738-bc364680-1e2c-11eb-9804-6f73384b305c.png)

**Is it that I don't understand something and it's intended to be so or this is a mistake?**

It can actually be bad to change the default DVMT value according to [this Reddit post.](https://www.reddit.com/r/gpdwin/comments/5hxgpe/dont_change_dvmt_preallocated_video_memory_in/)

Another question: DVMT change is only required if I need HiDPI options and if I'm running at native 1080p with no external display, do I even need to change it to 64mb (or 128mb)?

**Comment by stevezhengshiqi** [comment]
> And the line uncommented says that it sets DVMT to 92mb, though improvement section states that it need to be set to 64mb, although the guide doesn't specify editing this script.

That's an interesting finding. I have no idea about how these scripts work, @FallenChromium would you mind have a check of that?

> I also took a screenshot from Windows (eww !) and it says that DVMT is 128mb also.

You can't trust Windows panel as a source of showing dvmt. The [tonymacx86.com](www.tonymacx86.com)'s moderator has clearly said at [here](https://www.tonymacx86.com/threads/hd-5500-panic-128mb-dvmt-prealloc.269430/post-1888926).

> windows is not a reliable source for determining DVMT values

> if I'm running at native 1080p with no external display, do I even need to change it to 64mb (or 128mb)?

No, you don't need that. All the sections in the [Improvements](https://github.com/daliansky/XiaoMi-Pro-Hackintosh#improvements) are not necessarily needed.

**Comment by larryare** [comment]
Thank you for your answer. Though the script clearly has the wrong line uncommented and I'm too afraid to test it because I don't understand these things also. Well, let's wait for someone more knowledgeable and see how it really is.

**Comment by FallenChromium** [comment]
Actually Windows report on DVMT memory is incorrect, so it doesn't represent the real value. Don't worry about the script, it does work as intended and I tested it with the developer of this script. I am using this patch myself and I haven't noticed anything bad (I set it to 64MB though). As of why it is needed, @stevezhengshiqi said the right thing - without it we have to make a patch, and basically if you use your internal graphics a lot, for increased performance (especially on higher resolutions) you'd like to set the DVMT value higher. Take a note though that it steals more memory from RAM then.

**Comment by larryare** [comment]
@FallenChromium So, to set it to 64mb I NEED to edit the script right? If so, in my opinion it should be set to 64mb by default.

**Comment by FallenChromium** [comment]
@larryare Yes, that's correct. As for the script change, @stevezhengshiqi, what do you think?

**Comment by stevezhengshiqi** [comment]
@FallenChromium If you can make sure the comment and code are correct, I will say we can change the script to 64mb after some testing.

**Comment by Miskotonic** [comment]
Hello. Does this script work for GTX version? 
Is there any ideas how to change without BIOS tuning?

**Comment by larryare** [comment]
@Miskotonic I have no idea about GTX patching but changing DVMT without tuning the BIOS is impossible.
