### ISSUE TITLE
Graphics acceleration not working

### ISSUE THREAD

**Issue by ennioitaliano** [daliansky/XiaoMi-Pro-Hackintosh#482]
Hi guys, as the title says iGpu acceleration is not working for me, causing animation to be laggy and trasparencies disabled at all. In about my mac it shows that only 7mb are assigned to the Intel UHD 620, I've tried to fix this in lots of ways but it never worked and I also noticed that no one with the Mi Notebook Pro has never had this issue. My model is the one with i5 8250u, MX250 and 8Gb RAM, thanks in advance. 
![image](https://user-images.githubusercontent.com/47503625/98101800-ffc39b80-1e92-11eb-94e1-d5d00ae31662.png)

**Comment by stevezhengshiqi** [comment]
When using the EFI release, please follow the README instruction. Delete  BOOT and CLOVER folders completely and then copy new ones from https://github.com/daliansky/XiaoMi-Pro-Hackintosh/releases. Never just replace folders.

**Comment by stevezhengshiqi** [comment]
Close as it’s an user operation mistake.
