### ISSUE TITLE
SIP set to disabled

### ISSUE THREAD

**Issue by larryare** [daliansky/XiaoMi-Pro-Hackintosh#483]
Using stock **latest** EFI release SIP is disabled, though it shouldn't be because we're not doing anything in /System or /Library, so by default SIP _should_ be enabled.

`csrutil status` output:

```sh
System Integrity Protection status: disabled.
```

`nvram -p` output:

```sh
fmm-computer-name	Laurynas%e2%80%99s MacBook Pro
platform-uuid	audited #idk if I should hide it
SystemAudioVolumeDB	%ed
backlight-level	%d6%00
run-efi-updater	No%00
SystemAudioVolume	Y
LocationServicesEnabled	%01
csr-active-config	g%00%00%00
boot-args	darkwake=0 gfxrst=1
```

**Comment by stevezhengshiqi** [comment]
It is intentionally to disable SIP in this repository's EFI release. Since we are Hackintosh users, some people need to disable SIP to enable HiDPI, inject unsigned kexts, and so on. People can turn on SIP as what you did manually.
