### ISSUE TITLE
It's Additional macos upgrade 10.15.7 safe ?

### ISSUE THREAD

**Issue by Remmed96** [daliansky/XiaoMi-Pro-Hackintosh#484]
It's Additional macos upgrade 10.15.7 safe ?

<img width="862" alt="Schermata 2020-11-06 alle 21 51 06" src="https://user-images.githubusercontent.com/44156733/98413636-3e677a80-207a-11eb-82a5-4c3adc1f842f.png">

**Comment by larryare** [comment]
I did it, everything is fine.

**Comment by stevezhengshiqi** [comment]
Please see README. The latest EFI release support whatever macOS version in Catalina, even 10.15.8.
