### ISSUE TITLE
请问如何在clover中启用intel的蓝牙？

### ISSUE THREAD

**Issue by codecola** [daliansky/XiaoMi-Pro-Hackintosh#485]
安装了双系统，希望在clover选择界面可以用蓝牙键盘选择启动项。在CLOVER\kexts\Other里放上了IntelBluetoothFirmware.kext和IntelBluetoothInjector.kext，但是没有起作用。求指导，谢谢！

**Comment by HKMV** [comment]
选择界面时没法驱动蓝牙的。
