### ISSUE TITLE
Pass Through NVidia GPU to Parallels?

### ISSUE THREAD

**Issue by jackreeves** [daliansky/XiaoMi-Pro-Hackintosh#486]
Given the Bluetooth and Graphics Card hacks that we've seen on this machine is it possible to load the GPU in Parallels/VMWare for to atleast use it in windows/linux environment?

**Comment by stevezhengshiqi** [comment]
It's not possible on macOS because macOS does not support Optimus. Different from SD and Bluetooth, macOS does not have the ability to contact our discrete card since our MX Nvidia shares the same output channel with iGPU.
