### ISSUE TITLE
最新的oc，安装big sur，不断重复：service only ran for 0 seconds. pushing respawn out by 10 seconds 

### ISSUE THREAD

**Issue by TenzinJamyangZHS** [daliansky/XiaoMi-Pro-Hackintosh#487]
service only ran for 0 seconds. pushing respawn out by 10 seconds

**Comment by stevezhengshiqi** [comment]
Too little information is provided. Please declare your model, EFI version, and better to post a screenshot.

Remember to completely replace your BOOT and OC folder before update: Delete these two folders and copy them from the release pack.

**Comment by TenzinJamyangZHS** [comment]
> Too little information is provided. Please declare your model, EFI version, and better to post a screenshot.
> 
> Remember to completely replace your BOOT and OC folder before update: Delete these two folders and copy them from the release pack.

efi version 1.4.7

**Comment by TenzinJamyangZHS** [comment]
![IMG_20201112_233355396.jpg](https://user-images.githubusercontent.com/22554163/99009354-e6051100-2582-11eb-8d95-d0eecc742c73.jpg)

**Comment by stevezhengshiqi** [comment]
No idea. I don't see anyone who has the same problem as you. Try to install with a Big Sur USB.

**Comment by stevezhengshiqi** [comment]
Close as it’s an user side issue.

**Comment by flutting** [comment]
I also have this problem.
我也出现这个问题.
