### ISSUE TITLE
MacOS bigsur installation question

### ISSUE THREAD

**Issue by Alex131111** [daliansky/XiaoMi-Pro-Hackintosh#488]
Hello everybody, I wanted to know if it was possible to upgrade from Catalina 10.15.7 to MacOS Big Sur by simply updating and replacing the EFI item at the end of the update. 
It is a possible operation without errors or it is better to create a usb from 0 with the intaller?
thank you all
sorry for my english

**Comment by stevezhengshiqi** [comment]
You can always update online in Hackintosh if your EFI is the latest. You do whatever a real Mac does.
