### ISSUE TITLE
Install Big Sur on Clover

### ISSUE THREAD

**Issue by matvada** [daliansky/XiaoMi-Pro-Hackintosh#489]
Hello,
sorry for my question but i'm downloading Big Sur and i need to know if is compatible with Clover or only with Open Core as i read in other issues.

Thanks

**Comment by stevezhengshiqi** [comment]
Only with OpenCore at this stage, but future Clover EFI release can support Big Sur. You can build your own Big Sur supported Clover release by running `./makefile.sh --NO_GH_API --VERSION="${TRAVIS_TAG}" --PRE_RELEASE=Kext` in the Terminal.

**Comment by matvada** [comment]
@stevezhengshiqi thanks, i tried to run the command but this is the result:

![Schermata 2020-11-13 alle 07 54 22](https://user-images.githubusercontent.com/52761699/99038286-7e9c9080-2585-11eb-86c8-f9062992cbd1.png)

**Comment by stevezhengshiqi** [comment]
Sorry that I didn't explain it in detail.
These are the full steps:
- Make sure you have Xcode
- git clone https://github.com/daliansky/XiaoMi-Pro-Hackintosh.git && cd XiaoMi-Pro-Hackintosh
- ./makefile.sh --NO_GH_API --VERSION="1.4.8" --PRE_RELEASE=Kext

**Comment by matvada** [comment]
Ok @stevezhengshiqi thank you, i'll try to build the beta release or i'll wait for the next Clover EFI release.
Thanks for your help!

**Comment by superhero75** [comment]
> Sorry that I didn't explain it in detail.
> These are the full steps:
> 
> * Make sure you have Xcode
> * git clone https://github.com/daliansky/XiaoMi-Pro-Hackintosh.git && cd XiaoMi-Pro-Hackintosh
> * ./makefile.sh --NO_GH_API --VERSION="1.4.8" --PRE_RELEASE=Kext

is the current 1.4.8 beta version stable yet? or we should wait another week for the final version?

**Comment by stevezhengshiqi** [comment]
We have to wait for the Clover team to releasing r5127.

**Comment by kidaww** [comment]
I had a stupid problem when trying to upgrade from 10.15.5
Installed first 10.15.7 and then 11.0 and it worked :)

**Comment by DAFsuper** [comment]
@stevezhengshiqi pls can you make a tutorial on big sur update from catalina??
I can support the work if you do it.

**Comment by stevezhengshiqi** [comment]
> @stevezhengshiqi pls can you make a tutorial on big sur update from catalina??
> 
> I can support the work if you do it.

Just update the 1.4.7 OC efi, and then click update in SysPref-Software Update. It's simple so I don't see the necessity to make a update totrial.

**Comment by DAFsuper** [comment]
@stevezhengshiqi how to update the OC efi? And how to check wich version I’m at?

**Comment by stevezhengshiqi** [comment]
Please read [README](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/README.md#upgrade) to update OC EFI. Delete BOOT and OC folders and then copy into new ones from the 147 OC release pack. There's no way to check EFI version at this stage, just make sure you are using the latest release.

**Comment by DAFsuper** [comment]
I did update the efi to the last version! when I try to install big sur in syspref softwer it just goes in bootloop

**Comment by stevezhengshiqi** [comment]
@DAFsuper Typically, you won’t have problem. You can try work around here at https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/492#issuecomment-727212935, which is reinstall 10.15.7 and then update to 11.

**Comment by DAFsuper** [comment]
sorry mate I have tried all the day but got nothing... I might wait for a tutorial on yt or when new efi will be avaible...

**Comment by Remmed96** [comment]
> sorry mate I have tried all the day but got nothing... I might wait for a tutorial on yt or when new efi will be avaible...

Try to install again catalina 10.15.7 combo version from apple website (it should be this one: https://support.apple.com/kb/DL2052 ), after that reset NVRAM and try to install Big Sur again.
If this doesn't work, try to enter Big Sur beta testers and try to install the beta version.

**Comment by DAFsuper** [comment]
> > sorry mate I have tried all the day but got nothing... I might wait for a tutorial on yt or when new efi will be avaible...
> 
> Try to install again catalina 10.15.7 combo version from apple website (it should be this one: https://support.apple.com/kb/DL2052 ), after that reset NVRAM and try to install Big Sur again.
> If this doesn't work, try to enter Big Sur beta testers and try to install the beta version and after update to the stable one.

No either... tried everything today, spend all the day on it.. (can you add me on whatsapp? I’m also from italy) @Remmed96 
Maybe you can help me pls..

**Comment by Remmed96** [comment]
I'm not an expert, maybe I'm only lucky

**Comment by DAFsuper** [comment]
> I'm not an expert, maybe I'm just lucky

Please add me (3248337518) you can help me...

**Comment by matvada** [comment]
@stevezhengshiqi finally i took courage :)
1) deleted CLOVER and BOOT folders from EFI 
2) copied OC and BOOT folder to EFI from XiaoMi_Pro-OC-v1.4.7.zip https://github.com/daliansky/XiaoMi-Pro-Hackintosh/releases/latest
3) Booted into Catalina and then installed Big Sur without issues.

Just for clarity the computer with OC is identified as a new Mac by all sites/apps so you just need a moment of patience when restarting to insert iCloud password and give some permissions.

Worked like a charm!
Thanks

**Comment by hridoy43** [comment]
> @stevezhengshiqi finally i took courage :)
> 
> 1. deleted CLOVER and BOOT folders from EFI
> 2. copied OC and BOOT folder to EFI from XiaoMi_Pro-OC-v1.4.7.zip https://github.com/daliansky/XiaoMi-Pro-Hackintosh/releases/latest
> 3. Booted into Catalina and then installed Big Sur without issues.
> 
> Just for clarity the computer with OC is identified as a new Mac by all sites/apps so you just need a moment of patience when restarting to insert iCloud password and give some permissions.
> 
> Worked like a charm!
> Thanks

How did you upgrade from Catalina to big sur? can you guide me? won't it be upgradable via bootable USB? (actually, i have tried to clean install big sur from bootable USB but every time it stopped with a panic message after choosing to install macOs option)

**Comment by stevezhengshiqi** [comment]
@hridoy43 He has clearly listed out all the steps. You should not use Clover EFI to upgrade Big Sur, but use OpenCore EFI instead.

**Comment by d4ks39** [comment]
Is it safe nowdays with **Clover** EFI v1.5.2 to update from Calalina 10.15.7 to BigSur? Is the update process safe just like a normal macBook?

**Comment by stevezhengshiqi** [comment]
@d4ks39 Yes, but OC is a better way since Clover is using OC's kernel patcher.

**Comment by d4ks39** [comment]
Yesterday I gave a try to OC.. I have triple boot (macOS Catalina + Windows on one ssd, Linux on another) and with clover everything was perfect. When I switched to OC, I was only able to boot to macOS (luckily) and managed to revert the changes to go back to working triple boot with Clover.. This is my production laptop right now and I am "scared" to do anything risky.. That's why I am asking if it's safe to update directly to BigSur through Appstore with Clover EFI 1.5.2... I am just worried not to ruin everything.. Thanks
