### ISSUE TITLE
Sound lost after sleep

### ISSUE THREAD

**Issue by muzafferdede** [daliansky/XiaoMi-Pro-Hackintosh#490]
**State the model**
XiaoMi-Pro MX150

**State the version of the EFI**
v1.4.7

**Bootloader**
OC 

**Settings**
All default settings + SMBIOS 15,4 

**Describe the bug**
For some reason, when device is wake from sleep, it is fine for a while but then suddenly sound get lost, and only way to make it work again is, open system preferences/audio input tab then it works. if close system preferences, sound again get lost after few minutes. I faced this issue on some other builds as well but i remember it fixed using codecomender.kext. Since we also got that in the kext folder, not sure if there is something missing.

**Comment by stevezhengshiqi** [comment]
Did you install [ALCPlugFix](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/tree/master/ALCPlugFix)? You can run `sh -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/master/ALCPlugFix/one-key-alcplugfix.sh)"` in Terminal to install it. Remember to restart.

**Comment by muzafferdede** [comment]
Thanks for the answer. I haven't specifically install ALCPugFix but i thought it is all set by default. I just did install with the command you just give. Is there any way i can check if it fixed / applied? since it only happens after some amount time of sleep / wake so i can't really tell if it's fixed.

**Comment by stevezhengshiqi** [comment]
You can try running `launchctl list | grep goodwin` to check.

**Comment by muzafferdede** [comment]
Response is 1.
