### ISSUE TITLE
Big Sur installation problem

### ISSUE THREAD

**Issue by Remmed96** [daliansky/XiaoMi-Pro-Hackintosh#492]
Does anyone have problems installing Big Sur ? I can't update.

**Comment by ghondar** [comment]
i can't update to release candidate 2

**Comment by Remmed96** [comment]
How did you upgrade to big sur ?

**Comment by ghondar** [comment]
using opencore EFI

**Comment by stevezhengshiqi** [comment]
Please provide more information when creating an issue.

You need to add -v in `boot-args` of `/EFI/OC/config.plist` to boot in verbose mode and take a screenshot of the trouble.
Also, you can try deleting all the AirportItwm kexts under `/EFI/OC/Kexts/` since Intel Wi-Fi kexts are still not stable sometimes.

**Comment by Remmed96** [comment]
I have problem in upgradin from catalina to big sur.

**Comment by stevezhengshiqi** [comment]
I have said, it doesn't help by just saying "have problem". You need to provide troubleshooting to help solve the problem since no one knows what problems you have.

> You need to add -v in boot-args of /EFI/OC/config.plist to boot in verbose mode and take a screenshot of the trouble.

**Comment by kidaww** [comment]
I had a stupid problem when trying to upgrade from 10.15.5
Installed first 10.15.7 and then 11.0 and it worked.

**Comment by Remmed96** [comment]
> I had a stupid problem when trying to upgrade from 10.15.5
> Installed first 10.15.7 and then 11.0 and it worked.

I did exactly the same thing, installed (again) 10.15.7 and reset the NVRAM and succeeded in upgrading to Big Sur.

**Comment by p-uvarov** [comment]
I successfully updated to Big Sur using the latest release XiaoMi_Pro-OC-v1.4.7.zip. Please find the description below.
1. I used standard Software Update service on Mac OS to update to Big Sur. This leads me to an infinite loading loop after the update. I had CLOVER.
2. To fix this instead of XiaoMi_Pro-v1.4.7.zip I downloaded XiaoMi_Pro-OC-v1.4.7.zip from here:
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/releases
3. I deleted CLOVER and BOOT folder in the EFI partition and copy the new BOOT and OC folders to the EFI partition. I did it on Windows because I can't load Mac OS. Please find video instructions on how to it below:
https://www.youtube.com/watch?v=zx6HKkWequI&list=LL&index=10

I hope this would help.

**Comment by retsel89** [comment]
Hello, I just upgraded from Catalina to Big Sur, but I feel the system lagged, it is mounted on a Western Digital Green SSD, I don't know if it's any SSD problem but Catalina was OK, or is the intel HD 620 not supporting new Big Sur graphics

**Comment by Remmed96** [comment]
> Hello, I just upgraded from Catalina to Big Sur, but I feel the system lagged, it is mounted on a Western Digital Green SSD, I don't know if it's any SSD problem but Catalina was OK, or is the intel HD 620 not supporting new Big Sur graphics

Try to use NVME Fix from this repository, this is the link: https://github.com/acidanthera/NVMeFix

**Comment by stevezhengshiqi** [comment]
> > Hello, I just upgraded from Catalina to Big Sur, but I feel the system lagged, it is mounted on a Western Digital Green SSD, I don't know if it's any SSD problem but Catalina was OK, or is the intel HD 620 not supporting new Big Sur graphics
> 
> Try to use NVME Fix from this repository, this is the link: https://github.com/acidanthera/NVMeFix

NVMeFix is not related to the system lag. It only helps save power during sleep by enabling APST.

**Comment by Remmed96** [comment]
> > > Hello, I just upgraded from Catalina to Big Sur, but I feel the system lagged, it is mounted on a Western Digital Green SSD, I don't know if it's any SSD problem but Catalina was OK, or is the intel HD 620 not supporting new Big Sur graphics
> 
> > 
> 
> > Try to use NVME Fix from this repository, this is the link: https://github.com/acidanthera/NVMeFix
> 
> 
> 
> NVMeFix is not related to the system lag. It only helps save power during sleep by enabling APST.

Ah sorry I did not know, I thought it could help in these cases too.

**Comment by retsel89** [comment]
> Hello, I just upgraded from Catalina to Big Sur, but I feel the system lagged, it is mounted on a Western Digital Green SSD, I don't know if it's any SSD problem but Catalina was OK, or is the intel HD 620 not supporting new Big Sur graphics

Hello, any solution? Today I did a clean installation to rule out that it was a problem with the update on Catalina, I also did the clean installation on another SSD and the same lag problem continues.

**Comment by retsel89** [comment]
I don't know if this is the correct place for this issue, does anyone know why I can't install hackintoch on the original disk of the laptop, even if I try to format it or write to the Samsung (the original) the laptop reboots, and if I try to install Hack on the samsung does not boot, that is, it seems that it has no compatibility, the differences I see is that it detects the samsung as PCI-EXPRESS and the WD as SATA.
Thanks

**Comment by stevezhengshiqi** [comment]
@retsel89 Hackintosh install does not support PM981.

**Comment by retsel89** [comment]
> @retsel89 Hackintosh install does not support PM981. Clearly mentioned in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/FAQ#installation

Thanks, i dont see that.

**Comment by 19neo79** [comment]
> I successfully updated to Big Sur 11.0.1 using the latest release XiaoMi_Pro-OC-v1.4.7.zip. Please find the description below.
> 
> 1. I used standard Software Update service on Mac OS to update to Big Sur. This leads me to an infinite loading loop after the update. I had CLOVER.
> 2. To fix this instead of XiaoMi_Pro-v1.4.7.zip I downloaded XiaoMi_Pro-OC-v1.4.7.zip from here:
>    https://github.com/daliansky/XiaoMi-Pro-Hackintosh/releases
> 3. I deleted CLOVER and BOOT folder in the EFI partition and copy the new BOOT and OC folders to the EFI partition. I did it on Windows because I can't load Mac OS. Please find video instructions on how to it below:
>    https://www.youtube.com/watch?v=zx6HKkWequI&list=LL&index=10
> 
> I hope this would help.

Thank you very much for the solution. Great, now on my Xiaomi mi Notebook Pro I have Big Sur!!
