### ISSUE TITLE
Just a question for last release 

### ISSUE THREAD

**Issue by Remmed96** [daliansky/XiaoMi-Pro-Hackintosh#496]
What means Remove AAPL,slot-name to support HEVC on macOS11 ?

**Comment by larryare** [comment]
@Remmed96 Where is it written like that?

**Comment by Remmed96** [comment]
![Schermata 2020-11-14 alle 18 08 24](https://user-images.githubusercontent.com/44156733/99152808-653e3600-26a4-11eb-8b84-51a200fc8739.png)

Here

**Comment by kidaww** [comment]
Is it changelog or advice?)

**Comment by Remmed96** [comment]
It's in the release download page.
