### ISSUE TITLE
Help in converting from Clover to OC

### ISSUE THREAD

**Issue by paulzee09** [daliansky/XiaoMi-Pro-Hackintosh#497]
I know this is a stupid question but how can I convert to OC from Clover? Is it really just replacing folders? Thanks! I tried installing Bigsur but failed on first install and im scared to continue on, i have a fully working xiaomi mi notebook pro 2017 on catalina 10.15.7 and dont want to ruin it.

**Comment by stevezhengshiqi** [comment]
Yes, just replacing folders and add OC entry. Try to find information in past issues instead of creating new one. This is not a support forum.
