### ISSUE TITLE
Theme for OC

### ISSUE THREAD

**Issue by orhan-drsn** [daliansky/XiaoMi-Pro-Hackintosh#498]
Hi Guys,

I changed now from Clover to OC for Big Sur, but I don't like the theme from OC. 
Is it possible to get the same theme for OC "out of the box" or can someone tell me how to change?

Thanks in advise

**Comment by stevezhengshiqi** [comment]
You can change icon files in /EFI/OC/Resources/Image.

**Comment by orhan-drsn** [comment]
Is it possible to get this in OC as standard?
It looks more nicer then.

**Comment by stevezhengshiqi** [comment]
I am not sure what do you mean. The goal of OC is to stimulate real Mac’s boot picker, and that is the current OC theme.

**Comment by s-monti97** [comment]
I guess he would like to have on the OC efi the Xiaomi boot theme that clover has as default theme (that's what I need too). We can't swap to Clover efi, because big sur won't boot.

**Comment by matvada** [comment]
I found this repo that have a "Big Sur like" theme for icons, better than the default one:

https://github.com/blackosx/OpenCanopyIcons
As described by @stevezhengshiqi mount EFI and replace files in the folder indicated.

**Comment by s-monti97** [comment]
> I found this repo that have a "Big Sur like" theme for icons, better than the default one:
> 
> https://github.com/blackosx/OpenCanopyIcons
> As described by @stevezhengshiqi mount EFI and replace files in the folder indicated.

That's what I was looking for, I can't thank you enough. Now my boot just looks like the clover EFI version with xiaomi theme. I used set 4 > White_Plain and I've replaced cursor, selector, selected and harddrive.

![photo_2020-11-23_15-11-53](https://user-images.githubusercontent.com/29657457/99972495-de254800-2d9e-11eb-9b82-d5c949790ec2.jpg)

**Comment by stevezhengshiqi** [comment]
People actually can change to whatever they like by redesigning images under /EFI/OC/Resources/Image. I don't think is an issue, but related to user preference.
