### ISSUE TITLE
Glitch and lag after Big Sur update (OC EFI)

### ISSUE THREAD

**Issue by s-monti97** [daliansky/XiaoMi-Pro-Hackintosh#500]
Hi,
I've updated macOS Big Sur from catalina 11.15.7 with success. I'm using OC Efi, because mac os won't start without it. This efi is causing glitches and lag everywhere, is there any solutions? Thanks!

**Comment by stevezhengshiqi** [comment]
Unfortunately, there's nothing we can do on this repository. What I can do is to retrieve the latest OpenCore and WhateverGreen everytime when updating EFI. For professional graphics support, you can report to https://github.com/acidanthera/bugtracker with detailed logs, but I am afraid that’s it for UHD620 as a low performance graphics card.

**Comment by s-monti97** [comment]
I understand. What I noticed is that the os is "stable" after two minutes

**Comment by stevezhengshiqi** [comment]
They are the same, using the same kext list.
