### ISSUE TITLE
Stuck On Boot Occasionally on Big Sur

### ISSUE THREAD

**Issue by Cr0wTom** [daliansky/XiaoMi-Pro-Hackintosh#502]
Hello Everyone and thanks for the good work. After updating to Big Sur everything works except for Bluetooth... It seems like it is turned on but the turn off button isn't working.

I have the Xiaomi Pro MX150, I tried to rebuild the kext cache and I am on latest OC with latest settings... Also, once every 3 boots or so, I am stuck on boot screen which I guess it's because of the kext.

**Comment by stevezhengshiqi** [comment]
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/494#issuecomment-727201222

**Comment by stevezhengshiqi** [comment]
> Also, once every 3 boots or so, I am stuck on boot screen which I guess it's because of the kext.

Happens on mine too. Not sure which kext cause the problem. It would help if you can find out.

**Comment by stevezhengshiqi** [comment]
Solved by https://github.com/OpenIntelWireless/itlwm/commit/d9bd8d435b80c009c928156ef805e14b2a527fd7. Also please attach a screenshot with -v boot-args next time when reporting an issue.
