### ISSUE TITLE
Webcam low light

### ISSUE THREAD

**Issue by macca0612** [daliansky/XiaoMi-Pro-Hackintosh#503]
Hi, I have installed Catalina 10.15.7 on my Xiaomi mi notebook pro, everything's work fine, except for the webcam that is darker then normal, with low light in windows work fine, but here the image is dark, and I have not find any option to solve this.
I have see that https://phoboslab.org/log/2009/07/uvc-camera-control-for-mac-os-x another user make a took to change camera settings, but I can not run it in Catalina.

Xiaomi mi notebook pro 
i7 8550U
16gb
Clover EFI 1.4.7

Thank you

**Comment by stevezhengshiqi** [comment]
Duplicate as https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/357
