### ISSUE TITLE
USB issues when using Xcode

### ISSUE THREAD

**Issue by Speedymax02** [daliansky/XiaoMi-Pro-Hackintosh#504]
Hi,

I would like to develop iOS apps with Xcode. Because of your project it is not necessary for me to buy a new Mac. Thanks!
Unfortunately, I have not been able to solve a problem so far, I hope that you can help me.
When I connect my iPhone to my notebook via the USB C port, it is also recognized by Xcode. When I run an app, I always get the following error message after "Build Succeeded": "iPhone is not available. Please reconnect the device."
I have the same problem when I connect my iPhone to a USB A port. Are there any drivers that I need to install before the USB ports work properly?

Thanks

**Comment by stevezhengshiqi** [comment]
I don’t think it is an USB problem. Please update your Xcode version and restart iPhone. I also see lots of similiar questions on Google.

**Comment by Speedymax02** [comment]
Hello,

Thank you for your prompt reply. You were right, after I reinstalled Xcode everything worked.

Thank you!
