### ISSUE TITLE
Slow bluetooth mouse when uploading 

### ISSUE THREAD

**Issue by matvada** [daliansky/XiaoMi-Pro-Hackintosh#506]
Hello, i encountered a strange problem:
While uploading files to WeTransfer the mouse pointer is very slow. At the end of the transfer, everything returns to normal functioning.

I'm on EFI v1.4.7 and i use Apple Magic Mouse Bluetooth with internal bluetooth option and without usb Wifi dongle. 

Thank you

**Comment by stevezhengshiqi** [comment]
Please report to Intel BT driver issue page. https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues

**Comment by campiotto** [comment]
I have this problem too, did you find a solution?
