### ISSUE TITLE
Can't connect to the iPad air3 with USB

### ISSUE THREAD

**Issue by smallred-010102** [daliansky/XiaoMi-Pro-Hackintosh#507]
当我把ipad连上电脑后，我在访达里能看见1-2秒的ipad栏，然后立马断连，再次插拔也无效，只有每次关机重启第一次插才有一小会儿的反应，但始终连接不上。同时我把鼠标接收器重新插拔后，也偶尔出现usb无法使用的情况，关机重启后正常。

**Comment by stevezhengshiqi** [comment]
没有提供足够信息，请说明EFI版本和机型。

确保使用的是v1.4.7 EFI release，更新EFI的时候需要删除原本的BOOT和OC文件夹再复制进新的。更新完EFI还需要重建缓存重启（在终端运行 `sudo kextcache -i /`）

**Comment by stevezhengshiqi** [comment]
关闭因没有提供足够信息且没有回复。
