### ISSUE TITLE
clover转oc后开机到一半出现禁止图标

### ISSUE THREAD

**Issue by dddkyi** [daliansky/XiaoMi-Pro-Hackintosh#508]
大家好，抱歉打扰大家了，我之前一直在用clover的引导方式进入黑苹果系统，最近想转成OC方式，但是更改efi之后开机时就会出现一个圆形的禁止图标，换回clover之后也会出现同样的问题，现在无法进入系统，想麻烦问一下大家这种情况应该怎么办，谢谢大家！
我的系统：小米笔记本pro 15.6‘’ 8g 256g 黑苹果系统安装在新加的惠普ssd上

最后感谢作者daliansky 费心费力更新efi 感谢！

**Comment by dddkyi** [comment]
我在更换efi之前，对系统从15.7打算升级到big sur系统，但是升级时一直重启，并没有升级成功，不知道是不是和这个有关系，感谢大家！

**Comment by stevezhengshiqi** [comment]
@dddkyi 换OC的时候需要阅读[README](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/README_CN.md#opencore)里的步骤。要注意以下几点：
- 确保 BOOT 和 CLOVER文件夹备份并删除，然后复制进OC包里的 BOOT 和 OC 文件夹，不要漏掉更新 BOOT 文件夹
- 使用 OC 后需要 Reset NVRAM，在 OpenCore 启动界面按下 空格，选中进入 Reset NVRAM

**Comment by dddkyi** [comment]
> @dddkyi 换OC的时候需要阅读[README](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/README_CN.md#opencore)里的步骤。要注意以下几点：
> 
> * 确保 BOOT 和 CLOVER文件夹备份并删除，然后复制进OC包里的 BOOT 和 OC 文件夹，不要漏掉更新 BOOT 文件夹
> * 换成 OC 后需要 Reset NVRAM，在 OpenCore 启动界面按下 空格，选中进入 Reset NVRAM

感谢您的回复！我在重新更换oc之后遇到了同样的问题，不知道能不能麻烦您看一下我的操作步骤，谢谢您！
pre：我的电脑有两块硬盘，自带的硬盘（disk0）装有windows 系统，新加的硬盘（disk1）装有黑苹果系统。
我的步骤：
1、进入PE系统，打开DiskGenius软件，进入disk1的EFI(0)分区，选中EFI文件夹，右键“强制删除”；
2、将release中最新版本efi XiaoMi_Pro-OC-v1.4.7中的EFI文件夹复制到桌面上，然后以拖拽方式复制到disk1的EFI(0)文件夹；
3、由于我之前在调试过程中将disk0,也就是Windows系统盘中的启动程序进行了更换，所以在更换disk1中efi之后，进入disk0中SYSTEM(0)分区的EFI文件夹，使用 XiaoMi_Pro-OC-v1.4.7中EFI文件夹中BOOT和OC文件夹替换原有相应文件夹；
4、重启电脑，在OC启动页面按空格键，清空NVRAM；
5、重启电脑，点击Macintosh，系统仍旧出现禁止标志，无法启动。

写的很长，如果您愿意花时间看完的话，很感谢您！

**Comment by stevezhengshiqi** [comment]
@dddkyi 没看明白，你的操作过于繁琐，原本只用在mac系统里删除再复制的操作不用扩展得这么复杂。

找到正在使用的EFI分区，找不到的话把两块硬盘的EFI分区的BOOT和CLOVER文件夹删除，然后复制进BOOT和OC文件夹

这个问题很显然是用户操作问题，先关闭了。
