### ISSUE TITLE
External monitor over HDMI

### ISSUE THREAD

**Issue by Neolo** [daliansky/XiaoMi-Pro-Hackintosh#51]
When connecting external monitor, internal goes dark and never comes back, but picture shows on external. If you disconnect HDMI and reconnect it back, it goes no signal as well. Only forceful reboot is a way out.

**Comment by stevezhengshiqi** [comment]
Hi, many people have this problem and a temporary solution is to close the lid and reopen it after connecting HDMI. I haven't found a perfect solution yet because this problem hasn't happened on me. I think the problem may related to pipe, and I will test when I get home.

**Comment by Neolo** [comment]
Thank you. Unfortunately lid doesn't do anything either, had to reset the laptop.
I can't change the frequency, it's locked to 60.

**Comment by stevezhengshiqi** [comment]
Did you open the HiDPI, maybe that's the reason of the lock.

**Comment by Neolo** [comment]
I don't any HIDPI at all

**Comment by feiweiwei** [comment]
你好，我开了HIDPI，外接显示器黑屏问题有所缓解，盒盖再开盖一般都能解决，但是电脑休眠后再唤醒，外接屏幕就一直黑的，不管用什么办法都不行，只能把hdmi再拔了重插才行，这个有解决办法吗？

**Comment by stevezhengshiqi** [comment]
@feiweiwei 更新最新版EFI即可。
For more specific details, please visit https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/117
