### ISSUE TITLE
Clover BigSur 启动界面windows 图标损坏 ｜ 能否隐藏第三个图标

### ISSUE THREAD

**Issue by lulafun** [daliansky/XiaoMi-Pro-Hackintosh#511]
[点击查看图片](https://s3.jpg.cm/2020/12/09/ETyfz.jpg)

使用的是 XiaoMi NoteBook Pro EFI v1.4.8
12-7-2020

1、Clover 引导 BigSur，启动界面 windows 图标损坏，已经确认是**CLOVER**目录下 **CLOVERx64.efi**文件问题

2、启动系统需要选择 ~ via Preboot 来引导 Big Sur（使用的是第**二**个图标），能否隐藏第**三**个图标“Boot macOS from ...”

**Comment by stevezhengshiqi** [comment]
1. 确保你使用的是release里的小米主题，更新EFI的时候必须是删除旧的BOOT和CLOVER文件夹，然后复制进新的，不能覆盖。本仓库的小米主题图标已经针对新版CLOVER做了优化。

2. 这是Clover的已知bug，我在README里也注明了（https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/README_CN.md#clover）。请关注Clover对这个问题的动态https://github.com/CloverHackyColor/CloverBootloader/issues/315。本仓库只使用Clover，而不而不负责开发。
