### ISSUE TITLE
random restarts with reale v1.4.8 and Big Sur

### ISSUE THREAD

**Issue by Parziivall02** [daliansky/XiaoMi-Pro-Hackintosh#512]
Hi, after upgrading to MacOS Big Sur and updating the EFI to version 1.4.8, my Xiaomi My Notebook Pro randomly restarts after a power-up time. I leave the EFI folder I am using.
[EFI copy.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/5664685/EFI.copy.zip)

**Comment by stevezhengshiqi** [comment]
@Parziivall02 Please attach restart log. When restarts, a windows about "Your computer was restarted because of a problem" will appear, click `Report` and attach the log to help find the problem.

**Comment by stevezhengshiqi** [comment]
After a glimpse of your config, I found so many major changes that are not expected. Please use the original config.plilst and never edit it with Clover Configurator.app, the app will break the file.
