### ISSUE TITLE
使用1.4.8版本从10.15.7更新到big sur 失败问题反馈

### ISSUE THREAD

**Issue by dougzhaug** [daliansky/XiaoMi-Pro-Hackintosh#515]
本人之前从10.14+到10.15.7每次更新都很顺利（感谢大神的无私奉献）。但这次却掉坑了，原系统是10.15.7 efi是1.4.8 使用的是mac的自动更新，重启了一次以后安装读条走到三分之一的位置时跳出下面的提示，我使用的时原装intel的wifi。
![微信图片_20201212104421](https://user-images.githubusercontent.com/36411451/101970711-0817af00-3c67-11eb-9f47-ebd048eb89ec.jpg)

**Comment by stevezhengshiqi** [comment]
镜像损坏，重新下载镜像更新。

**Comment by dougzhaug** [comment]
> 彻底损坏，重新下载常规更新。

之前的系统已经没有了，只有这一个系统和win10了，如何重新下载呢？我还想保存之前的数据呢，求大神支招

**Comment by stevezhengshiqi** [comment]
@dougzhaug 请检查你的浏览器配置，你引用的不是我的原话。

> 之前的系统已经没有了，只有这一个系统和win10了

开机选系统的时候不要选Install即可进入原本系统正常使用，如果无法进入原本系统，使用U盘刻录一个Big Sur镜像来安装即可。只要不抹盘，所有数据都会保留。

**Comment by dougzhaug** [comment]
> @dougzhaug 请检查你的浏览器配置，你引用的不是我的原话。
> 
> > 之前的系统已经没有了，只有这一个系统和win10了
> 
> 开机选系统的时候不要选Install即可进入原本系统正常使用，如果无法进入原本系统，使用U盘刻录一个Big Sur镜像来安装即可。只要不抹盘，所有数据都会保留。确保下载的镜像是没有corrupt的。

开机已经不显示原来的系统了，只能用后面的U盘方法了，有具体的操作文章吗？能给一个连接最好！本人系统小白，第一次吃黑果见谅

**Comment by stevezhengshiqi** [comment]
和首次安装系统教程一样啊。https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/安装

**Comment by dougzhaug** [comment]
> 和首次安装系统教程一样啊。[https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/安装](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/%E5%AE%89%E8%A3%85)

万分感谢！大神威武。回复太及时了

**Comment by stevezhengshiqi** [comment]
更多安装问题可在QQ群里询问，仓库里不解答安装问题。
