### ISSUE TITLE
My touchpad can be used, but I can’t find the touchpad in the settings

### ISSUE THREAD

**Issue by binbin5261** [daliansky/XiaoMi-Pro-Hackintosh#516]
My touchpad can be used, but I can’t find the touchpad in the settings
xiaomi pro 15.6 i7 8550U 
EFI: oc 1.4.8
os :  11.0.1

**Comment by stevezhengshiqi** [comment]
@binbin5261 1. Make sure u use the latest EFI release completely.

2. Trackpad settings also need battery percentage working.

**Comment by stevezhengshiqi** [comment]
Closes as it's a user side issue.
