### ISSUE TITLE
no big sur 11.1 update

### ISSUE THREAD

**Issue by superhero75** [daliansky/XiaoMi-Pro-Hackintosh#519]
**State the model**
**阐述您的机型**
XiaoMi-Pro MX150

**State the version of the EFI**
**阐述您的EFI版本**
 v1.4.8

**Describe the bug**
**描述您遇到的问题**
- A clear and concise description of what the bug is.
- 清晰并详细地描述问题所在。
macos doesnt show the new 11.1 update

**Comment by stevezhengshiqi** [comment]
Open AppStore and search Big Sur.
