### ISSUE TITLE
pre release makefile issue

### ISSUE THREAD

**Issue by kampav** [daliansky/XiaoMi-Pro-Hackintosh#521]
Hi @stevezhengshiqi, Hope you are well. I am getting the below error while running the command ./makefile.sh --PRE_RELEASE=OC. Do you know what the issue is as its started happening recently.

![image](https://user-images.githubusercontent.com/31815827/102917034-68cf9480-447c-11eb-88f5-75bd02ab38ec.png)

**Comment by stevezhengshiqi** [comment]
@kampav The error you met is because the author hasn’t published any release for [RestrictEvent](https://github.com/acidanthera/RestrictEvents/releases) yet. It will be good after Acidanthera‘s January release.

**Comment by stevezhengshiqi** [comment]
BTW, command `./makefile.sh --NO_GH_API --PRE_RELEASE=Kext --PRE_RELEASE=OC` is better to grab the latest release.

**Comment by kampav** [comment]
Thanks @stevezhengshiqi
