### ISSUE TITLE
NOT an issue, but a help request!

### ISSUE THREAD

**Issue by profzei** [daliansky/XiaoMi-Pro-Hackintosh#522]
@stevezhengshiqi 
Sorry to bother you, but I'm trying to replicate/imitate your SSDT-USB for my machine which is a HUAWEI Matebook X Pro 2018 (my [repo](https://github.com/profzei/Matebook-X-Pro-2018))...
I almost succeeded in my intent: all USB ports are recognized correctly... except one (mine HS05 which is an internal port for Bluetooth device which is btw the same as yours) that only works properly after a sleep/wake process... 
Before sleep the bluetooth icon appears in menubar to be gray and crossed out while after wake up it is white as always... I think it is a "power" problem so I would like to analyze the dumping of the DSDT and all the original SSDT of your XIAOMI machine Pro...
Please, could you share with me your original DSDT and related SSDTs?
Thank you in advance!

**Comment by stevezhengshiqi** [comment]
@profzei Sure, I am happy to share XIaomi's whole ACPI table. However, I don;t think it's an ACPI issue, but more like a driver issue from IntelBluetoothFirmware.
[Xiaomi-Pro ACPI.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/5759552/Xiaomi-Pro.ACPI.zip)

**Comment by profzei** [comment]
@stevezhengshiqi Thank you very much! I found a way to manage the presence of a device (BT01) that I had never seen before! Many thanks again for your kind availability!
