### ISSUE TITLE
Dual boot problem - instant boot to WIN

### ISSUE THREAD

**Issue by macguru341** [daliansky/XiaoMi-Pro-Hackintosh#525]
Hello
I woke up this morning and turned on the laptop and it booted straight into windows.
I have single drive contain WiN10 and Mac OS X with open core.
When I go into bios I have there only the windows partition .
How can I fix it?
Thanks

**Comment by stevezhengshiqi** [comment]
Add OpenCore boot entry, just like what you did when you first install macOS.
