### ISSUE TITLE
Questions related to uuid after updating OC

### ISSUE THREAD

**Issue by Nirnturt** [daliansky/XiaoMi-Pro-Hackintosh#528]
Hi, I noticed that you mentioned something about windows activation failure in the OpenCore related notes. After updating the efi by replacing the oc and boot folders, my mac app (Surge) also has an activation failure problem.
- Is this also a problem caused by OC update uuid?
- Can I solve the above problem by backing up the original mac uuid and filling in the configuration file in subsequent updates?

Thank you for your work.

**Comment by stevezhengshiqi** [comment]
Yes, you also have to update your MLB, SystemSerialNumber, and SystemUUID when updating EFI.

**Comment by Nirnturt** [comment]
Thank you for your answer
