### ISSUE TITLE
Problem after set DVMT to 64mb 

### ISSUE THREAD

**Issue by kanekifont** [daliansky/XiaoMi-Pro-Hackintosh#529]
Hi, i have a Xiaomi TM1701, with Big Sur and the last release of OC EFI. 
I change the resolution with one-key-hidpi, and i follow the guide for DVMT and 0xE2 fix.
But when i boot to macOs the logo appears but the screen remains black.
Idk what to do or how to look for the problem. it's my first hackintosh.
Thanks

**Comment by stevezhengshiqi** [comment]
It seems like the dvmt scripts are not working. You need to reverse changes in config.plist.
Better to attach screenshot of the dvmt scirpts.

**Comment by kanekifont** [comment]
ok, how can i change the config.plist from opencore boot menu?
Should i post the screenshot of cmd after runned DVMT_set.cmd, CFG_unlock.cmd ecc.. ?

**Comment by stevezhengshiqi** [comment]
@kanekifont You may need to change it in Windows, PE, or other OS. 

> Should i post the screenshot of cmd after runned DVMT_set.cmd, CFG_unlock.cmd ecc.. ?

Yeah, I recommend to re-run these scripts and watch for any error message.

**Comment by kanekifont** [comment]
I re-run the scripts and now i can boot on macOs. But font they look very grainy, idk maybe i chose the wrong settings for one-key-hidpi. 
<img width="580" alt="Schermata 2021-01-23 alle 14 14 41" src="https://user-images.githubusercontent.com/61090448/105579222-77fc7780-5d85-11eb-99df-99487232c433.png">
And for the last i chose option "2"
These are the ones I put on. 
could you explain to me the other options? Thanks

**Comment by stevezhengshiqi** [comment]
> But font they look very grainy

Yes, that's a known problem for macOS on 1080p screen. Modern macOS is unfriendly to low resolution screen, and there are no solution for that.
