### ISSUE TITLE
macOS Big Sur 11.1 update doesn't appear

### ISSUE THREAD

**Issue by adri-m173** [daliansky/XiaoMi-Pro-Hackintosh#530]
When I try to check system updates, it says that I have the Mac updated to the latest version (macOS 11.0.1), and I don't know how to update to macOS 11.1.
I have the latest release of EFI on my Xiaomi Mi Notebook Pro.

**Comment by stevezhengshiqi** [comment]
Open AppStore and search Big Sur.
