### ISSUE TITLE
External Monitor will not be Activated after Sleep

### ISSUE THREAD

**Issue by schenkxx** [daliansky/XiaoMi-Pro-Hackintosh#532]
**Pre-requirement**
**前提条件**
After updated the OC to the latest version available now, the external monitor I use maintains off when the laptop is waked by mouse or keyboard. The built-in monitor will flash for few times when it's being awaked, just like I unplug the HDMI cable, and the external monior will not respond.

**State the model**
**阐述您的机型**
XiaoMi-Pro MX250

**State the version of the EFI**
**阐述您的EFI版本**
- v1.5.1
 
**Describe the bug**
**描述您遇到的问题**
The external monitor will not be activated with the built-in one when it's awaked after sleep.

If there is anything else needed, I can help add it. Thank you so much!

**Comment by stevezhengshiqi** [comment]
@schenkxx That’s a known issue and you can update the latest config to solve this problem. The drawback is you have to reopen the lid when you first plug in.

**Comment by schenkxx** [comment]
Hi, thank you so much for your response!

So I have another immature and rookie question... so if I have to update the config.plist, I will lost the serial number (and other properties)😂 I think there is a procedure to “carve” these information, but I’m too afraid to ask, so every time I update OC(following the guidance, replacing the whole folders with the new one) I have to re-fake the hackintosh. Could you please tell me what to do?🧎‍♂️🙇‍♂️

**Comment by stevezhengshiqi** [comment]
You can use Text Editor or any other plist editor to copy MLB, SystemSerialNumber and SmUUID and paste them to the corresponding place in the new config.

**Comment by schenkxx** [comment]
Hi, thank you again and it's me again.

I am not sure whether I am doing this right: so I have updated the cofig.plist and the properties of my device are well-attahced, but the external monitor will not be lit up. I tried reopening the lid with the hdmi cable already plug-in, but the external monitor stays dark. 

I also tried: close the lid and the laptop sleeps, then I plug in the hdmi cable, open the lid, the monitor was not lit up still.

Would you mind specifying the meaning of "reopen the lid when you first plug in" memtioned by you 17 hours ago? Thanks a lot! 🙏

**Comment by stevezhengshiqi** [comment]
It’s in README, “ You have to re-plug it, or close the lid for about five seconds and reopen the lid”

Re-plug is an alternative choice.

**Comment by stevezhengshiqi** [comment]
Already fixed.
