### ISSUE TITLE
Question about config

### ISSUE THREAD

**Issue by Mateo1234454545** [daliansky/XiaoMi-Pro-Hackintosh#534]
Can you tell me what "reg-ltrovr" key in config.plist is about?

**Comment by stevezhengshiqi** [comment]
It's about Latency Tolerance Reporting, and commonly injected in Apple's DSDTs under PCI devices. Ref: https://www.insanelymac.com/forum/topic/320561-enable-iopcifamily-to-set-tolerance-latency-for-pci-devices/
