### ISSUE TITLE
OC Boot entry disappeared after upgrade to v1.52

### ISSUE THREAD

**Issue by msr1715** [daliansky/XiaoMi-Pro-Hackintosh#537]
**State the model**
XiaoMi-Pro MX150

**State the version of the EFI**
 v1.52
On MacOS11

**Describe the bug**
After upgrading from v1.51 to 1.52 as always do I am only able to boot on linux now, tried mounting the EFI and redoing the process without editing anything from the release but still missing OpenCore as boot entry.

**Attach your entire EFI folder**
Same as release now.

Is it a known error or did I miss something?
I upgraded as usual, removing all AirportItlwm sections of config.plist that are not BigSur and rebooted to find no OC entry for boot.

**Comment by stevezhengshiqi** [comment]
Yes, you need to re-add OpenCore entry as they removed Bootstrap and replaced with `LauncherOption`. Also, it is an intended behavior according to https://github.com/acidanthera/bugtracker/issues/1222#issuecomment-739241310. When upgrading from OC version lower than v0.6.4, users have to disable BootProtect and reset NVRAM, which will delete the OC boot entry.

**Comment by msr1715** [comment]
To read OpenCore entry you mean with the efibootmgr -c from my linux?

**Comment by stevezhengshiqi** [comment]
I am not sure how it works on Linux, but it's the same thing when you first install macOS and add OpenCore boot entry.
