### ISSUE TITLE
Wireless does not work if I install an update release higher than EFI v1.4.7. 

### ISSUE THREAD

**Issue by kitenko** [daliansky/XiaoMi-Pro-Hackintosh#539]
Can you please tell me what the problem is? 
I have i7-8550U Processor configuration.

**Comment by stevezhengshiqi** [comment]
Please read README, it says

> r5127 do not support Intel Wi-Fi on macOS version < Big Sur due to incomplete ForceKextsToLoad functionality (Only v1.4.7 supports Intel Wi-Fi on old macOS versions, or you can add IO80211Family.kext to the kext folder)

You have to use OC to drive Intel Wifi on Catalina, or you can update to Big Sur to enjoy Intel Wifi with Clover.

**Comment by kitenko** [comment]
Thank you very much!!!!

пн, 8 февр. 2021 г. в 20:54, Steve Zheng <notifications@github.com>:
