### ISSUE TITLE
Replacing itlwm.kext with Airportitlwm.kext

### ISSUE THREAD

**Issue by d4ks39** [daliansky/XiaoMi-Pro-Hackintosh#540]
Hi all,
I am running currently macOS Catalina 10.15.7 with Clover bootloader. I am interested in switching from itlwm.kext to  Airportitlwm.kext in order to use native Airport WiFi menu, Location services etc.. I read [this](https://openintelwireless.github.io/itlwm/Installation.html#airportitlwm) installation guide but there aren't many details available. Tried to simply replace the itlwm.kext with AirportItlwm.kext in CLOVER/kexts/Other but no luck. Is there anyone who tried it and has an opinion about it?
Thanks in advance!

**Comment by stevezhengshiqi** [comment]
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/539
