### ISSUE TITLE
Doesn't boot on OC

### ISSUE THREAD

**Issue by vcombey** [daliansky/XiaoMi-Pro-Hackintosh#542]
I tried to do a dual boot windows / macos on my xiaomi notebook pro 2020. It boot on OC when I branch the USB stick. But It directly boot on windows if I don't. I don't clearly understand what to be able to boot without the key. I followed the 2 videos tutorials, and that: https://dortania.github.io/OpenCore-Post-Install/universal/oc2hdd.html.
What I don't understand is that after mounting the efi partition of my harddrive I got that: 
![Screenshot 2021-02-15 at 21 49 38](https://user-images.githubusercontent.com/23608875/107991870-cb09c900-6fd7-11eb-9b66-9bfc6e82134b.png) I am no seeing an APPLE as in the documentation. Why ?

**Comment by stevezhengshiqi** [comment]
You don't need the APPLE folder, it's only effective for Apple computer.
Please read README, you need to replace BOOT and OC folders downloaded from the release page.

This repository is only for post-installation issues.

**Comment by vcombey** [comment]
Ok thanks, but I did that, and it doesn't work, where can I post the issue ?

**Comment by vcombey** [comment]
sorry for not being clear enough, It put the BOOT and OC folders and It still boots directly on windows

**Comment by stevezhengshiqi** [comment]
You need to add an OC boot entry by using BOOTICE mentioned in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/Installation or any other boot management apps.
