### ISSUE TITLE
Wifi bug

### ISSUE THREAD

**Issue by vcombey** [daliansky/XiaoMi-Pro-Hackintosh#543]
the wifi works 1/20 times. When I chose the network I constantly ask the password or it disconnects from the network directly or it keeps trying for 2 minutes. When it finally succeeds in connecting, after 30 minutes of hard try, it works well, but when the xiaomi goes to sleep, it disconnects from the network and I have to restart trying.

I didn't do anything to configure wifi
It isn't really clear if I have to do anything from the doc?
I have the 2020 version with core i7

**Comment by stevezhengshiqi** [comment]
Please report to https://github.com/OpenIntelWireless/itlwm for any WiFi issues. This repository only uses the drivers but not develop them.
