### ISSUE TITLE
APP store 无法检测到APP更新

### ISSUE THREAD

**Issue by HouWin** [daliansky/XiaoMi-Pro-Hackintosh#547]
机型：小米PRO GTX
EFI版本：Clover-v1.5.2
问题：APP store 无法检测到APP更新，点击APPstore 里的更新，显示所有APP已经是最新版，但APP明显是旧版本

**Comment by stevezhengshiqi** [comment]
此Issue界面只接受EFI相关问题，使用问题可使用搜索引擎。如果不显示更新，点击去具体的app界面即可出现更新按钮。

**Comment by HKMV** [comment]
> 机型：小米PRO GTX
> EFI版本：Clover-v1.5.2
> 问题：APP store 无法检测到APP更新，点击APPstore 里的更新，显示所有APP已经是最新版，但APP明显是旧版本

我记得上面菜单里面有个，什么刷新功能，更新一下列表就好了。

**Comment by HouWin** [comment]
> > 机型：小米PRO GTX
> > EFI版本：Clover-v1.5.2
> > 问题：APP store 无法检测到APP更新，点击APPstore 里的更新，显示所有APP已经是最新版，但APP明显是旧版本
> 
> 我记得上面菜单里面有个，什么刷新功能，更新一下列表就好了。

好的，谢谢老哥

**Comment by HouWin** [comment]
> 此Issue界面只接受EFI相关问题，使用问题可使用搜索引擎。如果不显示更新，点击去具体的app界面即可出现更新按钮。

好的，麻烦了，谢谢！
