### ISSUE TITLE
Not possible to login Apple ID (ICLOUD_UNSUPPORTED_DEVICE)

### ISSUE THREAD

**Issue by orhan-drsn** [daliansky/XiaoMi-Pro-Hackintosh#548]
It's not possible to login in Apple ID in settings after updating to 1.5.3 OC.

I allways got the message ICLOUD_UNSUPPORTED_DEVICE after login.

**Comment by stevezhengshiqi** [comment]
You need to set serial numbers in config.plist.  https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/412#issuecomment-650790417

**Comment by orhan-drsn** [comment]
I already added in config.plist and still getting this error
![config](https://user-images.githubusercontent.com/47851919/109768036-ac6f1900-7bf8-11eb-8ec4-89ba25402cbb.png)

**Comment by orhan-drsn** [comment]
> You need to set serial numbers in config.plist. [#412 (comment)](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/412#issuecomment-650790417)

can we please reopen?

**Comment by stevezhengshiqi** [comment]
You didn't add serial numbers in the config.plist. (MLB/SystemSerialNumber/smUUID)

**Comment by stevezhengshiqi** [comment]
> > You need to set serial numbers in config.plist. [#412 (comment)](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/412#issuecomment-650790417)
> 
> can we please reopen?

It's a user configuration problem.

**Comment by adeniji57** [comment]
@stevezhengshiqi I'm having the same issue and I have put in the serial numbers.

**Comment by stevezhengshiqi** [comment]
@adeniji57 You can try injecting ROM (mac address) and also do a nvram reset.

**Comment by adeniji57** [comment]
> @adeniji57 You can try injecting ROM (mac address) and also do a nvram reset.

I have already tried an NVRAM reset but the issue still persisted. Is there any possibility that it could be caused by me not having any en0?

**Comment by adeniji57** [comment]
> @adeniji57 Did you inject ROM? Also, you might need to change MAC address in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/main/ACPI/Shared/Source/SSDT-RMNE.dsl#L13

Which network device should o take the MAC address from?

**Comment by stevezhengshiqi** [comment]
Use a random mac address is good. It's just a spoof network device on en0.

**Comment by adeniji57** [comment]
I mean which network should I use for the ROM?

**Comment by stevezhengshiqi** [comment]
Whatever, it does not matter a lot.

**Comment by adeniji57** [comment]
> Whatever, it does not matter a lot.

I wiped my NVRAM a few times and now I'm able to log in. Thank You. It's restoring my iCloud folders rn. I'll let you know how it goes.
