### ISSUE TITLE
使用AirPods语音时不能正常使用

### ISSUE THREAD

**Issue by Notobey** [daliansky/XiaoMi-Pro-Hackintosh#551]
**State the model**
**阐述您的机型**
- e.g. XiaoMi-Pro Intel i7 8th MX250 10.15.7

**State the version of the EFI**
**阐述您的EFI版本**
- e.g v1.4.7

**Describe the bug**
**描述您遇到的问题**
- A clear and concise description of what the bug is.
- 清晰并详细地描述问题所在。
在使用AirPods与对方进行语音（腾讯会议，微信等软件）时，不能听到对方说话，对方也不能听到自己说话。请问一下有什么办法可以解决

**Comment by stevezhengshiqi** [comment]
IntelBluetoothFirmware 蓝牙驱动问题，不属于本仓库范畴，请前往 https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/180 来寻求帮助。Intel 蓝牙bug很多，寻求完美体验请更换白果网卡。
