### ISSUE TITLE
Trackpad not working in OpenCore boot menu

### ISSUE THREAD

**Issue by SimonCaignart** [daliansky/XiaoMi-Pro-Hackintosh#552]
XiaoMi-Pro MX150 TM1707

EFI v1.5.3

My trackpad is not working when I'm on the boot picker of OpenCore, is it normal ? Keyboard and Mouse are working great.

Thanks :)

**Comment by stevezhengshiqi** [comment]
Yes, it's normal. Trackpad won't work on bootpicker, and you might want to report this issue to https://github.com/acidanthera/bugtracker.
