### ISSUE TITLE
关于原装WiFi频繁断开的问题

### ISSUE THREAD

**Issue by dougzhaug** [daliansky/XiaoMi-Pro-Hackintosh#556]
**Pre-requirement**
**前提条件**
- Try to rebuild the kextcache and restart whenever you encounter a problem. It always works like a charm!
- 请在遇到任何问题时，先重建缓存并重启。它通常能修复99%的问题！
- To rebuild the kextcache, run `sudo kextcache -i /` in `Terminal.app`.
- 在`终端.app`运行命令`sudo kextcache -i /`来重建缓存。

**State the model**
**阐述您的机型**
- XiaoMi-Pro GTX

**State the version of the EFI**
**阐述您的EFI版本**
- v1.5.3

**Describe the bug**
**描述您遇到的问题**
- A clear and concise description of what the bug is.
- 清晰并详细地描述问题所在。

本人使用的是原装wifi，但总是很不稳定，电脑锁屏后，输入密码进入后wifi会自动断开，而且需要多次开关wifi，才有可能链接上。还有就是长时间阅读网页（大概5-10分钟）后点击下一页后也会出现wifi断开的问题。想了解这个是我个人的问题还是普遍问题，有没有补救办法？
还存在一个问题，本人经常外出需要使用手机热点，但每次切换热点的时候都链接不上，必须关闭wifi重新打开才可能链接上

**System log**
**系统报告**
- If a windows "Your computer was restarted because of a problem" appears, click `Report` and attach the log to help find the problem.
- 如果出现窗口"您的电脑因为出现问题而重新启动"，点击`报告`并附上错误日志来帮助定位问题。

**Screenshots**
**截图**
- If applicable, add screenshots to help explain your problem.
- 如果可用，请添加截图来帮助说明您遇到的问题。
- 
![WechatIMG457](https://user-images.githubusercontent.com/36411451/112756162-803b9200-9016-11eb-89c0-f155d05153f7.jpeg)

**Attach your entire EFI folder**
**附上您的整个EFI文件夹**
- Please attach your entire EFI folder to help solve your problem.
- Erasing serial numbers in config.plist is required!
- 请附上整个EFI文件夹来方便解决问题。
- 附件里的config.plist请清除序列号！

**Attach system.log**
**附上system.log**
- If applicable, please run `log show --predicate "processID == 0" --last boot --debug | grep "ERR"` in `Terminal.app` to help locate the problem.
- 如果可用，请在`终端.app`运行命令`log show --predicate "processID == 0" --last boot --debug | grep "ERR"`来帮助定位问题。

**Comment by stevezhengshiqi** [comment]
本仓库只使用驱动，并没有开发驱动的能力。Intel网卡驱动问题请移步 https://github.com/OpenIntelWireless/itlwm/issues 此驱动还在开发阶段，很多问题是已知待解决的。
