### ISSUE TITLE
外接显示 器使用小米typec转接器接miniDP转DP无法显示

### ISSUE THREAD

**Issue by sxdxzkq** [daliansky/XiaoMi-Pro-Hackintosh#557]
**Pre-requirement**
**前提条件**
- Try to rebuild the kextcache and restart whenever you encounter a problem. It always works like a charm!
- 请在遇到任何问题时，先重建缓存并重启。它通常能修复99%的问题！
- To rebuild the kextcache, run `sudo kextcache -i /` in `Terminal.app`.
- 在`终端.app`运行命令`sudo kextcache -i /`来重建缓存。

**State the model**
**阐述您的机型**
- XiaoMi-Pro MX150

**State the version of the EFI**
**阐述您的EFI版本**
- v1.5.3 opencore

**Describe the bug**
**描述您遇到的问题**
- A clear and concise description of what the bug is.
- 外接显示器使用小米typec转接器接miniDP转DP无法显示
- Windows 10 下可以使用
**System log**
**系统报告**
- If a windows "Your computer was restarted because of a problem" appears, click `Report` and attach the log to help find the problem.
- 如果出现窗口"您的电脑因为出现问题而重新启动"，点击`报告`并附上错误日志来帮助定位问题。

**Screenshots**
**截图**
- If applicable, add screenshots to help explain your problem.
- 如果可用，请添加截图来帮助说明您遇到的问题。

![18611616980665_ pic_hd](https://user-images.githubusercontent.com/16347380/112775510-ae998b80-906f-11eb-8231-522649e824d2.jpg)
![18601616980562_ pic_hd](https://user-images.githubusercontent.com/16347380/112775516-b35e3f80-906f-11eb-9522-9ad25ed31a42.jpg)

**Attach your entire EFI folder**
**附上您的整个EFI文件夹**
- Please attach your entire EFI folder to help solve your problem.
- Erasing serial numbers in config.plist is required!
- 请附上整个EFI文件夹来方便解决问题。
- 并未修改EFI, 只添加了三码

**Attach system.log**
**附上system.log**
- If applicable, please run `log show --predicate "processID == 0" --last boot --debug | grep "ERR"` in `Terminal.app` to help locate the problem.
- 如果可用，请在`终端.app`运行命令`log show --predicate "processID == 0" --last boot --debug | grep "ERR"`来帮助定位问题。

**Comment by stevezhengshiqi** [comment]
直接接dp可以使用吗？

**Comment by sxdxzkq** [comment]
> 直接接dp可以使用吗？

小米Pro没有dp接口，所以使用了typec转minidp的转接器，目前是无法使用的。

**Comment by sxdxzkq** [comment]
> 直接接dp可以使用吗？

使用的是新买的硬盘，新装的系统

**Comment by stevezhengshiqi** [comment]
> 小米Pro没有dp接口，所以使用了typec转minidp的转接器，目前是无法使用的。

充电typec支持dp呀，直接插进充电typec。

**Comment by sxdxzkq** [comment]
> > 小米Pro没有dp接口，所以使用了typec转minidp的转接器，目前是无法使用的。
> 
> 充电typec支持dp呀，直接插进充电typec。

我插的确实是充电Type-C口， windows10下就是好的

**Comment by stevezhengshiqi** [comment]
我指不接入转接器，直接把外接dp线插进typec口 @sxdxzkq

**Comment by sxdxzkq** [comment]
> > > 小米Pro没有dp接口，所以使用了typec转minidp的转接器，目前是无法使用的。
> > 
> > 
> > 充电typec支持dp呀，直接插进充电typec。
> 
> 我插的确实是充电Type-C口， windows10下就是好的

这怎么插啊？

**Comment by sxdxzkq** [comment]
> 我指不接入转接器，直接把外接dp线插进typec口 @sxdxzkq

买一根typec转dp的线吗？那样无法充电吧....

**Comment by sxdxzkq** [comment]
解决了, 换了个型号就好了
