### ISSUE TITLE
外接2k显示器分辨率过低

### ISSUE THREAD

**Issue by dislazy** [daliansky/XiaoMi-Pro-Hackintosh#558]
**Pre-requirement**
**前提条件**
- Try to rebuild the kextcache and restart whenever you encounter a problem. It always works like a charm!
- 请在遇到任何问题时，先重建缓存并重启。它通常能修复99%的问题！
- To rebuild the kextcache, run `sudo kextcache -i /` in `Terminal.app`.
- 在`终端.app`运行命令`sudo kextcache -i /`来重建缓存。

**State the model**
**阐述您的机型**
- XiaoMi-Pro MX150

**State the version of the EFI**
**阐述您的EFI版本**
- v1.5.3

**Describe the bug**
**描述您遇到的问题**
- A clear and concise description of what the bug is.
- 清晰并详细地描述问题所在。
使用最新的EFI安装了10.15.7的系统；然后更新到了最新的 big sur，期间外接2K的显示器一直是1920*1080,无法正常使用更高分辨率，希望楼主帮助一起解决相关问题，非常感谢

**System log**
**系统报告**
- If a windows "Your computer was restarted because of a problem" appears, click `Report` and attach the log to help find the problem.
- 如果出现窗口"您的电脑因为出现问题而重新启动"，点击`报告`并附上错误日志来帮助定位问题。

**Screenshots**
**截图**
- If applicable, add screenshots to help explain your problem.
- 如果可用，请添加截图来帮助说明您遇到的问题。
![截屏2021-04-01 23 09 44](https://user-images.githubusercontent.com/30426054/113314933-5ac4c600-933f-11eb-9603-a0a3d0bf4a25.png)
![截屏2021-04-01 23 10 33](https://user-images.githubusercontent.com/30426054/113315151-919adc00-933f-11eb-8546-10f77f5b2d30.png)

**Attach your entire EFI folder**
**附上您的整个EFI文件夹**
- Please attach your entire EFI folder to help solve your problem.
- Erasing serial numbers in config.plist is required!
- 请附上整个EFI文件夹来方便解决问题。
- 附件里的config.plist请清除序列号！

**Attach system.log**
**附上system.log**
- If applicable, please run `log show --predicate "processID == 0" --last boot --debug | grep "ERR"` in `Terminal.app` to help locate the problem.
- 如果可用，请在`终端.app`运行命令`log show --predicate "processID == 0" --last boot --debug | grep "ERR"`来帮助定位问题。

**Comment by dislazy** [comment]
EFI文件未进行任何改动

**Comment by stevezhengshiqi** [comment]
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/设置64mb动态显存
+
https://github.com/xzhih/one-key-hidpi

**Comment by dislazy** [comment]
非常感谢

**Comment by dislazy** [comment]
你好，遇到新的问题，由于我的电脑只有macos.系统，无法运行cmd程序，有在macos系统下解决该问题的方案嘛，非常感谢
