### ISSUE TITLE
Wireless mouse or Bluetooth wakeup

### ISSUE THREAD

**Issue by hong8866** [daliansky/XiaoMi-Pro-Hackintosh#560]
Latest opencore and macos
Wireless wakeup ok after 10mins sleep
Cannot wireless wakeup after leaving the laptop overnight
I have to press the power button to wakeup the laptop

is this a known issue or is there any solution available?

**Comment by stevezhengshiqi** [comment]
That's the intended behavior. After the power button blinks, which means the laptop is in S3/S4 sleep, only opening the lid or pressing the button can wake up the laptop. Bluetooth wakeup won't work due to incompatible ACPI table on macOS.
