### ISSUE TITLE
Error running makefile.sh

### ISSUE THREAD

**Issue by arandax** [daliansky/XiaoMi-Pro-Hackintosh#561]
When running makefile.sh fromt terminal, after some other succesful download, I encounter the following error:

[ ERROR ]: Failed to download resources from EAPD-Codec-Commander, please check your connection!

**Comment by stevezhengshiqi** [comment]
@arandax Thank you for the report. Will fix it in the next commit. Also, I recommend add flag `--PRE_RELEASE=Kext` when running the makefile; otherwise you will get a ridiculously big size EFI.
