### ISSUE TITLE
修改Bios的DVMT重启电脑就一直黑屏只有电源指示灯亮着

### ISSUE THREAD

**Issue by stevenjx** [daliansky/XiaoMi-Pro-Hackintosh#563]
修改Bios的DVMT重启电脑就一直黑屏只有电源指示灯亮着，需要刷bios，请问小米笔记本pro GTX版的Bios盲刷文件名是什么？如何拯救？

**Comment by stevezhengshiqi** [comment]
如果无法进入BIOS界面，则必须找售后或者使用拆机编程器刷进BIOS芯片。Wiki里明确写了dvmt脚本只适用于[TM1701](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/设置64mb动态显存#tm1701)，其他机型刷进去会变砖。https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/166
