### ISSUE TITLE
Just a question about VoltageShift

### ISSUE THREAD

**Issue by Remmed96** [daliansky/XiaoMi-Pro-Hackintosh#571]
Has anyone managed to get VoltageShift to work on BigSur? Could you post the files and scripts you used?
Thanks in advance.

**Comment by Menchen** [comment]
It should work without problem, just make sure SIP is disabled.

**Comment by Remmed96** [comment]
I think it is disabled because i have the CFG Lock bit equals to 0, how can I check if SIP il disabled ?

**Comment by Remmed96** [comment]
@Menchen  I found online already, it's not completely disabled, is that okay or should I completely disable it?

![Schermata 2021-05-29 alle 15 20 47](https://user-images.githubusercontent.com/44156733/120071890-73c4cb80-c091-11eb-8c4c-284ac50a9cc9.png)

**Comment by Menchen** [comment]
I think it should be ok. Try this version https://github.com/daliansky/XiaoMi-Pro/files/3101379/VoltageShift.zip .

**Comment by Remmed96** [comment]
I'm with Catalina now, I just wanted to inform myself because I notice a noticeable increase in pc performance using voltageshift and I don't want to not be able to use it anymore.

**Comment by Menchen** [comment]
I’m using it on Big sur right now, the only thing you needs to make use is SIP is disabled and BIOS patch(new EFI enable SIP by default)

**Comment by Remmed96** [comment]
Yes I noticed that it is active by default, thank you very much for the tips.

**Comment by Remmed96** [comment]
@Menchen It is working perfectly, thanks a lot.
