### ISSUE TITLE
声卡始终不能驱动。完全没有声音。另外。蓝牙和触控板也无法驱动

### ISSUE THREAD

**Issue by lhxs123** [daliansky/XiaoMi-Pro-Hackintosh#579]
**Pre-requirement**
**前提条件**
- Try to rebuild the kextcache and restart whenever you encounter a problem. It always works like a charm!
- 请在遇到任何问题时，先重建缓存并重启。它通常能修复99%的问题！
- To rebuild the kextcache, run `sudo kextcache -i /` in `Terminal.app`.
- 在`终端.app`运行命令`sudo kextcache -i /`来重建缓存。

**State the model**
**阐述您的机型**
XiaoMi-AIR 13.3 8G I5-8250U

**State the version of the EFI**
**阐述您的EFI版本**
- EFI 1.5.8 

**Describe the bug**
**描述您遇到的问题**
- ALC255声卡死活不能驱动。已经试过255的所有的layid。都完全不能驱动。

[config.txt](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/6788910/config.txt)

**Comment by stevezhengshiqi** [comment]
不是本仓库所支持机型（小米笔记本Pro），请移步相应小米air仓库。
