### ISSUE TITLE
after high CPU use on Big Sur, macOS cannot shutdown or anything

### ISSUE THREAD

**Issue by queenleonidasth** [daliansky/XiaoMi-Pro-Hackintosh#582]
my TM1701 (macOS Big Sur 11.4 OC EFI v1.5.8) can not do anything after using for my work (YouTube 1080P + Google Sheet 40000 col + web Inspect on Safari) for 3-5 hour ,System will go too slow&laggy and I can not shutdown , open every program(Still loading) even use force close. I don't know what is the problem ?

**Comment by Menchen** [comment]
More info is needed, can you check for CPU usage in activity monitor, `htop` or `ps aux | head -n10`?

**Comment by FunnyDevs** [comment]
Big sur destroys your hard disk (as it did with me and with other people [549]( https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/549)).  
Revert to Catalina.

**Comment by queenleonidasth** [comment]
look like NVMEFix can solve this problem , after clean install + NVMEFix my system can work normally. thank for answer!
