### ISSUE TITLE
Setup assistant spinning wheel forever (Big Sur)

### ISSUE THREAD

**Issue by Neolo** [daliansky/XiaoMi-Pro-Hackintosh#583]
11.5 Big Sur on Xiaomi Ruby 2019 (Kabylake) never finishes, ends up on forever spinning wheel at the last step. Reboot and is all the same over again.

**Comment by stevezhengshiqi** [comment]
Unsupported machine model. Please use alternative EFI.

**Comment by Neolo** [comment]
> Unsupported machine model. Please use alternative EFI.

Very well supported, it's installing and booting. After migrating user data from old Catalina version it caused spinning death wheel.

To fix spinning wheel, reboot into installer, select terminal and enter
spctl --master-disable
touch /var/db/.AppleSetupDone

Of course Ethernet is not working, wifi and bt too. The rest is fine.

**Comment by stevezhengshiqi** [comment]
This repository is for XiaoMi NoteBook Pro 8th and 10th CPU. Ruby is not supported here.
Please find EFI that is specifically designed for your model.

**Comment by Neolo** [comment]
Why don't you compare the hardware first before you answer?

**Comment by stevezhengshiqi** [comment]
There's no need to compare. Even if two models are using the same CPU, GPU, motherboard, and sound card, they should never share the same EFI. The key component for hackintosh is ACPI modification, and Ruby's DSDT is dramatically different with Xiaomi-Pro's(e.p. Ruby has an EC device, but Xiaomi-Pro doesn't). You should create your own EFI and carefully re-write SSDTs.

**Comment by Neolo** [comment]
Ok, I will leave a link for anyone who with Ruby go here https://github.com/XenOriginal/XiaoMi-Ruby-15.6-UMA-only
