### ISSUE TITLE
RTS5129 issue

### ISSUE THREAD

**Issue by gnpaone** [daliansky/XiaoMi-Pro-Hackintosh#585]
My card reader is not working with latest release of "RealtekCardReader.kext + RealtekCardReaderFriend.kext". (The second "VMware" method is confusing so not wanted to follow it and go with kext method) Can you please tell what version of kexts are you using? Also, can you please send the both "working" kexts?

**Comment by stevezhengshiqi** [comment]
RealtekCardReader is not working for now, even the latest commit. Please contact the author for more support.

**Comment by gnpaone** [comment]
Ok
