### ISSUE TITLE
EFI v1.5.9 doesn't boot with SSDT-NVMe-Pcc.aml

### ISSUE THREAD

**Issue by Miskotonic** [daliansky/XiaoMi-Pro-Hackintosh#587]
Hello.

I faced with Clover r5138 (EFI v1.5.9) and SSDT-NVMe-Pcc.aml problem.
New EfI (v1.5.9) can’t boot with this SSDT.aml. (I get this error: pic-1) (Without SSDT.aml EFi can boot.)
But I do need this Patch, because my second SSD does’t work without it. (I always get kernel panic: error 5230 after using second SSD without NVMe-Pcc.aml (Panic.pdf/panic.txt)
How can I fix this or can I change …Pcc.aml to another patch?
Please, help!!!
**Thx)**

(This is "worked" and "non-worked" EFi folders, SSDT-NVMe-Pcc.aml and Panic report)
(Model XiaoMi-Pro GTX, now I am using EFI v 1.4.8 with latest Catalina 10.15.7)
![pic - 1](https://user-images.githubusercontent.com/71147477/128870715-e1acb0a7-d01a-4e64-8702-2767991b99e4.jpg)
[Panic.pdf](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/6961824/Panic.pdf)
[panic.txt](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/6961832/panic.txt)
[SSDT-NVMe-Pcc.aml.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/6961837/SSDT-NVMe-Pcc.aml.zip)
[EFI (Not worked).zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/6961838/EFI.Not.worked.zip)
[EFI old (Worked).zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/6961842/EFI.old.Worked.zip)

**Comment by stevezhengshiqi** [comment]
Please mention your SSD model. If it's a PM981 or any unsupported SSD listed in https://github.com/dortania/bugtracker/issues/192, then it's not supported here. We have no way to make EFI work on broken IONVME compatibility SSDs. Your NVMePcc path is to spoof SSD's class-code. It would work, but it can't guarantee long term stability.

**Comment by Miskotonic** [comment]
**Thanks for the quick reply.** Sadly one of my SSD Is Samsung PM981A (SAMSUNG MZVLB256HAHQ-00000) and another is Western Digital Black SN720.

**Comment by stevezhengshiqi** [comment]
If your macOS installed on your non-PM981 SSD, I can help make you a new patch to disable PM981 detection on macOS. Otherwise, there’s no solution, and you might have to roll back to v1.4.8. The bootloader and kexts developers do not consider PM981 as a valid SSD so they could break support for it while they update their work.

**Comment by Miskotonic** [comment]
Yes, my Mac OS is installed on another (WD SN) ssd.
It would be really cool if you help me with the patch!!! Thx)

**Comment by stevezhengshiqi** [comment]
I just found out that I posted the patch in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/419#issuecomment-657741119.

> (P.S. But will I be able to use PM981 storage after applying the patch?)

No, the main idea of the patch is to block PM981 so that IONVME won't read them. PM981 is definitely a no-macOS SSD.
