### ISSUE TITLE
1.6.0EFI导致cpu功耗提升

### ISSUE THREAD

**Issue by maomingyang1314** [daliansky/XiaoMi-Pro-Hackintosh#590]
尊敬的开发者，我在中午更新最新的EFI1.6.0，发现电脑闲置的时候电脑发热，用inetl的软件观察，发现闲置的时候，cpu功耗为5w左右，之前闲置的时候cpu功耗大概在1.23w附近，cpu温度很高。
之后我换回了1.5.9，cpu温度和功耗回归正常，待机cpu功耗1w多一些。可能1.6.0中存在一些问题。
型号：小米笔记本pro15.6
cpu：8250U

**Comment by maomingyang1314** [comment]
![W1](https://user-images.githubusercontent.com/49444693/132459612-d6f53660-8a29-499b-b2fa-315aad00655d.jpeg)
![w2](https://user-images.githubusercontent.com/49444693/132459626-6fd456b7-78d0-435b-942d-1e69302080af.jpg)

**Comment by maomingyang1314** [comment]
图一为1.6.0，图二为换回1.5.9时候cpu的功耗。

**Comment by iainlau** [comment]
同，升级刚开机的时候感觉好卡。

**Comment by kakakuangkuang** [comment]
更新后发现总是卡，看网页都卡。
我看了一下cpu信息
发现空载cpu 2.0Ghz 功耗9w 。

![image](https://user-images.githubusercontent.com/37232324/132490930-d4042c1a-8e3f-494c-be13-6cbeee537487.jpeg)

一旦点开网页视频，变得非常卡顿，只要视频不关一直，cpu维持0.5Ghz 稳定在15w 温度62度

![image](https://user-images.githubusercontent.com/37232324/132490998-3fbc81e6-ffb2-4877-b3af-f339086bdc0b.jpeg)

关闭网页视频 ，cpu频率恢复正常。

![image](https://user-images.githubusercontent.com/37232324/132491035-1dc598e7-191a-46ba-85e0-6ca16032c8b2.jpeg)

我发现只要有高一点负载，如看网页视频，cpu骤降到0.5Ghz，在上一个版本没有这样的问题

**Comment by maomingyang1314** [comment]
短期内还是建议回滚到1.5.9版本。

**Comment by kakakuangkuang** [comment]
> 同，升级刚开机的时候感觉好卡。

你看看卡的时候，cpu频率是不是降到0.6ghz左右，我打开应用要等好长时间，频率一直维持0.6ghz，直到应用打开完成....

**Comment by maomingyang1314** [comment]
是高温，导致cpu撞温度墙了。所以频率上不去了。

**Comment by Menchen** [comment]
1.5.9 好像也出现过问题 #589 , 用 AppleIntelInfo.kext (`MSR_CORE_PERF_LIMIT_REASONS`) 确认一下是不是温度问题.

**Comment by HKMV** [comment]
听师傅们这么一说，我还是先不升了

**Comment by justforlxz** [comment]
我说怎么这么卡…

**Comment by stevezhengshiqi** [comment]
config里搜boot-args，把forceRenderStandby=0去掉试试呢？

**Comment by kakakuangkuang** [comment]
> config里搜boot-args，把forceRenderStandby=0去掉试试呢？

去掉之后，正常了，也流畅了，cpu不会掉到0.6ghz，最高可以去到4.0ghz，待机功耗也不高 ，大概2.5w

**Comment by maomingyang1314** [comment]
你是怎么做到4.0Ghz的，我的最多3.4Ghz@kakakuangkuang

**Comment by kakakuangkuang** [comment]
我cpu是i7-8550U

**Comment by stevezhengshiqi** [comment]
已在v1.6.1解决。
