### ISSUE TITLE
Stuck on Apple Logo after update

### ISSUE THREAD

**Issue by orhan-drsn** [daliansky/XiaoMi-Pro-Hackintosh#595]
Hi guys,
sorry if it's a easy question but I'm not so good in this.

I downloaded the newest OC build from here (as always) and chanched the EFI folder -> restart -> everything works.

Than I installed the macOS update -> restart -> everything works.

I shutdown the laptop and started it a few hours later and now it stucks on the Apple Logo. I created a OpenCore stick with the EFI folder from here (v1.6.1) and go into verbose mode.

![16322274135875751904780975851778](https://user-images.githubusercontent.com/47851919/134170564-9b0ee5cc-4fad-44b5-9153-ebb18e3f5c08.jpg)
![16322274373544218298161121658483](https://user-images.githubusercontent.com/47851919/134170607-ac659950-81b9-448e-a688-c34785a9f337.jpg)

Does anybody know why it stucks on the Apple Logo?

Thanks in advice!

**Comment by Menchen** [comment]
It seems like memory errors, I don’t know much about kernel panic but you should be able to boot into recovery mode and restore a snapshot as it’s always* created before system update , it will take some hours though...

**Comment by orhan-drsn** [comment]
> It seems like memory errors, I don’t know much about kernel panic but you should be able to boot into recovery mode and restore a snapshot as it’s always* created before system update , it will take some hours though...

Thanks for your answer!
I think I have to change config.plist to enter recovery mode?

**Comment by Menchen** [comment]
It should appear in opencore boot menu, but if everything fail you can just use a live usb with macos image in it, just like the one you installed hackintosh with.

**Comment by stevezhengshiqi** [comment]
>  I think I have to change config.plist to enter recovery mode?

Press space in the bootpicker page, and Recovery entry will show.

This panic looks weird to me too. My suggestion:
- Make sure the EFI is a clean copy of v1.6.1, it happens when user just replace their OC folder without delete it first
- Make sure no CPU modifications exist, e.x. CPUFriend
- You can always roll back to an older version EFI to check if it can work, e.x. v1.5.9

**Comment by orhan-drsn** [comment]
> * A nvram refresh might help: press space in the bootpicker page, and choose reset nvram
Thanks a lot! this worked for me and it started. Now I changed the EFI folder again, just to get sure everything is ok.
