### ISSUE TITLE
Update OTA Monterey Beta 8

### ISSUE THREAD

**Issue by Giannidmg** [daliansky/XiaoMi-Pro-Hackintosh#598]
I have EFI 1.6.1 and i changed my SMBIOS in MacBookPro14,1 to receive the OTA BETA 8 but when I boot the UPDATE partition from OC freezes and reboots

**Comment by stevezhengshiqi** [comment]
You need to have the latest OC version since https://github.com/acidanthera/OpenCorePkg/commit/1cb8490fd60f6b5f983d42e5bbf08e3d2d43d8f6. You can download it from GitHub artifacts or wait for the next EFI release.
