### ISSUE TITLE
Slow Internet in Big Sur 11.4

### ISSUE THREAD

**Issue by bzapata95** [daliansky/XiaoMi-Pro-Hackintosh#600]
I am in Big sur 11.4 and my contracted internet is 90Mbps, when I was in Catalina it reached the maximum peak. Now that I updated it to Big sur 11.4 my internet has gone down very ugly, it reaches 2Mbps, sometimes alone it stays in Kbps. Any solution to this problem ?. Thanks

![Screen Shot 2021-10-03 at 10 40 49](https://user-images.githubusercontent.com/15035675/135761564-7bec2433-b768-43ff-8252-246991ec4761.png)

**Comment by stevezhengshiqi** [comment]
For the Intel Wi-Fi driver issue, I recommend posting them on https://github.com/OpenIntelWireless/itlwm/issues, which is the source page. This EFI repository only uses drivers but not develops them. Remember to include logs following the instructions on https://openintelwireless.github.io/itlwm/Troubleshooting.html#runtime-logs

**Comment by bzapata95** [comment]
It's fine. Thanks
