### ISSUE TITLE
HDMI black-screen problem OpenCore

### ISSUE THREAD

**Issue by samarsky-canary** [daliansky/XiaoMi-Pro-Hackintosh#603]
With latest EFI 1.6.2 i have troubles with HDMI. When plug it in, main screen turns black and works only second one, even if i unplug it. How can i help you to fix this problem, maybe get some logs?

**Comment by stevezhengshiqi** [comment]
What model are you using? 8th or 10th CPU?

And what about closing the lid for about five seconds and reopening the lid?

**Comment by samarsky-canary** [comment]
> What model are you using? 8th or 10th CPU?
> 
> And what about closing the lid for about five seconds and reopening the lid?

TM1701 8th intel i5-8250u
After closing and reopenning the lid nothing happened. Black screen

**Comment by samarsky-canary** [comment]
Yes, it works! But what was the reason
