### ISSUE TITLE
Mi Notebook Pro X 15

### ISSUE THREAD

**Issue by influenist** [daliansky/XiaoMi-Pro-Hackintosh#615]
Hi @stevezhengshiqi is there any possibility you will be supporting the new Mi Notebook Pro X 15 i5 11300H /  i7 11370H?  

Cheers!

**Comment by stevezhengshiqi** [comment]
@orditeck There are not much things we cam do if Apple does not release 11 Gen Intel notebooks. We do not have avilable ig-platform-id for new Xe graphics.
