### ISSUE TITLE
PS2 Keyboard not responding in BootPicker if restart from macOS Monterey

### ISSUE THREAD

**Issue by stevezhengshiqi** [daliansky/XiaoMi-Pro-Hackintosh#616]
Model: XiaoMi-Pro 10 Gen CPU

When restart from Monterey, the keyboard will not work in BootPicker page. A similar issue is at https://github.com/acidanthera/bugtracker/issues/1838, and it would probably be a firmware issue according to vit9696.

A workaround of this is to **use trackpad**, or a cold boot from macOS. (After shutdown, wait for about 20s to boot)

Any opencore log is welcome here.

**Comment by webfalter** [comment]
https://github.com/acidanthera/bugtracker/issues/1838#issuecomment-1174020108

Seems to do something, even if it doesn't fix the firmware

**Comment by stevezhengshiqi** [comment]
Fixed in https://github.com/acidanthera/VoodooPS2/commit/2f0d204cd1cda1a9925b722ae7f7126cdaab2fae
