### ISSUE TITLE
Wrong Time (Clock) when switching from MacOS to Windows

### ISSUE THREAD

**Issue by arandax** [daliansky/XiaoMi-Pro-Hackintosh#617]
When I boot into macOs and then into Windows again, time (clock) is wrong, 1hour before of real time. 
Anyone with same problem?

**Comment by Menchen** [comment]
@arandax It's a windows problem due to backward compatibility, follow https://www.tonymacx86.com/threads/fix-incorrect-time-in-windows-osx-dual-boot.133719/ to use UTC time in windows.

**Comment by arandax** [comment]
Thank you so much!
