### ISSUE TITLE
Cannot Install Monterey and BigSur on Xiaomi TM1707

### ISSUE THREAD

**Issue by itsjeffersonli** [daliansky/XiaoMi-Pro-Hackintosh#618]
Model: XiaoMi-Pro i7 8th Gen CPU

EFI Version 1.6.2 and 1.6.3 

After booting into the Installation Screen, i cannot install and show the greyed out partition saying that `The Update Cannot be installed in this computer.` tried Mac OS Montery and Bigsur Already Did not Work. i tried reformating the drives to APFS and Mac os Journaled

Additional
When i use clover it will boot into the installation screen, but when i use OC it will show the boot menu but when i click the install mac os it will go to blank screen and it wont go to the installation screen.

Tried Reseting the NVRAM, Tried Pulling out the ssd's installed and putting it back.

**Comment by stevezhengshiqi** [comment]
Everytime you change from Clover to OC, you need to reset NVRAM in OC boot page. Also, only v1.6.3 is recommended because v1.6.2's firmware version is lower than Monterey required.

**Comment by itsjeffersonli** [comment]
> Everytime you change from Clover to OC, you need to reset NVRAM in OC boot page. Also, only v1.6.3 is recommended because v1.6.2's firmware version is lower than Monterey required.

I tried to reset the nvram but this happens to me

i cannot install mac os into the nvme ssd and show the greyed out partition saying that `The Update Cannot be installed in this computer.` tried Mac OS Montery and Bigsur Already Did not Work. i tried reformating the drives to APFS and Mac os Journaled

**Comment by stevezhengshiqi** [comment]
Then I have no idea about that. EFI provided here should have no problem for installation.

**Comment by itsjeffersonli** [comment]
> EFI provided here should have no problem for installation. Make sure you delete BOOT and OC folders and then copy. Replace won't work.

My Bad my SSD has very low health already, i replaced with a new nvme it was working
