### ISSUE TITLE
Mac OS 12 always restarts automatically

### ISSUE THREAD

**Issue by yuzejun** [daliansky/XiaoMi-Pro-Hackintosh#619]
In the past, Mac OS 11 was often blocked and restarted automatically after startup. It can be used normally only after it is no longer restarted automatically

**Comment by stevezhengshiqi** [comment]
Please provide more information about your model and EFI version.
Also check your SSD model. Samsung PM981 should be blocked in macOS.

**Comment by yuzejun** [comment]
xiaomi  book pro gtx i7，EFI is latest. intel SSD， macos 12.0.1

**Comment by yuzejun** [comment]
Xiaomi Mi Notebook Pro i7 GeForce GTX 1050 Max-Q

**Comment by stevezhengshiqi** [comment]
So you replaced the original SSD, or just inserted the intel one? Is Samsung SSD in your slot?

**Comment by yuzejun** [comment]
inserted

**Comment by yuzejun** [comment]
Samsung SSD is still  in my slot

**Comment by stevezhengshiqi** [comment]
Could you check your Samsung model number? If it's PM981, you have to block it then.
See https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/419#issuecomment-657741119
