### ISSUE TITLE
Monterey with clover efi 1.6.3

### ISSUE THREAD

**Issue by svtmontagna** [daliansky/XiaoMi-Pro-Hackintosh#620]
Hi,
I have big sur installed right now and I'd like to upgrade to monterey. Is clover efi 1.6.3 safe for this upgrade or I need to switch to OC? Thanks.

**Comment by svtmontagna** [comment]
I tried to download the upgrade, but when I select partition show up "The Update Cannot be installed in this computer."

**Comment by stevezhengshiqi** [comment]
For macOS version >= Big Sur, Open Core is reecommended.

**Comment by matvada** [comment]
Hello, any update about compatibility of Monterey with Clover on XiaoMi NoteBook Pro EFI v1.6.4?
