### ISSUE TITLE
Battery life issue

### ISSUE THREAD

**Issue by wildanbaraja** [daliansky/XiaoMi-Pro-Hackintosh#625]
Hello, greetings from Indonesia. Thank you for providing this setting. I'm glad I came to this page.

I currently have a problem, I have a 15inch mi notebook intel core i7 8550u, when I use bigsur I have battery problems. Battery life was fine at first, but after a month of using it suddenly reduced battery life. And one time I couldn't boot into mac os, I turned on my laptop, and suddenly it shuts down which shows that the battery is empty, sometimes when on the desktop, sometimes when on the mi logo. And after some time, this problem also occurs when I charge my laptop. I think my battery needs to be replaced. But I tried to remove mac os and install linux and windows, the battery life is good, it can last 2 hours. Do you think maybe I misconfigured opencore? Or maybe my battery needs to be patched?

Thank you in advance.

**Comment by stevezhengshiqi** [comment]
Hi, I am afraid we can do nothing regarding to the battery. In this repository, we use SMCBatteryManager from VirtualSMC at https://github.com/acidanthera/VirtualSMC. We do not have EC registers, so we do not need to patch.

**Comment by Menchen** [comment]
It might be problem with hibernate...  Check with `pmset -g`  and look for hibernatemode.

**Comment by wildanbaraja** [comment]
> It might be problem with hibernate... Check with `pmset -g` and look for hibernatemode.

Thank you for your response!
hibernatemode is 3. Is it correct?

**Comment by wildanbaraja** [comment]
> Hi, I am afraid we can do nothing regarding to the battery. In this repository, we use SMCBatteryManager from VirtualSMC at https://github.com/acidanthera/VirtualSMC. We do not have EC registers, so we do not need to patch.

Thank you for your info. 
Do you experience this too?

**Comment by Menchen** [comment]
I would recommend hibernation mode 0 https://gist.github.com/hariel18/c370bf53fe795bd7aa345937746251b0

**Comment by wildanbaraja** [comment]
> I would recommend hibernation mode 0 https://gist.github.com/hariel18/c370bf53fe795bd7aa345937746251b0

if I change to 0, will I still be able to sleep my laptop?

**Comment by Menchen** [comment]
You can sleep(save to ram) but it won’t hibernate(save to disk).

**Comment by wildanbaraja** [comment]
> You can sleep(save to ram) but it won’t hibernate(save to disk).

so the disk is still operating?
And about the battery, will it help save battery more?
Thank you

**Comment by Menchen** [comment]
The disk is powered and cpu is in sleep mode(still powered). It will save battery compared to normal use.
