### ISSUE TITLE
Wifi Airport Apple Original Card

### ISSUE THREAD

**Issue by fsword-13** [daliansky/XiaoMi-Pro-Hackintosh#629]
Hi, every one. I would like to install on my laptop Xiaomi Mi Notebook Pro 2020 an Apple Wifi Card for a full compability (airport, handoff etc...).
I want to achive this goal with less invasivity possibile. I want to use Intel Card for Bluetooth connectivity and the Apple WiFi installing this card:

https://it.aliexpress.com/item/1005001414140383.html?spm=a2g0o.new_account_index

The question is, if I install 2 antennas under the battery, this adapter card can work without USB pin soldered?

**Comment by Giannidmg** [comment]
Yes, I have used this method for more than a year but the reception of wifi is scarce with the antennas in that position, I recommend you buy extension cords and attach the original wifi antennas to the new card and add an antenna for the bluetooth intel

**Comment by fsword-13** [comment]
Wich one is better for your method?

BCM943602CS (3 Antennas)

BCM94360CS2 (2 Antennas)

**Comment by Giannidmg** [comment]
I have the 3 antennas, but for this pc I recommend the two so you use its original antennas and you don’t need to add more, then I recommend using the bluetooth of the apple board for complete compatibility (look for a technician good for the job and have the two cables soldered on the wlan tracks

**Comment by fsword-13** [comment]
I will try with 2 antennas adapter. Intel Bluetooth works well, so I'll integrate two extra antennas for it. Thanks for your help.

**Comment by fsword-13** [comment]
Hello, I instelled BCM94360CS2 and it works! But after 30 sec / 2 min max my laptop freeze (no mouse and keyboard control) My OS is Monterey. How i can resolve?
