### ISSUE TITLE
Upgrade question.

### ISSUE THREAD

**Issue by Chazy12** [daliansky/XiaoMi-Pro-Hackintosh#630]
Hello. Forgive me if I did stupid question, but the EFI should be upgraded before of after the macOS update?! Thanks.

**Comment by Menchen** [comment]
Before

**Comment by Chazy12** [comment]
Thanks. All works perfectly!
I just have an issue with a Microsoft Bluetooth mouse.
I tried with the native Bluetooth module, find the mouse but don't pair. Same with the adapter.. do I need some text or it's a common problem?

**Comment by Menchen** [comment]
By "native" you meant intel bluetooth? It won't work I think.

**Comment by Chazy12** [comment]
Yes, Intel bluetooth. To me it's working.. search and find the device, but won't connect to my Microsoft mouse..

**Comment by Chazy12** [comment]
And with other devices (as smartphone) works perfectly. The native wifi too.

**Comment by Menchen** [comment]
> Yes, Intel bluetooth. To me it's working.. search and find the device, but won't connect to my Microsoft mouse..

It's not "working" because it won't connect to mouse or headphone, you need an usb bluetooth for those devices.
