### ISSUE TITLE
Screen freezes and I need to reboot the laptop

### ISSUE THREAD

**Issue by fsword-13** [daliansky/XiaoMi-Pro-Hackintosh#633]
Hello, I have the same issue. "After about 2-3 minutes in the network, the screen freezes and I need to reboot the laptop."

I use the Intel integrated card for Bluetooth and BCM94360CS2 for Wi-Fi.

How i can resolve freze problem?

I have OpenCore with Monterey installed.

_Originally posted by @fsword-13 in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/99#issuecomment-1033948996_

**Comment by Menchen** [comment]
Maybe intel Bluetooth is causing problem? Try disabling it with ssdt.

**Comment by stevezhengshiqi** [comment]
I had that problem before also, it's because of the Brcm card. Try to reinstall it on your motherboard or unload it.

**Comment by fsword-13** [comment]
I removed BCM94360CS2 card and now i don't have any problem.

I need to use Intel Bluetooth (integrated) and Apple BCM94360CS2 card for Wi-Fi. I cant use solder for Apple Bluetooth. So, maybe it cause a conflict?
I's possible to use together?

**Comment by stevezhengshiqi** [comment]
Yes, they can be used together. I believe it's your BCM94360CS2 card hardware problem. I solved my problem by replacing a new one. Also, don't forget to disable Intel Wi-Fi kexts just in case.

**Comment by fsword-13** [comment]
How to disable Intel Wi-Fi kext correctly?

**Comment by M69W** [comment]
I don't know it is useful to your;
try it if you have no idea.

https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki/%E7%99%BD%E6%9E%9C%E6%8B%86%E6%9C%BA%E7%BD%91%E5%8D%A1

**Comment by stevezhengshiqi** [comment]
Closes as a hardware problem.
