### ISSUE TITLE
MacOS updates no longer show up via Software Update

### ISSUE THREAD

**Issue by segfault32** [daliansky/XiaoMi-Pro-Hackintosh#635]
Does anyone else experience this?  For example, I know there's a Monterey 12.2 update and now a 12.2.1 update but every time I go into Software Update to check, it always just says my Mac is up to date.

I am on KBL OC v1.6.4 with the only difference from the release EFI having changed the SecureBootModel from Default to Disabled. (As per the other thread, the machine won't boot with the Default setting. It just gets stuck at the xiaomi logo)

**Comment by stevezhengshiqi** [comment]
Software update requires `SecureBootModel` to be `Default`. You can manually go to appstore and search Monterey to get updates.
