### ISSUE TITLE
对TM1701的0E07版bios进行了提取与解包成txt

### ISSUE THREAD

**Issue by kexirong** [daliansky/XiaoMi-Pro-Hackintosh#636]
内容在附件，请问这版bios是否可以dvmt脚本？
[SetupUtility_PE32_image_section IFR.txt](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/8101888/SetupUtility_PE32_image_section.IFR.txt)

**Comment by kexirong** [comment]
Suppress If: {0A 82}
0x14A442 			Variable 0xB10 equals 0x20 {12 06 10 0B 20 00}
0x14A448 			Setting: DVMT Pre-Allocated, Variable: 0xDF {05 91 7C 11 8F 11 B8 01 02 00 DF 00 10 10 00 FE 00}
0x14A459 				Default: Other {5B 85 00 00 08}
0x14A45E 					Value {5A 82}
0x14A460 						Variable 0xB10 equals value in list (0x73, 0x74) {14 8A 10 0B 02 00 73 00 74 00}
0x14A46A 							64 Bit Unsigned Int: 0x1 {45 0A 01 00 00 00 00 00 00 00}
0x14A474 							64 Bit Unsigned Int: 0x2 {45 0A 02 00 00 00 00 00 00 00}
0x14A47E 							Conditional {50 02}
0x14A480 						End {29 02}
0x14A482 					End {29 02}
0x14A484 				End {29 02}
0x14A486 				Option: 0M, Value: 0x0 {09 07 7D 11 00 00 00}
0x14A48D 				Option: 32M, Value: 0x1 {09 07 7E 11 30 00 01}
0x14A494 				Option: 64M, Value: 0x2 {09 07 7F 11 00 00 02}
0x14A49B 				Option: 4M, Value: 0xF0 {09 07 80 11 00 00 F0}
0x14A4A2 				Option: 8M, Value: 0xF1 {09 07 81 11 00 00 F1}
0x14A4A9 				Option: 12M, Value: 0xF2 {09 07 82 11 00 00 F2}
0x14A4B0 				Option: 16M, Value: 0xF3 {09 07 83 11 00 00 F3}
0x14A4B7 				Option: 20M, Value: 0xF4 {09 07 84 11 00 00 F4}
0x14A4BE 				Option: 24M, Value: 0xF5 {09 07 85 11 00 00 F5}
0x14A4C5 				Option: 28M, Value: 0xF6 {09 07 86 11 00 00 F6}
0x14A4CC 				Option: 32M/F7, Value: 0xF7 {09 07 87 11 00 00 F7}
0x14A4D3 				Option: 36M, Value: 0xF8 {09 07 88 11 00 00 F8}
0x14A4DA 				Option: 40M, Value: 0xF9 {09 07 89 11 00 00 F9}
0x14A4E1 				Option: 44M, Value: 0xFA {09 07 8A 11 00 00 FA}
0x14A4E8 				Option: 48M, Value: 0xFB {09 07 8B 11 00 00 FB}
0x14A4EF 				Option: 52M, Value: 0xFC {09 07 8C 11 00 00 FC}
0x14A4F6 				Option: 56M, Value: 0xFD {09 07 8D 11 00 00 FD}
0x14A4FD 				Option: 60M, Value: 0xFE {09 07 8E 11 00 00 FE}
0x14A504 			End of Options {29 02}
0x14A506 		End If {29 02}

**Comment by stevezhengshiqi** [comment]
可以
