### ISSUE TITLE
Hackintosh on new Mibook Pro

### ISSUE THREAD

**Issue by matvada** [daliansky/XiaoMi-Pro-Hackintosh#637]
Hello,
mine is more a question than an issue:
Anyone know if it is possible to install MacOs on one of these models?

https://it.banggood.com/AMD-VersionXiaomi-Mi-Pro-15-Laptop-15_6-inch-3_5K-100-pencent-P3-OLED-93-pencent-Ratio-Screen-AMD-Ryzen-R7-5800H-16G-RAM-3200MHz-512G-PCIe-SSD-WiFi-6-Type-C-Baclilght-Fingerprint-Camera-Notebook-p-1856692.html?cur_warehouse=CN&rmmds=search

https://it.banggood.com/Top-VersionXiaomi-Mi-Pro-X-15-Laptop-15_6-inch-3_5K-100-pencent-P3-OLED-93-pencent-Ratio-Screen-Intel-Core-i5-11300H-NVIDIA-GeForce-RTX3050Ti-16G-RAM-4266MHz-LPDDR4X-512Gb-PCIe4_0-SSD-Thunderbolt4-WiFi6-Type-C-Baclilght-Fingerprint-Camera-DLSS-Notebook-p-1868737.html?cur_warehouse=CN&rmmds=search

https://it.banggood.com/Xiaomi-Mi-Pro-15-Laptop-15_6-inch-3_5K-100-pencent-P3-OLED-93-pencent-Ratio-Screen-Intel-Core-i5-11300H-Intel-Xe-Graphics-16G-RAM-3200MHz-512G-PCIe-SSD-WiFi-6-Thunderport-4-Baclilght-Fingerprint-Camera-Notebook-p-1841616.html?cur_warehouse=CN&rmmds=search

Thank you!

**Comment by stevezhengshiqi** [comment]
For 11th Gen CPU laptops, please wait until Apple releases related Intel notebooks. Otherwise, Intel Iris Xe Graphics used by new models are not supported.

AMD version is even harder, I will give up on that.
