### ISSUE TITLE
Universal Control Monterey 12.3

### ISSUE THREAD

**Issue by pepocrespo** [daliansky/XiaoMi-Pro-Hackintosh#639]
### Discussed in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/discussions/632

<div type='discussions-op-text'>

<sup>Originally posted by **pepocrespo** February  6, 2022</sup>
Has anyone tried the functionality of Universal Control with their Ipad and has it worked? In my case, the Universal Control option does not even appear in the screen tab, but it does in settings. I have a 6th generation iPad. It is simple curiosity in case some adjustment had to be made or it cannot work directly.</div>

**Comment by stevezhengshiqi** [comment]
The AWDL related issues can see https://github.com/OpenIntelWireless/itlwm/issues/292. They won't be solved by me.
