### ISSUE TITLE
Test on Mi NoteBook Pro 11th Gen

### ISSUE THREAD

**Issue by expacc007** [daliansky/XiaoMi-Pro-Hackintosh#640]
I have a [Mi NoteBook Pro](https://www.mi.com/in/product/mi-notebook-pro/specs) (i5-11300H, Iris® Xe). I saw some people were able to use 11th gen processors by spoofing it as 10th gen processors. What would happen if I follow the instructions for i5 10th gen. It won't boot or it would work sub optimally? Can we do general tasks like web browsing without the iGPU ?

**Comment by stevezhengshiqi** [comment]
I don't have the machine to test, and I don't recommend 11th gen processors to use this repository since the ACPI table changes a lot. As far as I know, the trackpad and sound are also not working well on new model.

**Comment by expacc007** [comment]
Would it be helpful if I test it on my device?

**Comment by leiyutian007** [comment]
Tm1701 it’s works





------------------ Original ------------------
From: Expacc ***@***.***&gt;
Date: Wed,Mar 30,2022 0:27 PM
To: daliansky/XiaoMi-Pro-Hackintosh ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [daliansky/XiaoMi-Pro-Hackintosh] Test on Mi NoteBook Pro 11thGen (Issue #640)





 
Would it be helpful if I test it on my device?

**Comment by stevezhengshiqi** [comment]
It could be helpful for other 11gen users, so far I don't have plan to support it since there're so many compatibility issues(graphics, sound, trackpad, poor power management), and they are probably can not be solved.

**Comment by expacc007** [comment]
Is this guide made for 2020 edition ? https://github.com/mBilG/Hackintosh-Laptop_Xiaomi-Mi-Notebook-Pro-2020-Enhanced

**Comment by stevezhengshiqi** [comment]
> Is this guide made for 2020 edition ? https://github.com/mBilG/Hackintosh-Laptop_Xiaomi-Mi-Notebook-Pro-2020-Enhanced

Yes.

**Comment by stevezhengshiqi** [comment]
No one I know has tested, but I don't recommend to do that.

**Comment by expacc007** [comment]
I tried the 10th gen OC EFI but it got stock at apple logo however the Olarila Opencore NoteBook TigerLake EFI worked for me. https://www.olarila.com/topic/5676-hackintosh-efi-folders-for-all-chipsets-clover-and-opencore/

**Comment by expacc007** [comment]
They have a app called runme which is used to generate a full dump of the device which can then be used to create one full ACPI solution/ patch the DSDT . Since you have to expertise, can you do it if I send you the full dump?

**Comment by stevezhengshiqi** [comment]
So sorry that I am busy these days. To be honest, Intel 11th Gen iGPU notebook does not worth doing that. It won't work well on macOS as long as Apple does not release their Intel 11th Gen notebooks.
