### ISSUE TITLE
看视频闪屏

### ISSUE THREAD

**Issue by leiyutian007** [daliansky/XiaoMi-Pro-Hackintosh#642]
目前使用都正常，就是在我在disney plus 全屏看视频的时候会有闪屏。类似像人眨眼睛一样，一般1分钟内有2到3次。在别的视频网站看也是一样的。

**Comment by leiyutian007** [comment]
还有就是wifi偶尔自动断连

**Comment by fang0814** [comment]
我也会遇到，即使不是在看视频的时候

**Comment by leiyutian007** [comment]
但是我在用emby和infuse的时候正常





------------------ 原始邮件 ------------------
发件人: Auto Fang ***@***.***&gt;
发送时间: 2022年4月2日 19:34
收件人: daliansky/XiaoMi-Pro-Hackintosh ***@***.***&gt;
抄送: leiyutian007 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [daliansky/XiaoMi-Pro-Hackintosh] 看视频闪屏 (Issue #642)

**Comment by stevezhengshiqi** [comment]
> 我也会遇到，即使不是在看视频的时候

检查是否开了HiDPI

**Comment by stevezhengshiqi** [comment]
请写出机型，EFI版本和使用的浏览器。

**Comment by leiyutian007** [comment]
> 请写出机型，EFI版本和使用的浏览器。

我的机器型号是tm1701. Clover 1.6.4，请问如果要开hidpi，还需要改动态显存64m吗

**Comment by stevezhengshiqi** [comment]
> > 请写出机型，EFI版本和使用的浏览器。
> 
> 我的机器型号是tm1701. Clover 1.6.4，请问如果要开hidpi，还需要改动态显存64m吗

没必要，如果你用的是Chrome，建议关闭硬件加速，如果不能解决，请在显示器设置里选择sRGB IEC61966-2.1 色彩配置。

**Comment by leiyutian007** [comment]
> > > 请写出机型，EFI版本和使用的浏览器。
> 
> > 
> 
> > 我的机器型号是tm1701. Clover 1.6.4，请问如果要开hidpi，还需要改动态显存64m吗
> 
> 
> 
> 没必要，如果你用的是Chrome，建议关闭硬件加速，如果不能解决，请在显示器设置里选择sRGB IEC61966-2.1 色彩配置。

感谢大神，在谷歌浏览器关闭硬件加速即可！谢谢您，请问有必要去开启one key hidpi吗

**Comment by stevezhengshiqi** [comment]
没必要
