### ISSUE TITLE
Failure to run Make.sh (Failed to copy resources!)

### ISSUE THREAD

**Issue by Casm101** [daliansky/XiaoMi-Pro-Hackintosh#643]
As I run the make file to create the EFI file for Xiaomi-Pro 10th Gen, the script fails with the following:

```
[ Unpacking ]
cp: IntelBluetoothFirmware*/IntelBluetoothFirmware.kext: No such file or directory
[ ERROR ]: Failed to copy resources!
```

Have attempted with multiple flags and on it's own, but to no avail.

**Comment by stevezhengshiqi** [comment]
Thanks, nice finding!
