### ISSUE TITLE
休眠唤醒后蓝牙无法使用

### ISSUE THREAD

**Issue by leiyutian007** [daliansky/XiaoMi-Pro-Hackintosh#645]
我的笔记本是xiaomi pro mx150 ，用的clover 1.6.4. 蓝牙在第一次启动都正常，但是合上盖子休眠，唤醒后，蓝牙无法使用，蓝牙无法连接鼠标，也无法发现别的设备，必须重新启动才正常。

**Comment by stevezhengshiqi** [comment]
蓝牙问题请咨询 https://github.com/OpenIntelWireless/IntelBluetoothFirmware，本仓库只使用驱动，并没有能力调教。

**Comment by In1t0** [comment]
> 我的笔记本是xiaomi pro mx150 ，用的clover 1.6.4. 蓝牙在第一次启动都正常，但是合上盖子休眠，唤醒后，蓝牙无法使用，蓝牙无法连接鼠标，也无法发现别的设备，必须重新启动才正常。

借助sleepwatcher自动开关蓝牙即可。
参考文章:[https://cotes.page/posts/turn-off-bluetooth-when-macbook-sleeps/](https://cotes.page/posts/turn-off-bluetooth-when-macbook-sleeps/)
