### ISSUE TITLE
Driver for windows - Wi-Fi/BT card

### ISSUE THREAD

**Issue by Techinbed** [daliansky/XiaoMi-Pro-Hackintosh#648]
Hello
I’ve added the card recommendation for Wi-Fi and BT for macOS and have a dual boot with windows 11.
Is there a driver for windows for this card? 
thanks for great resource !!!!
Love this project

**Comment by stevezhengshiqi** [comment]
For win10, it's https://www.driver-wireless.com/broadcom-bcm43xx-driver-win7810.html.

I don't have info for win11 yet.

Ref: https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/132#issuecomment-451629385
