### ISSUE TITLE
Intel 8265 bluetooth not working after Monterey update

### ISSUE THREAD

**Issue by retsel89** [daliansky/XiaoMi-Pro-Hackintosh#649]
Hi mi bluetooth not working, i found this on google (https://github.com/acidanthera/BrcmPatchRAM/releases/tag/2.6.1), but i can't get it to work

Also found this
https://dortania.github.io/OpenCore-Install-Guide/extras/monterey.html#bluetooth

Thanks

**Comment by stevezhengshiqi** [comment]
@retsel89 No enough information is provided. Please specify your EFI version. A good attempt is to keep you EFI to the latest version as new EFI has BlueToolFixup which Monterey requires.
