### ISSUE TITLE
升级至Monterey后，登录时自带键盘失效

### ISSUE THREAD

**Issue by heissedesanlengjing** [daliansky/XiaoMi-Pro-Hackintosh#651]
背景：小米Pro10代U，MX250,16G版本，10.15.7+win10双系统，替换为最新版本clover1.6.5之后执行升级，升级过程没有出现报错

问题：
1.系统选择页面，仍然是preBoot选择，而非正常的系统选项
2.选择preBoot之后，
2.1先出现了登录界面，没有常规的白苹果加载条
2.2此时自带键盘失效，仅电源键正常，按下即关机
2.3外接键盘可正常使用，输入密码后白苹果加载条出现
2.4进入系统后一切正常
3.升级Monterey的图标始终存在，再点击无反应，也无法删除

猜测：系统实际上并未完成升级，异常情况如2.1 2.2 3所描述，主要问题在自带键盘登录时无法使用

**Comment by stevezhengshiqi** [comment]
@heissedesanlengjing 

> 2.1先出现了登录界面，没有常规的白苹果加载条

这是因为你开启了磁盘加密/文件保险箱，升级系统是这个选项默认勾选，要手动取消。在系统偏好设置-隐私-文件保险箱可手动关闭。

> 2.2此时自带键盘失效，仅电源键正常，按下即关机

这个是 VoodooPS2 的bug，从macOS重启后键盘会失效直至进入系统，暂时无解，可以用触控板手动选择系统/从windows重启进mac/mac关机后等很久再开机

相关问题：https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/616

**Comment by heissedesanlengjing** [comment]
谢谢答复
