### ISSUE TITLE
删除 NullEthernet.kext，让英特尔 WiFi 变成 en0。

### ISSUE THREAD

**Issue by 1457384613gh** [daliansky/XiaoMi-Pro-Hackintosh#653]
现在，`AirportItlwm` 能够驱动 英特尔 WiFi 了，而且效果还特别好，应该不需要让一个 假的以太网 充当 `en0 `了吧？？？
英特尔 WiFi 是 `en1` 的话，好多app 总是账户掉线，在重新打开时，又要重新输入密码，重新登录账户，不方便，例如：appstore。
英特尔 WiFi 是 `en0` 的话，这些app 就不会账户掉线，不需要重新输入密码登录，更加方便。

- 删除 `NullEthernet.kext`
- 删除 `SSDT-RMNE.aml`
- 更改网络配置

已经这样尝试了，感觉效果还可以。就是不知道有没有什么负面影响。
顺便问下，`NullEthernet.kext` 现在应该不是什么必备的了吧？？？
删除的话，应该不会有负面影响吧？？？
后果严重的话，我就恢复；
没什么负面影响的话，那我就 只保留 英特尔 WiFi  作为 `en0`，减轻强加驱动的负荷，顺便节约 ESP 的一点点空间。

**Comment by leiyutian007** [comment]
请问一下你的airdrop 双向能发送吗？

**Comment by 1457384613gh** [comment]
> 请问一下你的airdrop 双向能发送吗？

隔空投送吗？我没有苹果手机，不太需要这个功能。没使用过。

**Comment by aKuan1693** [comment]
删除 NullEthernet.kext
删除 SSDT-RMNE.aml
更改网络配置
这个文件在哪删呀 移除以后稳定吗

**Comment by 1457384613gh** [comment]
> 删除 NullEthernet.kext
> 删除 SSDT-RMNE.aml
> 更改网络配置
> 这个文件在哪删呀 移除以后稳定吗

目前，没什么异常的。
但是，不知道有什么副作用，所以 issue 一下。
如果 steve 觉得没副作用的话，应该会支持的吧。

**Comment by aKuan1693** [comment]
删除 NullEthernet.kext
删除 SSDT-RMNE.aml
这两个文件还不知道在哪删啊 是在efi配置文件里吗

**Comment by 1457384613gh** [comment]
> 删除 NullEthernet.kext
> 删除 SSDT-RMNE.aml
> 这两个文件还不知道在哪删啊 是在efi配置文件里吗

还要在OC配置中关闭相关条目。
万一有副作用呢？
要不，先等大佬回复吧。

**Comment by stevezhengshiqi** [comment]
你好，这个问题我也有考虑过。我觉得nullethernet已经是个很成熟的方案了，没出过什么错。airportitlwm可能会不支持新macos，或者偶尔检测不到硬件。我可能倾向于保留ethernet。

**Comment by 1457384613gh** [comment]
📂Steve, Steve, ____________ 📂石奇，石奇，
Files EFI lief; ________________归档EFI而欣喜；

🚩Steve, Steve, ____________🚩石奇，石奇，
Is our belief; ________________我们大家都相信；

🌹Steve, Steve, ____________🌹石奇，石奇，
Gives Hack relief; ___________给予黑果援助哩；

👨‍💻Steve, Steve, ____________👨‍💻石奇，石奇，
Lets' achieve; _______________带着我们开天地；

💻Steve, Steve, ____________💻石奇，石奇，
Has drivers to retrieve; ______不会把驱动放弃；

⚖️Steve, Steve, ____________⚖️石奇，石奇，
We don't sieve; ______________我们不挑他的剔；

👕Steve, Steve, ____________👕石奇，石奇，
We pull his sleeve. __________我们不舍他离弃；

**Comment by stevezhengshiqi** [comment]
> 如果 Catalina, Big Sur, Monterey 三个版本的 WiFi 驱动同时装载

我给每个版本的aiportitlwm设置了maxkernel和minkernel，每个macos版本只会有一个airportitlwm被加载。

nullethernet目前确实只是个保险手段，不那么需要了。

**Comment by 1457384613gh** [comment]
还有一件事情，我觉得 设置 `LauncherOption=system` 比较好。
- 可以防止 overwrite nvram，对 nvram 起到保养作用。
- 可以防止 设置了 BIOS 开机密码的用户（毫不知情）在没有外置键盘的情况下无法开机。 因为，键盘驱动有点问题，OC始终为默认选项的话，会无法输入 BIOS密码。倘若没有外置键盘，会很着急的。假如OC不是BIOS默认的UEFI选项的话。强行断电以后，重启，好歹可以加载 Windows Boot Manager 或者 其他，这样内置键盘可以使用，还可以及时（在没有外置键盘的情况下）关闭BIOS的开机密码。

**Comment by stevezhengshiqi** [comment]
十代u确实会有热重启键盘失效问题，https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/616 有提到。原因是VoodooPS2让键盘处于一个bad state，暂时无解。

据我所知，Launcheroption只有 disabled，full和short，根据https://github.com/acidanthera/OpenCorePkg/blob/master/Utilities/ocvalidate/README.md

**Comment by 1457384613gh** [comment]
> 据我所知，Launcheroption只有 disabled，full和short，根据

![image](https://user-images.githubusercontent.com/69227436/167322316-b642240e-28f7-4c6c-8842-317e18031db1.png)

**Comment by 1457384613gh** [comment]
> 原因是VoodooPS2让键盘处于一个bad state，暂时无解。

可不可以这样理解？
`Mac OS 也有类似于 Windows 的【快速启动】，为了让开机更快而关机不彻底。`

是这种情况吗？？？

**Comment by stevezhengshiqi** [comment]
> > 原因是VoodooPS2让键盘处于一个bad state，暂时无解。
> 
> 可不可以这样理解？ `Mac OS 也有类似于 Windows 的【快速启动】，为了让开机更快而关机不彻底。`
> 
> 是这种情况吗？？？

不太是，单纯是因为VoodooPS2这个驱动有bug，在monterey下被触发了，导致键盘关机时处于一个不好的状态。

**Comment by 1457384613gh** [comment]
可是，我认为，应该是Mac OS 关机不彻底。原因如下：

- BIOS输入开机密码的界面出现了鼠标指针，而且可以移动指针。
用过 小米BIOS 的都知道，输入BIOS开机密码 和 BIOS 管理员密码的界面是不会出现鼠标指针的。如果说，内置键盘失灵是驱动造成的。那么鼠标指针突然出现了，难道是 USB 鼠标/触控板 驱动也有问题，过分加载吗？这个情况更像是 OC 的外设驱动 接管了 BIOS 的驱动。

**Comment by stevezhengshiqi** [comment]
@1457384613gh 驱动会给硬件注入固件，有时一些带有bug的驱动会注入有问题的代码导致硬件死锁。十代U的键盘问题完全是VoodooPS2在monterey下的bug造成的，或者是insyde BIOS有一些bug被偶然出发了。

Monterey确实改变了关机逻辑，可能间接导致VoodooPS2，但如果使用非VoodooPS2驱动来驱动键盘，比如[HIDPS2Keyboard](https://github.com/coolstar/HIDPS2Keyboard) 或者干脆不加载VoodooPS2，重启后键盘都是完好的，VoodooPS2背大锅。

**Comment by 1457384613gh** [comment]
> VoodooPS2背大锅

那我们的机型可以使用 非VoodooPS2 驱动吗？

**Comment by stevezhengshiqi** [comment]
> > VoodooPS2背大锅
> 
> 那我们的机型可以使用 非VoodooPS2 驱动吗？可以使用 HIDPS2Keyboard 吗？

可以使用 [HIDPS2Keyboard](https://github.com/coolstar/HIDPS2Keyboard), 但亮度快捷键等会失效。

**Comment by 1457384613gh** [comment]
可我认为，阻止 OC 过分接管 BIOS 的外设或者彻底关闭 Mac，才是最佳解决方案。理由如下：

- 无论如何，BIOS 自带键盘驱动，可以使用键盘。不需要 OC 的驱动强行接管到 BIOS 的外设。

- 假如能够 阻止 OC 过分接管BIOS 的外设或者可以彻底关闭 Mac。那么，PS/2 的外设驱动 是否对 BIOS 起作用就不重要并且无所谓了。

- 兴许还可以解决 从 Mac 关机以后放干电量的问题。如果关机不彻底，硬件一直都是在息屏状态被OC驱动强行接管并且浪费电量。

**Comment by stevezhengshiqi** [comment]
@1457384613gh OC并没有接管外设，在 OC Bootpicker阶段是由 BIOS自身驱动控制，但由于硬件在macOS下被留在了一个坏的状态，重启后并不能被BIOS驱动。

mac关机是彻底的，电量问题是因为不同系统之间的算法不同。

**Comment by 1457384613gh** [comment]
> OC并没有接管外设

OC 的确接管了 BIOS 的外设。

- 在 BIOS 不该出现鼠标指针的界面（输入管理员密码界面，输入BIOS开机密码界面），也出现了鼠标指针。这说明，OC 的 USB 鼠标/触控板 驱动 接管了 BIOS 的外设。

**Comment by stevezhengshiqi** [comment]
我们的触控板应该是 I2C 总线，HID设备，OC并没有载入相关的 efi驱动

**Comment by 1457384613gh** [comment]
我的意思是 OC 的 kext 驱动。
异常情况下，操作系统的驱动 和 efi 驱动也会互相影响，占用，挤掉吧？

我记得，我有一次 装载了 `AudioDXE.EFI`，然后 启动进入 windows，发现 Windows 的声卡驱动失败，系统处于禁音状态，无法调节音量。取消装载 `AudioDXE.EFI`后，重启，windows的声音恢复正常。可见，（当时是旧版的） AudioDXE.EFI 占用了接口 会导致 Windows 的声卡失灵。

那么同理反过来。
kext 驱动 占用接口，会不会影响重启以后的 efi 驱动的加载呢？

**Comment by stevezhengshiqi** [comment]
不太是，kext驱动开机才会执行start和probe函数载入，关机会执行stop函数，就算驱动有问题，系统也会强制卸载掉，但无法保证硬件里的固件是否卸载正确。目前键盘的表现是很典型的驱动没有以正常的方式关闭，从而导致死锁或者固件错误。

**Comment by 1457384613gh** [comment]
Thank you very much for your early reply and how earnest you are!​

**Comment by 1457384613gh** [comment]
我看到你收藏了英伟达开源内核模块；英伟达开源内核模块对黑苹果的建设来说，有没有一丝一毫的积极作用啊？？？
![image](https://user-images.githubusercontent.com/69227436/168027298-5e5cc438-b472-46fe-892d-cbb7a3776e33.png)
还有，BSD 的 显卡驱动对黑苹果的建设来说，有没有一丝一毫的积极作用呢？？？
![image](https://user-images.githubusercontent.com/69227436/168027969-70733efd-a794-4b1c-9aaf-171021b18d46.png)
https://www.nvidia.cn/Download/driverResults.aspx/187568/cn/
据说 Mac 的图形层涉及到 Darwin，跟 BSD 的图形层非常不一样。
[Darling](https://github.com/darlinghq/darling) 可以让 Linux/Unix 运行 Mac OS 的 app，包括图形界面的，说明图形界面还是有突破口的。
那么，英伟达的显卡驱动有移植成功的可能性吗？？？

**Comment by 1457384613gh** [comment]
静候别的大佬？那就是有可能咯。

**Comment by 1457384613gh** [comment]
> 据我所知，Launcheroption只有 disabled，full和short，根据https://github.com/acidanthera/OpenCorePkg/blob/master/Utilities/ocvalidate/README.md

这个是怎么回事啊？图形界面的OC编辑器 不是一直都可以设置 `LauncherOption=System` 吗？还有，你这两次更新的 EFI 设置的是 FULL，而我恰巧开启 Bitlocker 并且手头没有USB键盘，结果只能进入 macOS，进入Windows 需要输入很长的密钥解锁 Bitlocker，而且不进 Windows 就无法删除 FULL模式给OpenCore自动创建的默认启动项。更新 v1.6.6 以后，我输入了两次老长的 Bitlocker 密钥；更新了
 v1.6.7 以后，我用微PE工具箱 删除了 FULL模式给OpenCore创建的 UEFI boot entry。
![IMG_20220615_001420.jpg](https://user-images.githubusercontent.com/69227436/173626142-7f14813f-7a4-4e59-a965-194ad19c6806.jpg)

**Comment by stevezhengshiqi** [comment]
@1457384613gh 之前LauncherOption=System会被ocvalidate认为是错误输入，那条更新是修复这个问题的。

嗯明白你开启Bitlocker后的麻烦之处。我使用Full的原因是Windows更新会修改默认启动项，经常把Windows Boot Manager顶到第一位，给用户造成不方便。

**Comment by 1457384613gh** [comment]
> Windows更新会修改默认启动项

现在，应该不会了吧。
BcdStore 这里记录有默认引导器的信息。
![image](https://user-images.githubusercontent.com/69227436/173975376-13c3af4e-e84d-41c6-b1b5-90bb887e12a3.png)
我Windows更新了好几个版本都没有出现过 “Windows更新会修改默认启动项” 的情况。
万一会被篡改，我觉得现在突然把 `Full` 改成 `System` 也没关系，因为 【Bootstrap 模式中创建的启动选项】未被删除，依然可以工作，依然可以把 OC 调成默认的。
有 `Full` 需求的用户，把 `System` 改成 `Full` 很容易，把该项的值更改一下就好了。
但是，有 `System` 需求的用户，把 `Full` 改成 `System` 很繁琐，除了更改该项的值以外，还需删除【Bootstrap 模式中创建的启动选项】
- 有可能要输入 80位字符 的 Bitlocker 密钥，进入Windows 去删除
- 有可能需要 USB键盘，进入 BIOS 设置去删除
- 有可能需要 U盘启动 PE 去删除

考虑到需求后者的用户也不少，而且 后者繁琐程度胜于前者，再加上【防止Windows更新修改默认启动项】的这个原因好像过期了，🤣🤣🤣是不是以后更新的 EFI 要设置 LauncherOption=System 比较好？？？

**Comment by stevezhengshiqi** [comment]
@1457384613gh 我个人在使用Windows的时候比较大的累积更新是会自动把Windows Boot Manager顶到最前面的，这个也是OpenCore有LauncherOption的初衷：防止其他系统篡改启动项顺序。我还是坚持使用LauncherOption=Full，但我会把你这个情况记录在常见问题解答里。

**Comment by CobanRamo** [comment]
> 我记得，我有一次 装载了 `AudioDXE.EFI`，然后 启动进入 windows，发现 Windows 的声卡驱动失败，系统处于禁音状态，无法调节音量。取消装载 `AudioDXE.EFI`后，重启，windows的声音恢复正常。可见，（当时是旧版的） AudioDXE.EFI 占用了接口 会导致 Windows 的声卡失灵。

this was not the case with earlier AudioDXE.efi. at some point it was tinkered with and no longer worked with "Smart Sound Technology Audio Controller".

Solution is this; Arguments = --restore-nosnoop

![AudiDXE Efi](https://user-images.githubusercontent.com/68192365/177190564-69690004-f30a-4d72-92d4-6d37c00779c3.png)

HIDPS2Keyboard.kext.zip
