### ISSUE TITLE
> 删除 NullEthernet.kext

### ISSUE THREAD

**Issue by aKuan1693** [daliansky/XiaoMi-Pro-Hackintosh#654]
> 删除 NullEthernet.kext
> 删除 SSDT-RMNE.aml
> 更改网络配置
> 这个文件在哪删呀 移除以后稳定吗

目前，没什么异常的。
但是，不知道有什么副作用，所以 issue 一下。
如果 steve 觉得没副作用的话，应该会支持的吧。
  
需要删除的那两个文件在哪 啊 没找到在哪删
_Originally posted by @1457384613gh in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/653#issuecomment-1120350888_

**Comment by stevezhengshiqi** [comment]
acpi/ssdt-rmne
kext/nullethernet
建议在config里禁用而不是直接删除。
