### ISSUE TITLE
layout-id= 99 处于禁音状态，无法发声，不能调节音量

### ISSUE THREAD

**Issue by 1457384613gh** [daliansky/XiaoMi-Pro-Hackintosh#655]
我的机型 是 TM1963 MX350。
README.md 上 表示 这个机型有两个声卡节点，69 和 99。
我想对比一下，哪个节点发声好听，音质高。
然后，把 69 节点 改成了 99 节点。
发现，系统处于禁音状态，无法发声，不能调节音量。
该机型无法使用 99 节点，只能使用 69 节点，README.md 需要被编辑一下。

**Comment by stevezhengshiqi** [comment]
感谢测试，稍后就会修改README。
