### ISSUE TITLE
SSDT-LGPA350.aml 的作用，以及是否多余。

### ISSUE THREAD

**Issue by 1457384613gh** [daliansky/XiaoMi-Pro-Hackintosh#656]
我的机型是 TM1963 MX350。

根据教程，我应该开启 `SSDT-LGPA350.aml` ，并且关闭 `SSDT-LGPA.aml`。注释上提及 `Brightness key` ，应该是与 调节屏幕亮度的功能键有关吧？

一次疏忽，我在升级 EFI 的时候，忽略了这个步骤，开机以后，一切正常，键盘的功能键依然能够调节屏幕亮度。多次尝试以后，进行对比，发现两者 调节亮度 的情况几乎一模一样，没什么 bug。

假如是的，
- 为什么 `SSDT-LGPA.aml` 也对 MX350的设备调节亮度起作用？

假如不是的，
- 为什么`SSDT-LGPA.aml` 看起来好像没有对 MX350 造成任何 bug。

疑问：
- `SSDT-LGPA.aml`和`SSDT-LGPA350.aml` 这两个文件，除了文件名以外，内容是一样的吗？
- 其作用是映射 调节亮度 的功能键吗？
- MX350 设备 使用`SSDT-LGPA.aml`，会有什么副作用吗？可以不使用 `SSDT-LGPA350.aml` 吗？
- `SSDT-LGPA350.aml` 是多余的吗？为什么感觉，用错了也没出现 bug。
- 假如真的是多余的，可以删除吗？以后升级 EFI ，MX350 设备是不是也不需要作出调整了？

**Comment by stevezhengshiqi** [comment]
SSDT-LGPA的主要目的是重写 DSDT 中的 LGPA 方法，并往一些 Case 里注入 PS2/ADB 码来让 VoodooPS2 收到快捷键指令。

> SSDT-LGPA.aml和SSDT-LGPA350.aml 这两个文件，除了文件名以外，内容是一样的吗？

你可以通过 diff 命令或者肉眼比对 https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/main/ACPI/CML/Source/SSDT-LGPA.dsl 和 https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/main/ACPI/CML/Source/SSDT-LGPA350.dsl

> 其作用是映射 调节亮度 的功能键吗？

是的，还包括投影。

> MX350 设备 使用SSDT-LGPA.aml，会有什么副作用吗？可以不使用 SSDT-LGPA350.aml 吗？

我在 [SSDT-LGPA350.dsl](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/main/ACPI/CML/Source/SSDT-LGPA350.dsl) 开头的注释里有提到，MX350 的 DSDT 的 LGPA方法 和 MX250 的不一样，如果混用，我并不知道有什么后果。但保险起见，我用 MX350 的 DSDT 做了一份完全基于 MX350 的 SSDT-LGPA。你可以比对你的 DSDT 和  [MX250 的 DSDT](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/main/ACPI/origin/TM1905/XMACM500P0401/DSDT.aml)。

**Comment by 1457384613gh** [comment]
根据教程，使用对应的配置。
目前的快捷键情况如下：
（Fn锁关闭的状态。）

- F1: 【禁音】 正常
- F2: 【音量-】正常
- F3: 【音量+】正常
- F4: 【亮度-】正常
- F5: 【亮度+】正常
- F6: 【投影】按了以后，
{    按下 F1, F2, F3，自动打开 系统偏好设置——声音；
    按下 F4, F5，自动打开 系统偏好设置——显示器；
    字母键变成希腊字母，数字键变成特殊符号；
}
- F7: 【截屏】 文本框内键入“fi”
- F8: 【多任务视图】正常
- F9: 【触控板开关】正常
- F10: 【键盘背光】正常
- F11: 【prtscn】（printscreen）窗口悬浮，飞出屏幕边界；鼠标点击可以飞回来。
- F12: 【insert】嘟的响声 无明显反应


那几个不太正常的功能键，可以自定义映射吗？
F7 最不正常，居然是文本框内键入“fi”，别的还多少可以当作是 Mac OS 的 Feature。
F12 还没试出来是干嘛的，反正没有 insert 键的作用。

**Comment by stevezhengshiqi** [comment]
f12是单纯的f12。f7的异常尚不清楚，mx250机子上是正常的，日后再研究。

**Comment by stevezhengshiqi** [comment]
还有一种情况是，为了让这些快捷键运作，不能修改command键的键位，也就是设置 键盘 修饰键里的内容不能被修改。如果要修改，需要重新订做。

**Comment by 1457384613gh** [comment]
我的确有修饰键，交换了 option 和 command。
我点击“恢复默认”以后，F7 就没有出现 `fi` 了，但是，也没试出截屏选项。

**Comment by 1457384613gh** [comment]
那 F11 的作用呢？是类似于 Windows 右下角的【显示桌面】的作用吗？
printscreen 不应该是截取全屏保存到剪切板中吗？

**Comment by stevezhengshiqi** [comment]
prtscn映射成了f11，系统可能对f11有默认的快捷操作，详情见设置键盘快捷键。
