### ISSUE TITLE
小米 pro增强版睡眠后无法开机，强制开机也不行

### ISSUE THREAD

**Issue by giracle** [daliansky/XiaoMi-Pro-Hackintosh#658]
我的小米笔记本pro增强版2020
i7-10510 16GB 1TB版本，最近在安装完12.1的系统(使用的最新的EFI)后，出现了将笔记本盖子合上后，电脑黑屏，强制关机后再次按下电源键还是无法启动电脑，只有将电源断电后才能启动。请问这个大家遇到过吗？有什么解决办法呢？非常感谢大家

**Comment by qingfengfenga** [comment]
看这个，我是类似的问题，去售后换了电池，刚用几天，目前没有再出现过睡死的问题 #414
