### ISSUE TITLE
i7-8550U 电池供电 睿频0.8Ghz battery power turbo 0.8Ghz

### ISSUE THREAD

**Issue by vidalouiswang** [daliansky/XiaoMi-Pro-Hackintosh#659]
**State the model**
XiaoMi Pro 15.6 i7-8550U MX150

**State the version of the EFI**
1.6.5

**MacOS version**
12.3

**SSD**
Samsung PM961 256GB(NVME, EFI 300MB, Windows 10 21H2 50GB NTFS, MacOS 12.3 rest of space APFS)
Micron MX600 512GB(SATA, currently full drive format as NTFS)

**Describe the bug**
首先感谢各位大佬帮我们制作的各种工具和驱动，我也是一名开发者，明白调试代码的工作量，谢谢你们的付出。

At first, thanks to all those guys who made tools and drivers for us, I'm also a developer, I know how many time you spent to debug those codes, thank you for all of your hard works.

以下是描述: 

Describe down below:

电池供电模式通过Intel Power Gadget观看CPU发现在闲置或轻度工作时，OS Core frequency request 一直处于1.4~1.6Ghz, 平均频率在1.5Ghz左右，在Windows下大部分时间是0.8Ghz，经过测试，在MacOS下平均每小时耗电量约为20%，Windows是13%，在B站观看FHD视频，使用的浏览器是Google Chrome，Intel核显已正常驱动，Chrome硬件加速已打开。Windows使用的电源选项是“更长的电池寿命”。

According to Intel Power Gadget informations, OS Core frequency request allways set up to 1.4 to 1.6Ghz, core average frequency is 1.5Ghz, when system idle or light works, only battery power. The frequency is most of time 0.8Ghz on Windows. The power consumption on MacOS is 20% per hour, 13% on Windows, watching online FHD videos on bilibili.com using Google Chrome. The Intel HD 620 had been powered successfully and the settings "Hardware acceleration" set to "on" both Windows and MacOS. The power config on Windows is "More battery lifetime".

看了OpenCore官方的教程，也看了这个仓库里的issues，尝试过CPUFriendFriend和one-key-CPUFriend，各种组合都尝试了，系统请求频率一直无法降到0.8Ghz，难道是我选的机型不对吗？我选择的是Macbook 16, 1 i9-9980HK，但是我也尝试过用其他的i5机型的Mac-xxx.plist生成CPUFriendDataProvider.kext，也无法到0.8Ghz。
但是不管用哪个plist文件生成的kext, Package功耗好像和Windows下Intel Power Gadget显示的差不多。难道是网卡或者其他的驱动不够完善才导致的功耗增加？另外，笔记本是新换的官方原厂电池。

I had read offical documents of OpenCore and all issues of this repo, I had tried CPUFriendFriend and one-key-CPUFriend, almost every combinations of different arguments, but MacOS Core frequency can not be set to 0.8Ghz automatically(by system). Is there and any relations to my chosen of machine type? I chose "Macbook 16, 1 i9-9980HK", and I had tried using other "Mac-xxx.plist" files of machine type to generate CPUFriendDataProvider.kext, like i5, also got same result. 
But whatever plist file I use to generate kext, power of Package shows almost same value as Windows. I wonder is there any relations to imperfect drivers of Intel 8265 or other drivers cause more power consumptions? BTW, the battery is brand new from offical XiaoMi fatory. 

总体来说除了电池续航表现不够好，其他一切运行都很完美，我是黑苹果新手，我会继续研究和学习，尝试开发指纹驱动，再次感谢各位的辛勤开发，谢谢。

Overall, everything works fine except battery usage, I'm new to Hackintosh, I will keep researching and learning to get further, try to make fingerprint available on MacOS, thanks to all you guys efforts.

空闲和轻度负载时CPU温度在35~40度。

The temperature of CPU is around 35~40 degrees.

**Screenshots**
![截屏2022-05-18 16 39 46](https://user-images.githubusercontent.com/26226049/169015995-9dd54594-b328-4604-930a-af1d0be5a1f7.png)

**Comment by leiyutian007** [comment]
读卡器已经可以驱动了

**Comment by vidalouiswang** [comment]
> 读卡器已经可以驱动了

哦是吗？那太好了，我去搜索一下，谢谢。

**Comment by vidalouiswang** [comment]
> 读卡器已经可以驱动了

之前没有仔细看文档，确实是有写。

**Comment by stevezhengshiqi** [comment]
因为macOS缺少thermal_daemon等功耗优化功能，黑苹果机器会比Windows耗电。
比如 [zhen-zen](https://github.com/zhen-zen/ThermalSolution/commits?author=zhen-zen) 最近在开发的 [ThermalSolution](https://github.com/zhen-zen/ThermalSolution) 是个不错的方案，但还在初期阶段。

目前想降低功耗的话，目前只能通过voltageshift降压来实现。

> 我选择的是Macbook 16, 1 i9-9980HK

这个机型很显然不适用于你的 i7-8550U，i7-8550U TDP为15瓦，而你选择的机型是标压U，TDP为45W。本仓库默认的MacBookPro15,4是比较贴合你的机型的。

**Comment by vidalouiswang** [comment]
> 因为macOS缺少thermal_daemon等功耗优化功能，黑苹果机器会比Windows耗电。 比如 [zhen-zen](https://github.com/zhen-zen/ThermalSolution/commits?author=zhen-zen) 最近在开发的 [ThermalSolution](https://github.com/zhen-zen/ThermalSolution) 是个不错的方案，但还在初期阶段。
> 
> 目前想降低功耗的话，目前只能通过voltageshift降压来实现。
> 
> > 我选择的是Macbook 16, 1 i9-9980HK
> 
> 这个机型很显然不适用于你的 i7-8550U，i7-8550U TDP为15瓦，而你选择的机型是标压U，TDP为45W。本仓库默认的MacBookPro15,4是比较贴合你的机型的。

好的，非常感谢回复。
