### ISSUE TITLE
电池供电续航优化 Battery supply optimization

### ISSUE THREAD

**Issue by vidalouiswang** [daliansky/XiaoMi-Pro-Hackintosh#664]
中文:
系统的快捷指令没有检测供电类型的功能，所以我fork了https://github.com/sicreative/VoltageShift/ ，添加了检测供电类型功能，这样可以在系统的快捷指令中方便的检测供电类型，然后使用快捷指令即可实现能耗控制。

地址：
https://github.com/vidalouiswang/VoltageShift/

使用binary下的可执行文件替换原版的即可，或者你也可以自己编译。

用法：

./voltageshift ischarging

AC供电返回1，UPS和电池返回0。

目前我的使用方法供大家参考：
把VoltageShift.kext 复制到OC/Kexts/
config.plist启用扩展
然后把voltageshift 放在~/

建立几个菜单栏快捷指令：
低能耗: 执行shell: ~/voltageshift power 5 6
平衡: 执行shell: ~/voltageshift power 10 15
高性能: 执行shell: ~/voltageshift power 28 44

再建立一个自己循环的快捷指令，每隔一分钟 ~/voltageshift ischarging，返回0的话就自动执行别的设置能耗的捷径就可以了。

看了苹果的API，有个电源切换的通知API，我还是个新手，我回头再研究下。

English:
The Shortcut application does not have the function which could detect type of power supply, so I forked https://github.com/sicreative/VoltageShift/ , and I added this function to it. Then we could get current power supply type in stdout. And you could use this combined with Shortcut to change power limitation automatically.

URL: 
https://github.com/vidalouiswang/VoltageShift/

Replace original voltageshift with file in folder binary. Or you could compile it yourself.

Usage:

./voltageshift ischarging

1 will be print if AC connected, 0 for UPS and built-in battery.

Currently, my method is like this:
Copy VoltageShift.kext to OC/Kexts/
Enable extension in config.plist
Put voltageshift into folder ~/

Then build several shortcut:
Low energy: exec shell: ~/voltageshift power 5 6
Balanced: exec shell: ~/voltageshift power 10 15
High performance: exec shell: ~/voltageshift power 28 44

Add extra shortcut loop itself to detect power supply type, like every 60 secs, if the return value is 0 then execute other shortcut to set power limitation automatically.

I have seen that Apple has an API could let application be notified if power supply type changed, but I'm still a beginner of XCode, so I leave this later.

![截屏2022-05-22 23 33 33](https://user-images.githubusercontent.com/26226049/169703712-6ba4d23d-9f2c-4bb7-843a-be954cb5431f.png)
![截屏2022-05-22 23 34 01](https://user-images.githubusercontent.com/26226049/169703714-29c1dbce-91ed-4461-b64b-5f88dca8d80a.png)
![截屏2022-05-22 23 36 26](https://user-images.githubusercontent.com/26226049/169703716-e34bc4c3-5dd1-4e2e-9741-464d2fc015e9.png)

**Comment by Menchen** [comment]
You could just used the AC information in system information instead of modifying VoltageShift...

```bash
system_profiler SPPowerDataType | grep 'Connected: '
```

or one liner in quiet mode

```bash
system_profiler SPPowerDataType | grep 'Connected: No$' -q
```

**Comment by vidalouiswang** [comment]
> You could just used the AC information in system information instead of modifying VoltageShift...
> 
> ```shell
> system_profiler SPPowerDataType | grep 'Connected: '
> ```
> 
> or one liner in quiet mode
> 
> ```shell
> system_profiler SPPowerDataType | grep 'Connected: No$' -q
> ```

Oh thank you, I'm didn't know this before.

**Comment by vidalouiswang** [comment]
> You could just used the AC information in system information instead of modifying VoltageShift...
> 
> ```shell
> system_profiler SPPowerDataType | grep 'Connected: '
> ```
> 
> or one liner in quiet mode
> 
> ```shell
> system_profiler SPPowerDataType | grep 'Connected: No$' -q
> ```

I had searched is there some system commands could detect power state, but I didn't find any information from internet, so I modified VoltageShift. :D
