### ISSUE TITLE
Touchpad does not show up in settings

### ISSUE THREAD

**Issue by lakshanthad** [daliansky/XiaoMi-Pro-Hackintosh#667]
**Pre-requirement**
- I have already rebuilt the kextcache and restarted

**State the model**
- Xiaomi NoteBook Pro 15.6'' i7-8550U GTX1050 16GB

**State the version of the EFI**
- v1.6.6 (XiaoMi_Pro-KBL-Clover-v1.6.6.zip)

**Describe the bug**
- Touchpad does not show up in settings. When I click on the touchpad, it does not register as a left click. I think it registers as a force touch. Also right-click does not work.

**Screenshots**
<div align=center><img width=400 src="https://user-images.githubusercontent.com/20147381/172423338-d3125e95-15b0-4a52-8b21-d67b9e63e1e8.png"/></div>

**Attach your entire EFI folder**
- [EFI.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/8854696/EFI.zip)

**Attach system.log**
- Result of `log show --predicate "processID == 0" --last boot --debug | grep "ERR"`:
[log.txt](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/8854738/log.txt)

**MacOS ISO location**
- https://www.mediafire.com/file/4fcx0aeoehmbnmp/macOS+Monterey+by+Techrechard.com.iso/file

**Comment by stevezhengshiqi** [comment]
@lakshanthad Hi, can you confirm that your battery works good? Do you have battery percentage working?

**Comment by stevezhengshiqi** [comment]
The trackpad setting panel needs a working battery. Although it sounds weird, it is the case.

**Comment by lakshanthad** [comment]
> Also, you can disable force click by go to ~/Library/Preferences/com.apple.AppleMultitouchTrackpad.plist and changing "ForceSuppressed" to True.
> 
> Ref: https://www.reddit.com/r/hackintosh/comments/jvwtuz/is_there_a_way_to_disable_force_touch_with/

Downloading XCode now to edit the plist file. Will keep updated when it is done.

Will this also fix the touch to left click without hard pressing on the trackpad?

**Comment by lakshanthad** [comment]
> The trackpad setting panel needs a working battery. Although it sounds weird, it is the case.

This could be added to FAQ I believe. to help out others who encounter a similar issue.

**Comment by stevezhengshiqi** [comment]
I will say it's more like a rare case, but I will consider that. Thank you for mentioning it!

**Comment by lakshanthad** [comment]
Also a quick question before closing this. Can I update this when minor updates are rolled? 

For example 12.xxxx

**Comment by stevezhengshiqi** [comment]
> Also a quick question before closing this issue.. Can I update the OS when minor updates are rolled?

Yes, you can do that for macOS < 13.

> Also does it support to update to major versions. For example from 12 to 13? Or we need to go through the process of installing from bootable USB again?

For now, we can't upgrade from macOS12 to 13, as briefly explained in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/666#issuecomment-1148423536. We do not need a bootable USB once our EFI supports macOS13. However, backup is always recommended for major upgrade.

**Comment by Neolo** [comment]
Same problem, trackpad not detected, plist has already YES set. And of course there is a battery in the laptop.

**Comment by ssrlive** [comment]
Me too, and how do you resolve it? @Delitants 
> Same problem, trackpad not detected, plist has already YES set. And of course there is a battery in the laptop.
