### ISSUE TITLE
CLOVER升级到1.6.6后触摸板的右键无法使用

### ISSUE THREAD

**Issue by leiyutian007** [daliansky/XiaoMi-Pro-Hackintosh#668]
我的笔记本是kbl平台，触摸板一切正常，看到1.6.6放出来后，升级efi.都正常，就是触摸板的右键无法调出。我在偏好设置里面取消，改了设置，都不行。我的macos 是12.3   clover 1.6.6

**Comment by stevezhengshiqi** [comment]
截图看一下你的触控板设置

**Comment by leiyutian007** [comment]
![截屏2022-06-12 19 43 46](https://user-images.githubusercontent.com/81942744/173231619-3242c9e6-0c98-4594-984a-c0fc4ebd3684.png)

**Comment by stevezhengshiqi** [comment]
辅助点按改成双指点按有效吗，如果你还是想右下角点按，可以回滚VoodooI2C版本 https://github.com/VoodooI2C/VoodooI2C

**Comment by leiyutian007** [comment]
测试了oc，不行，下载了您给的voodool2c也是不行，我回去1.6.4了

**Comment by stevezhengshiqi** [comment]
1.6.4使用的voodooi2c版本为https://github.com/VoodooI2C/VoodooI2C/releases/tag/2.6.5 可以自行回滚版本。

触控板相关问题可以向触控板驱动的issue提问https://github.com/VoodooI2C/VoodooI2C/issues，本仓库只使用最新驱动，并无改善他们的能力。

**Comment by stevezhengshiqi** [comment]
根据https://github.com/VoodooI2C/VoodooI2C/issues/496，这是个VoodooI2C v2.7的已知问题，使用旧版即可。
