### ISSUE TITLE
Older OS installation

### ISSUE THREAD

**Issue by wildanbaraja** [daliansky/XiaoMi-Pro-Hackintosh#679]
Hi, I wanna ask simple question. Can we install older OS, like Lion or Mountain Lion using opencore? If yes, please inform me the best efi version that I can install.
thank you in advance

**Comment by stevezhengshiqi** [comment]
Are you using Xiaomi Pro? Because Xiaomi Pro uses 8th Gen CPU with NVMe SSD, it can not install macOS older than Sierra.
