### ISSUE TITLE
使用过程中或者睡眠唤醒偶发死机

### ISSUE THREAD

**Issue by jackxuechen** [daliansky/XiaoMi-Pro-Hackintosh#680]
**Pre-requirement**
- Try to rebuild the kextcache and restart whenever you encounter a problem. It always works like a charm!
- To rebuild the kextcache, run `sudo kextcache -i /` in `Terminal.app`.
- If you are using OpenCore, also try to reset NVRAM. Press `Space` key when you are in OpenCore boot page and choose `Reset NVRAM`.

**State the model**
- XiaoMi-Pro MX150

**State the version of the EFI**
- 1.6.8

**Describe the bug**
使用过程中或者睡眠唤醒偶发死机

**System log**
{"timestamp":"2022-07-27 15:58:13.00 +0800","bug_type":"210","os_version":"macOS 12.5 (21G72)","incident_id":"E9353B86-E650-4750-A8E7-FD1FD2A86372"}
{"macOSProcessedStackshotData":"bm8gb24gZGlzayBwYW5pYyBzdGFja3Nob3QgZm91bmQgaW4gY29yZWZpbGU=","macOSPanicString":"panic(cpu 0 caller 0xffffff801e3856a2): nvme: \"3rd party NVMe controller. Loss of MMIO space. Write. fBuiltIn=1 MODEL=SAMSUNG MZVLW256HEHP-00000 FW=CXB7401Q CSTS=0xffffffff US[1]=0x0 US[0]=0x20c VID=0x144d DID=0xa804 CRITICAL_WARNING=0x0.\\n\" @IONVMeController.cpp:6090\nPanicked task 0xffffff9bbe056670: 218 threads: pid 0: kernel_task\nBacktrace (CPU 0), panicked thread: 0xffffffa08b800540, Frame : Return Address\n0xfffffff2d107ba20 : 0xffffff801ba7fd6d \n0xfffffff2d107ba70 : 0xffffff801bbe1016 \n0xfffffff2d107bab0 : 0xffffff801bbd0383 \n0xfffffff2d107bb00 : 0xffffff801ba1fa70 \n0xfffffff2d107bb20 : 0xffffff801ba8013d \n0xfffffff2d107bc40 : 0xffffff801ba7f8f6 \n0xfffffff2d107bca0 : 0xffffff801c314d93 \n0xfffffff2d107bd90 : 0xffffff801e3856a2 \n0xfffffff2d107bda0 : 0xffffff801e3687cb \n0xfffffff2d107bdd0 : 0xffffff801c24a0b5 \n0xfffffff2d107be40 : 0xffffff801c249fb8 \n0xfffffff2d107be70 : 0xffffff801bad2655 \n0xfffffff2d107bee0 : 0xffffff801bad3722 \n0xfffffff2d107bfa0 : 0xffffff801ba1f19e \n      Kernel Extensions in backtrace:\n         com.apple.iokit.IONVMeFamily(2.1)[B75F47AC-091B-38F4-99D7-F8BF0C8E6910]@0xffffff801e360000->0xffffff801e38cfff\n            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[B1C6E01A-DB3B-350F-A15E-696BF6EFC16D]@0xffffff801d1b1000->0xffffff801d1d2fff\n            dependency: com.apple.iokit.IOPCIFamily(2.9)[1C239712-AA61-3895-87E3-236603DBD253]@0xffffff801e635000->0xffffff801e661fff\n            dependency: com.apple.iokit.IOReportFamily(47)[66824C9A-7BC1-3F5D-A056-D789C8A86B8C]@0xffffff801e673000->0xffffff801e675fff\n            dependency: com.apple.iokit.IOStorageFamily(2.1)[24743B95-072D-31C4-A59D-7FF38502C0C4]@0xffffff801e778000->0xffffff801e78efff\n\nProcess name corresponding to current thread (0xffffffa08b800540): kernel_task\nBoot args: darkwake=0 chunklist-security-epoch=0 -chunklist-no-rev2-dev\n\nMac OS version:\n21G72\n\nKernel version:\nDarwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1\/RELEASE_X86_64\nKernel UUID: E3E2BC4D-7B6F-39CC-8890-73A6FB513830\nKernelCache slide: 0x000000001b800000\nKernelCache base:  0xffffff801ba00000\nKernel slide:      0x000000001b810000\nKernel text base:  0xffffff801ba10000\n__HIB  text base: 0xffffff801b900000\nSystem model name: MacBookPro15,4 (Mac-53FDB3D8DB8CA971)\nSystem shutdown begun: NO\nPanic diags file available: YES (0x0)\nHibernation exit count: 0\n\nSystem uptime in nanoseconds: 193115797280043\nLast Sleep:           absolute           base_tsc          base_nano\n  Uptime  : 0x0000afa3467f584f\n  Sleep   : 0x000014208ba40e12 0x000000004db0f64c 0x00001403ec019cb2\n  Wake    : 0x000014208f293aeb 0x000000004d94dec7 0x000014208ca32157\nCompressor Info: 12% of compressed pages limit (OK) and 12% of segments limit (OK) with 6 swapfiles and OK swap space\nZone info:\n  Zone map: 0xffffff90897f3000 - 0xffffffb0897f3000\n  . PGZ   : 0xffffff90897f3000 - 0xffffff908b7f4000\n  . VM    : 0xffffff908b7f4000 - 0xffffff9557ff3000\n  . RO    : 0xffffff9557ff3000 - 0xffffff96f17f3000\n  . GEN0  : 0xffffff96f17f3000 - 0xffffff9bbdff3000\n  . GEN1  : 0xffffff9bbdff3000 - 0xffffffa08a7f3000\n  . GEN2  : 0xffffffa08a7f3000 - 0xffffffa556ff3000\n  . GEN3  : 0xffffffa556ff3000 - 0xffffffaa237f3000\n  . DATA  : 0xffffffaa237f3000 - 0xffffffb0897f3000\n  Metadata: 0xffffffb089803000 - 0xffffffb0a9803000\n  Bitmaps : 0xffffffb0a9803000 - 0xffffffb0af803000\n\n\n\n"}

**Comment by stevezhengshiqi** [comment]
根据日志来看是由于NVMe硬盘导致的。也有可能是别的问题诱发的，老问题，暂无解决方案。

**Comment by jackxuechen** [comment]
重新固定了下主硬盘，没有在发过该问题
