### ISSUE TITLE
MacOS 13 Ventura beta

### ISSUE THREAD

**Issue by matvada** [daliansky/XiaoMi-Pro-Hackintosh#682]
Good afternoon everyone,
How far have we are with compatibility with Ventura beta versions?
With EFI 1.6.9 is it possible to proceed with the OTA update without modifying anything else?
Thank you

**Comment by stevezhengshiqi** [comment]
OC v1.6.9 supports the latest Ventura beta. However, a full backup is always recommended.

**Comment by matvada** [comment]
Hello @stevezhengshiqi thank you for your answer.
I made a full Time Machine backup yesterday.

I'll post the result of the upgrade.
Thanks

**Comment by matvada** [comment]
Installation completed in about 1 hour without any problems!
I joined the open beta program following this URL: https://beta.apple.com/sp/betaprogram and and the download started directly from the settings.

**Comment by stevezhengshiqi** [comment]
> Installation completed in about 1 hour without any problems!
> I joined the open beta program following this URL: https://beta.apple.com/sp/betaprogram and and the download started directly from the settings.

Nice job! Glad to hear that.

**Comment by stevezhengshiqi** [comment]
@matvada Hi matvada. If you are still using the latest Ventura beta, could you help me upload a bluetooth process to investigate? I would like to check if BlueToolFixup is still valid in the latest Ventura beta.

File location: /usr/sbin/bluetoothd

**Comment by matvada** [comment]
@stevezhengshiqi i'm very sorry for my late answer, I know it's been several day but if you still need help i can upload the file on Monday.
Thanks
