### ISSUE TITLE
更新Monterey后经常“您的电脑因出现问题而导致重启”

### ISSUE THREAD

**Issue by coocv** [daliansky/XiaoMi-Pro-Hackintosh#683]
panic(cpu 0 caller 0xffffff801d6a9b3a): mbuf_watchdog: 1 waiters stuck for 44 secs
46267/46367 mbufs in use:
	45543 mbufs allocated to data
	724 mbufs allocated to packet headers
	100 mbufs allocated to caches
324/1364 mbuf 2KB clusters in use
22552/22561 mbuf 4KB clusters in use
1/72 mbuf 16KB clusters in use
105867 KB allocated to network (approx. 96% in use)
0 KB returned to the system
worker thread runs: 22, expansions: 561, cl 0/0, bigcl 20/38392, 16k 1/21
worker thread last run time: 4116 (44 seconds ago)

top proc mbuf space 32768 bytes by ClashX:3261

mbuf leak detection table:
	total captured: 2931 (one per 500)
	total allocs outstanding: 149
	new hash recorded: 2886 allocs, 2318 traces
	hash collisions: 62 allocs, 41 traces
	overwrites: 2336 allocs, 0 traces
	lock conflicts: 0

top 5 outstanding traces:
[1] 43 outstanding alloc(s), 416 hit(s), 2 collision(s)
[2] 39 outstanding alloc(s), 43 hit(s), 1 collision(s)
[3] 29 outstanding alloc(s), 56 hit(s), 0 collision(s)
[4] 15 outstanding alloc(s), 40 hit(s), 0 collision(s)
[5] 12 outstanding alloc(s), 286 hit(s), 0 collision(s)

    trace [1]           trace [2]           trace [3]       	trace [4]           trace [5]      
    ------------------  ------------------  ------------------      ------------------  ------------------ 
 1: 0xffffff80008a82ba  0xffffff80008a82ba  0xffffff80008a82ba  0xffffff80008a82ba  0xffffff80008a82ba  
 2: 0xffffff8000881e69  0xffffff8000881f22  0xffffff8000881f22  0xffffff8000881e69  0xffffff8000881e69  
 3: 0xffffff80008ac298  0xffffff80008a723d  0xffffff80008ae915  0xffffff80008a71ea  0xffffff80008ae915  
 4: 0xffffff80008b04cb  0xffffff8000881dde  0xffffff800087c05a  0xffffff8000881dde  0xffffff800087c05a  
 5: 0xffffff800087b423  0xffffff80008ae915  0xffffff8002ba10bd  0xffffff80008ae915  0xffffff8002ba10bd  
 6: 0x0  0xffffff800087c05a  0x0  0xffffff800087c05a  0x0  
 7: 0x0  0xffffff8002ba10bd  0x0  0xffffff8002ba10bd  0x0  
 8: 0x0  0x0  0x0  0x0  0x0  
 9: 0x0  0x0  0x0  0x0  0x0  
10: 0x0  0x0  0xffffff8000a44e54  0x0  0xffffff8000a44e54  
11: 0x0  0x0  0xffffff8000a4370e  0x0  0xffffff8000a4370e  
12: 0x0  0xffffff8000a44e54  0xffffff8000a42d37  0xffffff8000a44e54  0xffffff8000a42d37  
13: 0xffffff8000a44e54  0xffffff8000a4370e                      0xffffff8000a4370e                      
14: 0xffffff8000a4370e  0xffffff8000a42d37                      0xffffff8000a42d37                      
15: 0xffffff8000a42d37                                                                                  
16:                                                                                                     

Panicked task 0xffffff8b66373030: 4 threads: pid 236: symptomsd
Backtrace (CPU 0), panicked thread: 0xffffff95015fc000, Frame : Return Address
0xffffffe5a7ce2dc0 : 0xffffff801d07fd6d 
0xffffffe5a7ce2e10 : 0xffffff801d1e1086 
0xffffffe5a7ce2e50 : 0xffffff801d1d03f3 
0xffffffe5a7ce2ea0 : 0xffffff801d01fa70 
0xffffffe5a7ce2ec0 : 0xffffff801d08013d 
0xffffffe5a7ce2fe0 : 0xffffff801d07f8f6 
0xffffffe5a7ce3040 : 0xffffff801d914e03 
0xffffffe5a7ce3130 : 0xffffff801d6a9b3a 
0xffffffe5a7ce31c0 : 0xffffff801d6a7837 
0xffffffe5a7ce3230 : 0xffffff801d681dde 
0xffffffe5a7ce32a0 : 0xffffff801d6a723d 
0xffffffe5a7ce3340 : 0xffffff801d681dde 
0xffffffe5a7ce33b0 : 0xffffff801d6ae915 
0xffffffe5a7ce3440 : 0xffffff801d3dfa5e 
0xffffffe5a7ce3480 : 0xffffff801d3e034c 
0xffffffe5a7ce3b30 : 0xffffff801d3dee2e 
0xffffffe5a7ce3c80 : 0xffffff801d63803b 
0xffffffe5a7ce3cd0 : 0xffffff801d6ba019 
0xffffffe5a7ce3de0 : 0xffffff801d6cc911 
0xffffffe5a7ce3ed0 : 0xffffff801d6cc523 
0xffffffe5a7ce3f40 : 0xffffff801d78918b 
0xffffffe5a7ce3fa0 : 0xffffff801d020236 

Process name corresponding to current thread (0xffffff95015fc000): symptomsd
Boot args: darkwake=0

Mac OS version:
21G83

Kernel version:
Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64
Kernel UUID: D0DC2052-71F4-3DCB-B189-BEE5A59B3B42
KernelCache slide: 0x000000001ce00000
KernelCache base:  0xffffff801d000000
Kernel slide:      0x000000001ce10000
Kernel text base:  0xffffff801d010000
__HIB  text base: 0xffffff801cf00000
System model name: MacBookPro15,3 (Mac-1E7E29AD0135F9BC)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 4159863349517
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000003c88b2d65ee
  Sleep   : 0x0000025f1d4dc51e 0x0000000a99e02244 0x0000000000000000
  Wake    : 0x0000025f20bccd2f 0x000000004a8e1a52 0x0000025f1df2309e
Compressor Info: 14% of compressed pages limit (OK) and 19% of segments limit (OK) with 5 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff8031c2a000 - 0xffffffa031c2a000
  . PGZ   : 0xffffff8031c2a000 - 0xffffff8033c2b000
  . VM    : 0xffffff8033c2b000 - 0xffffff850042a000
  . RO    : 0xffffff850042a000 - 0xffffff8699c2a000
  . GEN0  : 0xffffff8699c2a000 - 0xffffff8b6642a000
  . GEN1  : 0xffffff8b6642a000 - 0xffffff9032c2a000
  . GEN2  : 0xffffff9032c2a000 - 0xffffff94ff42a000
  . GEN3  : 0xffffff94ff42a000 - 0xffffff99cbc2a000
  . DATA  : 0xffffff99cbc2a000 - 0xffffffa031c2a000
  Metadata: 0xffffffe580fe2000 - 0xffffffe5a0fe2000
  Bitmaps : 0xffffffe5a0fe2000 - 0xffffffe5a6fe2000

**State the model**
- e.g. XiaoMi-Pro 8th GTX

**State the version of the EFI**
- e.g v1.7.0

**Comment by kvcoo** [comment]
> 检查config里的SystemProductName

嗯，受您的指导我已经改成了MacBookPro15,4，为了隐私，我将序列号抹除了。
![截屏2022-09-09 08 13 41](https://user-images.githubusercontent.com/70266699/189247251-4c66edfb-1b95-4fbf-b20d-de6d215cd2e5.png)

[config.plist.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/9531342/config.plist.zip)

**Comment by stevezhengshiqi** [comment]
@kvcoo Misc-Serial里你有定制东西，是不需要的。
<img width="403" alt="Screen Shot 2022-09-09 at 00 09 00" src="https://user-images.githubusercontent.com/36894554/189270101-2039e28a-82ae-4b9f-ae55-cff7484a4c91.png">

**Comment by kvcoo** [comment]
> @kvcoo Misc-Serial里你有定制东西，是不需要的。
> <img alt="Screen Shot 2022-09-09 at 00 09 00" width="403" src="https://user-images.githubusercontent.com/36894554/189270101-2039e28a-82ae-4b9f-ae55-cff7484a4c91.png">
> 而且你的编辑器版本低了，最新1.7.0用的OpenCore版本是0.8.4。不建议使用OpenCore Configurator修改config。

这次我使用PlistEdit Pro来修改config，我想它应该没问题了
[config.plist.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/9536389/config.plist.zip)
