### ISSUE TITLE
MacOS 13 Ventura 频繁死机重启

### ISSUE THREAD

**Issue by HKMV** [daliansky/XiaoMi-Pro-Hackintosh#688]
更新ventura bate2以后没多久，开机后5分钟内必死机或重启，已升级最新配置1.7.1问题依旧。
已经测试清除nvme,不到没解决问题反而加重了问题，每次开机都会有一堆软件提示已损坏

日志如下：
![IMG_20221014_225631.jpg](https://user-images.githubusercontent.com/26456469/195880022-9ec8b1f9-3f5e-4e92-8415-3485011e2cdf.jpg)
![IMG_20221014_225356.jpg](https://user-images.githubusercontent.com/26456469/195880041-91580707-fca5-429e-b4fa-207c3a027bc3.jpg)
![IMG_20221014_231339.jpg](https://user-images.githubusercontent.com/26456469/195881106-71965791-735e-4af1-9da5-c929757bc53a.jpg)

请问各位大佬，是什么原因导致的呢？

**Comment by stevezhengshiqi** [comment]
@HKMV 说一下机型。然后确认下两个硬盘槽都没有插入PM981。

**Comment by HKMV** [comment]
> @HKMV 说一下机型。然后确认下两个硬盘槽都没有插入PM981。

型号是:mibook pro2019 mx250
主槽位是pm981,但是已经使用您之前发我的aml禁用掉了。

**Comment by Leon-zym** [comment]
@HKMV 提示软件已损坏的问题，不知道你有没有安装腾讯柠檬，腾讯柠檬的清理垃圾在Ventura上有个bug会导致.app损坏。
https://www.v2ex.com/t/881497

**Comment by HKMV** [comment]
> @HKMV 提示软件已损坏的问题，不知道你有没有安装腾讯柠檬，腾讯柠檬的清理垃圾在Ventura上有个bug会导致.app损坏。
> https://www.v2ex.com/t/881497

是的使用了，请问有解决方案吗？

**Comment by HKMV** [comment]
一直重启这个问题是bate2的bug,昨天通过下载最新正式版镜像，写入到U盘升级后，没再发生死机重启的情况。
