### ISSUE TITLE
Updating KBL to 1.7.1

### ISSUE THREAD

**Issue by Chazy12** [daliansky/XiaoMi-Pro-Hackintosh#690]
I would love to update OC KBL to the latest 1.7.1 to update the OS to Ventura.
Reading the update FAQ it says to delete and replace the folder "Boot" and "OC", but in the 1.7.1 package the structure is different..

**Comment by Chazy12** [comment]
Old folder structure VS new folder to update

![PXL_20221025_223119187](https://user-images.githubusercontent.com/6653347/197875977-b2aaff2e-ddc1-436a-bfc4-6b3c55645761.jpg)
![PXL_20221025_223136924](https://user-images.githubusercontent.com/6653347/197875987-a3911898-3324-49a8-850f-00be60ad038b.jpg)

**Comment by stevezhengshiqi** [comment]
Boot and OC folders sit inside the EFI folder.

**Comment by Chazy12** [comment]
Yes, but the release 1.7.1 folder structure is different. There's not "boot" and "OC" folder..

**Comment by Chazy12** [comment]
So. Just update them? Others not?

**Comment by stevezhengshiqi** [comment]
Yes. Other folders are for additional tweats.
