### ISSUE TITLE
3.5mm耳机孔在电脑不连接充电器时睡眠后唤醒失灵

### ISSUE THREAD

**Issue by BeiBeiMoe** [daliansky/XiaoMi-Pro-Hackintosh#693]
- 存在的问题：

> 电脑在不使用电源适配器的情况下，睡眠后唤醒时，3.5mm耳机孔连接耳机无声，但是外放有声，且系统能够正常识别接入耳机。在使用电源适配器后，电脑睡眠再唤醒，耳机有声音。求大佬的解决方案。

- 当前机型：

> Xiaomi Pro 15.6 GTX (TM1707)

- 使用系统

> Monterey

**Comment by stevezhengshiqi** [comment]
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/main/ALCPlugFix/README_CN.md

**Comment by BeiBeiMoe** [comment]
感谢大佬🙏

> https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/main/ALCPlugFix/README_CN.md

**Comment by xjh169** [comment]
在终端输入以下命令并回车：
sh -c "$(curl -fsSL https://hackintosh.stevezheng.workers.dev/https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/main

出现：(35) error:02FFF036:system library:func(4095):Connection reset by peer

**Comment by stevezhengshiqi** [comment]
使用命令 sh -c "$(curl -fsSL https://hackintosh.stevezheng.workers.dev/https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/main/ALCPlugFix/one-key-alcplugfix_cn.sh)"

或

sh -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/main/ALCPlugFix/one-key-alcplugfix.sh)"

第二个命令可能需要有梯子
