### ISSUE TITLE
声音问题

### ISSUE THREAD

**Issue by xjh169** [daliansky/XiaoMi-Pro-Hackintosh#695]
OC /三叶草 ，（KBL）系统在睡眠中唤醒之后 声音服务工作不正常，出现没有声音的情况 ，使用终端 运行 sudo killall coreaudiod 也没有反应，重启也是没有用的，只能关机 断电之后 重新开机才能恢复 正常。

**Comment by xjh169** [comment]
以上是 KBL. OC/三叶草

**Comment by stevezhengshiqi** [comment]
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/tree/main/ALCPlugFix
