### ISSUE TITLE
麦克风问题，KBL ，13.0.1 (22A400) 

### ISSUE THREAD

**Issue by xjh169** [daliansky/XiaoMi-Pro-Hackintosh#697]
Siri 无法使用，使用 *语音备忘录*录音的时候只有杂音。（小米笔记本pro 2019，i7 8550U，mx250）

**Comment by xjh169** [comment]
> 尝试安装alcplugfix，运行指令sh -c "$(curl -fsSL [https://hackintosh.stevezheng.workers.dev/https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/main/ALCPlugFix/one -key-alcplugfix_cn.sh](https://hackintosh.stevezheng.workers.dev/https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/main/ALCPlugFix/one-key-alcplugfix_cn.sh) )”

curl: (28) Failed to connect to hackintosh.stevezheng.workers.dev port 443 after 75265 ms: Operation timed out
错误: 下载ALCPlugFix失败, 请检查网络连接状态

**Comment by stevezhengshiqi** [comment]
@xjh169 有条件的话尝试搭个梯子

**Comment by xjh169** [comment]
> @xjh169有条件的试搭搭梯子

换了几个梯子也是出现网络错误。

**Comment by In1t0** [comment]
> > @xjh169有条件的试搭搭梯子
> 
> 换了几个梯子也是出现网络错误。

有梯子的话直接在终端运行`sh -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/main/ALCPlugFix/one-key-alcplugfix_cn.sh)"`就行了。

**Comment by xjh169** [comment]
![截屏2023-01-21 13 56 53](https://user-images.githubusercontent.com/28785981/213845936-442169e7-2a44-4a82-a75f-fcabd7829c3d.png)

使用内建麦克风只有杂音，使用内建线路输入 插上耳机可以正常使用 麦克风（睡眠唤醒或者开机时 都要插拔才生效）
