### ISSUE TITLE
KBL ,睡眠唤醒之后 使用#抖音#看视频 的时候出现卡死 只能强制关机重启

### ISSUE THREAD

**Issue by xjh169** [daliansky/XiaoMi-Pro-Hackintosh#698]
以下是系统报告，请各位大佬帮忙分析一下，谢谢 🙏

panic(cpu 0 caller 0xffffff800c74aee3): Kernel trap at 0xffffff7fa22f9031, type 13=general protection, registers:
CR0: 0x0000000080010033, CR2: 0xffffffb095bbd000, CR3: 0x00000002b86ea171, CR4: 0x00000000003626e0
RAX: 0xffff7f8b876dcf80, RBX: 0xffffff8b874bdfe0, RCX: 0xffffff8b87787820, RDX: 0x0000000000000000
RSP: 0xffffffffff4af840, RBP: 0xffffffffff4af840, RSI: 0xffffff8b874bdfe0, RDI: 0xffffff9516ed43e8
R8:  0x0000000000000000, R9:  0x00000000000040aa, R10: 0x0000000000000000, R11: 0xffffff7fa23086ec
R12: 0xffffff8b872f6820, R13: 0xffffff86b9b58090, R14: 0x0000000008057b84, R15: 0xffffff9518da0400
RFL: 0x0000000000010282, RIP: 0xffffff7fa22f9031, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0xffffffb095bbd000, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 0, VF: 0

Panicked task 0xffffff90517df638: 12 threads: pid 849: f
i3 Helper (G
Backtrace (CPU 0), panicked thread: 0xffffff951963eb30, Frame : Return Address
0xffffff800c30c1a0 : 0xffffff800c5edf9d 
0xffffff800c30c1f0 : 0xffffff800c75b786 
0xffffff800c30c230 : 0xffffff800c74aa10 
0xffffff800c30c280 : 0xffffff800c588951 
0xffffff800c30c2a0 : 0xffffff800c5ee27d 
0xffffff800c30c390 : 0xffffff800c5ed929 
0xffffff800c30c3f0 : 0xffffff800cde0ecb 
0xffffff800c30c4e0 : 0xffffff800c74aee3 
0xffffff800c30c660 : 0xffffff800c74abd2 
0xffffff800c30c6b0 : 0xffffff800c588951 
0xffffff800c30c6d0 : 0xffffff7fa22f9031 
0xffffffffff4af840 : 0xffffff7fa232ebf8 
0xffffffffff4af860 : 0xffffff7fa22fd68b 
0xffffffffff4af890 : 0xffffff7fa22fda95 
0xffffffffff4af8c0 : 0xffffff7fa2308794 
0xffffffffff4af900 : 0xffffff800cd4b1f6 
0xffffffffff4af990 : 0xffffff800cd49a11 
0xffffffffff4af9e0 : 0xffffff7fa2309e76 
0xffffffffff4afa30 : 0xffffff800cd544ca 
0xffffffffff4afb90 : 0xffffff800c702319 
0xffffffffff4afca0 : 0xffffff800c5c5999 
0xffffffffff4afd50 : 0xffffff800c5de892 
0xffffffffff4afdc0 : 0xffffff800c5def9a 
0xffffffffff4afef0 : 0xffffff800c72d02a 
0xffffffffff4affa0 : 0xffffff800c588db6 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOAcceleratorFamily2(475.0)[94801D42-4EEE-3934-A18E-E5985844DBDD]@0xffffff7fa22db000->0xffffff7fa2345fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[A0F531C1-2689-359B-AA04-000F5DB5DF2D]@0xffffff800db91000->0xffffff800dbbffff
            dependency: com.apple.iokit.IOGraphicsFamily(597)[0C72861D-E774-323C-BFFE-3DD90C242EEC]@0xffffff7fa247b000->0xffffff7fa24a9fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[E2CE416B-59DA-3836-9985-FDC527C5E6C7]@0xffffff800efff000->0xffffff800f02efff
            dependency: com.apple.iokit.IOReportFamily(47)[3115840D-90F4-383F-8991-D3CF8891C24C]@0xffffff800f040000->0xffffff800f042fff
            dependency: com.apple.iokit.IOSurface(334.0.1)[AC62E371-3B14-3156-83EA-70CF1A239238]@0xffffff800f160000->0xffffff800f187fff

Process name corresponding to current thread (0xffffff951963eb30): f
i3 Helper (GPU)
Boot args: darkwake=0

Mac OS version:
22A400

Kernel version:
Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
Kernel UUID: BF7C9676-EF23-3E8D-A2E2-25DAC63091B6
roots installed: 0
KernelCache slide: 0x000000000c200000
KernelCache base:  0xffffff800c400000
Kernel slide:      0x000000000c2dc000
Kernel text base:  0xffffff800c4dc000
__HIB  text base: 0xffffff800c300000
System model name: MacBookPro15,3 (Mac-1E7E29AD0135F9BC)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 2072507470540
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000001e28b125854
  Sleep   : 0x0000015b2af26316 0x0000000044467e4f 0x000001543afbad4c
  Wake    : 0x0000015b2da93ef5 0x00000000449a9d40 0x0000015b2b23bc1a
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff8051887000 - 0xffffffa051887000
  . PGZ   : 0xffffff8051887000 - 0xffffff8053888000
  . VM    : 0xffffff8053888000 - 0xffffff8520087000
  . RO    : 0xffffff8520087000 - 0xffffff86b9887000
  . GEN0  : 0xffffff86b9887000 - 0xffffff8b86087000
  . GEN1  : 0xffffff8b86087000 - 0xffffff9052887000
  . GEN2  : 0xffffff9052887000 - 0xffffff951f087000
  . GEN3  : 0xffffff951f087000 - 0xffffff99eb887000
  . DATA  : 0xffffff99eb887000 - 0xffffffa051887000
  Metadata: 0xffffffe559c8e000 - 0xffffffe579c8e000
  Bitmaps : 0xffffffe579c8e000 - 0xffffffe57fc8e000

**Comment by stevezhengshiqi** [comment]
根据日志来看，是显卡加速导致的崩溃。我能想到两个可能的解决方案：
- 根据 https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/设置64mb动态显存 来开启 64mb动态显存
- 或者尝试更改色彩描述文件：前往 `系统偏好设置 - 显示器 - 颜色`，选择 `sRGB IEC61966-2.1`

**Comment by xjh169** [comment]
> 根据日志来看，是显卡加速导致的崩溃。我能想到两个可能的解决方案：
> 
> * 根据[https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/设置64mb动态显示](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/%E8%AE%BE%E7%BD%AE64mb%E5%8A%A8%E6%80%81%E6%98%BE%E5%AD%98)来启动 64mb动态显示
> * 或者尝试更改色彩描述文件：前往`系统偏好设置 - 显示器 - 颜色`，选择`sRGB IEC61966-2.1`

我本机是 MX250 ,还是先 前往系统偏好设置 - 显示器 - 颜色，选择sRGB IEC61966-2.1

**Comment by DengFX2010105421** [comment]
> > 根据日志来看，是显卡加速导致的崩溃。我能想到两个可能的解决方案：
> > 
> > * 根据[https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/设置64mb动态显示](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/%E8%AE%BE%E7%BD%AE64mb%E5%8A%A8%E6%80%81%E6%98%BE%E5%AD%98)来启动 64mb动态显示
> > * 或者尝试更改色彩描述文件：前往`系统偏好设置 - 显示器 - 颜色`，选择`sRGB IEC61966-2.1`
> 
> 我本机是 MX250 ,还是先 前往系统偏好设置 - 显示器 - 颜色，选择sRGB IEC61966-2.1

你的MX250咋驱动的呢？我的独显MX250用不了，用的集显

**Comment by HKMV** [comment]
> > > 根据日志来看，是显卡加速导致的崩溃。我能想到两个可能的解决方案：
> > > 
> > > * 根据[https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/设置64mb动态显示](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/%E8%AE%BE%E7%BD%AE64mb%E5%8A%A8%E6%80%81%E6%98%BE%E5%AD%98)来启动 64mb动态显示
> > > * 或者尝试更改色彩描述文件：前往`系统偏好设置 - 显示器 - 颜色`，选择`sRGB IEC61966-2.1`
> > 
> > 我本机是 MX250 ,还是先 前往系统偏好设置 - 显示器 - 颜色，选择sRGB IEC61966-2.1
> 
> 你的MX250咋驱动的呢？我的独显MX250用不了，用的集显

放弃吧，大家用的都是集显
