### ISSUE TITLE
求教MX250显卡怎么驱动？？？？？

### ISSUE THREAD

**Issue by DengFX2010105421** [daliansky/XiaoMi-Pro-Hackintosh#699]
**Pre-requirement**
- Try to rebuild the kextcache and restart whenever you encounter a problem. It always works like a charm!
- To rebuild the kextcache, run `sudo kextcache -i /` in `Terminal.app`.
- If you are using OpenCore, also try to reset NVRAM. Press `Space` key when you are in OpenCore boot page and choose `Reset NVRAM`.

**State the model**
- e.g. XiaoMi-Pro MX150, XiaoMi-Pro 8th GTX,...

**State the version of the EFI**
- e.g v1.3.4, v1.3.5,...

**Describe the bug**
- A clear and concise description of what the bug is.

**System log**
- If a windows "Your computer was restarted because of a problem" appears, click `Report` and attach the log to help find the problem.

**Screenshots**
- If applicable, add screenshots to help explain your problem.

**Attach your entire EFI folder**
- Please attach your entire EFI folder to help solve your problem.
- Erasing serial numbers in config.plist is required!

**Attach system.log**
- If applicable, please run `log show --predicate "processID == 0" --last boot --debug | grep "ERR"` in `Terminal.app` to help locate the problem.

**Comment by DengFX2010105421** [comment]
看历史issue好像没有明确回答这个问题，最新的cml里面都是MX350的驱动，真心求教。

**Comment by stevezhengshiqi** [comment]
独显无法被驱动
