### ISSUE TITLE
触控板无法使用

### ISSUE THREAD

**Issue by xjh169** [daliansky/XiaoMi-Pro-Hackintosh#703]
![WX20230107-133926](https://user-images.githubusercontent.com/28785981/211133129-ca5db73f-28a7-4827-b204-a7e932ce995a.png)
![WX20230107-133848](https://user-images.githubusercontent.com/28785981/211133131-8234dec7-6c93-4fef-91ac-7636cc6740b7.png)
![WX20230107-133814](https://user-images.githubusercontent.com/28785981/211133134-8faee980-d2d3-4167-8ff6-ffbb1248a1bc.png)
![WX20230107-133718](https://user-images.githubusercontent.com/28785981/211133136-13748a22-23ae-477f-ae49-416f548ffb47.png)
小米笔记本pro 2019 15.6  什么时候才能修复触控板问题呢？

**Comment by HKMV** [comment]
我也是pro2019 美遇到这个问题

**Comment by stevezhengshiqi** [comment]
@xjh169 你是用的不是本仓库的EFI。小米笔记本Pro的显卡为 UHD 620，而不是你截图显示的 HD 620。

**Comment by xjh169** [comment]
不好意思，我改了用补丁改了显卡信息。。。

**Comment by xjh169** [comment]
原来我使用了 [OCAuxiliaryTools  智能OC版本]更新了驱动导致触控板无法使用！抱歉，实在不好意思！

**Comment by ssrlive** [comment]
### 关于触控板

我的笔记本机型是 TM1701 , 因此得下载 XiaoMi_Pro-KBL-OC-v1.7.8.zip 等类型的 efi 套件. 
由于我的运气太好(糟), 买到了个带 三星硬盘的 PM981 型号, 因此我不得不再买了个金士顿的固态硬盘, 原来的硬盘拆下, 让金士顿做了主盘, 三星盘做了副盘.但似乎不管用, 列出盘符还是像这样:
```
geektest@Mi-Book-Pro ~ % sudo diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *512.1 GB   disk0 
   1:                        EFI NO NAME                 239.1 MB   disk0s1

/dev/disk1 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *240.1 GB   disk1
   1:       Microsoft Basic Data EFI                     209.7 MB   disk1s1
```
我设法将启动盘设置为 金士顿 `disk1s1` , efi 启动套件也放在 `disk1s1` , 然后安装 macOS 到 `disk1`.
为了有效利用那个三星盘, 就装了其它一些系统.
一切看起来很好.
最近我将macOS升级到 `13.3.1 (22E261)`, 升级过程倒是没什么错误, 但 触控板 不工作了. 找遍网络无解.
苦恼了很久, 今天无意中看到一个神奇的现象, 机子竟然神不知鬼不觉地将 `disk1s1 (EFI)/EFI/BOOT/BOOTx64.efi` 文件 
移动到了 `disk0s1 (EFI)/EFI/BOOT/BOOTx64.efi` , 即从 金士顿 跑到了 三星, 但与它相邻的 OC 目录并没有被移走. 
这就让这个启动过程极其纠结:
从 disk0 加载引导代码, 完事后从 disk1 加载 open core 的其余部分, 这就导致了 哪里不对劲, 触控板没有被正确初始化. 

于是我就启动到 Windows , 运行 `DiskGenius` 软件, 将 `disk0` 上到 `BOOT` 文件夹删除, 
下载最新的 `XiaoMi_Pro-KBL-OC-v1.7.8.zip` 文件, 将其中的 `BOOT` 和 `OC` 文件夹 复制到 `disk1` 盘上的正确位置, 
替换掉 `disk1s1 (EFI)/EFI/` 里的 `BOOT` 和 `OC`, 重启机器.
触控板就回来了.

分享出来, 给其他有同样困扰的人士参考.
