### ISSUE TITLE
UHD620 VRAM 3072MB

### ISSUE THREAD

**Issue by xjh169** [daliansky/XiaoMi-Pro-Hackintosh#707]
来自CSDN - 专业开发者社区，[漫漫梅溪](https://blog.csdn.net/qq_45171581)，说  UHD620缓冲帧的注入，在UHD 为2048MB大小的基础上进行修改，使UHD620 VRAM设置为3072MB大小，提高核显的性能 ?
![截屏2023-01-26 11 46 59](https://user-images.githubusercontent.com/28785981/214755251-8f8aafdb-87b5-47bd-9879-3afda7f0e0dd.png)
![截屏2023-01-26 11 47 44](https://user-images.githubusercontent.com/28785981/214755256-1d674fbc-0289-4d18-81b8-b6c22bc6f0d7.png)
![截屏2023-01-26 11 48 11](https://user-images.githubusercontent.com/28785981/214755257-d797c12c-3456-44a9-9fb3-c5668978b21a.png)

**Comment by stevezhengshiqi** [comment]
此方法修改显存只起到修饰作用，并无实际收益。

**Comment by xjh169** [comment]
好的！谢谢了
