### ISSUE TITLE
Fn-key must be pressed to function keys

### ISSUE THREAD

**Issue by orhan-drsn** [daliansky/XiaoMi-Pro-Hackintosh#709]
After the last update to 13.1/13.2 to I have to press the Fn-key to use the functions keys.
I tried to change it in the settings from macOS, but no matter if on or off, you have to press the Fn-key.

**Comment by stevezhengshiqi** [comment]
Hi, what about pressing Fn and Esc together to unlock Fn lock?

**Comment by orhan-drsn** [comment]
Yeah thanks that worked!
