### ISSUE TITLE
sleep mode problem with usb wifi dongle

### ISSUE THREAD

**Issue by sebmoris** [daliansky/XiaoMi-Pro-Hackintosh#71]
Hi,
after replace. `USBInjectAll` and `SSDT-USB.aml` to `USBPower` is a problem on sleep mode. 
When I push power on bottom or click Sleep option on main bar I see black screen and after 2-3 seconds display back to login screen.
But sometimes "go to sleep mode" works fine but after 1 minute sometimes 2 min, notebook wake up independently.
I use wifi dongle tp link.

**Comment by sebmoris** [comment]
I tested many times and problem exist only when battery go to low level

**Comment by stevezhengshiqi** [comment]
@sebmoris Hi, could you test that whether the sleep problem exists when using USBInjectAll + SSDT-USB?

**Comment by stevezhengshiqi** [comment]
Switched back to `USBInjectAll`. Feel free to reopen this issue if it still exists.
