### ISSUE TITLE
关于设置bios为64mb后，开机黑屏不显示

### ISSUE THREAD

**Issue by Yicenzzu** [daliansky/XiaoMi-Pro-Hackintosh#711]
使用小米progtx i7 ， 运行脚本，更改bios后开机黑屏死机了

**Comment by stevezhengshiqi** [comment]
本仓库的 dvmt 64mb脚本只适用于TM1701机型，也就是MX150版本的8代U。其他机型使用后可能需要编程器刷回原始BIOS。

**Comment by xjh169** [comment]
> 使用小米progtx i7，运行脚本，更改bios后开机黑屏死机了

我的小米笔记本pro 2019 TM1701   i7  16+512   MX250版本   不敢弄这个脚本！

**Comment by stevezhengshiqi** [comment]
> > 使用小米progtx i7，运行脚本，更改bios后开机黑屏死机了
> 
> 我的小米笔记本pro 2019 TM1701 i7 16+512 MX250版本 不敢弄这个脚本！

对的，MX250也不能用。https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/main/BIOS/TM1701/DVMT_and_0xE2_fix/README_CN.md 第一句话有写 “<b>仅支持 MX150！<b/>”
