### ISSUE TITLE
内存16GB已经很大了，关闭 交换文件，可以吗？

### ISSUE THREAD

**Issue by 1457384613gh** [daliansky/XiaoMi-Pro-Hackintosh#713]
- 考虑到 SSD 是 QLC的，擦写次数少。想 关闭类似于 虚拟内存/分页文件/SWAP 的功能，以便延长固态硬盘寿命。

- - 内存16GB已经很大了，关闭 交换文件，可以吗？

- - 可以关吗？有负面影响吗？影响大吗？

- - 除了终端命令以外，有方便一点的图形界面的开关吗？

- 对了，还想禁用“休眠”，只保留“睡眠”和“关机”，想删除已经生成的类似分页文件的镜像文件。
- - 除了终端命令，有图形界面的开关吗？
- - 类似于分页文件的镜像文件在哪个路径？

**Comment by HKMV** [comment]
你低估你软件使用内存的能力，这要看你日常怎么用，正常情况下不联系关闭缓存，关闭后很可能会导致系统和软件不稳定导致的崩溃问题

**Comment by stevezhengshiqi** [comment]
> * * 除了终端命令以外，有方便一点的图形界面的开关吗？

应该是没有的

> * 对了，还想禁用“休眠”，只保留“睡眠”和“关机”，想删除已经生成的类似分页文件的镜像文件。

```sh
sudo rm /var/vm/sleepimage
sudo mkdir /var/vm/sleepimage
```
命令来源 https://www.tonymacx86.com/threads/guide-native-power-management-for-laptops.175801/ ，不敢保证适用于新系统

> * * 除了终端命令，有图形界面的开关吗？

据我所知是没有的。

> * * 类似于分页文件的镜像文件在哪个路径？

`/var/vm/sleepimage`

**Comment by stevezhengshiqi** [comment]
> > sudo rm /var/vm/sleepimage sudo mkdir /var/vm/sleepimage
> 
> 输入了以后，就可以 仅仅只禁用 S4 的休眠了吧？

上面的指令是删除“已经生成的类似分页文件的镜像文件”。禁用S4休眠的指令位于 https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/main/Docs/README_CML.txt 。

> 
> 还有 类似于 SWAP 的镜像文件在哪个路径？

也在 `/var/vm/` 目录下。

**Comment by HKMV** [comment]
> 内存压缩/ZRAM 不就行了吗?
> M1的 Macbook，60天就有高达 261TB 的硬盘写入量。
> 假设 Intel 的是其1/10，26.1TB，也好多，更何况还可能不止。
> 
> ![Screenshot_2023-03-01-09-09-35-170_com.android.browser-edit.jpg](https://user-images.githubusercontent.com/69227436/222019128-41a26d86-8ac0-457e-8233-5da2cc07600e.jpg)
> 
> 
> 由于独显不能驱动，自然不会有庞大的工程。
> 日常使用，拿来 浏览器访问网页，都尽量使用 PWA 应用；播放离线的音视频；发送邮件等低级基础的操作。Microsoft Office 等专业软件，都是在 Windows 下操作的。
> 
> 应该是可以关的，不容易崩溃吧。

我之前在win上禁用以后，就会经常出现程序崩溃的问题。和你一样的想法，原本想着32G内存已经很大了，结果就悲剧了，还排查了好久才发现是这个原因导致的；你可以测试下是否会有问题。

**Comment by HKMV** [comment]
> 那是因为 你 没有设置 禁止 UWP后台运行。
> 
> 邮件、天气之类，一直挂在后台，商店也挂在后台自动更新。
> 
> 系统设置，隐私 那里，有个禁用所有UWP后台运行的选项。
> 
> 还有，内核隔离要关掉。
> 
> 反正，我限制后台，并且不隔离内核，还关掉虚拟内存以后，从来都没崩溃过。

可能和使用场景有关，我是一名程序员，开发环境要使用大量内存，所以在物理内存用完后就会出现程序崩溃的问题

**Comment by stevezhengshiqi** [comment]
@1457384613gh 这里不是论坛，非EFI相关问题可自行在 [InsanelyMac](https://www.insanelymac.com)，[tonymacx86](https://www.tonymacx86.com)和远景来获得专业解答。
