### ISSUE TITLE
键盘功能键 将F1、F2等键用作标准功能键不生效

### ISSUE THREAD

**Issue by sjje** [daliansky/XiaoMi-Pro-Hackintosh#714]
Os Version: 13.2 (22D49)
Model:   TM1963
EFI:  XiaoMi_Pro-CML-OC-v1.7.5.zip

现在的情况下: 按 F1-F3 是调节音量, ﬁ只能安住FN的同时才能使用F1-F3
期望:  不按FN就能使用 F1-F12

**Comment by stevezhengshiqi** [comment]
同时按Fn和Esc键来打开Fn锁。
