### ISSUE TITLE
KBL，MX250 独立显卡能正常工作？

### ISSUE THREAD

**Issue by xjh169** [daliansky/XiaoMi-Pro-Hackintosh#717]
[请问这样设置独立显卡有效果吗？，不知道有没有作用？
![WX20230311-180447](https://user-images.githubusercontent.com/28785981/224478411-b0bdb2a0-8501-49b2-ae3d-45eae78ae69b.png)
![WX20230311-180557](https://user-images.githubusercontent.com/28785981/224478413-2ecc52c0-0a2c-46dc-ba60-5046eef14cc0.png)

执行以下操作：
* 验证 SSDT-PNLF 是否已安装（即 EFI/OC/ACPI 以及 config.plist -> ACPI -> 添加并启用）
* 添加以下内容PciRoot(0x0)/Pci(0x2,0x0)：
@0,backlight-control | Data | 01000000
applbkl | Data | 01000000
AAPL,backlight-control | Data | 01000000
AAPL00,backlight-control | Data | 01000000
* 将以下内容添加到您的 dGPU PCI 地址：(地址可以使用Hackintool.app获取)
@0,backlight-control | Data | 00000000
applbkl | Data | 00000000
AAPL,backlight-control | Data | 00000000
重启,重启时候记得OpenCore引导界下选择Reset NVRAM重置一下.
原文链接：http://imacos.top/2023/02/26/2256/，转载请注明出处。

**Comment by xjh169** [comment]
目前开启独立显卡之后 睡眠 唤醒黑屏 需要长按电源键重启

**Comment by xjh169** [comment]
![截屏2023-03-11 22 59 13](https://user-images.githubusercontent.com/28785981/224491629-6e3b0f4e-8dcd-4af7-a45c-8a61669e132d.png)
只有装饰效果，发挥不了作用

**Comment by xjh169** [comment]
![截屏2023-03-11 23 00 48](https://user-images.githubusercontent.com/28785981/224491724-1f46a911-155b-4d97-9607-3461923a875c.png)

**Comment by stevezhengshiqi** [comment]
英伟达MX系列独立显卡永久无解。需要屏蔽来保证睡眠唤醒正常。不屏蔽他的话也会导致耗电增加。
