### ISSUE TITLE
KBL ， OC，AirportItlwm_Ventura.kext 加载慢 (Intel Wireless 8265)

### ISSUE THREAD

**Issue by xjh169** [daliansky/XiaoMi-Pro-Hackintosh#718]
Ventura 开机加载 Wi-Fi 需要一分钟以上才能连接上网络，导致状态栏其他图标延迟显示。

如果禁用AirportItlwm_Ventura.kext    ，开机进入桌面就直接看到 状态栏 的所有图标 那就不用等待加载了

测试使用Big_Sur、Catalina、Monterey版本 Wi-Fi加载速度没有异常。可能是Ventura的问题

希望AirportItlwm_Ventura.kext 加载速度可以得到优化！

![截屏2023-03-13 21 31 07](https://user-images.githubusercontent.com/28785981/224718738-1981a1ca-4126-46af-9ee6-9dacb25f95fb.png)
![WX20230313-212947](https://user-images.githubusercontent.com/28785981/224718992-e613eb7b-35f4-4dd3-876d-cb407918921f.png)

**Comment by stevezhengshiqi** [comment]
本仓库只使用这些驱动，没有能力维护他们。AirportItlwm相关问题可以反馈给 https://github.com/OpenIntelWireless/itlwm/issues 或者参与 Gitter 讨论 https://app.gitter.im/#/room/#OpenIntelWireless_itlwm:gitter.im
