### ISSUE TITLE
播放视频卡死自动重启

### ISSUE THREAD

**Issue by xjh169** [daliansky/XiaoMi-Pro-Hackintosh#720]
型号 
TM1701  XiaoMi Pro MX250 

EFI的版本v1.7.6

**系统日志**

panic(cpu 0 caller 0xffffff801ae963ed): "kfree: addr 0x800000000000, size 128 not found in any zone"@/System/Volumes/Data/SWE/macOS/BuildRoots/f9ec9dd09a/Library/Caches/com.apple.xbs/Sources/xnu/xnu-7195.141.49.700.6/osfmk/kern/kalloc.c:1051
Backtrace (CPU 0), Frame : Return Address
0xffffffa0bf67b5a0 : 0xffffff801a6822bd 
0xffffffa0bf67b5f0 : 0xffffff801a7cacb3 
0xffffffa0bf67b630 : 0xffffff801a7bb2aa 
0xffffffa0bf67b680 : 0xffffff801a626a2f 
0xffffffa0bf67b6a0 : 0xffffff801a681add 
0xffffffa0bf67b7c0 : 0xffffff801a681dd3 
0xffffffa0bf67b830 : 0xffffff801ae95e8a 
0xffffffa0bf67b8a0 : 0xffffff801ae963ed 
0xffffffa0bf67b8b0 : 0xffffff801a691def 
0xffffffa0bf67b910 : 0xffffff801ada6d0a 
0xffffffa0bf67b930 : 0xffffff7fb53de989 
0xffffffa0bf67b960 : 0xffffff7fb53debb7 
0xffffffa0bf67b990 : 0xffffff7fb53e9376 
0xffffffa0bf67b9d0 : 0xffffff801ae18131 
0xffffffa0bf67ba80 : 0xffffff801ae167ea 
0xffffffa0bf67bad0 : 0xffffff7fb53eaa44 
0xffffffa0bf67bb20 : 0xffffff801ae209fb 
0xffffffa0bf67bc80 : 0xffffff801a7764f1 
0xffffffa0bf67bd90 : 0xffffff801a68793d 
0xffffffa0bf67be00 : 0xffffff801a65dda5 
0xffffffa0bf67be60 : 0xffffff801a675402 
0xffffffa0bf67bef0 : 0xffffff801a79f37d 
0xffffffa0bf67bfa0 : 0xffffff801a627216 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOAcceleratorFamily2(442.10)[A2290A37-AA73-3D1C-846E-90C205D2E095]@0xffffff7fb53bd000->0xffffff7fb5427fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[170D7D8C-0DE2-32D0-B3C0-16F6E8CCB4EB]@0xffffff801bcc0000->0xffffff801bcd5fff
            dependency: com.apple.iokit.IOGraphicsFamily(585.2)[9E8A1AC1-1E51-3926-8C5F-CE84D4FBBD75]@0xffffff7fb553f000->0xffffff7fb556dfff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[CDD21753-E9D6-3836-BEAD-830EA73B6AD9]@0xffffff801d16d000->0xffffff801d195fff
            dependency: com.apple.iokit.IOReportFamily(47)[1CBC8CD2-C5ED-373F-803C-16E8565C25B6]@0xffffff801d1a4000->0xffffff801d1a6fff
            dependency: com.apple.iokit.IOSurface(290.8.1)[98BEF558-4441-345E-A68C-5705D23F1A0E]@0xffffff801d297000->0xffffff801d2b3fff

Process name corresponding to current thread: VTDecoderXPCService
Boot args: darkwake=0 ps2kbdonly=1

Mac OS version:
20G1225

Kernel version:
Darwin Kernel Version 20.6.0: Thu Mar  9 20:39:26 PST 2023; root:xnu-7195.141.49.700.6~1/RELEASE_X86_64
Kernel UUID: 16F174F8-4EC4-30AA-94B2-6FD0FC398C34
KernelCache slide: 0x000000001a400000
KernelCache base:  0xffffff801a600000
Kernel slide:      0x000000001a410000
Kernel text base:  0xffffff801a610000
__HIB  text base: 0xffffff801a500000
System model name: MacBookPro15,4 (Mac-53FDB3D8DB8CA971)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 4681526644345
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000044200bb9301
  Sleep   : 0x000003b8d14b26bf 0x000000068fa1c628 0x0000000000000000
  Wake    : 0x000003b8d4c99ac6 0x000000004421bd16 0x000003b8d22c3dd1
-

**Comment by xjh169** [comment]
接着又一次死机
系统报告
panic(cpu 0 caller 0xffffff8006fbb676): Kernel trap at 0xffffff8006f9876f, type 13=general protection, registers:
CR0: 0x0000000080010033, CR2: 0xffffffb0ac865000, CR3: 0x00000002ab891004, CR4: 0x00000000003626e0
RAX: 0xffff7f86946dba50, RBX: 0x00000000054aae60, RCX: 0x0000000000000000, RDX: 0x000000003b5dc100
RSP: 0xffffffb0ac1eb3f0, RBP: 0xffffffb0ac1eb500, RSI: 0xffffff86938239f8, RDI: 0x0000000000000000
R8:  0xfffffe98be9df328, R9:  0x000ffffffffff000, R10: 0x0000000000000000, R11: 0xffffffb0ac1eb5d0
R12: 0xffffff8007cd2c40, R13: 0xffff7f86946dba50, R14: 0x0010000000000000, R15: 0xfffffe98be9df328
RFL: 0x0000000000010286, RIP: 0xffffff8006f9876f, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0xffffffb0ac865000, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 3, VF: 0

Backtrace (CPU 0), Frame : Return Address
0xffffff8006d561e0 : 0xffffff8006e822bd 
0xffffff8006d56230 : 0xffffff8006fcacb3 
0xffffff8006d56270 : 0xffffff8006fbb2aa 
0xffffff8006d562c0 : 0xffffff8006e26a2f 
0xffffff8006d562e0 : 0xffffff8006e81add 
0xffffff8006d56400 : 0xffffff8006e81dd3 
0xffffff8006d56470 : 0xffffff8007695e8a 
0xffffff8006d564e0 : 0xffffff8006fbb676 
0xffffff8006d56660 : 0xffffff8006fbb35d 
0xffffff8006d566b0 : 0xffffff8006e26a2f 
0xffffff8006d566d0 : 0xffffff8006f9876f 
0xffffffb0ac1eb500 : 0xffffff8006f18b4b 
0xffffffb0ac1eb580 : 0xffffff8006f175bc 
0xffffffb0ac1eb600 : 0xffffff8006f1b30a 
0xffffffb0ac1eb890 : 0xffffff8006fbafcb 
0xffffffb0ac1eb900 : 0xffffff8006e26a2f 
0xffffffb0ac1eb920 : 0xffffff8006d01057 
0xffffffb0ac1eba80 : 0xffffff8009aa86cf 
0xffffffb0ac1ebad0 : 0xffffff800761674e 
0xffffffb0ac1ebb20 : 0xffffff80076209fb 
0xffffffb0ac1ebc80 : 0xffffff8006f764f1 
0xffffffb0ac1ebd90 : 0xffffff8006e8793d 
0xffffffb0ac1ebe00 : 0xffffff8006e5dda5 
0xffffffb0ac1ebe60 : 0xffffff8006e75402 
0xffffffb0ac1ebef0 : 0xffffff8006f9f37d 
0xffffffb0ac1ebfa0 : 0xffffff8006e27216 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOSurface(290.8.1)[98BEF558-4441-345E-A68C-5705D23F1A0E]@0xffffff8009a97000->0xffffff8009ab3fff

Process name corresponding to current thread: f
i3
Boot args: darkwake=0 ps2kbdonly=1

Mac OS version:
20G1225

Kernel version:
Darwin Kernel Version 20.6.0: Thu Mar  9 20:39:26 PST 2023; root:xnu-7195.141.49.700.6~1/RELEASE_X86_64
Kernel UUID: 16F174F8-4EC4-30AA-94B2-6FD0FC398C34
KernelCache slide: 0x0000000006c00000
KernelCache base:  0xffffff8006e00000
Kernel slide:      0x0000000006c10000
Kernel text base:  0xffffff8006e10000
__HIB  text base: 0xffffff8006d00000
System model name: MacBookPro15,4 (Mac-53FDB3D8DB8CA971)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 1500973750498
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000015d7901df2e
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x00000006301e6fcc 0x0000000000000000

还有救吗🙏

**Comment by stevezhengshiqi** [comment]
如果使用的是Chrome，请关闭硬件加速。

**Comment by xjh169** [comment]
> 如果使用的是Chrome，请关闭硬件加速。

好的，谢谢
