### ISSUE TITLE
3.5mm耳机无法正常工作

### ISSUE THREAD

**Issue by 1607941875** [daliansky/XiaoMi-Pro-Hackintosh#721]
**State the model**
- XiaoMi-Pro MX150
![Snipaste_2023-04-09_00-30-56](https://user-images.githubusercontent.com/59784883/230732820-e68505d1-f199-4671-a7fc-a3a26e55af70.png)

**State the version of the EFI**
- v1.7.6

**Describe the bug**
- 在不接电源的情况下使用3.5mm耳机，耳机无法正常工作。
> 过程描述：不接电源的情况下，一段时间后耳机会没有声音，重新接上电源一段时间后，耳机又会恢复声音。
- 在接电源的情况下使用3.5mm耳机，耳机全程正常工作。

**System log**
- 无

**Comment by stevezhengshiqi** [comment]
请按照 https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/main/ALCPlugFix/README_CN.md 安装ALCPlugFix。

**Comment by 1607941875** [comment]
> 请按照 [https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/main/ALCPlugFix/README_CN.md ](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/main/ALCPlugFix/README_CN.md)安装ALCPlugFix。
解决了👌
