### ISSUE TITLE
更新 v1.7.8 后 播放视频 卡死机频繁

### ISSUE THREAD

**Issue by xjh169** [daliansky/XiaoMi-Pro-Hackintosh#723]
Mac操作系统版本：22F5059b

系统型号：MacBookPro15,4

XiaoMi Pro MX250 TM1701  KBL

色彩描述文件：一直选择sRGB IEC61966-2.1

![截屏2023-05-10 22 33 38](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/assets/28785981/607afdaf-fb02-4a0b-96a9-6552b7eeb826)

EFI的版本 [v1.7.8]

**描述错误**

 Mac 系统似乎出现了紧急情况。恐慌消息表明在函数执行期间发生超时mp_cpus_call_wait()，特别是在 CPU 0 上。这种恐慌导致 WindowServer 进程崩溃。
以下是恐慌消息中的一些关键细节：
* 恐慌原因：mp_cpus_call_wait() timeout, cpus: 0x2
* 恐慌任务：WindowServer（进程 ID 144）
* 受影响的 CPU：CPU 0

Based on the panic report, it seems that a spinlock timeout occurred on CPU 0, which led to a panic. Spinlocks are synchronization mechanisms used by the kernel to protect critical sections of code from concurrent access. In this case, the spinlock timed out after waiting for a certain number of loops, indicating a potential deadlock or a race condition

**Comment by stevezhengshiqi** [comment]
有无 HDMI/DP 外接显示器，或者开启了HiDPI？

**Comment by xjh169** [comment]
> 有无HDMI/DP外接显示器，或者开启了HiDPI？

无外接DMI/DP显示器，无开启 HiDPI。

**Comment by stevezhengshiqi** [comment]
根据 [Panic then Reboot - How to Read Panic Reports](https://www.tonymacx86.com/threads/panic-then-reboot-how-to-read-panic-reports.270688/)，可能是核显相关问题。但 v1.7.8 并没有更新核显相关驱动 (WhateverGreen)。对于这个问题我也没有头绪。可以尝试回滚 [OpenCore](https://github.com/acidanthera/OpenCorePkg) v0.9.1，或者回滚 https://github.com/daliansky/XiaoMi-Pro-Hackintosh/actions 中的 commit 来逐一排查是什么改动造成的。

**Comment by xjh169** [comment]
> 根据[Panic then Reboot - How to Read Panic Reports](https://www.tonymacx86.com/threads/panic-then-reboot-how-to-read-panic-reports.270688/)，可能是核心问题。但 v1.7.8 并没有更新核心显示相关驱动 (WhateverGreen)。对于这个问题我也没有头绪。可以尝试回滚OpenCore [v0.9.1](https://github.com/acidanthera/OpenCorePkg)，或者返回滚https://github.com/daliansky/XiaoMi-Pro-Hackintosh/actions中的commit来逐一排查是什么改动生成的。

好的 ，我先观察一段时间， 实在不行再回滚旧版本！

**Comment by xjh169** [comment]
在 macOS Monterey 12.6.5 (21G531) 使用 OpenCore v0.9.2 （EFI v1.7.8）没有出现死机问题！
macOS 13 bug 太多了，macOS13 Wi-Fi问题 还有 BETA 3版本之后 蓝牙无法启动。我已经退回 Monterey。🙏

**Comment by xjh169** [comment]
安装EDID补丁 使用 kext ，解决哔哩哔哩app 全屏播放 不禁用GUP加速 情况下 闪屏的问题。

我选择了 MacBook Pro 显示器
它是16:10 ，而我的电脑显示器上16:9，色彩描述文件选择 默认 显示器。
，并没有显示异常。
![WX20230517-221315](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/assets/28785981/4cf64bd8-17cc-4281-9bd9-730cedd39fa2)

**Comment by xjh169** [comment]
> 安装EDID补丁 使用 kext ，解决哔哩哔哩app 全屏播放 不禁用GUP加速 情况下 闪屏的问题。
> 
> 我选择了 MacBook Pro 显示器 它是16:10 ，而我的电脑显示器上16:9，色彩描述文件选择 默认 显示器。 ，并没有显示异常。 ![WX20230517-221315](https://user-images.githubusercontent.com/28785981/238982369-4cf64bd8-17cc-4281-9bd9-730cedd39fa2.png)

不折腾了，此方法 重新启动又失效，还是要用sRGB IEC61966-2.1，核显始终还是有问题！。
