### ISSUE TITLE
Sonoma 触控板 不工作

### ISSUE THREAD

**Issue by xjh169** [daliansky/XiaoMi-Pro-Hackintosh#732]
机型：TM1701 i78550U
EFI版本： 最新测试版https://github.com/daliansky/XiaoMi-Pro-Hackintosh/actions
系统版本：macOS Sonoma 14 Beta 2
问题：触控板 不工作。

**Comment by stevezhengshiqi** [comment]
麻烦终端运行一下 kextstat | grep "Voodoo" 查看一下VoodooI2C是否成功加载

**Comment by stevezhengshiqi** [comment]
大概率是VoodooI2C最新的commit导致的，可以尝试自行回滚至2.8。https://github.com/VoodooI2C/VoodooI2C/releases

**Comment by xjh169** [comment]
终端运行没反应，回滚至2.8。😄，完美解决。🙏
