### ISSUE TITLE
Bluetooth: Not working in Ventura 13.4.1

### ISSUE THREAD

**Issue by potatosalad775** [daliansky/XiaoMi-Pro-Hackintosh#733]
Hi. thanks for maintaining EFI.

With latest EFI (v1.7.8), latest Ventura (13.4.1) and TM1701, the bluetooth feature is not working at all.

It seems like Apple added some changes between NVRAM and bluetooth, and apparently broke the 'BlueToolFix'.

'BrcmPatchRAM' with 'BlueToolFix' is not yet updated with latest PR, but I confirmed bluetooth function is working again with updated 'BlueToolFix' inside [latest Action Artifact of the project.](https://github.com/acidanthera/BrcmPatchRAM/actions/runs/5283322833) 

Thank you!

**Comment by stevezhengshiqi** [comment]
Thanks for the research and discovery of the updated BlueToolFixup. The EFI release of this repository will pull the latest commit of every kext, so it's not a problem that the next EFI release will contain that bluetooth fix.

I am still waiting for VoodooI2C team to finalize 2.9 release at https://github.com/VoodooI2C/VoodooI2C/pull/532 and OpenIntelWireless team to release Sonoma Airport kext. It has been a while to wait all developers updating their kexts to support the latest macOS.

**Comment by potatosalad775** [comment]
Thanks for the reply. 
I hope this issue will help others trying to solve bluetooth issue while we wait for an updated kext.

**Comment by williamoak1988** [comment]
NVRAM — 7C436110-AB2A-4BBB-A880-FE41995C9F82 add：
key：bluetoothInternalControllerInfo，VAULE：0000000000000000000000000000，类型：DATA
key：bluetoothExternalDongleFailed，VAULE：00，类型：DATA

**Comment by williamoak1988** [comment]
> Thanks for the reply. I hope this issue will help others trying to solve bluetooth issue while we wait for an updated kext. I will close this issue when we get EFI updated.

try this

**Comment by stevezhengshiqi** [comment]
@williamoak1988 Thank you for listing out the NVRAM configuration.
However, the latest BlueToolFixup includes https://github.com/acidanthera/BrcmPatchRAM/pull/31, which has already fixed NVRAM checking issue. Please check if the problem still exists.

**Comment by potatosalad775** [comment]
Closing this issue as updated EFI (1.7.9) will solve this problem.
