### ISSUE TITLE
ALCPlugFix失效

### ISSUE THREAD

**Issue by xjh169** [daliansky/XiaoMi-Pro-Hackintosh#734]
EFI v1.7.9

机型：TM1701（小米笔记本Pro2019 i7-8550U）
MacOS版本：14.0 Beta版(23A5286i)
![截屏2023-07-19 13 08 23](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/assets/28785981/a6828986-d0c6-4001-8442-5505af979a94)

睡眠 唤醒后 3.5mm有线耳机不工作。

**Comment by stevezhengshiqi** [comment]
可以先检测一下CodecCommander是否加载，终端运行 `kextstat | grep "CodecCommander"`

我在Ventura和更新的系统测试发现 `CodecCommander` 有无法加载的问题，进而导致 ALCPlugFix 失效。暂时没有解决方案，推测为CodecCommander 与 AppleHDA 在 Ventura+ 系统上存在 race condition。

**Comment by xjh169** [comment]
![截屏2023-07-19 17 06 17](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/assets/28785981/5ac60eda-7682-47d4-954c-ae8ba3218b5f)

好像是加载了，  看不懂终端显示是啥意思😅

**Comment by stevezhengshiqi** [comment]
@xjh169 根据你的终端显示应该是加载了。可能是 ALCPlugFix 守护程序在新系统上没有被成功运行。
Hackintool 的“被合并入”可以被忽略，AppleALC并没有完全吸收CodecCommander的所有功能，他无法发送 hda-verb 指令来激活耳机的node。

我的建议是在参照 [README.MD](https://github.com/Menchen/ALCPlugFix/blob/e11141021c07207482a6131bfc928a7fd8542943/README.MD) `/Library/LaunchDaemons/good.win.ALCPlugFix.plist` 里加上
```xml
<key>StandardOutPath</key>
<string>/tmp/ALCPlugFix.log</string>
<key>StandardErrorPath</key>
<string>/tmp/ALCPlugFix.log</string>
```
然后上传日志文件`/tmp/ALCPlugFix.log`。
CC @Menchen

@

**Comment by stevezhengshiqi** [comment]
@xjh169 不太对，你是用的ALCPlugFix是旧版本，不符合新版macOS进程策略。请运行`sh -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/main/ALCPlugFix/one-key-alcplugfix_cn.sh)"`来安装

参考：https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/main/ALCPlugFix/README_CN.md

**Comment by xjh169** [comment]
终端运行安装 提示 无法连接到服务器，提示：
curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 10 ms: Couldn't connect to server
用了VPN也不行。 可以发个zip包吗？🙏

**Comment by xjh169** [comment]
![截屏2023-07-19 21 48 47](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/assets/28785981/8994dd30-d5be-4aec-92be-febafa2bb130)
@stevezhengshiqi

**Comment by stevezhengshiqi** [comment]
@xjh169 每个 https://github.com/daliansky/XiaoMi-Pro-Hackintosh/releases KBL EFI 包里面都有 ALCPlugFix 文件夹。使用方法用 v1.7.9 OC 包为例：
``` shell
cd XiaoMi_Pro-KBL-OC-v1.7.9/ALCPlugFix/alc_fix/ # 修改为你自己的 ALCPlugFix/alc_fix 路径
./install.sh
```

**Comment by xjh169** [comment]
使用终端运行install.sh提示找不到文件目录 @stevezhengshiqi 
![截屏2023-07-19 22 51 31](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/assets/28785981/3ab3cec2-d1ba-41f5-9941-21de5559f5b7)


然后。。。我手动把文件复制到安装目录 重启测试完美解决。🤝

**Comment by stevezhengshiqi** [comment]
@xjh169 根据你的终端，你没有执行第一条 `cd XiaoMi_Pro-KBL-OC-v1.7.9/ALCPlugFix/alc_fix/ # 修改为你自己的 ALCPlugFix/alc_fix 路径` 这个命令。需要先cd到alc_fix路径，install.sh才能根据相对路径找到工程文件。

**Comment by xjh169** [comment]
问题已经解决，谢了🙏，目前还有一个 睡眠唤醒Wi-Fi没有自动连接问题，我会把log 发到https://github.com/OpenIntelWireless/itlwm/issues/896
