### ISSUE TITLE
使用 OpenCore 的 DUET，ps/2 键盘失灵，没法按。

### ISSUE THREAD

**Issue by 1457384613gh** [daliansky/XiaoMi-Pro-Hackintosh#735]
使用 OpenCore 的 DUET，ps/2 键盘失灵，没法按。

尝试使用 OpenCore 的 DUET，覆盖了 MBR 和 PBR，复制了 boot 文件。

可以进入 OC 的图形界面，但是 PS/2 的键盘会失灵，无法切换选项，USB 鼠标可以正常使用。

OpenCore 那里没有 issue 和 discussion 的 按钮，不知道上哪儿反馈，所以……就……写这了。

**Comment by stevezhengshiqi** [comment]
OpenCore 相关帮助需要在 [insanelymac](https://www.insanelymac.com/forum/723-opencore/) 上求助，如果确定是bug，则在 https://github.com/acidanthera/bugtracker/issues 上提 issue 并附上详细日志。

个人建议调试`PollAppleHotKeys`，`TakeoffDelay`，`KeyInitialDelay`，`KeySubsequentDelay`，`KeySupport` 等相关键盘设置。也可以试试加上`Ps2KeyboardDxe` driver。
