### ISSUE TITLE
CML-1.7.9-OC 解压后没有 Realtek 读卡器驱动

### ISSUE THREAD

**Issue by 1457384613gh** [daliansky/XiaoMi-Pro-Hackintosh#736]
CML-1.7.9-OC 解压后没有 Realtek 读卡器驱动。

是因为不能用，然后移除了吗？
更新日志上没看到移除的说明啊。

**Comment by stevezhengshiqi** [comment]
@1457384613gh Realtek读卡器驱动从未出现在正式 EFI release 包里。经QQ群友反馈，驱动会导致休眠唤醒后频繁卡死问题。还有系统报告的USB树下会反复添加SD卡设备。
