### ISSUE TITLE
Black screen during OC picker

### ISSUE THREAD

**Issue by Menchen** [daliansky/XiaoMi-Pro-Hackintosh#738]
Well, Today I have decided to reinstall macOS with a fresh config.plist directly from the release, I had to reinstall 3 times because the OpenCore picker is a black screen, but working after the 5s timeout (keep rebooting into recovery as I cannot see the option).

After a bit of [research](https://www.reddit.com/r/hackintosh/comments/w8eeae/opencore_black_screen_with_working_picker_after/), it seems that `ProvideConsoleGop` should be `false`, and after changing it the picker worked. 

Is there a reason for `ProvideConsoleGop` set to true? In the OC documentation, the failsafe value seems to be `false`.

**Comment by stevezhengshiqi** [comment]
@Menchen Hi Menchen, thanks for reporting. I am gald you find it out about ProvideConsoleGop. It is enabled aince the very first version of OpenCore to show the picker. There might be some changes, and we could no longer need that. Could you verify your OpenCore version? I thought newer version OpenCore picker will work no matter ProvideConsoleGop is enabled or not.
