### ISSUE TITLE
Trackpad not working

### ISSUE THREAD

**Issue by dimitrios-ath** [daliansky/XiaoMi-Pro-Hackintosh#745]
Hello everyone,

I just updated to macOS Sonoma 14.0 but have a problem, trackpad doesn't work at all. I already tried `sudo kextcache -i /` to rebuild kext cache and resetting NVRAM but it didn't work. The problem occured after following up this guide https://www.youtube.com/watch?v=I2tT5BCMr6I to enable broadcom wifi in macOS Sonoma, which worked well regarding the wifi problem. Do you have any suggestions?

Here is `kextstat | grep "Voodoo"` output:
```
Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
   58    0 0xffffff8003cac000 0xb000     0xb000     com.alexandred.VoodooI2CServices (1) DBFA5EBE-2783-30ED-8E39-5829C42D6832 <6 3>
   79    0 0xffffff8003c85000 0x27000    0x27000    org.coolstar.VoodooGPIO (1.1) 7ED39A4D-2EFD-35AE-9BC6-6215C17D93F1 <17 7 6 3>
```

Thanks in advance!

My EFI: https://drive.google.com/file/d/1Fjc-NMwjc2yWlzXD4bSDJ6DP1u2yoXrz/view?usp=sharing

**Comment by stevezhengshiqi** [comment]
@dimitrios-ath From the kextstat output we can see that `VoodooI2C` is not loaded. By looking at your `config.plist`, I notice that you did some minor adjustments on kext order, which might lead to unsuccessful kext loading
- `VoodooI2CServices` should be placed before `VoodooI2C`. It is a dependent for `VoodooI2C`
- Recommend kext order for VoodooI2C kext series: `VoodooI2CServices` -> `VoodooGPIO` -> `VoodooI2C` -> `VoodooI2CHID` -> `VoodooInput`, you can always refer to the original config.plist and check your kext loading order.

**Comment by dimitrios-ath** [comment]
Hello @stevezhengshiqi , I didn't really noticed that I made these rearrangements in the kexts order, my mistake. I reordered them like you suggested and it worked like charm! Thank you very much for your help!
