### ISSUE TITLE
HDMI or Standby problem

### ISSUE THREAD

**Issue by kyokusa** [daliansky/XiaoMi-Pro-Hackintosh#746]
Hi, i own a Xiaomi Air Pro 2019 MX250 i7-8550U KBL.
Using OC 18 The latest version of OpenCore 1.8.0
My OS is Sonoma 14.2
I use Tripleboot Sonoma, Arch and Windows.

The problem occurs with Standby if ACPI-->SSDT-DDGPU disabled, I have no problem with HDMI...
External monitor works correctly both via HDMI and USB-C-HDMI, but Standby does not work with any modifications and even more.

The problem occurs with HDMI if ACPI-->SSDT-DDGPU enabled, I have no problem with Standby...
Standby works fine, but HDMI and usb-c-HDMI don't work with any changes.

Thanks for all help

**Comment by stevezhengshiqi** [comment]
`SSDT-DDGPU` turns off power line for discrete graphics card, which is not supported on macOS. So disable that could result in unexpected power consumption and wake request from discrete card.

To make HDMI work, you can go into `DeviceProperties` for iGPU. You might want to play with `force-online`, `enable-max-pixel-clock-override` and `complete-modeset-framebuffers`. Also you can play with `framebuffer-flags`. You can find more information at WhateverGreen Manual.
Ref: https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md

**Comment by kyokusa** [comment]
> `SSDT-DDGPU` turns off power line for discrete graphics card, which our Optimus NVDIA Graphics card is not supported on macOS. And disabling that patch could result in unexpected power consumption and wake request from discrete card, which could be the reason for broken standby.
> 
> To make HDMI work, you can go into `DeviceProperties` for iGPU. You might want to play with `force-online`, `enable-max-pixel-clock-override` and `complete-modeset-framebuffers`. Also you can play with `framebuffer-flags`. You can find more information at WhateverGreen Manual. Ref: https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md

For now, many thanks, I'll do some tests based on what you explained to me, then I'll tell you, see you soon.

**Comment by kyokusa** [comment]
Hi stevezhengshiqi, i solved it thanks to your tips. Specifically it was the OpenCore version 1.8.0 framebuffer-flags -->0B07C300 for my laptop was not working. I wish you good luck with everything, thanks again...
