### ISSUE TITLE
v1.8.1 在KBL的WIFI无法连接网络了

### ISSUE THREAD

**Issue by Nymph2333** [daliansky/XiaoMi-Pro-Hackintosh#747]
**Pre-requirement**
Sonoma 14.0 (23A344)
Clover

**State the model**
- XiaoMi-Pro MX150 改32G内存 killer网卡

**State the version of the EFI**
- v1.8.1

**Describe the bug**
- wifi无法连上了,能扫描出wifi列表,但是无法连上,在换回v1.8.0可以正常连上ಥ_ಥ

**Comment by stevezhengshiqi** [comment]
你好，Wi-Fi问题请关注英特尔Wi-Fi驱动官方仓库https://github.com/OpenIntelWireless/itlwm。本仓库只会拉取最新驱动，修复不了驱动上的问题。

我也收到有群友反馈相似问题，目前暂时只能回滚到上一个版本。

**Comment by Nymph2333** [comment]
> 你好，Wi-Fi问题请关注英特尔Wi-Fi驱动官方仓库https://github.com/OpenIntelWireless/itlwm 。本仓库只会拉取最新驱动，修复不了驱动上的问题。
> 
> 我也收到有群友反馈相似问题，目前暂时只能回滚到上一个版本。

谢谢

**Comment by Fenco-Han** [comment]
替换了1.8.1的Kext中内容为1.8.0中的内容，问题解决。

**Comment by orhan-drsn** [comment]
Can you tell how to change the kext?

**Comment by ssrlive** [comment]
是把文件夹 Kexts 中的内容整体换掉吗?

**Comment by ssrlive** [comment]
是把文件夹 Kexts 中的内容整体换掉吗? @Fenco-Han

**Comment by stevezhengshiqi** [comment]
Fixed in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/commit/198b9911ad5922152b0d6e1ac5d6ffa5c52cd0f3
