### ISSUE TITLE
开启hidpi睡眠唤醒后屏幕变小，且出现闪屏，关机出现花屏

### ISSUE THREAD

**Issue by one1ife** [daliansky/XiaoMi-Pro-Hackintosh#750]
型号:TM1701，EFI:V1.8.1，尝试多个mac版本都有该现象，只有设置802p~1080p之间hidpi分辨率会出现，请问有没有解决方法
还有就是3个QQ群人满了，同型号还可以去哪里交流问题呢

**Comment by stevezhengshiqi** [comment]
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/main/Docs/README_CN.md#改善体验

**Comment by one1ife** [comment]
我看了一下，但是我的是MX250显卡是不是用不了这个脚本

**Comment by one1ife** [comment]
> https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/main/Docs/README_CN.md#改善体验

我看了一下但是我的是mx250显卡，是不是用不了这个脚本

**Comment by stevezhengshiqi** [comment]
一样的
