### ISSUE TITLE
Cannot see MacOS installation partition after first reboot during install

### ISSUE THREAD

**Issue by SanderVocke** [daliansky/XiaoMi-Pro-Hackintosh#751]
**State the model**
XiaoMi-Pro MX150 (kaby lake)

**State the version of the EFI**
1.8.1 OpenCore

**Describe the bug**
I used the released EFI in combination with an online MacOS Ventura installation image. Installation started like a charm. However, after first reboot, cannot see the MacOS installation partition.

**System log**
I would like to share a boot log, but couldn't figure out how to generate one.

**Attach your entire EFI folder**
[EFI.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/13490295/EFI.zip)

I appreciate any help!
What I already tried:

- ApfsDriverLoader.efi
- NVMeFix
- MinVersion / ScanPolicy settings

I don't think the installation itself went wrong. I can see and mount the new MacOS partition from my Windows install.

**Comment by SanderVocke** [comment]
> You can try press Space key in the boot picker page, and select your volume.

Sorry I forgot to mention, but I did try this. The online installer .DMG image shows up, but not the installation volume on the SSD.

I appreciate the quick reply though!

**Comment by SanderVocke** [comment]
In your opinion, would it be a good idea to approach this with a fresh opencore "vanilla" install as per their installation guide? Or would I just be repeating a bunch of steps that you have already done here?

**Comment by stevezhengshiqi** [comment]
It seems that the installation does not proceed successfully. Are you able to find your SSD model? Is it PM981 or PM961? PM981 starts with `MZVLB`.

**Comment by SanderVocke** [comment]
> It seems that the installation does not proceed successfully. Are you able to find your SSD model? Is it PM981 or PM961? PM981 starts with `MZVLB`.

SAMSUNG MZVLB256HAHQ-00000 is how it is listed, so I guess it is a PM981 then.

**Comment by stevezhengshiqi** [comment]
@SanderVocke PM981 is not supported for macOS. So you might need to have an alternate SSD.

**Comment by SanderVocke** [comment]
I see. Thanks again for the help! I will look for alternatives.

**Comment by stevezhengshiqi** [comment]
NVMeFix is not supported on PM981. You can refer to https://github.com/dortania/bugtracker/issues/192.

Under Incompatible with IONVMeFamily (die under heavy load), you can find PM981 is listed there.
