### ISSUE TITLE
Update not possible 

### ISSUE THREAD

**Issue by orhan-drsn** [daliansky/XiaoMi-Pro-Hackintosh#758]
I'm stuck on  14.4.1 and can't update to newer version.
Is there any changes from Apple or is it an issue from our kext files?

**Comment by stevezhengshiqi** [comment]
Hi, could you be more specific on what version you are updating to? And what issues do you have for that update?

**Comment by orhan-drsn** [comment]
I tried it now again. 
I have 14.4.1 installed and I tried to update to 14.6.1
First it installs and reboot, it automatic picks "macOS installer" in boot menu, then restarts again and boots into "macOS". Now it takes about 10 min and macOS login screen appears. The installed version is still 14.4.1

I'm using the latest release "XiaoMi NoteBook Pro EFI v1.8.3".

In boot picker now I see always two options, "macOS installer" and "macOS".

**Comment by stevezhengshiqi** [comment]
Thank you for the information. EFI should be good for updating to 14.6.1. A good practice for failed upgrade is to reset NVRAM:
Press Space key when you are in OpenCore boot page and choose `Reset NVRAM`.

If this does not work, you can try to set `SecureBootModel` to `Disabled` in config.plist and download complete macOS 14.6.1 in AppStore and then upgrade.

**Comment by stevezhengshiqi** [comment]
@HKMV 可以尝试把 SecureBootModel 设置为 Disabled，升级完成后再调回Default，参考https://github.com/acidanthera/bugtracker/issues/2395

**Comment by HKMV** [comment]
> @HKMV 可以尝试把 SecureBootModel 设置为 Disabled，升级完成后再调回Default
> 
> Reference: https://github.com/acidanthera/bugtracker/issues/2395

确实是这样重启升级前要把SecureBootModel 设置为 Disabled才可以。感谢感谢

**Comment by orhan-drsn** [comment]
Now the update is installed!
The problem really was the `SecureBootModel`.

**Comment by orhan-drsn** [comment]
Now the update is installed!
The problem really was the SecureBootModel.

**Comment by stevezhengshiqi** [comment]
@openmindead Try https://github.com/daliansky/XiaoMi-Pro-Hackintosh/releases/tag/v1.8.8 without any edit. That stop icon is usually due to some security setting in config.
