### ISSUE TITLE
最新的1.8.3 似乎不支持升级macos 15

### ISSUE THREAD

**Issue by tianh** [daliansky/XiaoMi-Pro-Hackintosh#761]
**Pre-requirement**
- For macOS version < Big Sur, try to rebuild the kextcache (e.g. run `sudo kextcache -i /` in `Terminal.app`) and restart whenever you encounter a problem. It always works like a charm!
- If you are using OpenCore, also try to reset NVRAM. Press `Space` key when you are in OpenCore boot page and choose `Reset NVRAM`.

**State the model**
XiaoMi-Pro 8th GTX

**State the version of the EFI**
V1.8.3

**Describe the bug**
从macos11升级macos15 , 引导一直重启， 无法进入系统

**System log**
无

**Screenshots**
无

**Attach your entire EFI folder**
默认， 只改了LGPA到 LGPAGTX

**Attach system.log**
无

**Comment by stevezhengshiqi** [comment]
最新EFI不支持15的，在Release页面和README都有写支持的版本。
Supported macOS Version: 10.15, 11, 12, 13, 14

**Comment by stevezhengshiqi** [comment]
1.8.3版本EFI不支持Sequoia。我没有发布Sequoia版本EFI因为还有很多驱动不兼容。具体来说，我在关注 https://github.com/acidanthera/bugtracker/issues/2423, https://github.com/acidanthera/BrcmPatchRAM/pull/33, https://github.com/OpenIntelWireless/itlwm/issues/983, https://github.com/acidanthera/bugtracker/issues/2426, 和 https://github.com/acidanthera/bugtracker/issues/2431

因为这些原因，我不是很想更新EFI。用户可以自行更新驱动并升级系统，但可能有风险。

**Comment by uptownzombi21** [comment]
你们尽然都说中文

**Comment by uptownzombi21** [comment]
我试过在15beta上面使用olarila的stock bluetooth, 有时候好用有时候不好用

**Comment by uptownzombi21** [comment]
你们可以试一试olarila.com的[opencore MOD EF](https://olarila.com/topic/25111-hackintosh-efi-folders-with-opencore-mod/)I，很好用，只需要更行/添加kexts, aml，然后注入自己的三码，就可以直接使用了

**Comment by stevezhengshiqi** [comment]
@uptownzombi21 感谢推荐。但此仓库一直严格按照官方OpenCore规范对机型高度定制，且所有aml都做了多系统兼容处理，所以不需要第三方MOD。

**Comment by uptownzombi21** [comment]
ok, 其实我后来也是删除了mald0n.aml, 原因是因为安全问题，当初用是因为方便
